# Generated by Django 3.1.7 on 2021-05-28 19:34

import django.db.models.deletion
from django.db import migrations, models

import cl.lib.storage
import cl.recap_rss.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RssItemCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The time when this item was created')),
                ('hash', models.CharField(db_index=True, max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RssFeedStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('date_last_build', models.DateTimeField(blank=True, help_text='The dateLastBuilt field from the feed when it was visited.', null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Feed processed successfully.'), (2, 'Feed unchanged since last visit'), (3, 'Feed encountered an error while processing.'), (4, 'Feed is currently being processed.'), (5, 'Feed failed processing, but will be retried.')], help_text='The current status of this feed. Possible values are: (1): Feed processed successfully., (2): Feed unchanged since last visit, (3): Feed encountered an error while processing., (4): Feed is currently being processed., (5): Feed failed processing, but will be retried.')),
                ('is_sweep', models.BooleanField(default=False, help_text='Whether this object is tracking the progress of a sweep or a partial crawl.')),
                ('court', models.ForeignKey(help_text='The court where the upload was from', on_delete=django.db.models.deletion.CASCADE, related_name='rss_feed_statuses', to='search.court')),
            ],
            options={
                'verbose_name_plural': 'RSS Feed Statuses',
            },
        ),
        migrations.CreateModel(
            name='RssFeedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('filepath', models.FileField(help_text='The path of the file in the local storage area.', max_length=150, storage=cl.lib.storage.S3PrivateUUIDStorage(), upload_to=cl.recap_rss.models.make_rss_feed_path)),
                ('court', models.ForeignKey(help_text='The court where the RSS feed was found', on_delete=django.db.models.deletion.CASCADE, related_name='rss_feed_data', to='search.court')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
