# Generated by Django 3.2.12 on 2022-04-05 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_fix_on_delete_noop'),
        ('recap_rss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeeddata',
            name='court',
            field=models.ForeignKey(help_text='The court where the RSS feed was found', on_delete=django.db.models.deletion.RESTRICT, related_name='rss_feed_data', to='search.court'),
        ),
    ]
