# Generated by Django 3.1.7 on 2021-05-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recap_rss', '0006_abstract_datetime_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeedstatus',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Feed processed successfully.'), (2, 'Feed unchanged since last visit'), (3, 'Feed encountered an error while processing.'), (4, 'Feed is currently being processed.'), (5, 'Feed failed processing, but will be retried.')], help_text='The current status of this feed. Possible values are: (1): Feed processed successfully., (2): Feed unchanged since last visit, (3): Feed encountered an error while processing., (4): Feed is currently being processed., (5): Feed failed processing, but will be retried.'),
        ),
    ]
