# Generated by Django 5.0 on 2023-12-14 21:25

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "donate",
            "0005_remove_donation_update_or_delete_snapshot_update_and_more",
        ),
        ("pghistory", "0005_events_middlewareevents"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NeonWebhookEvents",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "createMembership"),
                            (2, "editMembership"),
                            (3, "deleteMembership"),
                            (4, "updateMembership"),
                        ],
                        help_text="The current membership tier of a user within Neon CRM",
                        null=True,
                    ),
                ),
                (
                    "account_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Unique identifier assigned by Neon CRM to a customer record",
                    ),
                ),
                (
                    "membership_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Unique identifier assigned by Neon CRM to a membership record",
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        blank=True,
                        help_text="The content of the payload of the POST request.",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NeonMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "neon_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Unique identifier assigned by Neon CRM to a membership record",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "CL Membership - Basic"),
                            (2, "CL Legacy Membership"),
                            (3, "CL Membership - Tier 1"),
                            (4, "CL Membership - Tier 2"),
                            (5, "CL Membership - Tier 3"),
                            (6, "CL Membership - Tier 4"),
                            (7, "CL Membership - Tier 5"),
                            (8, "CL Platinum Membership"),
                        ],
                        help_text="The current membership tier of a user within Neon CRM",
                        null=True,
                    ),
                ),
                (
                    "termination_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date a user's Neon membership will be terminated",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="the user linked to the membership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NeonMembershipEvent",
            fields=[
                (
                    "pgh_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                (
                    "neon_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Unique identifier assigned by Neon CRM to a membership record",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "CL Membership - Basic"),
                            (2, "CL Legacy Membership"),
                            (3, "CL Membership - Tier 1"),
                            (4, "CL Membership - Tier 2"),
                            (5, "CL Membership - Tier 3"),
                            (6, "CL Membership - Tier 4"),
                            (7, "CL Membership - Tier 5"),
                            (8, "CL Platinum Membership"),
                        ],
                        help_text="The current membership tier of a user within Neon CRM",
                        null=True,
                    ),
                ),
                (
                    "termination_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date a user's Neon membership will be terminated",
                        null=True,
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="event",
                        to="donate.neonmembership",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="the user linked to the membership",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="neonmembership",
            trigger=pgtrigger.compiler.Trigger(
                name="update_or_delete_snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "donate_neonmembershipevent" ("id", "level", "neon_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "termination_date", "user_id") VALUES (OLD."id", OLD."level", OLD."neon_id", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."termination_date", OLD."user_id"); RETURN NULL;',
                    hash="b30b699cb1448c94ae87296cbc13a33c7868e332",
                    operation="UPDATE",
                    pgid="pgtrigger_update_or_delete_snapshot_update_91de0",
                    table="donate_neonmembership",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="neonmembership",
            trigger=pgtrigger.compiler.Trigger(
                name="update_or_delete_snapshot_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "donate_neonmembershipevent" ("id", "level", "neon_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "termination_date", "user_id") VALUES (OLD."id", OLD."level", OLD."neon_id", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."termination_date", OLD."user_id"); RETURN NULL;',
                    hash="63d1d1750e80727961907ce9a56ceae3c1257f3c",
                    operation="DELETE",
                    pgid="pgtrigger_update_or_delete_snapshot_delete_e81b6",
                    table="donate_neonmembership",
                    when="AFTER",
                ),
            ),
        ),
    ]
