# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-24 16:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0006_add_unlimited_alert_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Awaiting Payment'), (1, 'Unknown Error'), (2, 'Completed, but awaiting processing'), (3, 'Cancelled'), (4, 'Processed'), (5, 'Pending'), (6, 'Failed'), (7, 'Reclaimed/Refunded'), (8, 'Captured'), (9, 'Disputed'), (10, 'Dispute closed')]),
        ),
    ]
