# Generated by Django 5.0.2 on 2024-02-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "donate",
            "0006_neonwebhookevent_neonmembership_neonmembershipevent_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="neonmembership",
            name="level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "CL Membership - Basic"),
                    (2, "CL Legacy Membership"),
                    (3, "CL Membership - Tier 1"),
                    (4, "CL Membership - Tier 2"),
                    (5, "CL Membership - Tier 3"),
                    (6, "CL Membership - Tier 4"),
                    (7, "CL Membership - Tier 5"),
                    (8, "CL Platinum Membership"),
                    (9, "EDU Membership"),
                ],
                help_text="The current membership tier of a user within Neon CRM",
            ),
        ),
        migrations.AlterField(
            model_name="neonmembershipevent",
            name="level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "CL Membership - Basic"),
                    (2, "CL Legacy Membership"),
                    (3, "CL Membership - Tier 1"),
                    (4, "CL Membership - Tier 2"),
                    (5, "CL Membership - Tier 3"),
                    (6, "CL Membership - Tier 4"),
                    (7, "CL Membership - Tier 5"),
                    (8, "CL Platinum Membership"),
                    (9, "EDU Membership"),
                ],
                help_text="The current membership tier of a user within Neon CRM",
            ),
        ),
    ]
