# Generated by Django 5.0.6 on 2024-06-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donate", "0007_add_membership_type_for_edu_accounts_noop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="neonmembership",
            name="level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "CL Membership - Basic"),
                    (2, "CL Legacy Membership"),
                    (3, "CL Membership - Tier 1"),
                    (4, "CL Membership - Tier 2"),
                    (5, "CL Membership - Tier 3"),
                    (6, "CL Membership - Tier 4"),
                    (7, "CL Membership - Tier 5"),
                    (8, "CL Platinum Membership"),
                    (9, "EDU Membership"),
                    (10, "Group Membership - Smallest"),
                    (11, "Group Membership - Small"),
                    (12, "Group Membership - Medium"),
                    (13, "Group Membership - Large"),
                    (14, "Group Membership - Unlimited"),
                ],
                help_text="The current membership tier of a user within Neon CRM",
            ),
        ),
        migrations.AlterField(
            model_name="neonmembershipevent",
            name="level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "CL Membership - Basic"),
                    (2, "CL Legacy Membership"),
                    (3, "CL Membership - Tier 1"),
                    (4, "CL Membership - Tier 2"),
                    (5, "CL Membership - Tier 3"),
                    (6, "CL Membership - Tier 4"),
                    (7, "CL Membership - Tier 5"),
                    (8, "CL Platinum Membership"),
                    (9, "EDU Membership"),
                    (10, "Group Membership - Smallest"),
                    (11, "Group Membership - Small"),
                    (12, "Group Membership - Medium"),
                    (13, "Group Membership - Large"),
                    (14, "Group Membership - Unlimited"),
                ],
                help_text="The current membership tier of a user within Neon CRM",
            ),
        ),
    ]
