# Generated by Django 5.1.8 on 2025-05-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0009_pghistory_v3_4_0_trigger_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neonmembership',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CL Membership - Basic'), (2, 'CL Legacy Membership'), (3, 'CL Membership - Tier 1'), (4, 'CL Membership - Tier 2'), (5, 'CL Membership - Tier 3'), (6, 'CL Membership - Tier 4'), (9, 'EDU Membership'), (10, 'Group Membership - Smallest'), (11, 'Group Membership - Small'), (12, 'Group Membership - Medium'), (13, 'Group Membership - Large'), (14, 'Group Membership - Unlimited')], help_text='The current membership tier of a user within Neon CRM'),
        ),
        migrations.AlterField(
            model_name='neonmembershipevent',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CL Membership - Basic'), (2, 'CL Legacy Membership'), (3, 'CL Membership - Tier 1'), (4, 'CL Membership - Tier 2'), (5, 'CL Membership - Tier 3'), (6, 'CL Membership - Tier 4'), (9, 'EDU Membership'), (10, 'Group Membership - Smallest'), (11, 'Group Membership - Small'), (12, 'Group Membership - Medium'), (13, 'Group Membership - Large'), (14, 'Group Membership - Unlimited')], help_text='The current membership tier of a user within Neon CRM'),
        ),
    ]
