# Generated by Django 5.1.8 on 2026-01-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0012_add_missing_membership_levels_noop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neonmembership',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CL Membership - Basic'), (2, 'CL Legacy Membership'), (3, 'CL Membership - Tier 1'), (4, 'CL Membership - Tier 2'), (5, 'CL Membership - Tier 3'), (6, 'CL Membership - Tier 4'), (9, 'EDU Membership'), (10, 'Group Membership - Smallest'), (11, 'Group Membership - Small'), (12, 'Group Membership - Medium'), (13, 'Group Membership - Large'), (14, 'Group Membership - Unlimited'), (20, 'Group Tier 1 Membership - Smallest'), (21, 'Group Tier 1 Membership - Small'), (22, 'Group Tier 1 Membership - Medium'), (23, 'Group Tier 1 Membership - Large'), (24, 'Group Tier 1 Membership - Unlimited'), (30, 'Group Tier 2 Membership - Smallest'), (31, 'Group Tier 2 Membership - Small'), (32, 'Group Tier 2 Membership - Medium'), (33, 'Group Tier 2 Membership - Large'), (34, 'Group Tier 2 Membership - Unlimited'), (40, 'Group Tier 3 Membership - Smallest'), (41, 'Group Tier 3 Membership - Small'), (42, 'Group Tier 3 Membership - Medium'), (43, 'Group Tier 3 Membership - Large'), (44, 'Group Tier 3 Membership - Unlimited'), (50, 'Group Tier 4 Membership - Smallest'), (51, 'Group Tier 4 Membership - Small'), (52, 'Group Tier 4 Membership - Medium'), (53, 'Group Tier 4 Membership - Large'), (54, 'Group Tier 4 Membership - Unlimited'), (60, 'HeyCounsel Tier 1'), (61, 'HeyCounsel Tier 2'), (62, 'HeyCounsel Tier 3'), (63, 'HeyCounsel Tier 4')], help_text='The current membership tier of a user within Neon CRM'),
        ),
        migrations.AlterField(
            model_name='neonmembershipevent',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CL Membership - Basic'), (2, 'CL Legacy Membership'), (3, 'CL Membership - Tier 1'), (4, 'CL Membership - Tier 2'), (5, 'CL Membership - Tier 3'), (6, 'CL Membership - Tier 4'), (9, 'EDU Membership'), (10, 'Group Membership - Smallest'), (11, 'Group Membership - Small'), (12, 'Group Membership - Medium'), (13, 'Group Membership - Large'), (14, 'Group Membership - Unlimited'), (20, 'Group Tier 1 Membership - Smallest'), (21, 'Group Tier 1 Membership - Small'), (22, 'Group Tier 1 Membership - Medium'), (23, 'Group Tier 1 Membership - Large'), (24, 'Group Tier 1 Membership - Unlimited'), (30, 'Group Tier 2 Membership - Smallest'), (31, 'Group Tier 2 Membership - Small'), (32, 'Group Tier 2 Membership - Medium'), (33, 'Group Tier 2 Membership - Large'), (34, 'Group Tier 2 Membership - Unlimited'), (40, 'Group Tier 3 Membership - Smallest'), (41, 'Group Tier 3 Membership - Small'), (42, 'Group Tier 3 Membership - Medium'), (43, 'Group Tier 3 Membership - Large'), (44, 'Group Tier 3 Membership - Unlimited'), (50, 'Group Tier 4 Membership - Smallest'), (51, 'Group Tier 4 Membership - Small'), (52, 'Group Tier 4 Membership - Medium'), (53, 'Group Tier 4 Membership - Large'), (54, 'Group Tier 4 Membership - Unlimited'), (60, 'HeyCounsel Tier 1'), (61, 'HeyCounsel Tier 2'), (62, 'HeyCounsel Tier 3'), (63, 'HeyCounsel Tier 4')], help_text='The current membership tier of a user within Neon CRM'),
        ),
    ]
