# Generated by Django 3.2.16 on 2023-01-17 17:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio', '0001_initial'),
        ('search', '0009_alter_court_jurisdiction'),
        ('favorites', '0002_rename_favorite_model_to_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='audio_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audio.audio', verbose_name='the audio file that is saved'),
        ),
        migrations.AlterField(
            model_name='note',
            name='cluster_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.opinioncluster', verbose_name='the opinion cluster that is saved'),
        ),
        migrations.AlterField(
            model_name='note',
            name='docket_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.docket', verbose_name='the docket that is saved'),
        ),
        migrations.AlterField(
            model_name='note',
            name='notes',
            field=models.TextField(blank=True, max_length=500, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='notes about the item saved'),
        ),
        migrations.AlterField(
            model_name='note',
            name='recap_doc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.recapdocument', verbose_name='the RECAP document that is saved'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(help_text='The user that owns the note', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
