# Generated by Django 3.2.18 on 2023-03-16 00:18

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0004_add_event_tables_and_triggers'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='dockettag',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='dockettag',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='note',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='note',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='prayer',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='prayer',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='usertag',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='usertag',
            name='snapshot_update',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='dockettag',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "favorites_dockettagevent" ("docket_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tag_id") VALUES (NEW."docket_id", NEW."id", _pgh_attach_context(), NOW(), \'custom_snapshot\', NEW."id", NEW."tag_id"); RETURN NULL;', hash='2245a35bf4b14b4c298bac1fc69728b67a4aa1aa', operation='INSERT', pgid='pgtrigger_custom_snapshot_insert_cc486', table='favorites_dockettag', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='dockettag',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "favorites_dockettagevent" ("docket_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tag_id") VALUES (OLD."docket_id", OLD."id", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."id", OLD."tag_id"); RETURN NULL;', hash='0d5e0dea082de5be16a88c01949c94c0769b4a8f', operation='UPDATE', pgid='pgtrigger_custom_snapshot_update_c954a', table='favorites_dockettag', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='note',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "favorites_noteevent" ("audio_id_id", "cluster_id_id", "date_created", "date_modified", "docket_id_id", "id", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recap_doc_id_id", "user_id") VALUES (NEW."audio_id_id", NEW."cluster_id_id", NEW."date_created", NEW."date_modified", NEW."docket_id_id", NEW."id", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'custom_snapshot\', NEW."id", NEW."recap_doc_id_id", NEW."user_id"); RETURN NULL;', hash='caf2ac98e3b1d3e25427d5e6c3cef33a73411f8b', operation='INSERT', pgid='pgtrigger_custom_snapshot_insert_3c2b9', table='favorites_note', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='note',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "favorites_noteevent" ("audio_id_id", "cluster_id_id", "date_created", "date_modified", "docket_id_id", "id", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recap_doc_id_id", "user_id") VALUES (OLD."audio_id_id", OLD."cluster_id_id", OLD."date_created", OLD."date_modified", OLD."docket_id_id", OLD."id", OLD."name", OLD."notes", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."id", OLD."recap_doc_id_id", OLD."user_id"); RETURN NULL;', hash='c9f4a67bd63a80a6b5a896efe503cc98d7f855e7', operation='UPDATE', pgid='pgtrigger_custom_snapshot_update_f3950', table='favorites_note', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='prayer',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "favorites_prayerevent" ("date_created", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recap_document_id", "status", "user_id") VALUES (NEW."date_created", NEW."id", _pgh_attach_context(), NOW(), \'custom_snapshot\', NEW."id", NEW."recap_document_id", NEW."status", NEW."user_id"); RETURN NULL;', hash='c54d1f0acbc31280198d11d4726ec8f21966538c', operation='INSERT', pgid='pgtrigger_custom_snapshot_insert_c50f7', table='favorites_prayer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='prayer',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "favorites_prayerevent" ("date_created", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recap_document_id", "status", "user_id") VALUES (OLD."date_created", OLD."id", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."id", OLD."recap_document_id", OLD."status", OLD."user_id"); RETURN NULL;', hash='0f2afb5555c3077b506dcc060b1e601194df07e7', operation='UPDATE', pgid='pgtrigger_custom_snapshot_update_2ec38', table='favorites_prayer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usertag',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "favorites_usertagevent" ("date_created", "date_modified", "description", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "title", "user_id") VALUES (NEW."date_created", NEW."date_modified", NEW."description", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'custom_snapshot\', NEW."id", NEW."published", NEW."title", NEW."user_id"); RETURN NULL;', hash='61c6862a024bdcf58ee49bfff5917a9e289e21bf', operation='INSERT', pgid='pgtrigger_custom_snapshot_insert_69c36', table='favorites_usertag', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usertag',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM NEW."id" OR OLD."user_id" IS DISTINCT FROM NEW."user_id" OR OLD."name" IS DISTINCT FROM NEW."name" OR OLD."title" IS DISTINCT FROM NEW."title" OR OLD."description" IS DISTINCT FROM NEW."description" OR OLD."published" IS DISTINCT FROM NEW."published")', func='INSERT INTO "favorites_usertagevent" ("date_created", "date_modified", "description", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "title", "user_id") VALUES (OLD."date_created", OLD."date_modified", OLD."description", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."id", OLD."published", OLD."title", OLD."user_id"); RETURN NULL;', hash='7cc87b68eebe9ef32ea286387409a1220b42a7d2', operation='UPDATE', pgid='pgtrigger_custom_snapshot_update_ee5b4', table='favorites_usertag', when='AFTER')),
        ),
    ]
