# Generated by Django 3.2.18 on 2023-03-18 00:29

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0004_add_event_tables_and_triggers'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='dockettag',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='dockettag',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='note',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='note',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='prayer',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='prayer',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='usertag',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='usertag',
            name='snapshot_update',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='dockettag',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "favorites_dockettagevent" ("docket_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tag_id") VALUES (OLD."docket_id", OLD."id", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."tag_id"); RETURN NULL;', hash='8f1df53f9cd8f17eb461118f6b48459fbf9db58e', operation='UPDATE', pgid='pgtrigger_update_or_delete_snapshot_update_88501', table='favorites_dockettag', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='dockettag',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "favorites_dockettagevent" ("docket_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tag_id") VALUES (OLD."docket_id", OLD."id", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."tag_id"); RETURN NULL;', hash='be481286dac59ff8609039001c4d5c0079f533c7', operation='DELETE', pgid='pgtrigger_update_or_delete_snapshot_delete_1a570', table='favorites_dockettag', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='note',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM NEW."id" OR OLD."date_created" IS DISTINCT FROM NEW."date_created" OR OLD."user_id" IS DISTINCT FROM NEW."user_id" OR OLD."cluster_id_id" IS DISTINCT FROM NEW."cluster_id_id" OR OLD."audio_id_id" IS DISTINCT FROM NEW."audio_id_id" OR OLD."docket_id_id" IS DISTINCT FROM NEW."docket_id_id" OR OLD."recap_doc_id_id" IS DISTINCT FROM NEW."recap_doc_id_id" OR OLD."name" IS DISTINCT FROM NEW."name" OR OLD."notes" IS DISTINCT FROM NEW."notes")', func='INSERT INTO "favorites_noteevent" ("audio_id_id", "cluster_id_id", "date_created", "date_modified", "docket_id_id", "id", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recap_doc_id_id", "user_id") VALUES (OLD."audio_id_id", OLD."cluster_id_id", OLD."date_created", OLD."date_modified", OLD."docket_id_id", OLD."id", OLD."name", OLD."notes", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."recap_doc_id_id", OLD."user_id"); RETURN NULL;', hash='fcd6d536ae66f06cea145de113f778913b839c34', operation='UPDATE', pgid='pgtrigger_update_or_delete_snapshot_update_ed3a1', table='favorites_note', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='note',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "favorites_noteevent" ("audio_id_id", "cluster_id_id", "date_created", "date_modified", "docket_id_id", "id", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recap_doc_id_id", "user_id") VALUES (OLD."audio_id_id", OLD."cluster_id_id", OLD."date_created", OLD."date_modified", OLD."docket_id_id", OLD."id", OLD."name", OLD."notes", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."recap_doc_id_id", OLD."user_id"); RETURN NULL;', hash='4c1d04b7683ae122c2497aeee499ec9ac1025f4a', operation='DELETE', pgid='pgtrigger_update_or_delete_snapshot_delete_b6726', table='favorites_note', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='prayer',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "favorites_prayerevent" ("date_created", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recap_document_id", "status", "user_id") VALUES (OLD."date_created", OLD."id", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."recap_document_id", OLD."status", OLD."user_id"); RETURN NULL;', hash='3bc4cc39bc791dfeb8fff181e29662e13ceae902', operation='UPDATE', pgid='pgtrigger_update_or_delete_snapshot_update_67cd0', table='favorites_prayer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='prayer',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "favorites_prayerevent" ("date_created", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recap_document_id", "status", "user_id") VALUES (OLD."date_created", OLD."id", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."recap_document_id", OLD."status", OLD."user_id"); RETURN NULL;', hash='e37fb648af3bce037c4d52a45d4202357da1ca8c', operation='DELETE', pgid='pgtrigger_update_or_delete_snapshot_delete_89611', table='favorites_prayer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usertag',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM NEW."id" OR OLD."date_created" IS DISTINCT FROM NEW."date_created" OR OLD."user_id" IS DISTINCT FROM NEW."user_id" OR OLD."name" IS DISTINCT FROM NEW."name" OR OLD."title" IS DISTINCT FROM NEW."title" OR OLD."description" IS DISTINCT FROM NEW."description" OR OLD."published" IS DISTINCT FROM NEW."published")', func='INSERT INTO "favorites_usertagevent" ("date_created", "date_modified", "description", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "title", "user_id") VALUES (OLD."date_created", OLD."date_modified", OLD."description", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."published", OLD."title", OLD."user_id"); RETURN NULL;', hash='1f0b6589dbf1673b54b022f55026d469b7497e06', operation='UPDATE', pgid='pgtrigger_update_or_delete_snapshot_update_9deec', table='favorites_usertag', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usertag',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "favorites_usertagevent" ("date_created", "date_modified", "description", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "title", "user_id") VALUES (OLD."date_created", OLD."date_modified", OLD."description", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."published", OLD."title", OLD."user_id"); RETURN NULL;', hash='ae91cd3be4454f2f23f7e656d244f63d8d79ff18', operation='DELETE', pgid='pgtrigger_update_or_delete_snapshot_delete_e4ac4', table='favorites_usertag', when='AFTER')),
        ),
    ]
