# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-23 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0007_add_unique_together'),
        ('favorites', '0007_abstract_datetime_model'),
    ]

    operations = [
    ]
