# Generated by Django 5.0.8 on 2024-09-21 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "favorites",
            "0007_rename_prayer_recap_document_status_favorites_p_recap_d_00e8c5_idx_and_more",
        ),
        ("search", "0034_add_harvard_pdf_to_opinioncluster"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="prayer",
            constraint=models.UniqueConstraint(
                fields=("user", "recap_document"),
                name="unique_prayer_for_user_document",
            ),
        ),
    ]
