# Generated by Django 5.0.8 on 2024-09-10 16:53

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("favorites", "0008_prayer_unique_prayer_for_user_document"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="dockettag",
            name="update_or_delete_snapshot_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="dockettag",
            name="update_or_delete_snapshot_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="note",
            name="update_or_delete_snapshot_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="note",
            name="update_or_delete_snapshot_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="prayer",
            name="update_or_delete_snapshot_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="prayer",
            name="update_or_delete_snapshot_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="usertag",
            name="update_or_delete_snapshot_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="usertag",
            name="update_or_delete_snapshot_update",
        ),
        migrations.AlterField(
            model_name="dockettagevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="favorites.dockettag",
            ),
        ),
        migrations.AlterField(
            model_name="noteevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="favorites.note",
            ),
        ),
        migrations.AlterField(
            model_name="prayerevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="favorites.prayer",
            ),
        ),
        migrations.AlterField(
            model_name="usertagevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="favorites.usertag",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="dockettag",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "favorites_dockettagevent" ("docket_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tag_id") VALUES (OLD."docket_id", OLD."id", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."tag_id"); RETURN NULL;',
                    hash="22c966e490778be46a88feb91352c39113f70aed",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_110f5",
                    table="favorites_dockettag",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="dockettag",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "favorites_dockettagevent" ("docket_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tag_id") VALUES (OLD."docket_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."tag_id"); RETURN NULL;',
                    hash="733f250b01fdd0f3c9493e757e08ecae30d8a51c",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_55118",
                    table="favorites_dockettag",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="note",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."audio_id_id" IS DISTINCT FROM (NEW."audio_id_id") OR OLD."cluster_id_id" IS DISTINCT FROM (NEW."cluster_id_id") OR OLD."docket_id_id" IS DISTINCT FROM (NEW."docket_id_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."recap_doc_id_id" IS DISTINCT FROM (NEW."recap_doc_id_id") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))',
                    func='INSERT INTO "favorites_noteevent" ("audio_id_id", "cluster_id_id", "date_created", "date_modified", "docket_id_id", "id", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recap_doc_id_id", "user_id") VALUES (OLD."audio_id_id", OLD."cluster_id_id", OLD."date_created", OLD."date_modified", OLD."docket_id_id", OLD."id", OLD."name", OLD."notes", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."recap_doc_id_id", OLD."user_id"); RETURN NULL;',
                    hash="4ea97fb38a73a10ea8800879c916a5d49014a870",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_8ef2a",
                    table="favorites_note",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="note",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "favorites_noteevent" ("audio_id_id", "cluster_id_id", "date_created", "date_modified", "docket_id_id", "id", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recap_doc_id_id", "user_id") VALUES (OLD."audio_id_id", OLD."cluster_id_id", OLD."date_created", OLD."date_modified", OLD."docket_id_id", OLD."id", OLD."name", OLD."notes", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."recap_doc_id_id", OLD."user_id"); RETURN NULL;',
                    hash="271c9da155a4b05ff0c38ffe427ab4d124f6060a",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_eebc8",
                    table="favorites_note",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="prayer",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."recap_document_id" IS DISTINCT FROM (NEW."recap_document_id") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))',
                    func='INSERT INTO "favorites_prayerevent" ("date_created", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recap_document_id", "status", "user_id") VALUES (OLD."date_created", OLD."id", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."recap_document_id", OLD."status", OLD."user_id"); RETURN NULL;',
                    hash="30bdce2e3992f50c8f8aa205d81d3008fcf6dc69",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_4ac15",
                    table="favorites_prayer",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="prayer",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "favorites_prayerevent" ("date_created", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recap_document_id", "status", "user_id") VALUES (OLD."date_created", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."recap_document_id", OLD."status", OLD."user_id"); RETURN NULL;',
                    hash="90606969447d9cb1cba457986ba54ef5158ec5bb",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_0bac2",
                    table="favorites_prayer",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="usertag",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."published" IS DISTINCT FROM (NEW."published") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))',
                    func='INSERT INTO "favorites_usertagevent" ("date_created", "date_modified", "description", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "title", "user_id") VALUES (OLD."date_created", OLD."date_modified", OLD."description", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."published", OLD."title", OLD."user_id"); RETURN NULL;',
                    hash="79e7e7ba10ed9b4e1a697a182ec407fd443f8112",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_e2b0e",
                    table="favorites_usertag",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="usertag",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "favorites_usertagevent" ("date_created", "date_modified", "description", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published", "title", "user_id") VALUES (OLD."date_created", OLD."date_modified", OLD."description", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."published", OLD."title", OLD."user_id"); RETURN NULL;',
                    hash="b308b0a84f02836a28a017ebb430410becfdb4ba",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_db01a",
                    table="favorites_usertag",
                    when="AFTER",
                ),
            ),
        ),
    ]
