# Generated by Django 5.1.5 on 2025-03-23 02:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("favorites", "0009_pghistory_v3_4_0_trigger_update"),
        ("search", "0037_alter_citation_type_noop"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrayerAvailability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_checked",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025,
                            3,
                            23,
                            2,
                            44,
                            46,
                            731346,
                            tzinfo=datetime.timezone.utc,
                        ),
                        help_text="The time when the availability of this document was last checked.",
                    ),
                ),
                (
                    "recap_document",
                    models.ForeignKey(
                        help_text="The document people prayed for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prayeravailability",
                        to="search.recapdocument",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["recap_document", "last_checked"],
                        name="favorites_p_recap_d_23db1e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recap_document",),
                        name="unique_recap_document",
                    )
                ],
            },
        ),
    ]
