# Generated by Django 5.1.7 on 2025-03-31 02:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("favorites", "0009_pghistory_v3_4_0_trigger_update"),
        ("search", "0037_alter_citation_type_noop"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrayerAvailability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_checked",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The time when the availability of this document was last checked.",
                    ),
                ),
                (
                    "recap_document",
                    models.ForeignKey(
                        help_text="The document people prayed for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prayeravailability",
                        to="search.recapdocument",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recap_document",),
                        include=("last_checked",),
                        name="unique_recap_document",
                    )
                ],
            },
        ),
    ]
