# Generated by Django 5.1.8 on 2025-06-18 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0010_create_prayeravailability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prayeravailability',
            options={'verbose_name_plural': 'Prayer Availabilities'},
        ),
    ]
