# Generated by Django 6.0.1 on 2026-03-20 23:13

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0012_genericcount'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='prayer',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='prayer',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='prayer',
            name='source',
            field=models.SmallIntegerField(choices=[(1, 'Website'), (2, 'API request')], default=1, help_text='The interface used to create the prayer.'),
        ),
        migrations.AddField(
            model_name='prayerevent',
            name='source',
            field=models.SmallIntegerField(choices=[(1, 'Website'), (2, 'API request')], default=1, help_text='The interface used to create the prayer.'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='prayer',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."recap_document_id" IS DISTINCT FROM (NEW."recap_document_id") OR OLD."source" IS DISTINCT FROM (NEW."source") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))', func='INSERT INTO "favorites_prayerevent" ("date_created", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recap_document_id", "source", "status", "user_id") VALUES (OLD."date_created", OLD."id", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."recap_document_id", OLD."source", OLD."status", OLD."user_id"); RETURN NULL;', hash='a27b578b6a9e3352c6eaf5180b7538173fdf1056', operation='UPDATE', pgid='pgtrigger_update_update_4ac15', table='favorites_prayer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='prayer',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "favorites_prayerevent" ("date_created", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recap_document_id", "source", "status", "user_id") VALUES (OLD."date_created", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."recap_document_id", OLD."source", OLD."status", OLD."user_id"); RETURN NULL;', hash='1aa7a432c088f0f642ce443b20fab34836a72adb', operation='DELETE', pgid='pgtrigger_delete_delete_0bac2', table='favorites_prayer', when='AFTER')),
        ),
    ]
