# Generated by Django 3.1.14 on 2022-03-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_recap_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(help_text='Email address flagged.', max_length=254)),
                ('flag_type', models.CharField(choices=[('ban', 'Email ban'), ('flag', 'Email flag')], help_text='The flag type assigned.', max_length=5)),
                ('flag', models.CharField(blank=True, help_text='The flag assigned to email address.', max_length=25)),
                ('reason', models.CharField(blank=True, help_text='The notification subtype', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The moment when the item was created.')),
            ],
        ),
        migrations.AddIndex(
            model_name='emailflag',
            index=models.Index(fields=['email_address'], name='users_email_email_a_624792_idx'),
        ),
    ]
