# Generated by Django 3.1.14 on 2022-03-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_email_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackoffEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(help_text='Email address under backoff event.', max_length=254)),
                ('retry_counter', models.SmallIntegerField(help_text='The retry counter for exponential backoff events.')),
                ('next_retry_date', models.DateTimeField(help_text='The datetime for next retry.')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The moment when the item was created.')),
            ],
        ),
        migrations.AddIndex(
            model_name='backoffevent',
            index=models.Index(fields=['email_address'], name='users_backo_email_a_f71b7f_idx'),
        ),
    ]
