# Generated by Django 3.2.13 on 2022-05-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_failed_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='backoffevent',
            name='notification_subtype',
            field=models.SmallIntegerField(choices=[(0, 'Undetermined'), (1, 'General'), (2, 'NoEmail'), (3, 'Suppressed'), (4, 'OnAccountSuppressionList'), (5, 'MailboxFull'), (6, 'MessageTooLarge'), (7, 'ContentRejected'), (8, 'AttachmentRejected'), (9, 'Complaint'), (10, 'Other')], default=0, help_text='The SES notification subtype that triggered the object.'),
        ),
        migrations.AlterField(
            model_name='backoffevent',
            name='email_address',
            field=models.EmailField(help_text='The email address the Backoff event is related to.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='emailflag',
            name='email_address',
            field=models.EmailField(help_text='The email address the EmailFlag object is related to.', max_length=254),
        ),
        migrations.AlterField(
            model_name='emailflag',
            name='event_sub_type',
            field=models.SmallIntegerField(choices=[(0, 'Undetermined'), (1, 'General'), (2, 'NoEmail'), (3, 'Suppressed'), (4, 'OnAccountSuppressionList'), (5, 'MailboxFull'), (6, 'MessageTooLarge'), (7, 'ContentRejected'), (8, 'AttachmentRejected'), (9, 'Complaint'), (10, 'Other')], help_text='The SES notification subtype that triggered the object.'),
        ),
        migrations.AlterField(
            model_name='emailflag',
            name='flag',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Small Email Only'), (1, 'Max Retry Reached')], help_text='The actual flag assigned, e.g: Small Email Only.', null=True),
        ),
    ]
