# Generated by Django 3.2.13 on 2022-05-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_failed_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='backoffevent',
            name='event_sub_type',
            field=models.SmallIntegerField(choices=[(0, 'Undetermined'), (1, 'General'), (2, 'NoEmail'), (3, 'Suppressed'), (4, 'OnAccountSuppressionList'), (5, 'MailboxFull'), (6, 'MessageTooLarge'), (7, 'ContentRejected'), (8, 'AttachmentRejected'), (9, 'Complaint'), (10, 'Other')], default=0, help_text='The SNS bounce subtype that triggered the object.'),
        ),
    ]
