# Generated by Django 3.2.13 on 2022-06-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_failed_email_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_subscribe',
            field=models.BooleanField(default=False, help_text="If enabled, for every new case that comes in from the user's recap.email address, a new docket subscription for the case will be created; if disabled we'll ask users if they want to subscribe to the case."),
        ),
    ]
