# Generated by Django 3.2.12 on 2022-03-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_backoff_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backoffevent',
            name='email_address',
            field=models.EmailField(help_text="The backoff event is related to this email address instead of a user, in this way, if users change their email address this won't affect the user's new email address.", max_length=254),
        ),
        migrations.AlterField(
            model_name='backoffevent',
            name='next_retry_date',
            field=models.DateTimeField(help_text='The next retry datetime for exponential backoff events.'),
        ),
        migrations.AlterField(
            model_name='emailflag',
            name='email_address',
            field=models.EmailField(help_text="EmailFlag object is related to this email address instead of a user, in this way, if users change their email address this won't affect the user's new email address.", max_length=254),
        ),
        migrations.AlterField(
            model_name='emailflag',
            name='event_sub_type',
            field=models.SmallIntegerField(choices=[(0, 'Undetermined'), (1, 'General'), (2, 'NoEmail'), (3, 'Suppressed'), (4, 'OnAccountSuppressionList'), (5, 'MailboxFull'), (6, 'MessageTooLarge'), (7, 'ContentRejected'), (8, 'AttachmentRejected'), (9, 'Complaint'), (10, 'Other')], help_text='The SNS bounce subtype that triggered the object.'),
        ),
        migrations.AlterField(
            model_name='emailflag',
            name='flag',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'small_email_only'), (1, 'max_retry_reached')], help_text='The actual flag assigned, e.g: small_email_only.', null=True),
        ),
        migrations.AlterField(
            model_name='emailflag',
            name='object_type',
            field=models.SmallIntegerField(choices=[(0, 'Email ban'), (1, 'Email flag')], help_text='The object type assigned, Email ban: ban an email address and avoid sending any email. Email flag: flag an email address for a special treatment.'),
        ),
    ]
