# Generated by Django 3.2.12 on 2022-03-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_help_text'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='backoffevent',
            name='users_backo_email_a_f71b7f_idx',
        ),
        migrations.AlterField(
            model_name='backoffevent',
            name='email_address',
            field=models.EmailField(help_text="The backoff event is related to this email address instead of a user, in this way, if users change their email address this won't affect the user's new email address, this unique.", max_length=254, unique=True),
        ),
        migrations.AddConstraint(
            model_name='emailflag',
            constraint=models.UniqueConstraint(condition=models.Q(('object_type', 0)), fields=('email_address',), name='unique_email_ban'),
        ),
    ]
