# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-17 13:17

from __future__ import unicode_literals

from django.db import migrations, models


def make_tenn_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group",)
    Group.objects.create(name="Tennessee",)


def delete_tenn_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="Tennessee").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_add_is_tester_field"),
    ]

    operations = [
        migrations.RunPython(make_tenn_group, reverse_code=delete_tenn_group)
    ]
