# Generated by Django 3.2.15 on 2022-10-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_tweak_verbose_name_noop'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailflag',
            name='checked',
            field=models.DateTimeField(blank=True, help_text="The datetime the recipient's deliverability was checked since the last bounce event.", null=True),
        ),
        migrations.AddIndex(
            model_name='emailflag',
            index=models.Index(fields=['flag_type', 'checked'], name='users_email_flag_ty_5341fa_idx'),
        ),
    ]
