# Generated by Django 3.2.18 on 2023-03-16 02:47

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_event_tables_and_triggers'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='grouppermissions',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='grouppermissions',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='groupproxy',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='groupproxy',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='permissionproxy',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='permissionproxy',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='usergroups',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='usergroups',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='userpermissions',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='userpermissions',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='userprofile',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='userprofile',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='userprofilebarmembership',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='userprofilebarmembership',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='userproxy',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='userproxy',
            name='snapshot_update',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='grouppermissions',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_grouppermissionsevent" ("group_id", "id", "permission_id", "pgh_context_id", "pgh_created_at", "pgh_label") VALUES (NEW."group_id", NEW."id", NEW."permission_id", _pgh_attach_context(), NOW(), \'custom_snapshot\'); RETURN NULL;', hash='a913be0ded6e322227721a9a76e5762d3e186368', operation='INSERT', pgid='pgtrigger_custom_snapshot_insert_c4ca5', table='auth_group_permissions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='grouppermissions',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "users_grouppermissionsevent" ("group_id", "id", "permission_id", "pgh_context_id", "pgh_created_at", "pgh_label") VALUES (OLD."group_id", OLD."id", OLD."permission_id", _pgh_attach_context(), NOW(), \'custom_snapshot\'); RETURN NULL;', hash='1a8e56395d1425a8b0fb5014d274dc76d74a110e', operation='UPDATE', pgid='pgtrigger_custom_snapshot_update_9dcb9', table='auth_group_permissions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='groupproxy',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_groupproxyevent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'custom_snapshot\', NEW."id"); RETURN NULL;', hash='46895547f519f8ca245c474f09f509b2da67cb34', operation='INSERT', pgid='pgtrigger_custom_snapshot_insert_f2fc5', table='auth_group', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='groupproxy',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "users_groupproxyevent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."id"); RETURN NULL;', hash='ba78b5f0795b51cf67736067a943b3fecc3af9f0', operation='UPDATE', pgid='pgtrigger_custom_snapshot_update_3afa4', table='auth_group', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='permissionproxy',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_permissionproxyevent" ("codename", "content_type_id", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."codename", NEW."content_type_id", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'custom_snapshot\', NEW."id"); RETURN NULL;', hash='6e202b10078d446c99dfa8e2e02f5890508b2fc7', operation='INSERT', pgid='pgtrigger_custom_snapshot_insert_44e9e', table='auth_permission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='permissionproxy',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "users_permissionproxyevent" ("codename", "content_type_id", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."codename", OLD."content_type_id", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."id"); RETURN NULL;', hash='81dd17f9a5fe251ed7fb28dbe0e6e4d91a07ffdb', operation='UPDATE', pgid='pgtrigger_custom_snapshot_update_6176f', table='auth_permission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usergroups',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_usergroupsevent" ("group_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "user_id") VALUES (NEW."group_id", NEW."id", _pgh_attach_context(), NOW(), \'custom_snapshot\', NEW."user_id"); RETURN NULL;', hash='4705d749296d26be77c7d84047327da208f05950', operation='INSERT', pgid='pgtrigger_custom_snapshot_insert_096ce', table='auth_user_groups', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usergroups',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "users_usergroupsevent" ("group_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "user_id") VALUES (OLD."group_id", OLD."id", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."user_id"); RETURN NULL;', hash='ceba1d0a6dcdd784efa76bab3ae8e352a3893b44', operation='UPDATE', pgid='pgtrigger_custom_snapshot_update_cfd8c', table='auth_user_groups', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userpermissions',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_userpermissionsevent" ("id", "permission_id", "pgh_context_id", "pgh_created_at", "pgh_label", "user_id") VALUES (NEW."id", NEW."permission_id", _pgh_attach_context(), NOW(), \'custom_snapshot\', NEW."user_id"); RETURN NULL;', hash='8fa18f2bc1d66b93b0cdc4420aac75287f9cd915', operation='INSERT', pgid='pgtrigger_custom_snapshot_insert_e7d6b', table='auth_user_user_permissions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userpermissions',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "users_userpermissionsevent" ("id", "permission_id", "pgh_context_id", "pgh_created_at", "pgh_label", "user_id") VALUES (OLD."id", OLD."permission_id", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."user_id"); RETURN NULL;', hash='38242fce23b92a51e16d445a2a71739afd67c3e3', operation='UPDATE', pgid='pgtrigger_custom_snapshot_update_f1f22', table='auth_user_user_permissions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userprofile',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_userprofileevent" ("activation_key", "address1", "address2", "auto_subscribe", "avatar", "city", "email_confirmed", "employer", "id", "is_tester", "key_expires", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plaintext_preferred", "recap_email", "state", "stub_account", "unlimited_docket_alerts", "user_id", "wants_newsletter", "zip_code") VALUES (NEW."activation_key", NEW."address1", NEW."address2", NEW."auto_subscribe", NEW."avatar", NEW."city", NEW."email_confirmed", NEW."employer", NEW."id", NEW."is_tester", NEW."key_expires", NEW."notes", _pgh_attach_context(), NOW(), \'custom_snapshot\', NEW."id", NEW."plaintext_preferred", NEW."recap_email", NEW."state", NEW."stub_account", NEW."unlimited_docket_alerts", NEW."user_id", NEW."wants_newsletter", NEW."zip_code"); RETURN NULL;', hash='9ec4e32f15588487400cefa3993f1f740c64c97d', operation='INSERT', pgid='pgtrigger_custom_snapshot_insert_11340', table='users_userprofile', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userprofile',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "users_userprofileevent" ("activation_key", "address1", "address2", "auto_subscribe", "avatar", "city", "email_confirmed", "employer", "id", "is_tester", "key_expires", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plaintext_preferred", "recap_email", "state", "stub_account", "unlimited_docket_alerts", "user_id", "wants_newsletter", "zip_code") VALUES (OLD."activation_key", OLD."address1", OLD."address2", OLD."auto_subscribe", OLD."avatar", OLD."city", OLD."email_confirmed", OLD."employer", OLD."id", OLD."is_tester", OLD."key_expires", OLD."notes", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."id", OLD."plaintext_preferred", OLD."recap_email", OLD."state", OLD."stub_account", OLD."unlimited_docket_alerts", OLD."user_id", OLD."wants_newsletter", OLD."zip_code"); RETURN NULL;', hash='0d086b7148d56eb34bf1491e0b222d82d7e006a2', operation='UPDATE', pgid='pgtrigger_custom_snapshot_update_34fb2', table='users_userprofile', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userprofilebarmembership',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_userprofilebarmembershipevent" ("barmembership_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "userprofile_id") VALUES (NEW."barmembership_id", NEW."id", _pgh_attach_context(), NOW(), \'custom_snapshot\', NEW."userprofile_id"); RETURN NULL;', hash='73f015bfb608275e7648ded13a236d0ca3b0844f', operation='INSERT', pgid='pgtrigger_custom_snapshot_insert_3a21a', table='users_userprofile_barmembership', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userprofilebarmembership',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "users_userprofilebarmembershipevent" ("barmembership_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "userprofile_id") VALUES (OLD."barmembership_id", OLD."id", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."userprofile_id"); RETURN NULL;', hash='323ae60f4f3db7e65d3e75d54df24d227b8a274f', operation='UPDATE', pgid='pgtrigger_custom_snapshot_update_d59ec', table='users_userprofile_barmembership', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userproxy',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_userproxyevent" ("date_joined", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_login", "last_name", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "username") VALUES (NEW."date_joined", NEW."email", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_login", NEW."last_name", NEW."password", _pgh_attach_context(), NOW(), \'custom_snapshot\', NEW."id", NEW."username"); RETURN NULL;', hash='350f796baa24063fde11bc2c8e2b3c9fc4e32406', operation='INSERT', pgid='pgtrigger_custom_snapshot_insert_b3032', table='auth_user', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userproxy',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "users_userproxyevent" ("date_joined", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_login", "last_name", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "username") VALUES (OLD."date_joined", OLD."email", OLD."first_name", OLD."id", OLD."is_active", OLD."is_staff", OLD."is_superuser", OLD."last_login", OLD."last_name", OLD."password", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."id", OLD."username"); RETURN NULL;', hash='77562423dbf9160fc240cd27f477ae8a877b188b', operation='UPDATE', pgid='pgtrigger_custom_snapshot_update_aa503', table='auth_user', when='AFTER')),
        ),
    ]
