# Generated by Django 3.2.18 on 2023-04-10 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_docket_default_order_desc'),
        ('users', '0011_update_triggers'),
    ]

    operations = [
    ]
