# Generated by Django 3.2.18 on 2023-04-10 23:02

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_docket_default_order_desc'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='grouppermissions',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='grouppermissions',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='groupproxy',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='groupproxy',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='permissionproxy',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='permissionproxy',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='usergroups',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='usergroups',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='userpermissions',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='userpermissions',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='userprofile',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='userprofile',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='userprofilebarmembership',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='userprofilebarmembership',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='userproxy',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='userproxy',
            name='snapshot_update',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='grouppermissions',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "users_grouppermissionsevent" ("group_id", "id", "permission_id", "pgh_context_id", "pgh_created_at", "pgh_label") VALUES (OLD."group_id", OLD."id", OLD."permission_id", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\'); RETURN NULL;', hash='dda10f45a908286aee8498dd6919f4469ce9b9ad', operation='UPDATE', pgid='pgtrigger_update_or_delete_snapshot_update_7bfc9', table='auth_group_permissions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='grouppermissions',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_grouppermissionsevent" ("group_id", "id", "permission_id", "pgh_context_id", "pgh_created_at", "pgh_label") VALUES (OLD."group_id", OLD."id", OLD."permission_id", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\'); RETURN NULL;', hash='4402ea2dbb97b3274b2af5623b8744983805172c', operation='DELETE', pgid='pgtrigger_update_or_delete_snapshot_delete_09233', table='auth_group_permissions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='groupproxy',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "users_groupproxyevent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id"); RETURN NULL;', hash='aa1d93825a6d36ca10f98b47e436f8c817f6842e', operation='UPDATE', pgid='pgtrigger_update_or_delete_snapshot_update_98718', table='auth_group', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='groupproxy',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_groupproxyevent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id"); RETURN NULL;', hash='9dd3dc558d20bb42c358636e9620377cc2369c2c', operation='DELETE', pgid='pgtrigger_update_or_delete_snapshot_delete_4d24b', table='auth_group', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='permissionproxy',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "users_permissionproxyevent" ("codename", "content_type_id", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."codename", OLD."content_type_id", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id"); RETURN NULL;', hash='14a3f3cafcfbdd3842550ed7e8020d54045d611e', operation='UPDATE', pgid='pgtrigger_update_or_delete_snapshot_update_e1c9f', table='auth_permission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='permissionproxy',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_permissionproxyevent" ("codename", "content_type_id", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."codename", OLD."content_type_id", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id"); RETURN NULL;', hash='e04e12d446b8e9a74882a42f972fe9010770b419', operation='DELETE', pgid='pgtrigger_update_or_delete_snapshot_delete_11509', table='auth_permission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usergroups',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "users_usergroupsevent" ("group_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "user_id") VALUES (OLD."group_id", OLD."id", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."user_id"); RETURN NULL;', hash='81e6f6fc164efc85f6edcc0ee1d49805b172ef5e', operation='UPDATE', pgid='pgtrigger_update_or_delete_snapshot_update_58112', table='auth_user_groups', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usergroups',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_usergroupsevent" ("group_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "user_id") VALUES (OLD."group_id", OLD."id", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."user_id"); RETURN NULL;', hash='04d987731772f8f175f3dc7dfa3506ae9d4c3894', operation='DELETE', pgid='pgtrigger_update_or_delete_snapshot_delete_cd0a6', table='auth_user_groups', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userpermissions',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "users_userpermissionsevent" ("id", "permission_id", "pgh_context_id", "pgh_created_at", "pgh_label", "user_id") VALUES (OLD."id", OLD."permission_id", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."user_id"); RETURN NULL;', hash='0e8867ca245b7b4a4350b540f6a611ebf05ddbc7', operation='UPDATE', pgid='pgtrigger_update_or_delete_snapshot_update_b7585', table='auth_user_user_permissions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userpermissions',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_userpermissionsevent" ("id", "permission_id", "pgh_context_id", "pgh_created_at", "pgh_label", "user_id") VALUES (OLD."id", OLD."permission_id", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."user_id"); RETURN NULL;', hash='0aeeaceeb8547987202afae4fabe968e44040a2d', operation='DELETE', pgid='pgtrigger_update_or_delete_snapshot_delete_17cec', table='auth_user_user_permissions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userprofile',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "users_userprofileevent" ("activation_key", "address1", "address2", "auto_subscribe", "avatar", "city", "docket_default_order_desc", "email_confirmed", "employer", "id", "is_tester", "key_expires", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plaintext_preferred", "recap_email", "state", "stub_account", "unlimited_docket_alerts", "user_id", "wants_newsletter", "zip_code") VALUES (OLD."activation_key", OLD."address1", OLD."address2", OLD."auto_subscribe", OLD."avatar", OLD."city", OLD."docket_default_order_desc", OLD."email_confirmed", OLD."employer", OLD."id", OLD."is_tester", OLD."key_expires", OLD."notes", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."plaintext_preferred", OLD."recap_email", OLD."state", OLD."stub_account", OLD."unlimited_docket_alerts", OLD."user_id", OLD."wants_newsletter", OLD."zip_code"); RETURN NULL;', hash='0dde39ef7888bd8ac1239a2f665b33b8de703af4', operation='UPDATE', pgid='pgtrigger_update_or_delete_snapshot_update_c9b7b', table='users_userprofile', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userprofile',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_userprofileevent" ("activation_key", "address1", "address2", "auto_subscribe", "avatar", "city", "docket_default_order_desc", "email_confirmed", "employer", "id", "is_tester", "key_expires", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plaintext_preferred", "recap_email", "state", "stub_account", "unlimited_docket_alerts", "user_id", "wants_newsletter", "zip_code") VALUES (OLD."activation_key", OLD."address1", OLD."address2", OLD."auto_subscribe", OLD."avatar", OLD."city", OLD."docket_default_order_desc", OLD."email_confirmed", OLD."employer", OLD."id", OLD."is_tester", OLD."key_expires", OLD."notes", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."plaintext_preferred", OLD."recap_email", OLD."state", OLD."stub_account", OLD."unlimited_docket_alerts", OLD."user_id", OLD."wants_newsletter", OLD."zip_code"); RETURN NULL;', hash='f3a89f21d5285009b1c78a6e6434dc51da5b9314', operation='DELETE', pgid='pgtrigger_update_or_delete_snapshot_delete_f463b', table='users_userprofile', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userprofilebarmembership',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "users_userprofilebarmembershipevent" ("barmembership_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "userprofile_id") VALUES (OLD."barmembership_id", OLD."id", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."userprofile_id"); RETURN NULL;', hash='40454d33f14945213a91ef7401ab0d32abcb69ea', operation='UPDATE', pgid='pgtrigger_update_or_delete_snapshot_update_dd24a', table='users_userprofile_barmembership', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userprofilebarmembership',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_userprofilebarmembershipevent" ("barmembership_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "userprofile_id") VALUES (OLD."barmembership_id", OLD."id", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."userprofile_id"); RETURN NULL;', hash='112520df9e7eede66b40cdcc23ae23175ce42362', operation='DELETE', pgid='pgtrigger_update_or_delete_snapshot_delete_1a7fe', table='users_userprofile_barmembership', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userproxy',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "users_userproxyevent" ("date_joined", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_login", "last_name", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "username") VALUES (OLD."date_joined", OLD."email", OLD."first_name", OLD."id", OLD."is_active", OLD."is_staff", OLD."is_superuser", OLD."last_login", OLD."last_name", OLD."password", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."username"); RETURN NULL;', hash='39a450a930c2a34ee6ce8f0523e6e1e53c3fdcfd', operation='UPDATE', pgid='pgtrigger_update_or_delete_snapshot_update_d8df2', table='auth_user', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userproxy',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_userproxyevent" ("date_joined", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_login", "last_name", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "username") VALUES (OLD."date_joined", OLD."email", OLD."first_name", OLD."id", OLD."is_active", OLD."is_staff", OLD."is_superuser", OLD."last_login", OLD."last_name", OLD."password", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."username"); RETURN NULL;', hash='5fc996933c46fa65e83c44b0f81b514f074ceeb2', operation='DELETE', pgid='pgtrigger_update_or_delete_snapshot_delete_9691d', table='auth_user', when='AFTER')),
        ),
    ]
