# Generated by Django 5.0.1 on 2024-02-03 22:20

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0013_remove_userprofile_update_or_delete_snapshot_update_and_more",
        ),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="userprofile",
            name="update_or_delete_snapshot_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="userprofile",
            name="update_or_delete_snapshot_delete",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="wants_newsletter",
        ),
        migrations.RemoveField(
            model_name="userprofileevent",
            name="wants_newsletter",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="userprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="update_or_delete_snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "users_userprofileevent" ("activation_key", "address1", "address2", "auto_subscribe", "avatar", "city", "docket_default_order_desc", "email_confirmed", "employer", "id", "is_tester", "key_expires", "neon_account_id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plaintext_preferred", "recap_email", "state", "stub_account", "unlimited_docket_alerts", "user_id", "zip_code") VALUES (OLD."activation_key", OLD."address1", OLD."address2", OLD."auto_subscribe", OLD."avatar", OLD."city", OLD."docket_default_order_desc", OLD."email_confirmed", OLD."employer", OLD."id", OLD."is_tester", OLD."key_expires", OLD."neon_account_id", OLD."notes", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."plaintext_preferred", OLD."recap_email", OLD."state", OLD."stub_account", OLD."unlimited_docket_alerts", OLD."user_id", OLD."zip_code"); RETURN NULL;',
                    hash="a236caf8b36ad5402c1b675cb3b6dbf11868bb4f",
                    operation="UPDATE",
                    pgid="pgtrigger_update_or_delete_snapshot_update_c9b7b",
                    table="users_userprofile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="userprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="update_or_delete_snapshot_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "users_userprofileevent" ("activation_key", "address1", "address2", "auto_subscribe", "avatar", "city", "docket_default_order_desc", "email_confirmed", "employer", "id", "is_tester", "key_expires", "neon_account_id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plaintext_preferred", "recap_email", "state", "stub_account", "unlimited_docket_alerts", "user_id", "zip_code") VALUES (OLD."activation_key", OLD."address1", OLD."address2", OLD."auto_subscribe", OLD."avatar", OLD."city", OLD."docket_default_order_desc", OLD."email_confirmed", OLD."employer", OLD."id", OLD."is_tester", OLD."key_expires", OLD."neon_account_id", OLD."notes", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."plaintext_preferred", OLD."recap_email", OLD."state", OLD."stub_account", OLD."unlimited_docket_alerts", OLD."user_id", OLD."zip_code"); RETURN NULL;',
                    hash="a5e74626ec0baacab556ca4ad27c637b8d2d4b05",
                    operation="DELETE",
                    pgid="pgtrigger_update_or_delete_snapshot_delete_f463b",
                    table="users_userprofile",
                    when="AFTER",
                ),
            ),
        ),
    ]
