# Generated by Django 6.0.7 on 2026-08-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_add_flag_to_make_prayers_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="activation_key",
            field=models.CharField(
                blank=True,
                help_text="A single-use key emailed to the user to confirm their email address. Blanked once it is spent (GHSA-638g-xf9h-6qcg), so it is empty for most accounts.",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="userprofileevent",
            name="activation_key",
            field=models.CharField(
                blank=True,
                help_text="A single-use key emailed to the user to confirm their email address. Blanked once it is spent (GHSA-638g-xf9h-6qcg), so it is empty for most accounts.",
                max_length=40,
            ),
        ),
    ]
