# Generated by Django 6.0.8 on 2026-09-27 16:10

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_add_auth_user_email_lower_index"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="userprofile",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="userprofile",
            name="delete_delete",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="save_query_history",
            field=models.BooleanField(
                default=True,
                help_text="Should the user's search query history be saved?",
            ),
        ),
        migrations.AddField(
            model_name="userprofileevent",
            name="save_query_history",
            field=models.BooleanField(
                default=True,
                help_text="Should the user's search query history be saved?",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="userprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "users_userprofileevent" ("activation_key", "address1", "address2", "auto_subscribe", "avatar", "city", "docket_default_order_desc", "email_confirmed", "employer", "id", "is_tester", "key_expires", "neon_account_id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plaintext_preferred", "prayers_public", "recap_email", "save_query_history", "state", "stub_account", "unlimited_docket_alerts", "user_id", "zip_code") VALUES (OLD."activation_key", OLD."address1", OLD."address2", OLD."auto_subscribe", OLD."avatar", OLD."city", OLD."docket_default_order_desc", OLD."email_confirmed", OLD."employer", OLD."id", OLD."is_tester", OLD."key_expires", OLD."neon_account_id", OLD."notes", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."plaintext_preferred", OLD."prayers_public", OLD."recap_email", OLD."save_query_history", OLD."state", OLD."stub_account", OLD."unlimited_docket_alerts", OLD."user_id", OLD."zip_code"); RETURN NULL;',
                    hash="f172dcdd63696bf6a1808575f814409665e3bd25",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_52a36",
                    table="users_userprofile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="userprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "users_userprofileevent" ("activation_key", "address1", "address2", "auto_subscribe", "avatar", "city", "docket_default_order_desc", "email_confirmed", "employer", "id", "is_tester", "key_expires", "neon_account_id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plaintext_preferred", "prayers_public", "recap_email", "save_query_history", "state", "stub_account", "unlimited_docket_alerts", "user_id", "zip_code") VALUES (OLD."activation_key", OLD."address1", OLD."address2", OLD."auto_subscribe", OLD."avatar", OLD."city", OLD."docket_default_order_desc", OLD."email_confirmed", OLD."employer", OLD."id", OLD."is_tester", OLD."key_expires", OLD."neon_account_id", OLD."notes", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."plaintext_preferred", OLD."prayers_public", OLD."recap_email", OLD."save_query_history", OLD."state", OLD."stub_account", OLD."unlimited_docket_alerts", OLD."user_id", OLD."zip_code"); RETURN NULL;',
                    hash="7ce68e040ac36c8e7170073005b8e0950fc97721",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_4530f",
                    table="users_userprofile",
                    when="AFTER",
                ),
            ),
        ),
    ]
