"""
This tool allows you to partially clone data from courtlistener.com to your
local environment, you only need to pass the type and object id and run it.

manage.py clone_from_cl --type Opinion --id 9355884
manage.py clone_from_cl --type Docket --id 5377675
manage.py clone_from_cl --type Person --id 16207
manage.py clone_from_cl --type Court --id usnmcmilrev

This tool is only for development purposes, so it only works when
the DEVELOPMENT env is set to True. It also relies on the CL_API_TOKEN
env variable.

This is still work in progress, some data is not cloned yet.
"""

import os
import sys

import requests
from django.conf import settings
from django.db import transaction
from django.urls import reverse
from django.utils.dateparse import parse_date

from cl.lib.command_utils import VerboseCommand
from cl.people_db.models import Person
from cl.search.models import Citation, Court, Docket, Opinion, OpinionCluster
from cl.search.tasks import add_items_to_solr

VALID_TYPES = ("OpinionCluster", "Docket", "Person", "Court")

cluster_endpoint = "https://www.courtlistener.com/api/rest/v3/clusters/"
people_endpoint = "https://www.courtlistener.com/api/rest/v3/people/"
courts_endpoint = "https://www.courtlistener.com/api/rest/v3/courts/"


class Command(VerboseCommand):
    help = "Clone data from CourtListener.com into dev environment"

    def __init__(self, *args, **kwargs):
        super(Command, self).__init__(*args, **kwargs)
        self.options = []
        self.type = None

        self.s = requests.session()
        self.s.headers = {
            "Authorization": f"Token {os.environ.get('CL_API_TOKEN', '')}"
        }

    def add_arguments(self, parser):
        parser.add_argument(
            "--type",
            type=str,
            choices=VALID_TYPES,
            help="Object type to clone. Current choices are %s"
            % ", ".join(VALID_TYPES),
        )

        parser.add_argument(
            "--id",
            help="Object id, " "object id to clone",
        )

    def handle(self, *args, **options):
        super(Command, self).handle(*args, **options)
        self.type = options.get("type")
        self.id = options.get("id")

        if not self.id:
            self.stdout.write("Object id required!")
            sys.exit(1)

        if settings.DEVELOPMENT:
            if self.type == "OpinionCluster":
                self.clone_opinion_cluster(self.id)
            elif self.type == "Docket":
                self.clone_docket(self.id)
            elif self.type == "Person":
                self.clone_person(self.id)
            elif self.type == "Court":
                self.clone_court(self.id)
            else:
                self.stdout.write("Invalid type!")

        else:
            self.stdout.write("Command not enabled for production environment")

    def clone_opinion_cluster(self, cluster_id) -> None:
        """Download opinion cluster data from courtlistener.com and add it to
        local environment
        """

        try:
            obj = OpinionCluster.objects.get(pk=cluster_id)
            print(
                f"OpinionCluster with id: {cluster_id} already in local env."
            )
            return
        except OpinionCluster.DoesNotExist:

            cluster_url = f"{cluster_endpoint}{cluster_id}/"
            results = self.s.get(cluster_url).json()
            cluster_datum = results
            docket_id = cluster_datum["docket"].split("/")[7]
            docket = self.clone_docket(docket_id)
            citation_data = cluster_datum["citations"]
            opinion_data = cluster_datum["sub_opinions"]
            # delete resource_uri value generated by DRF
            del cluster_datum["resource_uri"]
            # delete fields with fk or m2m relations or unneeded fields
            del cluster_datum["docket"]
            del cluster_datum["citations"]
            del cluster_datum["sub_opinions"]
            del cluster_datum["absolute_url"]
            del cluster_datum["panel"]
            del cluster_datum["non_participating_judges"]
            with transaction.atomic():

                # Assign docket pk in cluster data
                cluster_datum["docket_id"] = docket.pk

                # Create opinion cluster
                opinion_cluster = OpinionCluster.objects.create(
                    **cluster_datum
                )

                for cite_data in citation_data:
                    # Create citations
                    cite_data["cluster_id"] = opinion_cluster.pk
                    Citation.objects.create(**cite_data)

                for op in opinion_data:
                    op_data = self.s.get(op).json()
                    # delete fields with fk or m2m relations or unneeded fields
                    del op_data["opinions_cited"]
                    del op_data["cluster"]
                    del op_data["absolute_url"]
                    del op_data["resource_uri"]
                    del op_data["author"]
                    del op_data["joined_by"]

                    # Update cluster_id in opinion's json
                    op_data["cluster_id"] = opinion_cluster.pk

                    # Create opinion
                    op = Opinion.objects.create(**op_data)

                    # Add opinion to search engine
                    add_items_to_solr.delay([op.id], "search.Opinion")

                print(
                    ">> View cloned case here:",
                    reverse(
                        "view_case", args=[opinion_cluster.pk, docket.slug]
                    ),
                )

    def clone_docket(self, docket_id) -> [Docket, None]:
        """Download docket data from courtlistener.com and add it to local
        environment
        """
        try:
            obj = Docket.objects.get(pk=docket_id)
            print(f"Docket with id: {docket_id} already in local env.")
            return
        except Docket.DoesNotExist:
            # Create new Docket

            docket_endpoint = f"https://www.courtlistener.com/api/rest/v3/dockets/{docket_id}/"
            docket_data = self.s.get(docket_endpoint).json()

            # Remove unneeded fields
            del docket_data["resource_uri"]
            del docket_data["original_court_info"]
            del docket_data["absolute_url"]
            # TODO helpers to create other objects and set m2m relations
            del docket_data["clusters"]
            del docket_data["audio_files"]
            del docket_data["tags"]
            del docket_data["panel"]
            # del docket_data["assigned_to"]

            with transaction.atomic():

                # Get or create required objects
                docket_data["court"] = (
                    self.clone_court(docket_data["court"].split("/")[7])
                    if docket_data["court"]
                    else None
                )

                docket_data["appeal_from"] = (
                    self.clone_court(docket_data["appeal_from"].split("/")[7])
                    if docket_data["appeal_from"]
                    else None
                )

                docket_data["assigned_to"] = (
                    self.clone_person(docket_data["assigned_to"].split("/")[7])
                    if docket_data["assigned_to"]
                    else None
                )

                docket = Docket.objects.create(**docket_data)
                print(
                    ">> View cloned docket here:",
                    reverse(
                        "view_docket",
                        args=[docket_data["id"], docket_data["slug"]],
                    ),
                )
                return docket

    def clone_person(self, person_id):
        """Download person data from courtlistener.com and add it to local
        environment
        """

        try:
            person = Person.objects.get(pk=person_id)
        except Person.DoesNotExist:

            person_url = f"{people_endpoint}{person_id}/"

            person_data = self.s.get(person_url).json()
            # delete resource_uri value generated by DRF
            del person_data["resource_uri"]
            # delete fields with fk or m2m relations or unneeded fields
            # TODO create helpers to build that objects
            del person_data["aba_ratings"]
            del person_data["race"]
            del person_data["sources"]
            del person_data["educations"]
            del person_data["positions"]
            del person_data["political_affiliations"]
            # Prepare some values
            if person_data["date_dob"]:
                person_data["date_dob"] = parse_date(person_data["date_dob"])
            try:
                person, created = Person.objects.get_or_create(**person_data)
            except:
                person = Person.objects.filter(pk=person_data["id"])[0]

        print(
            ">> View cloned person here:",
            reverse("person-detail", args=["v3", person_id]),
        )
        return person

    def clone_court(self, court_id):
        """Download court data from courtlistener.com and add it to local
        environment
        """

        try:
            ct = Court.objects.get(pk=court_id)
        except Court.DoesNotExist:
            court_url = f"{courts_endpoint}{court_id}/"

            court_data = self.s.get(court_url).json()
            # delete resource_uri value generated by DRF
            del court_data["resource_uri"]

            try:
                ct = Court.objects.get_or_create(**court_data)
            except:
                ct = Court.objects.filter(pk=court_data["id"])[0]

        print(
            ">> View cloned court here:",
            reverse("court-detail", args=["v3", court_id]),
        )
        return ct
