# Generated by Django 3.2.13 on 2022-05-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docketalert',
            name='alert_type',
            field=models.SmallIntegerField(choices=[(0, 'Unsubscription'), (1, 'Subscription')], default=1, help_text='The subscription type assigned, Unsubscription or Subscription.'),
        ),
        migrations.DeleteModel(
            name='DocketSubscription',
        ),
    ]
