# Generated by Django 3.2.18 on 2023-03-16 20:05

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):
    dependencies = [
        ('alerts', '0004_add_event_tables_and_triggers'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='alert',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='alert',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='docketalert',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='docketalert',
            name='snapshot_update',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='alert',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update',
                                               sql=pgtrigger.compiler.UpsertTriggerSql(
                                                   condition='WHEN (OLD."id" IS DISTINCT FROM NEW."id" OR OLD."date_created" IS DISTINCT FROM NEW."date_created" OR OLD."user_id" IS DISTINCT FROM NEW."user_id" OR OLD."date_last_hit" IS DISTINCT FROM NEW."date_last_hit" OR OLD."name" IS DISTINCT FROM NEW."name" OR OLD."query" IS DISTINCT FROM NEW."query" OR OLD."rate" IS DISTINCT FROM NEW."rate" OR OLD."secret_key" IS DISTINCT FROM NEW."secret_key")',
                                                   func='INSERT INTO "alerts_alertevent" ("date_created", "date_last_hit", "date_modified", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "query", "rate", "secret_key", "user_id") VALUES (OLD."date_created", OLD."date_last_hit", OLD."date_modified", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."id", OLD."query", OLD."rate", OLD."secret_key", OLD."user_id"); RETURN NULL;',
                                                   hash='464f78a5c11d734dc3a70ee81dcbe62514a6d816',
                                                   operation='UPDATE',
                                                   pgid='pgtrigger_custom_snapshot_update_f51a7',
                                                   table='alerts_alert',
                                                   when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='docketalert',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update',
                                               sql=pgtrigger.compiler.UpsertTriggerSql(
                                                   condition='WHEN (OLD."id" IS DISTINCT FROM NEW."id" OR OLD."date_created" IS DISTINCT FROM NEW."date_created" OR OLD."date_last_hit" IS DISTINCT FROM NEW."date_last_hit" OR OLD."docket_id" IS DISTINCT FROM NEW."docket_id" OR OLD."user_id" IS DISTINCT FROM NEW."user_id" OR OLD."secret_key" IS DISTINCT FROM NEW."secret_key" OR OLD."alert_type" IS DISTINCT FROM NEW."alert_type")',
                                                   func='INSERT INTO "alerts_docketalertevent" ("alert_type", "date_created", "date_last_hit", "date_modified", "docket_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "secret_key", "user_id") VALUES (OLD."alert_type", OLD."date_created", OLD."date_last_hit", OLD."date_modified", OLD."docket_id", OLD."id", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."id", OLD."secret_key", OLD."user_id"); RETURN NULL;',
                                                   hash='894b8fc655e283a150fe5e7ffebb86a3defc8493',
                                                   operation='UPDATE',
                                                   pgid='pgtrigger_custom_snapshot_update_3fcf1',
                                                   table='alerts_docketalert',
                                                   when='AFTER')),
        ),
    ]
