# Generated by Django 3.2.18 on 2023-03-17 23:13

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_add_event_tables_and_triggers'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='alert',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='alert',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='docketalert',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='docketalert',
            name='snapshot_update',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='alert',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM NEW."id" OR OLD."date_created" IS DISTINCT FROM NEW."date_created" OR OLD."user_id" IS DISTINCT FROM NEW."user_id" OR OLD."date_last_hit" IS DISTINCT FROM NEW."date_last_hit" OR OLD."name" IS DISTINCT FROM NEW."name" OR OLD."query" IS DISTINCT FROM NEW."query" OR OLD."rate" IS DISTINCT FROM NEW."rate" OR OLD."secret_key" IS DISTINCT FROM NEW."secret_key")', func='INSERT INTO "alerts_alertevent" ("date_created", "date_last_hit", "date_modified", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "query", "rate", "secret_key", "user_id") VALUES (OLD."date_created", OLD."date_last_hit", OLD."date_modified", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."query", OLD."rate", OLD."secret_key", OLD."user_id"); RETURN NULL;', hash='8112f80be041b38ac3d0a125f301204fd6423cd3', operation='UPDATE', pgid='pgtrigger_update_or_delete_snapshot_update_1285f', table='alerts_alert', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='alert',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "alerts_alertevent" ("date_created", "date_last_hit", "date_modified", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "query", "rate", "secret_key", "user_id") VALUES (OLD."date_created", OLD."date_last_hit", OLD."date_modified", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."query", OLD."rate", OLD."secret_key", OLD."user_id"); RETURN NULL;', hash='27189303378fea40e58a12b53035f75d81e76632', operation='DELETE', pgid='pgtrigger_update_or_delete_snapshot_delete_96037', table='alerts_alert', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='docketalert',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM NEW."id" OR OLD."date_created" IS DISTINCT FROM NEW."date_created" OR OLD."date_last_hit" IS DISTINCT FROM NEW."date_last_hit" OR OLD."docket_id" IS DISTINCT FROM NEW."docket_id" OR OLD."user_id" IS DISTINCT FROM NEW."user_id" OR OLD."secret_key" IS DISTINCT FROM NEW."secret_key" OR OLD."alert_type" IS DISTINCT FROM NEW."alert_type")', func='INSERT INTO "alerts_docketalertevent" ("alert_type", "date_created", "date_last_hit", "date_modified", "docket_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "secret_key", "user_id") VALUES (OLD."alert_type", OLD."date_created", OLD."date_last_hit", OLD."date_modified", OLD."docket_id", OLD."id", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."secret_key", OLD."user_id"); RETURN NULL;', hash='89b88f2e0a243e9cb89c8890bd2bb1a2687953df', operation='UPDATE', pgid='pgtrigger_update_or_delete_snapshot_update_c2b33', table='alerts_docketalert', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='docketalert',
            trigger=pgtrigger.compiler.Trigger(name='update_or_delete_snapshot_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "alerts_docketalertevent" ("alert_type", "date_created", "date_last_hit", "date_modified", "docket_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "secret_key", "user_id") VALUES (OLD."alert_type", OLD."date_created", OLD."date_last_hit", OLD."date_modified", OLD."docket_id", OLD."id", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."secret_key", OLD."user_id"); RETURN NULL;', hash='afac64cc4b14c1ef7069751813659220f7085861', operation='DELETE', pgid='pgtrigger_update_or_delete_snapshot_delete_641ee', table='alerts_docketalert', when='AFTER')),
        ),
    ]
