# Generated by Django 3.2.18 on 2023-03-16 02:44

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_add_event_tables_and_triggers'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='alert',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='alert',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='docketalert',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='docketalert',
            name='snapshot_update',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='alert',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "alerts_alertevent" ("date_created", "date_last_hit", "date_modified", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "query", "rate", "secret_key", "user_id") VALUES (NEW."date_created", NEW."date_last_hit", NEW."date_modified", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'custom_snapshot\', NEW."id", NEW."query", NEW."rate", NEW."secret_key", NEW."user_id"); RETURN NULL;', hash='1c953596cd9e5485227c23c06e19cce920b52eae', operation='INSERT', pgid='pgtrigger_custom_snapshot_insert_12a4b', table='alerts_alert', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='alert',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "alerts_alertevent" ("date_created", "date_last_hit", "date_modified", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "query", "rate", "secret_key", "user_id") VALUES (OLD."date_created", OLD."date_last_hit", OLD."date_modified", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."id", OLD."query", OLD."rate", OLD."secret_key", OLD."user_id"); RETURN NULL;', hash='fdb811e543ae7a708472e67ec5924bff7c872954', operation='UPDATE', pgid='pgtrigger_custom_snapshot_update_f51a7', table='alerts_alert', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='docketalert',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "alerts_docketalertevent" ("alert_type", "date_created", "date_last_hit", "date_modified", "docket_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "secret_key", "user_id") VALUES (NEW."alert_type", NEW."date_created", NEW."date_last_hit", NEW."date_modified", NEW."docket_id", NEW."id", _pgh_attach_context(), NOW(), \'custom_snapshot\', NEW."id", NEW."secret_key", NEW."user_id"); RETURN NULL;', hash='da4247073d6ac09d8a4c281d25fbff179daa1b33', operation='INSERT', pgid='pgtrigger_custom_snapshot_insert_beef4', table='alerts_docketalert', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='docketalert',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "alerts_docketalertevent" ("alert_type", "date_created", "date_last_hit", "date_modified", "docket_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "secret_key", "user_id") VALUES (OLD."alert_type", OLD."date_created", OLD."date_last_hit", OLD."date_modified", OLD."docket_id", OLD."id", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."id", OLD."secret_key", OLD."user_id"); RETURN NULL;', hash='18a8b2f426be5b6cfd25eeb5b47df85bd6c47b70', operation='UPDATE', pgid='pgtrigger_custom_snapshot_update_3fcf1', table='alerts_docketalert', when='AFTER')),
        ),
    ]
