# Generated by Django 4.2 on 2023-05-01 05:10

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0005_update_triggers"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="alert",
            name="update_or_delete_snapshot_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="docketalert",
            name="update_or_delete_snapshot_update",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="alert",
            trigger=pgtrigger.compiler.Trigger(
                name="update_or_delete_snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."date_created" IS DISTINCT FROM (NEW."date_created") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id") OR OLD."date_last_hit" IS DISTINCT FROM (NEW."date_last_hit") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."query" IS DISTINCT FROM (NEW."query") OR OLD."rate" IS DISTINCT FROM (NEW."rate") OR OLD."secret_key" IS DISTINCT FROM (NEW."secret_key"))',
                    func='INSERT INTO "alerts_alertevent" ("date_created", "date_last_hit", "date_modified", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "query", "rate", "secret_key", "user_id") VALUES (OLD."date_created", OLD."date_last_hit", OLD."date_modified", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."query", OLD."rate", OLD."secret_key", OLD."user_id"); RETURN NULL;',
                    hash="293966260c4bcbc18b172493aa6c0830feceaa7a",
                    operation="UPDATE",
                    pgid="pgtrigger_update_or_delete_snapshot_update_1285f",
                    table="alerts_alert",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="docketalert",
            trigger=pgtrigger.compiler.Trigger(
                name="update_or_delete_snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."date_created" IS DISTINCT FROM (NEW."date_created") OR OLD."date_last_hit" IS DISTINCT FROM (NEW."date_last_hit") OR OLD."docket_id" IS DISTINCT FROM (NEW."docket_id") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id") OR OLD."secret_key" IS DISTINCT FROM (NEW."secret_key") OR OLD."alert_type" IS DISTINCT FROM (NEW."alert_type"))',
                    func='INSERT INTO "alerts_docketalertevent" ("alert_type", "date_created", "date_last_hit", "date_modified", "docket_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "secret_key", "user_id") VALUES (OLD."alert_type", OLD."date_created", OLD."date_last_hit", OLD."date_modified", OLD."docket_id", OLD."id", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."secret_key", OLD."user_id"); RETURN NULL;',
                    hash="4865294073cc26bd4023371cc707f263f1fe619b",
                    operation="UPDATE",
                    pgid="pgtrigger_update_or_delete_snapshot_update_c2b33",
                    table="alerts_docketalert",
                    when="AFTER",
                ),
            ),
        ),
    ]
