# Generated by Django 4.2.1 on 2023-05-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "alerts",
            "0006_remove_alert_update_or_delete_snapshot_update_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="realtimequeue",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("o", "Opinions"),
                    ("r", "RECAP"),
                    ("d", "RECAP Dockets"),
                    ("oa", "Oral Arguments"),
                    ("p", "People"),
                    ("pa", "Parenthetical"),
                ],
                db_index=True,
                help_text="the type of item this is, one of: o (Opinions), r (RECAP), d (RECAP Dockets), oa (Oral Arguments), p (People), pa (Parenthetical)",
                max_length=3,
            ),
        ),
    ]
