# Generated by Django 4.2.1 on 2023-06-17 01:35

import cl.alerts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("alerts", "0007_alter_realtimequeue_item_type_noop"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentAlert",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        help_text="The related Alert object.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_alerts",
                        to="alerts.alert",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserRateAlert",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
                    ),
                ),
                (
                    "rate",
                    models.CharField(
                        choices=[
                            ("rt", "Real Time"),
                            ("dly", "Daily"),
                            ("wly", "Weekly"),
                            ("mly", "Monthly"),
                            ("off", "Off"),
                        ],
                        help_text="The rate chosen by the user for the alert",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The related User object.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_rates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduledAlertHit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
                    ),
                ),
                (
                    "document_content",
                    models.JSONField(
                        encoder=cl.alerts.models.DateJSONEncoder,
                        help_text="The content of the document at the moment it was added.",
                    ),
                ),
                (
                    "highlighted_fields",
                    models.JSONField(
                        blank=True,
                        help_text="The highlighted fields for the alert.",
                        null=True,
                    ),
                ),
                (
                    "parent_alert",
                    models.ForeignKey(
                        help_text="The related ParentAlert object.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_alerts",
                        to="alerts.parentalert",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="parentalert",
            name="user_rate",
            field=models.ForeignKey(
                help_text="The related UserRateAlert object.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_alerts",
                to="alerts.userratealert",
            ),
        ),
        migrations.AddConstraint(
            model_name="userratealert",
            constraint=models.UniqueConstraint(
                fields=("user", "rate"), name="unique_user_and_rate"
            ),
        ),
    ]
