BEGIN;
--
-- Create model ScheduledAlertHit
--
CREATE TABLE "alerts_scheduledalerthit" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date_created" timestamp with time zone NOT NULL, "date_modified" timestamp with time zone NOT NULL, "rate" varchar(10) NOT NULL, "document_content" jsonb NOT NULL, "highlighted_fields" jsonb NULL, "alert_id" integer NOT NULL, "user_id" integer NOT NULL);
ALTER TABLE "alerts_scheduledalerthit" ADD CONSTRAINT "alerts_scheduledalerthit_alert_id_b407b0ad_fk_alerts_alert_id" FOREIGN KEY ("alert_id") REFERENCES "alerts_alert" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "alerts_scheduledalerthit" ADD CONSTRAINT "alerts_scheduledalerthit_user_id_d94bee5e_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "alerts_scheduledalerthit_date_created_eef6e1d2" ON "alerts_scheduledalerthit" ("date_created");
CREATE INDEX "alerts_scheduledalerthit_date_modified_085e80b9" ON "alerts_scheduledalerthit" ("date_modified");
CREATE INDEX "alerts_scheduledalerthit_alert_id_b407b0ad" ON "alerts_scheduledalerthit" ("alert_id");
CREATE INDEX "alerts_scheduledalerthit_user_id_d94bee5e" ON "alerts_scheduledalerthit" ("user_id");
COMMIT;
