# Generated by Django 4.2.3 on 2023-08-29 04:05

import cl.alerts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("alerts", "0007_alter_realtimequeue_item_type_noop"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledAlertHit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
                    ),
                ),
                (
                    "rate",
                    models.CharField(
                        choices=[
                            ("rt", "Real Time"),
                            ("dly", "Daily"),
                            ("wly", "Weekly"),
                            ("mly", "Monthly"),
                            ("off", "Off"),
                        ],
                        help_text="The rate chosen by the user for the alert",
                        max_length=10,
                    ),
                ),
                (
                    "document_content",
                    models.JSONField(
                        encoder=cl.alerts.models.DateJSONEncoder,
                        help_text="The content of the document at the moment it was added.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="alert",
            name="update_or_delete_snapshot_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="alert",
            name="update_or_delete_snapshot_update",
        ),
        migrations.AddField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("o", "Opinions"),
                    ("r", "RECAP"),
                    ("d", "RECAP Dockets"),
                    ("oa", "Oral Arguments"),
                    ("p", "People"),
                    ("pa", "Parenthetical"),
                ],
                default="o",
                help_text="The type of search alert this is, one of: o (Opinions), r (RECAP), d (RECAP Dockets), oa (Oral Arguments), p (People), pa (Parenthetical)",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="alertevent",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("o", "Opinions"),
                    ("r", "RECAP"),
                    ("d", "RECAP Dockets"),
                    ("oa", "Oral Arguments"),
                    ("p", "People"),
                    ("pa", "Parenthetical"),
                ],
                default="o",
                help_text="The type of search alert this is, one of: o (Opinions), r (RECAP), d (RECAP Dockets), oa (Oral Arguments), p (People), pa (Parenthetical)",
                max_length=3,
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="alert",
            trigger=pgtrigger.compiler.Trigger(
                name="update_or_delete_snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."date_created" IS DISTINCT FROM (NEW."date_created") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id") OR OLD."date_last_hit" IS DISTINCT FROM (NEW."date_last_hit") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."query" IS DISTINCT FROM (NEW."query") OR OLD."rate" IS DISTINCT FROM (NEW."rate") OR OLD."alert_type" IS DISTINCT FROM (NEW."alert_type") OR OLD."secret_key" IS DISTINCT FROM (NEW."secret_key"))',
                    func='INSERT INTO "alerts_alertevent" ("alert_type", "date_created", "date_last_hit", "date_modified", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "query", "rate", "secret_key", "user_id") VALUES (OLD."alert_type", OLD."date_created", OLD."date_last_hit", OLD."date_modified", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."query", OLD."rate", OLD."secret_key", OLD."user_id"); RETURN NULL;',
                    hash="42b4804e1bd56a147658e07f14ee253e226ba809",
                    operation="UPDATE",
                    pgid="pgtrigger_update_or_delete_snapshot_update_1285f",
                    table="alerts_alert",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="alert",
            trigger=pgtrigger.compiler.Trigger(
                name="update_or_delete_snapshot_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "alerts_alertevent" ("alert_type", "date_created", "date_last_hit", "date_modified", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "query", "rate", "secret_key", "user_id") VALUES (OLD."alert_type", OLD."date_created", OLD."date_last_hit", OLD."date_modified", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."query", OLD."rate", OLD."secret_key", OLD."user_id"); RETURN NULL;',
                    hash="e964b655ff3f1c4613682420332696dba8e2f620",
                    operation="DELETE",
                    pgid="pgtrigger_update_or_delete_snapshot_delete_96037",
                    table="alerts_alert",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="scheduledalerthit",
            name="alert",
            field=models.ForeignKey(
                help_text="The related Alert object.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_alerts",
                to="alerts.alert",
            ),
        ),
        migrations.AddField(
            model_name="scheduledalerthit",
            name="user",
            field=models.ForeignKey(
                help_text="The related User object.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_rates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
