# Generated by Django 4.2.1 on 2023-06-08 22:22

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0007_alter_realtimequeue_item_type_noop"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="alert",
            name="update_or_delete_snapshot_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="alert",
            name="update_or_delete_snapshot_update",
        ),
        migrations.AddField(
            model_name="alert",
            name="es_id",
            field=models.CharField(
                blank=True,
                max_length=128,
                verbose_name="The percolator query ID in Elasticsearch.",
            ),
        ),
        migrations.AddField(
            model_name="alertevent",
            name="es_id",
            field=models.CharField(
                blank=True,
                max_length=128,
                verbose_name="The percolator query ID in Elasticsearch.",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["es_id"], name="alerts_aler_es_id_b61e27_idx"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="alert",
            trigger=pgtrigger.compiler.Trigger(
                name="update_or_delete_snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."date_created" IS DISTINCT FROM (NEW."date_created") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id") OR OLD."date_last_hit" IS DISTINCT FROM (NEW."date_last_hit") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."query" IS DISTINCT FROM (NEW."query") OR OLD."rate" IS DISTINCT FROM (NEW."rate") OR OLD."secret_key" IS DISTINCT FROM (NEW."secret_key") OR OLD."es_id" IS DISTINCT FROM (NEW."es_id"))',
                    func='INSERT INTO "alerts_alertevent" ("date_created", "date_last_hit", "date_modified", "es_id", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "query", "rate", "secret_key", "user_id") VALUES (OLD."date_created", OLD."date_last_hit", OLD."date_modified", OLD."es_id", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."query", OLD."rate", OLD."secret_key", OLD."user_id"); RETURN NULL;',
                    hash="fc7ba7cf9b5c2e7401f87326b18263678c6e01cd",
                    operation="UPDATE",
                    pgid="pgtrigger_update_or_delete_snapshot_update_1285f",
                    table="alerts_alert",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="alert",
            trigger=pgtrigger.compiler.Trigger(
                name="update_or_delete_snapshot_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "alerts_alertevent" ("date_created", "date_last_hit", "date_modified", "es_id", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "query", "rate", "secret_key", "user_id") VALUES (OLD."date_created", OLD."date_last_hit", OLD."date_modified", OLD."es_id", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."query", OLD."rate", OLD."secret_key", OLD."user_id"); RETURN NULL;',
                    hash="91bb2b0ff7d6146f40a16bc22f436f8c750164a0",
                    operation="DELETE",
                    pgid="pgtrigger_update_or_delete_snapshot_delete_96037",
                    table="alerts_alert",
                    when="AFTER",
                ),
            ),
        ),
    ]
