# Generated by Django 4.2.3 on 2023-08-26 07:43

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0008_add_scheduled_alert_hit"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="alert",
            name="update_or_delete_snapshot_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="alert",
            name="update_or_delete_snapshot_update",
        ),
        migrations.AddField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("o", "Opinions"),
                    ("r", "RECAP"),
                    ("d", "RECAP Dockets"),
                    ("oa", "Oral Arguments"),
                    ("p", "People"),
                    ("pa", "Parenthetical"),
                ],
                default="o",
                help_text="The type of search alert this is, one of: o (Opinions), r (RECAP), d (RECAP Dockets), oa (Oral Arguments), p (People), pa (Parenthetical)",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="alertevent",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("o", "Opinions"),
                    ("r", "RECAP"),
                    ("d", "RECAP Dockets"),
                    ("oa", "Oral Arguments"),
                    ("p", "People"),
                    ("pa", "Parenthetical"),
                ],
                default="o",
                help_text="The type of search alert this is, one of: o (Opinions), r (RECAP), d (RECAP Dockets), oa (Oral Arguments), p (People), pa (Parenthetical)",
                max_length=3,
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="alert",
            trigger=pgtrigger.compiler.Trigger(
                name="update_or_delete_snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."date_created" IS DISTINCT FROM (NEW."date_created") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id") OR OLD."date_last_hit" IS DISTINCT FROM (NEW."date_last_hit") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."query" IS DISTINCT FROM (NEW."query") OR OLD."rate" IS DISTINCT FROM (NEW."rate") OR OLD."alert_type" IS DISTINCT FROM (NEW."alert_type") OR OLD."secret_key" IS DISTINCT FROM (NEW."secret_key"))',
                    func='INSERT INTO "alerts_alertevent" ("alert_type", "date_created", "date_last_hit", "date_modified", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "query", "rate", "secret_key", "user_id") VALUES (OLD."alert_type", OLD."date_created", OLD."date_last_hit", OLD."date_modified", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."query", OLD."rate", OLD."secret_key", OLD."user_id"); RETURN NULL;',
                    hash="42b4804e1bd56a147658e07f14ee253e226ba809",
                    operation="UPDATE",
                    pgid="pgtrigger_update_or_delete_snapshot_update_1285f",
                    table="alerts_alert",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="alert",
            trigger=pgtrigger.compiler.Trigger(
                name="update_or_delete_snapshot_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "alerts_alertevent" ("alert_type", "date_created", "date_last_hit", "date_modified", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "query", "rate", "secret_key", "user_id") VALUES (OLD."alert_type", OLD."date_created", OLD."date_last_hit", OLD."date_modified", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."query", OLD."rate", OLD."secret_key", OLD."user_id"); RETURN NULL;',
                    hash="e964b655ff3f1c4613682420332696dba8e2f620",
                    operation="DELETE",
                    pgid="pgtrigger_update_or_delete_snapshot_delete_96037",
                    table="alerts_alert",
                    when="AFTER",
                ),
            ),
        ),
    ]
