# Generated by Django 5.0.6 on 2024-07-18 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0009_alter_alert_search_types_noop"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledalerthit",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="scheduledalerthit",
            name="object_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name="scheduledalerthit",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="alerts_sche_content_c5e627_idx",
            ),
        ),
    ]
