# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-25 00:02


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_add_date_last_hit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimequeue',
            name='item_type',
            field=models.CharField(choices=[('o', 'Opinions'), ('r', 'RECAP'), ('oa', 'Oral Arguments'), ('p', 'People')], db_index=True, help_text='the type of item this is, one of: o (Opinions), r (RECAP), oa (Oral Arguments), p (People)', max_length=3),
        ),
    ]
