# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-22 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_noop_update_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimequeue',
            name='item_type',
            field=models.CharField(choices=[(b'o', b'Opinions'), (b'r', b'RECAP'), (b'd', b'RECAP Dockets'), (b'oa', b'Oral Arguments'), (b'p', b'People')], db_index=True, help_text=b'the type of item this is, one of: o (Opinions), r (RECAP), d (RECAP Dockets), oa (Oral Arguments), p (People)', max_length=3),
        ),
    ]
