# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-23 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0011_add_recap_docket_search_type_noop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.'),
        ),
    ]
