# Generated by Django 5.1.2 on 2024-10-18 20:19

from django.contrib.postgres.operations import AddIndexConcurrently
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("alerts", "0011_add_schedule_alert_hit_content_type"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="scheduledalerthit",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="alerts_sche_content_c5e627_idx",
            ),
        ),
    ]
