# Generated by Django 5.1.8 on 2025-05-16 07:43

import cl.alerts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0013_alter_alert_search_type_validator_noop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('o', 'Opinions'), ('r', 'RECAP'), ('d', 'RECAP Dockets'), ('oa', 'Oral Arguments')], help_text='The type of search alert this is, one of: o (Opinions), r (RECAP), d (RECAP Dockets), oa (Oral Arguments)', max_length=3, validators=[cl.alerts.models.validate_alert_type]),
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='alert_type',
            field=models.CharField(choices=[('o', 'Opinions'), ('r', 'RECAP'), ('d', 'RECAP Dockets'), ('oa', 'Oral Arguments')], help_text='The type of search alert this is, one of: o (Opinions), r (RECAP), d (RECAP Dockets), oa (Oral Arguments)', max_length=3, validators=[cl.alerts.models.validate_alert_type]),
        ),
    ]
