# Generated by Django 5.1.8 on 2025-12-04 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0014_alter_alert_search_types_noop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RealTimeQueue',
        ),
    ]
