version: 2
jobs:
  build:
    docker:
      - image: freelawproject/courtlistener-testing:0.1.0

    steps:
    - checkout
    - run: rm -fr /var/www/courtlistener
    - run: mv ~/project /var/www/courtlistener
    - run: cp /var/www/courtlistener/cl/settings/05-private.example /var/www/courtlistener/cl/settings/05-private.py
    # TODO (davidxia): Not sure how to get circleCI to respect docker image's entrypoint, even if `command` is specified above.
    # See https://circleci.com/docs/2.0/configuration-reference/#docker--machine--macosexecutor.
    - run: /etc/init.d/postgresql start
    - run: source /var/www/.virtualenvs/courtlistener/bin/activate && pytest /var/www/courtlistener/cl/corpus_importer/tests.py
