# Generated by Django 4.2 on 2023-05-02 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lasc", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="docket",
            new_name="lasc_docket_docket__4b4f04_idx",
            old_fields=("docket_number", "district", "division_code"),
        ),
    ]
