# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-04 21:31
from __future__ import unicode_literals

import cl.lib.model_helpers
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('lasc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Action Entry', 'verbose_name_plural': 'Action Entries'},
        ),
        migrations.AlterModelOptions(
            name='lascjson',
            options={'verbose_name': 'LASC JSON File'},
        ),
        migrations.RemoveField(
            model_name='lascpdf',
            name='filepath',
        ),
        migrations.AddField(
            model_name='lascpdf',
            name='filepath_s3',
            field=models.FileField(blank=True, help_text=b'The path of the file in the s3 bucket.', max_length=150, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=cl.lib.model_helpers.make_pdf_path),
        ),
        migrations.AlterField(
            model_name='lascjson',
            name='filepath',
            field=models.FileField(blank=True, help_text=b'The path of the file in the local storage area.', max_length=150, upload_to=cl.lib.model_helpers.make_lasc_json_path),
        ),
    ]
