# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-19 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lasc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text=b'The last moment when the item was modified'),
        ),
    ]
