# Generated by Django 5.1.8 on 2025-10-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lasc', '0002_rename_docket_docket_number_district_division_code_lasc_docket_docket__4b4f04_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='lascpdf',
            name='source_url',
            field=models.CharField(blank=True, help_text='The URL this PDF was stored at before import, if known and public', max_length=1000, null=True),
        ),
    ]
