# Generated by Django 5.1.8 on 2025-12-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lasc', '0002_rename_docket_docket_number_district_division_code_lasc_docket_docket__4b4f04_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='lascpdf',
            name='filepath_original_source',
            field=models.CharField(blank=True, help_text='The URL of the file from the original source', max_length=1000),
        ),
    ]
