# Generated by Django 3.1.7 on 2021-05-21 23:57

from django.db import migrations, models

import cl.lib.model_helpers
import cl.lib.storage


class Migration(migrations.Migration):

    dependencies = [
        ('lasc', '0004_abstract_datetime_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lascpdf',
            name='filepath_local',
            field=models.FileField(blank=True, help_text='The path is AWS S3 where the file is saved. Note that the field name is historical, from before when we used S3. To find the location in S3, concatenate https://storage.courtlistener.com/ and the value of this field.', max_length=1000, storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.lib.model_helpers.make_pdf_path),
        ),
    ]
