import re


STATE_PAIRS = (
    (re.compile('D((istrict)|\.) (of )?C((olumbia)|\.) Court of Appeals', re.I), 'dc'),
        (re.compile('D((istrict)|\.) (of )?C((olumbia)|\.) Municipal Court of Appeals', re.I), 'dc'),
            (re.compile('Municipal Court of Appeals? (for the )?D((istrict)|\.) (of )?C((olumbia)|\.)', re.I), 'dc'),
        (re.compile('Supreme Court of the D((istrict)|\.) (of )?C((olumbia)|\.)', re.I), 'dc'),
    (re.compile('Supreme Court of Alabama', re.I), 'ala'),
    (re.compile('Court of Criminal Appeals? of Alabama', re.I), 'alacrimapp'),
        (re.compile('Alabama Court of Criminal Appeals?', re.I), 'alacrimapp'),
    (re.compile('Court of Civil Appeals? of Alabama', re.I), 'alacivapp'),
    (re.compile('Court of Appeals? of Alabama', re.I), 'alactapp'),  # Abolished.
    (re.compile('Supreme Court of Alaska', re.I), 'alaska'),
    (re.compile('Court of Appeals? of Alaska', re.I), 'alaskactapp'),
    (re.compile('Supreme Court of Arizona', re.I), 'ariz'),
    (re.compile('Court of Appeals,? of Arizona', re.I), 'arizctapp'),
    (re.compile('Tax Court of Arizona', re.I), 'ariztaxct'),
    (re.compile('Supreme Court of Arkansas', re.I), 'ark'),
    (re.compile('Court of Appeals? of Arkansas', re.I), 'arkctapp'),
    (re.compile('Supreme Court of California', re.I), 'cal'),
    (re.compile('California Court of Appeals', re.I), 'calctapp'),
        (re.compile('Court of Appeals? of California', re.I), 'calctapp'),
    (re.compile('Appellate Division, Superior Court', re.I), 'calappdeptsuperct'),
    (re.compile('Supreme Court of Colorado', re.I), 'colo'),
    (re.compile('Colorado Court of Appeals', re.I), 'coloctapp'),
        (re.compile('Court of Appeals? of Colorado', re.I), 'coloctapp'),
    (re.compile('Supreme Court of Connecticut', re.I), 'conn'),
    (re.compile('Appellate Court of Connecticut', re.I), 'connappct'),
        (re.compile('Superior Court of Connecticut', re.I), 'connsuperct'),
        (re.compile('Connecticut Superior Court', re.I), 'connsuperct'),
    (re.compile('Supreme Court of (the State of )?Delaware', re.I), 'del'),
        (re.compile('Delaware Supreme Court', re.I), 'del'),
    (re.compile('Court of Chancery of (the State of )?Delaware', re.I), 'delch'),
        (re.compile('Chancery Court of Delaware', re.I), 'delch'),
    (re.compile('Superior Court of (the State of )?Delaware', re.I), 'delsuperct'),
        # These two merged into the Superior court of Delaware
        (re.compile('Orphans\'? Court of Delaware', re.I), 'delsuperct'),
        (re.compile('Court of General Sessions', re.I), 'delsuperct'),
        (re.compile('Court of Oyer and Terminer of Delaware', re.I), 'delsuperct'),
    (re.compile('Family Court of Delaware', re.I), 'delfamct'),
    (re.compile('Court on the Judiciary of Delaware', re.I), 'deljudct'),
        (re.compile('Delaware Court on the Judiciary', re.I), 'deljudct'),
    (re.compile('Supreme Court of Florida', re.I), 'fla'),
        (re.compile('Supreme Court.*Nassau County', re.I), 'fla'),
    (re.compile('District Courts? of Appeal (of )?Florida', re.I), 'fladistctapp'),
    (re.compile('Supreme Court of Georgia', re.I), 'ga'),
    (re.compile('Court of Appeals? of Georgia', re.I), 'gactapp'),
    (re.compile('Supreme Court of Illinois', re.I), 'ill'),
    (re.compile('Supreme Court of Hawai', re.I), 'haw'),
    (re.compile('Intermediate Court (of )?Appeals? .*Hawai', re.I), 'hawapp'),
        (re.compile('Court of Appeals? of Hawai', re.I), 'hawapp'),
    (re.compile('Supreme Court of (the state of )?Idaho', re.I), 'idaho'),
    (re.compile('Court of Appeals? of Idaho', re.I), 'idahoctapp'),
        (re.compile('Idaho Court of Appeals', re.I), 'idahoctapp'),
    (re.compile('Supreme Court of Illinois', re.I), 'ill'),
    (re.compile('Appellate Court of Illinois', re.I), 'illappct'),
        (re.compile('Illinois Appellate Court', re.I), 'illappct'),
    (re.compile('Supreme Court of Indiana', re.I), 'ind'),
    (re.compile('Court of Appeals? ((of)|(in)) Indiana', re.I), 'indctapp'),
        (re.compile('Appe((llate)|(als)) Court of Indiana', re.I), 'indctapp'),
        (re.compile('Indiana Court of Appeals', re.I), 'indctapp'),
    (re.compile('Tax Court of Indiana', re.I), 'indtc'),
        (re.compile('Indiana Tax Court', re.I), 'indtc'),
    (re.compile('Supreme Court of Iowa', re.I), 'iowa'),
    (re.compile('Court of Appeals? (of )?Iowa', re.I), 'iowactapp'),
        (re.compile('Iowa Court of Appeals', re.I), 'iowactapp'),
    (re.compile('Supreme Court of Kansas', re.I), 'kan'),
    (re.compile('Court of Appeals? of Kansas', re.I), 'kanctapp'),
    (re.compile('Supreme Court of Kentucky', re.I), 'ky'),
    (re.compile('Court of Appeals? of Kentucky', re.I), 'kyctapp'),
    (re.compile('Supreme Court of Louisiana', re.I), 'la'),
    (re.compile('Court of Appeals? of Louisiana', re.I), 'lactapp'),
    (re.compile('Supreme Judicial Court of Maine', re.I), 'me'),
    (re.compile('Court of Appeals? of Maryland', re.I), 'md'),
        (re.compile('Supreme Court of Maryland', re.I), 'md'),
    (re.compile('Court of Special Appeals? of Maryland', re.I), 'mdctspecapp'),
    (re.compile('Supreme (Judicial )?Court of Massachusetts', re.I), 'mass'),
    (re.compile('Appeals? Court of Massachusetts', re.I), 'massappct'),
    (re.compile('Supreme Court of Michigan', re.I), 'mich'),
    (re.compile('Michigan Court of Appeals', re.I), 'michctapp'),
        (re.compile('Court of Appeals? of Michigan', re.I), 'michctapp'),
    (re.compile('Supreme Court of Minnesota', re.I), 'minn'),
    (re.compile('Court of Appeals? of Minnesota', re.I), 'minnctapp'),
    (re.compile('Supreme Court of Mississippi', re.I), 'miss'),
    (re.compile('Court of Appeals? of Mississippi', re.I), 'missctapp'),
    (re.compile('Supreme Court of Missouri', re.I), 'mo'),
    (re.compile('Missouri Court of Appeals', re.I), 'moctapp'),
        (re.compile('St\. Louis,? Court of Appeals', re.I), 'moctapp'),
        (re.compile('Kansas City.? Court of appeals', re.I), 'moctapp'),
        (re.compile('Springfield,? Court of appeals', re.I), 'moctapp'),
    (re.compile('Supreme Court of Montana', re.I), 'mont'),
    (re.compile('Supreme Court of Nebraska', re.I), 'neb'),
    (re.compile('Court of Appeals? of Nebraska', re.I), 'nebctapp'),
        (re.compile('Nebraska Court of Appeals', re.I), 'nebctapp'),
    (re.compile('Supreme Court of Nevada', re.I), 'nev'),
    (re.compile('Supreme Court of New Hampshire', re.I), 'nh'),
    (re.compile('Supreme Court of New Jersey', re.I), 'nj'),
    (re.compile('Superior Court of New Jersey', re.I), 'njsuperctappdiv'),
    (re.compile('Tax Court of New Jersey', re.I), 'njtaxct'),
    (re.compile('Supreme Court of New Mexico', re.I), 'nm'),
    (re.compile('Court of Appeals? of New Mexico', re.I), 'nmctapp'),
        (re.compile('New Mexico Court of Appeals', re.I), 'nmctapp'),
    (re.compile('Court of Appeals? of (the State of )?New York', re.I), 'ny'),
    (re.compile('Appellate Division of the Supreme Court of the State of New York', re.I), 'nyappdiv'),
        (re.compile('Supreme Court.*Albany County', re.I), 'nyappdiv'),
        (re.compile('Supreme Court.*New York County', re.I), 'nyappdiv'),
        (re.compile('Supreme Court.*Kings County', re.I), 'nyappdiv'),
        (re.compile('Supreme Court.*Oneida County', re.I), 'nyappdiv'),
        (re.compile('Supreme Court.*Queens County', re.I), 'nyappdiv'),
        (re.compile('Supreme Court.*Schenectady County', re.I), 'nyappdiv'),
        (re.compile('Supreme Court.*Westchester County', re.I), 'nyappdiv'),
    (re.compile('Family Court.*New York', re.I), 'nyfamct'),
    (re.compile('Surrogate\'s Court', re.I), 'nysurct'),
    (re.compile('Supreme Court of North Carolina', re.I), 'nc'),
    (re.compile('Court of Appeals? (of )?North Carolina', re.I), 'ncctapp'),
        (re.compile('North Carolina Court of Appeals', re.I), 'ncctapp'),
    (re.compile('Supreme Court of North Dakota', re.I), 'nd'),
    (re.compile('Court of Appeals? of North Dakota', re.I), 'ndctapp'),
    (re.compile('Supreme Court of Ohio', re.I), 'ohio'),
    (re.compile('Supreme Court (of )?Oklahoma', re.I), 'okla'),
    (re.compile('Court of Criminal Appeals? (of )?Oklahoma', re.I), 'oklacrimapp'),
        (re.compile('Criminal Courts of Appeals? of Oklahoma', re.I), 'oklacrimapp'),
    (re.compile('Court of Civils? Appeals? of Oklahoma', re.I), 'oklacivapp'),
        # When they refer to simply the "Court of Appeals" they mean the the civil court
        (re.compile('Court of Appeals?,? (civil )?(of )?(State )?(of )?Oklahoma', re.I), 'oklacivapp'),
    (re.compile('Oklahoma Judicial Ethics Advisory Panel', re.I), 'oklajeap'),
    (re.compile('Court on the Judiciary of Oklahoma', re.I), 'oklacoj'),
    (re.compile('Supreme Court (((for)|(of)) the State )?of (the )?Oregon', re.I), 'or'),
        (re.compile('Oregon Supreme Court', re.I), 'or'),
    (re.compile('Court of Appeals? of (the )?(state of )?Oregon', re.I), 'orctapp'),
        (re.compile('oregon court of appeals', re.I), 'orctapp'),
    (re.compile('Supreme Court of Pennsylvania', re.I), 'pa'),
    (re.compile('Superior Court of Pennsylvania', re.I), 'pasuperct'),
    (re.compile('Commonwealth Court of Pennsylvania', re.I), 'pacommwct'),
    (re.compile('Court of Judicial Discipline of Pennsylvania', re.I), 'cjdpa'),
    (re.compile('Supreme Court,? of Rhode Island', re.I), 'ri'),
    (re.compile('Supreme Court of South Carolina', re.I), 'sc'),
    (re.compile('Court of Appeals? of South Carolina', re.I), 'scctapp'),
    (re.compile('Supreme Court of South Dakota', re.I), 'sd'),
    (re.compile('Supreme Court of Tennessee', re.I), 'tenn'),
    (re.compile('Court of Appeals? (of )?Tennessee', re.I), 'tennctapp'),
        (re.compile('Tennessee Court of Appeals', re.I), 'tennctapp'),
    (re.compile('Court of Criminal Appeals? of Tennessee', re.I), 'tenncrimapp'),
    (re.compile('Supreme Court of Texas', re.I), 'tex'),
    (re.compile('Court of Appeals? of Texas', re.I), 'texapp'),
        # The Civil Appeals courts were renamed in 1985 to be the "Court of Appeals"
        (re.compile('Court of Civil Appeals,? of (Beaumont, )?Texas', re.I), 'texapp'),
    (re.compile('Court of Criminal Appeals? of Texas', re.I), 'texcrimapp'),
    (re.compile('Special Court of Review', re.I), 'texreview'),
    (re.compile('Supreme Court of (the )?(state of )?Utah', re.I), 'utah'),
    (re.compile('Court of Appeals? (of )?Utah', re.I), 'utahctapp'),
    (re.compile('Utah Court of Appeals', re.I), 'utahctapp'),
    (re.compile('Supreme Court of Vermont', re.I), 'vt'),
    (re.compile('Supreme Court of Virginia', re.I), 'va'),
    (re.compile('Court of Appeals? of Virginia', re.I), 'vactapp'),
    (re.compile('Supreme Court of Washington', re.I), 'wash'),
    (re.compile('Court of Appeals? of Washington', re.I), 'washctapp'),
    (re.compile('Supreme Court of( Appeals? of)?,? West Virginia', re.I), 'wva'),
    (re.compile('Supreme Court of Wisconsin', re.I), 'wis'),
    (re.compile('Court of Appeals? of (of )?Wisconsin', re.I), 'wisctapp'),
        (re.compile('Wisconsin Court of Appeals', re.I), 'wisctapp'),
    (re.compile('Supreme Court (of )?Wyoming', re.I), 'wyo'),

    # new codes by elliott
    (re.compile('Massachusetts Superior Court', re.I), 'masssuperct'),
    (re.compile('High Court of Errors and Appeals of Delaware', re.I), 'del'),
    (re.compile('Court of Errors and Appeals of Delaware', re.I), 'del'),
    (re.compile('Court of Common Pleas of Delaware', re.I), 'delcompl'),
    (re.compile('Hawaii Court of Appeals?', re.I), 'hawapp'),
    (re.compile('Massachusetts Appellate Division', re.I), 'massdistct'),
    (re.compile('Commonwealth of Massachusetts Department of Industrial Accidents', re.I), ''),
    (re.compile('Minnesota Court of Appeals?', re.I), 'minnctapp'),
    (re.compile('Minnesota Court of Appeals?', re.I), 'minnctapp'),
    (re.compile('Appellate Division of the Supreme Court of New York', re.I), 'nyappdiv'),
    (re.compile('Supreme Court of the State of New York', re.I), 'nysupremect'),
# Note that these next three might just become 'nylowercourts'
    (re.compile('Criminal Court of the City of New York', re.I), 'nycrimct'),
    (re.compile('Civil Court of the City of New York', re.I), 'nycivct'),
    (re.compile('Appellate Term of the Supreme Court of New York', re.I), 'nyappterm'),
    (re.compile('Superior Court of North Carolina', re.I), 'ncsuperct'),
    (re.compile('North Carolina Industrial Commission', re.I), 'ncworkcompcom'),
    (re.compile('Court of Appeals of Ohio', re.I), 'ohioctapp'),
    (re.compile('Court of Claims of Ohio', re.I), 'ohioctcl'),
    (re.compile('Oregon Tax Court', re.I), 'ortc'),
    (re.compile('State of Rhode Island, Superior Court', re.I), 'risuperct'),

    # attorneys general
    (re.compile('Attorney General of Arkansas', re.I), 'arkattygenop'),
    (re.compile('Attorney General of California', re.I), 'calattygenop'),
    (re.compile('Attorney General of Colorado', re.I), 'coloattygenop'),
    (re.compile('Attorney General of Florida', re.I), 'flaattygenop'),
    (re.compile('Attorney General of Kansas', re.I), 'kanattygenop'),
    (re.compile('Attorney General of Louisiana', re.I), 'laattygenop'),
    (re.compile('Attorney General of Maryland', re.I), 'mdattygenop'),
    (re.compile('Attorney General of Missouri', re.I), 'moattygenop'),
    (re.compile('Attorney General of Nebraska', re.I), 'nebattygenop'),
    (re.compile('Attorney General of New York', re.I), 'nyattygenop'),
    (re.compile('Attorney General of Oklahoma', re.I), 'oklaattygenop'),
    (re.compile('Attorney General of Texas', re.I), 'texattygenop'),
    (re.compile('Attorney General of Washington', re.I), 'washattygenop'),
    (re.compile('Attorney General of Wisconsin', re.I), 'wisattygenop'),

    # other items
    (re.compile('Industrial Claim Appeals Office', re.I), 'coloworkcompcom'),
    (re.compile('Connecticut Compensation Review Board', re.I), 'connworkcompcom'),

)

SPECIAL_REGEXES = {
    'tennessee/court_opinions': (
        (re.compile('Supreme Court of Errors and Appeals', re.I), 'tenn'),
        (re.compile('Court of Errors and Appeals', re.I), 'tenn'),
    )
}

FOLDER_DICT = {
    'arkansas/attorney_general_opinion'                       : 'arkattygenop',
    'arkansas/workers_compensation_commission'                : 'arkworkcompcom',
    'california/attorney_general_opinion'                     : 'calattygenop',
    'california/supreme_court_opinions'                       : 'cal',
    'california/court_of_appeal_opinions'                     : 'calctapp',
    'colorado/attorney_general_opinion'                       : 'coloattygenop',
    'colorado/industrial_claim_appeals_office'                : 'coloworkcompcom',
    'connecticut/appellate_court_opinions'                    : 'connappct',
    'connecticut/superior_court_opinions'                     : 'connsuperct',
    'connecticut/workers_compensation_commission'             : 'connworkcompcom',
    'district_of_columbia/court_of_appeals_opinions'          : 'dc',
    'florida/attorney_general_opinion'                        : 'flaattygenop',
    'georgia/supreme_court_opinions'                          : 'ga',
    'georgia/court_of_appeals_opinions'                       : 'gactapp',
    'illinois/appellate_court_opinions'                       : 'illappct',
    'illinois/supreme_court_opinions'                         : 'ill',
    'kansas/attorney_general_opinion'                         : 'kanattygenop',
    'louisiana/attorney_general_opinion'                      : 'laattygenop',
    'maine/supreme_judicial_court_opinions'                   : 'me',
    'maryland/attorney_general_opinion'                       : 'mdattygenop',
    'maryland/court_of_appeals_opinions'                      : 'md',
    'maryland/court_of_special_appeals_opinions'              : 'mdctspecapp',
    #'massachusetts/appellate_court_opinions'                 : 'massappct', -- contains supreme judicial court opinions
    'massachusetts/superior_court_opinions'                   : 'masssuperct',
    'massachusetts/department_of_industrial_accidents'        : 'massworkcompcom',
    'massachusetts/district_court_appellate_division_opinions': 'massdistct',
    'michigan/supreme_court_opinions'                         : 'mich',
    'michigan/court_of_appeals_opinions'                      : 'michctapp',
    'montana/attorney_general_opinion'                        : 'montattygenop',
    'nebraska/attorney_general_opinion'                       : 'nebattygenop',
    'nevada/supreme_court_opinions'                           : 'nev',
    'new_jersey/superior_court_opinions'                      : 'njsuperctappdiv',
    'new_jersey/supreme_court_opinions'                       : 'nj',
    'new_jersey/tax_court_opinions'                           : 'njtaxct',
    'new_york/attorney_general_opinion'                       : 'nyattygenop',
    'new_york/court_of_appeals_opinions'                      : 'ny',
    # This might be part of 'nylowercourts' or might be the only one worth keeping
    'new_york/supreme_court_appellate_division_opinions'      : 'nyappdiv',
    'new_york/miscellaneous_court_opinions'                   : 'nylowercourts',
    'north_carolina/business_court_opinions'                  : 'ncsuperct',
    'north_carolina/industrial_commission'                    : 'ncworkcompcom',
    'ohio/appellate_court_opinions'                           : 'ohioappct',
    'ohio/miscellaneous_court_opinions'                       : 'ohiolowercourts',
    'oklahoma/attorney_general_opinion'                       : 'oklaattygenop',
    'oregon/court_of_appeals_opinions'                        : 'orctapp',
    'oregon/tax_court_opinions'                               : 'ortc',
    'pennsylvania/superior_court_opinions'                    : 'pasuperct',
    'pennsylvania/supreme_court_opinions'                     : 'pa',
    'pennsylvania/commonwealth_court_opinions'                : 'pacommwct',
    'rhode_island/superior_court_opinions'                    : 'risuperct',
    'rhode_island/supreme_court_opinions'                     : 'ri',
    'south_dakota/supreme_court_opinions'                     : 'sd',
    'texas/attorney_general_opinion'                          : 'texattygenop',
    'vermont/supreme_court_opinions'                          : 'vt',
    'virginia/supreme_court_opinions'                         : 'va',
    'virginia/court_of_appeals_opinions'                      : 'vactapp',
    'washington/attorney_general_opinion'                     : 'washattygenop',
    'washington/supreme_court_opinions'                       : 'wash',
    'washington/court_of_appeals_opinions'                    : 'washctapp',
    'west_virginia/supreme_court_opinions'                    : 'wva',
    'wisconsin/attorney_general_opinion'                      : 'wisattygenop'
}