# Generated by Django 5.1.8 on 2025-12-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referer',
        ),
    ]
