# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-19 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0002_auto_20190719_1539'),
        ('visualizations', '0002_update_url_int_not_str'),
    ]

    operations = [
    ]
