# Generated by Django 3.1.14 on 2022-02-16 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0004_load_florida_state_courts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parenthetical",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="The text of the description as written in the describing opinion"
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        db_index=True,
                        default=0.0,
                        help_text="A score between 0 and 1 representing how descriptive the parenthetical is",
                    ),
                ),
                (
                    "described_opinion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parentheticals",
                        to="search.opinion",
                    ),
                ),
                (
                    "describing_opinion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_parentheticals",
                        to="search.opinion",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Opinion parentheticals",
            },
        ),
    ]
