# Generated by Django 3.2.12 on 2022-04-05 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people_db', '0009_fix_on_delete_add_acting_justice_noop'),
        ('recap', '0006_fix_on_delete_noop'),
        ('search', '0007_add_parenthetical_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='appeal_from',
            field=models.ForeignKey(blank=True, help_text='In appellate cases, this is the lower court or administrative body where this case was originally heard. This field is frequently blank due to it not being populated historically or due to our inability to normalize the value in appeal_from_str.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='search.court'),
        ),
        migrations.AlterField(
            model_name='docket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='The judge the case was assigned to.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='assigning', to='people_db.person'),
        ),
        migrations.AlterField(
            model_name='docket',
            name='court',
            field=models.ForeignKey(help_text='The court where the docket was filed', on_delete=django.db.models.deletion.RESTRICT, related_name='dockets', to='search.court'),
        ),
        migrations.AlterField(
            model_name='docket',
            name='idb_data',
            field=models.OneToOneField(blank=True, help_text='Data from the FJC Integrated Database associated with this case.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docket', to='recap.fjcintegrateddatabase'),
        ),
        migrations.AlterField(
            model_name='docket',
            name='originating_court_information',
            field=models.OneToOneField(blank=True, help_text='Lower court information for appellate dockets', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docket', to='search.originatingcourtinformation'),
        ),
        migrations.AlterField(
            model_name='docket',
            name='referred_to',
            field=models.ForeignKey(blank=True, help_text="The judge to whom the 'assigned_to' judge is delegated.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='referring', to='people_db.person'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='author',
            field=models.ForeignKey(blank=True, help_text='The primary author of this opinion as a normalized field', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='opinions_written', to='people_db.person'),
        ),
        migrations.AlterField(
            model_name='originatingcourtinformation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='The judge the case was assigned to.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='original_court_info', to='people_db.person'),
        ),
        migrations.AlterField(
            model_name='originatingcourtinformation',
            name='ordering_judge',
            field=models.ForeignKey(blank=True, help_text='The judge that issued the final order in the case.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='people_db.person'),
        ),
    ]
