# Generated by Django 3.2.16 on 2023-01-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_alter_court_jurisdiction'),
    ]

    operations = [
        migrations.AddField(
            model_name='docketentry',
            name='time_filed',
            field=models.TimeField(blank=True, help_text='The Docket Entry date filed time.', null=True),
        ),
    ]
