# Generated by Django 3.2.16 on 2023-01-16 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_alter_court_jurisdiction'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpinionsCitedByRECAPDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField(default=1, help_text='The number of times the cited opinion was cited in the citing document')),
                ('cited_opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citing_documents', to='search.opinion')),
                ('citing_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cited_opinions', to='search.recapdocument')),
            ],
            options={
                'verbose_name_plural': 'Opinions cited by RECAP document',
            },
        ),
        migrations.AddIndex(
            model_name='opinionscitedbyrecapdocument',
            index=models.Index(fields=['depth'], name='search_opin_depth_3307bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='opinionscitedbyrecapdocument',
            unique_together={('citing_document', 'cited_opinion')},
        ),
    ]
