# Generated by Django 3.2.16 on 2023-01-25 18:48

import cl.lib.fields
import cl.lib.model_helpers
import cl.lib.storage
from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0005_events_middlewareevents'),
        ('recap', '0011_alter_processingqueue_upload_type_noop'),
        ('people_db', '0013_remove_cl_id'),
        ('search', '0010_auto_20230116_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitationEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('volume', models.SmallIntegerField(help_text='The volume of the reporter')),
                ('reporter', models.TextField(help_text='The abbreviation for the reporter')),
                ('page', models.TextField(help_text="The 'page' of the citation in the reporter. Unfortunately, this is not an integer, but is a string-type because several jurisdictions do funny things with the so-called 'page'. For example, we have seen Roman numerals in Nebraska, 13301-M in Connecticut, and 144M in Montana.")),
                ('type', models.SmallIntegerField(choices=[(1, 'A federal reporter citation (e.g. 5 F. 55)'), (2, 'A citation in a state-based reporter (e.g. Alabama Reports)'), (3, 'A citation in a regional reporter (e.g. Atlantic Reporter)'), (4, "A citation in a specialty reporter (e.g. Lawyers' Edition)"), (5, 'A citation in an early SCOTUS reporter (e.g. 5 Black. 55)'), (6, 'A citation in the Lexis system (e.g. 5 LEXIS 55)'), (7, 'A citation in the WestLaw system (e.g. 5 WL 55)'), (8, 'A vendor neutral citation (e.g. 2013 FL 1)')], help_text='The type of citation that this is.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourtEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.CharField(help_text='a unique ID for each court as used in URLs', max_length=15, serialize=False)),
                ('pacer_court_id', models.PositiveSmallIntegerField(blank=True, help_text='The numeric ID for the court in PACER. This can be found by looking at the first three digits of any doc1 URL in PACER.', null=True)),
                ('pacer_has_rss_feed', models.BooleanField(blank=True, help_text="Whether the court has a PACER RSS feed. If null, this doesn't apply to the given court.", null=True)),
                ('pacer_rss_entry_types', models.TextField(blank=True, help_text="The types of entries provided by the court's RSS feed.")),
                ('date_last_pacer_contact', models.DateTimeField(blank=True, help_text='The last time the PACER website for the court was successfully contacted', null=True)),
                ('fjc_court_id', models.CharField(blank=True, help_text='The ID used by FJC in the Integrated Database', max_length=3)),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='The last moment when the item was modified')),
                ('in_use', models.BooleanField(default=False, help_text='Whether this jurisdiction is in use in CourtListener -- increasingly True')),
                ('has_opinion_scraper', models.BooleanField(default=False, help_text='Whether the jurisdiction has a scraper that obtains opinions automatically.')),
                ('has_oral_argument_scraper', models.BooleanField(default=False, help_text='Whether the jurisdiction has a scraper that obtains oral arguments automatically.')),
                ('position', models.FloatField(help_text='A dewey-decimal-style numeral indicating a hierarchical ordering of jurisdictions')),
                ('citation_string', models.CharField(blank=True, help_text='the citation abbreviation for the court as dictated by Blue Book', max_length=100)),
                ('short_name', models.CharField(help_text='a short name of the court', max_length=100)),
                ('full_name', models.CharField(help_text='the full name of the court', max_length=200)),
                ('url', models.URLField(blank=True, help_text='the homepage for each court or the closest thing thereto', max_length=500)),
                ('start_date', models.DateField(blank=True, help_text='the date the court was established, if known', null=True)),
                ('end_date', models.DateField(blank=True, help_text='the date the court was abolished, if known', null=True)),
                ('jurisdiction', models.CharField(choices=[('F', 'Federal Appellate'), ('FD', 'Federal District'), ('FB', 'Federal Bankruptcy'), ('FBP', 'Federal Bankruptcy Panel'), ('FS', 'Federal Special'), ('S', 'State Supreme'), ('SA', 'State Appellate'), ('ST', 'State Trial'), ('SS', 'State Special'), ('TRS', 'Tribal Supreme'), ('TRA', 'Tribal Appellate'), ('TRT', 'Tribal Trial'), ('TRX', 'Tribal Special'), ('TS', 'Territory Supreme'), ('TA', 'Territory Appellate'), ('TT', 'Territory Trial'), ('TSP', 'Territory Special'), ('SAG', 'State Attorney General'), ('C', 'Committee'), ('I', 'International'), ('T', 'Testing')], help_text='the jurisdiction of the court, one of: F (Federal Appellate), FD (Federal District), FB (Federal Bankruptcy), FBP (Federal Bankruptcy Panel), FS (Federal Special), S (State Supreme), SA (State Appellate), ST (State Trial), SS (State Special), TRS (Tribal Supreme), TRA (Tribal Appellate), TRT (Tribal Trial), TRX (Tribal Special), TS (Territory Supreme), TA (Territory Appellate), TT (Territory Trial), TSP (Territory Special), SAG (State Attorney General), C (Committee), I (International), T (Testing)', max_length=3)),
                ('notes', models.TextField(blank=True, help_text='any notes about coverage or anything else (currently very raw)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocketEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('source', models.SmallIntegerField(choices=[(0, 'Default'), (1, 'RECAP'), (2, 'Scraper'), (3, 'RECAP and Scraper'), (4, 'Columbia'), (6, 'Columbia and Scraper'), (5, 'Columbia and RECAP'), (7, 'Columbia, RECAP, and Scraper'), (8, 'Integrated Database'), (9, 'RECAP and IDB'), (10, 'Scraper and IDB'), (11, 'RECAP, Scraper, and IDB'), (12, 'Columbia and IDB'), (13, 'Columbia, RECAP, and IDB'), (14, 'Columbia, Scraper, and IDB'), (15, 'Columbia, RECAP, Scraper, and IDB'), (16, 'Harvard'), (17, 'Scraper and Harvard'), (32, 'Direct court input'), (64, '2020 anonymous database'), (66, '2020 anonymous database and Scraper'), (80, '2020 anonymous database and Harvard'), (82, '2020 anonymous database, Scraper, and Harvard')], help_text='contains the source of the Docket.')),
                ('appeal_from_str', models.TextField(blank=True, help_text='In appellate cases, this is the lower court or administrative body where this case was originally heard. This field is frequently blank due to it not being populated historically. This field may have values when the appeal_from field does not. That can happen if we are unable to normalize the value in this field.')),
                ('assigned_to_str', models.TextField(blank=True, help_text='The judge that the case was assigned to, as a string.')),
                ('referred_to_str', models.TextField(blank=True, help_text='The judge that the case was referred to, as a string.')),
                ('panel_str', models.TextField(blank=True, help_text="The initials of the judges on the panel that heard this case. This field is similar to the 'judges' field on the cluster, but contains initials instead of full judge names, and applies to the case on the whole instead of only to a specific decision.")),
                ('date_last_index', models.DateTimeField(blank=True, help_text='The last moment that the item was indexed in Solr.', null=True)),
                ('date_cert_granted', models.DateField(blank=True, help_text='date cert was granted for this case, if applicable', null=True)),
                ('date_cert_denied', models.DateField(blank=True, help_text='the date cert was denied for this case, if applicable', null=True)),
                ('date_argued', models.DateField(blank=True, help_text='the date the case was argued', null=True)),
                ('date_reargued', models.DateField(blank=True, help_text='the date the case was reargued', null=True)),
                ('date_reargument_denied', models.DateField(blank=True, help_text='the date the reargument was denied', null=True)),
                ('date_filed', models.DateField(blank=True, help_text='The date the case was filed.', null=True)),
                ('date_terminated', models.DateField(blank=True, help_text='The date the case was terminated.', null=True)),
                ('date_last_filing', models.DateField(blank=True, help_text="The date the case was last updated in the docket, as shown in PACER's Docket History report or iquery page.", null=True)),
                ('case_name_short', models.TextField(blank=True, help_text="The abridged name of the case, often a single word, e.g. 'Marsh'")),
                ('case_name', models.TextField(blank=True, help_text='The standard name of the case')),
                ('case_name_full', models.TextField(blank=True, help_text='The full name of the case')),
                ('slug', models.SlugField(blank=True, db_index=False, help_text='URL that the document should map to (the slug)', max_length=75)),
                ('docket_number', models.TextField(blank=True, help_text='The docket numbers of a case, can be consolidated and quite long. In some instances they are too long to be indexed by postgres and we store the full docket in the correction field on the Opinion Cluster.', null=True)),
                ('docket_number_core', models.CharField(blank=True, help_text='For federal district court dockets, this is the most distilled docket number available. In this field, the docket number is stripped down to only the year and serial digits, eliminating the office at the beginning, letters in the middle, and the judge at the end. Thus, a docket number like 2:07-cv-34911-MJL becomes simply 0734911. This is the format that is provided by the IDB and is useful for de-duplication types of activities which otherwise get messy. We use a char field here to preserve leading zeros.', max_length=20)),
                ('pacer_case_id', cl.lib.fields.CharNullField(blank=True, help_text='The cased ID provided by PACER.', max_length=100, null=True)),
                ('cause', models.CharField(blank=True, help_text='The cause for the case.', max_length=2000)),
                ('nature_of_suit', models.CharField(blank=True, help_text='The nature of suit code from PACER.', max_length=1000)),
                ('jury_demand', models.CharField(blank=True, help_text='The compensation demand.', max_length=500)),
                ('jurisdiction_type', models.CharField(blank=True, help_text="Stands for jurisdiction in RECAP XML docket. For example, 'Diversity', 'U.S. Government Defendant'.", max_length=100)),
                ('appellate_fee_status', models.TextField(blank=True, help_text='The status of the fee in the appellate court. Can be used as a hint as to whether the government is the appellant (in which case the fee is waived).')),
                ('appellate_case_type_information', models.TextField(blank=True, help_text="Information about a case from the appellate docket in PACER. For example, 'civil, private, bankruptcy'.")),
                ('mdl_status', models.CharField(blank=True, help_text='The MDL status of a case before the Judicial Panel for Multidistrict Litigation', max_length=100)),
                ('filepath_local', models.FileField(blank=True, help_text="Path to RECAP's Docket XML page as provided by the original RECAP architecture. These fields are for backup purposes only. Note that the field name is historical, from before when we used S3. To find the location in S3, concatenate https://storage.courtlistener.com/ and the value of this field.", max_length=1000, storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.lib.model_helpers.make_recap_path)),
                ('filepath_ia', models.CharField(blank=True, help_text='Path to the Docket XML page in The Internet Archive', max_length=1000)),
                ('filepath_ia_json', models.CharField(blank=True, help_text='Path to the docket JSON page in the Internet Archive', max_length=1000)),
                ('ia_upload_failure_count', models.SmallIntegerField(blank=True, help_text='Number of times the upload to the Internet Archive failed.', null=True)),
                ('ia_needs_upload', models.BooleanField(blank=True, help_text="Does this item need to be uploaded to the Internet Archive? I.e., has it changed? This field is important because it keeps track of the status of all the related objects to the docket. For example, if a related docket entry changes, we need to upload the item to IA, but we can't easily check that.", null=True)),
                ('ia_date_first_change', models.DateTimeField(blank=True, help_text='The moment when this item first changed and was marked as needing an upload. Used for determining when to upload an item.', null=True)),
                ('view_count', models.IntegerField(default=0, help_text='The number of times the docket has been seen.')),
                ('date_blocked', models.DateField(blank=True, help_text='The date that this opinion was blocked from indexing by search engines', null=True)),
                ('blocked', models.BooleanField(default=False, help_text='Whether a document should be blocked from indexing by search engines')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocketPanelEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocketTagsEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpinionClusterEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('judges', models.TextField(blank=True, help_text='The judges that participated in the opinion as a simple text string. This field is used when normalized judges cannot be placed into the panel field.')),
                ('date_filed', models.DateField(help_text='The date the cluster of opinions was filed by the court')),
                ('date_filed_is_approximate', models.BooleanField(default=False, help_text='For a variety of opinions getting the correct date filed isvery difficult. For these, we have used heuristics to approximate the date.')),
                ('slug', models.SlugField(db_index=False, help_text='URL that the document should map to (the slug)', max_length=75, null=True)),
                ('case_name_short', models.TextField(blank=True, help_text="The abridged name of the case, often a single word, e.g. 'Marsh'")),
                ('case_name', models.TextField(blank=True, help_text='The shortened name of the case')),
                ('case_name_full', models.TextField(blank=True, help_text='The full name of the case')),
                ('scdb_id', models.CharField(blank=True, help_text='The ID of the item in the Supreme Court Database', max_length=10)),
                ('scdb_decision_direction', models.IntegerField(blank=True, choices=[(1, 'Conservative'), (2, 'Liberal'), (3, 'Unspecifiable')], help_text='the ideological "direction" of a decision in the Supreme Court database. More details at: http://scdb.wustl.edu/documentation.php?var=decisionDirection', null=True)),
                ('scdb_votes_majority', models.IntegerField(blank=True, help_text='the number of justices voting in the majority in a Supreme Court decision. More details at: http://scdb.wustl.edu/documentation.php?var=majVotes', null=True)),
                ('scdb_votes_minority', models.IntegerField(blank=True, help_text='the number of justices voting in the minority in a Supreme Court decision. More details at: http://scdb.wustl.edu/documentation.php?var=minVotes', null=True)),
                ('source', models.CharField(blank=True, choices=[('C', 'court website'), ('R', 'public.resource.org'), ('CR', 'court website merged with resource.org'), ('L', 'lawbox'), ('LC', 'lawbox merged with court'), ('LR', 'lawbox merged with resource.org'), ('LCR', 'lawbox merged with court and resource.org'), ('M', 'manual input'), ('A', 'internet archive'), ('H', 'brad heath archive'), ('Z', 'columbia archive'), ('ZC', 'columbia merged with court'), ('ZLC', 'columbia merged with lawbox and court'), ('ZLR', 'columbia merged with lawbox and resource.org'), ('ZLCR', 'columbia merged with lawbox, court, and resource.org'), ('ZR', 'columbia merged with resource.org'), ('ZCR', 'columbia merged with court and resource.org'), ('ZL', 'columbia merged with lawbox'), ('U', 'Harvard, Library Innovation Lab Case Law Access Project'), ('CU', 'court website merged with Harvard'), ('D', 'direct court input')], help_text='the source of the cluster, one of: C (court website), R (public.resource.org), CR (court website merged with resource.org), L (lawbox), LC (lawbox merged with court), LR (lawbox merged with resource.org), LCR (lawbox merged with court and resource.org), M (manual input), A (internet archive), H (brad heath archive), Z (columbia archive), ZC (columbia merged with court), ZLC (columbia merged with lawbox and court), ZLR (columbia merged with lawbox and resource.org), ZLCR (columbia merged with lawbox, court, and resource.org), ZR (columbia merged with resource.org), ZCR (columbia merged with court and resource.org), ZL (columbia merged with lawbox), U (Harvard, Library Innovation Lab Case Law Access Project), CU (court website merged with Harvard), D (direct court input)', max_length=10)),
                ('procedural_history', models.TextField(blank=True, help_text='The history of the case as it jumped from court to court')),
                ('attorneys', models.TextField(blank=True, help_text='The attorneys that argued the case, as free text')),
                ('nature_of_suit', models.TextField(blank=True, help_text='The nature of the suit. For the moment can be codes or laws or whatever')),
                ('posture', models.TextField(blank=True, help_text='The procedural posture of the case.')),
                ('syllabus', models.TextField(blank=True, help_text='A summary of the issues presented in the case and the outcome.')),
                ('headnotes', models.TextField(blank=True, help_text='Headnotes are summary descriptions of the legal issues discussed by the court in the particular case. They appear at the beginning of each case just after the summary and disposition. They are short paragraphs with a heading in bold face type. From Wikipedia - A headnote is a brief summary of a particular point of law that is added to the text of a courtdecision to aid readers in locating discussion of a legalissue in an opinion. As the term implies, headnotes appearat the beginning of the published opinion. Frequently, headnotes are value-added components appended to decisions by the publisher who compiles the decisions of a court for resale. As handed down by the court, a decision or written opinion does not contain headnotes. These are added later by an editor not connected to the court, but who instead works for a legal publishing house.')),
                ('summary', models.TextField(blank=True, help_text='A summary of what happened in the case. Appears at the beginning of the case just after the title of the case and court information.')),
                ('disposition', models.TextField(blank=True, help_text='Description of the procedural outcome of the case, e.g. Reversed, dismissed etc. Generally a short paragraph that appears just after the summary or synopsis')),
                ('history', models.TextField(blank=True, help_text='History of the case (similar to the summary, but focused on past events related to this case). Appears at the beginning of the case just after the title of the case and court information')),
                ('other_dates', models.TextField(blank=True, help_text='Other date(s) as specified in the text (case header). This may include follow-up dates.')),
                ('cross_reference', models.TextField(blank=True, help_text='Cross-reference citation (often to a past or future similar case). It does NOT identify this case.')),
                ('correction', models.TextField(blank=True, help_text="Publisher's correction to the case text. Example: Replace last paragraph on page 476 with this text: blah blah blah. This is basically an unstructured text that can be used to manually correct case content according to publisher's instructions. No footnotes is expected within it.")),
                ('citation_count', models.IntegerField(default=0, help_text='The number of times this document is cited by other opinion')),
                ('precedential_status', models.CharField(blank=True, choices=[('Published', 'Precedential'), ('Unpublished', 'Non-Precedential'), ('Errata', 'Errata'), ('Separate', 'Separate Opinion'), ('In-chambers', 'In-chambers'), ('Relating-to', 'Relating-to orders'), ('Unknown', 'Unknown Status')], help_text='The precedential status of document, one of: Published, Unpublished, Errata, Separate, In-chambers, Relating-to, Unknown', max_length=50)),
                ('date_blocked', models.DateField(blank=True, help_text='The date that this opinion was blocked from indexing by search engines', null=True)),
                ('blocked', models.BooleanField(default=False, help_text='Whether a document should be blocked from indexing by search engines')),
                ('filepath_json_harvard', models.FileField(blank=True, help_text='Path to local storage of JSON collected from Harvard Case Law project containing available metadata, opinion and opinion cluster.', max_length=1000, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpinionClusterNonParticipatingJudgesEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpinionClusterPanelEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpinionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('author_str', models.TextField(blank=True, help_text='The primary author of this opinion, as a simple text string. This field is used when normalized judges cannot be placed into the author field.')),
                ('per_curiam', models.BooleanField(default=False, help_text='Is this opinion per curiam, without a single author?')),
                ('joined_by_str', models.TextField(blank=True, help_text='Other judges that joined the primary author in this opinion str')),
                ('type', models.CharField(choices=[('010combined', 'Combined Opinion'), ('015unamimous', 'Unanimous Opinion'), ('020lead', 'Lead Opinion'), ('025plurality', 'Plurality Opinion'), ('030concurrence', 'Concurrence Opinion'), ('035concurrenceinpart', 'In Part Opinion'), ('040dissent', 'Dissent'), ('050addendum', 'Addendum'), ('060remittitur', 'Remittitur'), ('070rehearing', 'Rehearing'), ('080onthemerits', 'On the Merits'), ('090onmotiontostrike', 'On Motion to Strike Cost Bill')], max_length=20)),
                ('sha1', models.CharField(blank=True, help_text='unique ID for the document, as generated via SHA1 of the binary file or text data', max_length=40)),
                ('page_count', models.IntegerField(blank=True, help_text='The number of pages in the document, if known', null=True)),
                ('download_url', models.URLField(blank=True, help_text='The URL where the item was originally scraped. Note that these URLs may often be dead due to the court or the bulk provider changing their website. We keep the original link here given that it often contains valuable metadata.', max_length=500, null=True)),
                ('local_path', models.FileField(blank=True, help_text='The location in AWS S3 where the original opinion file is stored. Note that the field name is historical, from before when we used S3. To find the location in S3, concatenate https://storage.courtlistener.com/ and the value of this field.', storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.lib.model_helpers.make_upload_path)),
                ('plain_text', models.TextField(blank=True, help_text='Plain text of the document after extraction using pdftotext, wpd2txt, etc.')),
                ('html', models.TextField(blank=True, help_text='HTML of the document, if available in the original')),
                ('html_lawbox', models.TextField(blank=True, help_text='HTML of Lawbox documents')),
                ('html_columbia', models.TextField(blank=True, help_text='HTML of Columbia archive')),
                ('html_anon_2020', models.TextField(blank=True, help_text='HTML of 2020 anonymous archive')),
                ('xml_harvard', models.TextField(blank=True, help_text='XML of Harvard CaseLaw Access Project opinion')),
                ('html_with_citations', models.TextField(blank=True, help_text='HTML of the document with citation links and other post-processed markup added')),
                ('extracted_by_ocr', models.BooleanField(default=False, help_text='Whether OCR was used to get this document content')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpinionJoinedByEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpinionOpinionsCitedEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('depth', models.IntegerField(default=1, help_text='The number of times the cited opinion was cited in the citing opinion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocketPanel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('search.docket_panel',),
        ),
        migrations.CreateModel(
            name='DocketTags',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('search.docket_tags',),
        ),
        migrations.CreateModel(
            name='OpinionClusterNonParticipatingJudges',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('search.opinioncluster_non_participating_judges',),
        ),
        migrations.CreateModel(
            name='OpinionClusterPanel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('search.opinioncluster_panel',),
        ),
        migrations.CreateModel(
            name='OpinionJoinedBy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('search.opinion_joined_by',),
        ),
        migrations.CreateModel(
            name='OpinionOpinionsCited',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('search.opinionscited',),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='citation',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_citationevent" ("cluster_id", "id", "page", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reporter", "type", "volume") VALUES (NEW."cluster_id", NEW."id", NEW."page", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."reporter", NEW."type", NEW."volume"); RETURN NULL;', hash='6754ba8bbf994aee87c5236c0cb63f6ac2dedba0', operation='INSERT', pgid='pgtrigger_snapshot_insert_596d3', table='search_citation', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='citation',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "search_citationevent" ("cluster_id", "id", "page", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reporter", "type", "volume") VALUES (NEW."cluster_id", NEW."id", NEW."page", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."reporter", NEW."type", NEW."volume"); RETURN NULL;', hash='b2b27f069bb64eddfd351add29fc2dbe8243da86', operation='UPDATE', pgid='pgtrigger_snapshot_update_31b3d', table='search_citation', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='court',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_courtevent" ("citation_string", "date_last_pacer_contact", "date_modified", "end_date", "fjc_court_id", "full_name", "has_opinion_scraper", "has_oral_argument_scraper", "id", "in_use", "jurisdiction", "notes", "pacer_court_id", "pacer_has_rss_feed", "pacer_rss_entry_types", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "position", "short_name", "start_date", "url") VALUES (NEW."citation_string", NEW."date_last_pacer_contact", NEW."date_modified", NEW."end_date", NEW."fjc_court_id", NEW."full_name", NEW."has_opinion_scraper", NEW."has_oral_argument_scraper", NEW."id", NEW."in_use", NEW."jurisdiction", NEW."notes", NEW."pacer_court_id", NEW."pacer_has_rss_feed", NEW."pacer_rss_entry_types", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."position", NEW."short_name", NEW."start_date", NEW."url"); RETURN NULL;', hash='ed2bc4b44e37b73726ebde31bf3c78f4c3619d98', operation='INSERT', pgid='pgtrigger_snapshot_insert_82101', table='search_court', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='court',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "search_courtevent" ("citation_string", "date_last_pacer_contact", "date_modified", "end_date", "fjc_court_id", "full_name", "has_opinion_scraper", "has_oral_argument_scraper", "id", "in_use", "jurisdiction", "notes", "pacer_court_id", "pacer_has_rss_feed", "pacer_rss_entry_types", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "position", "short_name", "start_date", "url") VALUES (NEW."citation_string", NEW."date_last_pacer_contact", NEW."date_modified", NEW."end_date", NEW."fjc_court_id", NEW."full_name", NEW."has_opinion_scraper", NEW."has_oral_argument_scraper", NEW."id", NEW."in_use", NEW."jurisdiction", NEW."notes", NEW."pacer_court_id", NEW."pacer_has_rss_feed", NEW."pacer_rss_entry_types", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."position", NEW."short_name", NEW."start_date", NEW."url"); RETURN NULL;', hash='51eac3389569bbe20caaf3d42566643bf6b7c091', operation='UPDATE', pgid='pgtrigger_snapshot_update_cc9e2', table='search_court', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='docket',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_docketevent" ("appeal_from_id", "appeal_from_str", "appellate_case_type_information", "appellate_fee_status", "assigned_to_id", "assigned_to_str", "blocked", "case_name", "case_name_full", "case_name_short", "cause", "court_id", "date_argued", "date_blocked", "date_cert_denied", "date_cert_granted", "date_created", "date_filed", "date_last_filing", "date_last_index", "date_modified", "date_reargued", "date_reargument_denied", "date_terminated", "docket_number", "docket_number_core", "filepath_ia", "filepath_ia_json", "filepath_local", "ia_date_first_change", "ia_needs_upload", "ia_upload_failure_count", "id", "idb_data_id", "jurisdiction_type", "jury_demand", "mdl_status", "nature_of_suit", "originating_court_information_id", "pacer_case_id", "panel_str", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "referred_to_id", "referred_to_str", "slug", "source", "view_count") VALUES (NEW."appeal_from_id", NEW."appeal_from_str", NEW."appellate_case_type_information", NEW."appellate_fee_status", NEW."assigned_to_id", NEW."assigned_to_str", NEW."blocked", NEW."case_name", NEW."case_name_full", NEW."case_name_short", NEW."cause", NEW."court_id", NEW."date_argued", NEW."date_blocked", NEW."date_cert_denied", NEW."date_cert_granted", NEW."date_created", NEW."date_filed", NEW."date_last_filing", NEW."date_last_index", NEW."date_modified", NEW."date_reargued", NEW."date_reargument_denied", NEW."date_terminated", NEW."docket_number", NEW."docket_number_core", NEW."filepath_ia", NEW."filepath_ia_json", NEW."filepath_local", NEW."ia_date_first_change", NEW."ia_needs_upload", NEW."ia_upload_failure_count", NEW."id", NEW."idb_data_id", NEW."jurisdiction_type", NEW."jury_demand", NEW."mdl_status", NEW."nature_of_suit", NEW."originating_court_information_id", NEW."pacer_case_id", NEW."panel_str", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."referred_to_id", NEW."referred_to_str", NEW."slug", NEW."source", NEW."view_count"); RETURN NULL;', hash='8177d4bbd7e4bede9a2a5e821fa582d48728a9a3', operation='INSERT', pgid='pgtrigger_snapshot_insert_fe9ff', table='search_docket', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='docket',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "search_docketevent" ("appeal_from_id", "appeal_from_str", "appellate_case_type_information", "appellate_fee_status", "assigned_to_id", "assigned_to_str", "blocked", "case_name", "case_name_full", "case_name_short", "cause", "court_id", "date_argued", "date_blocked", "date_cert_denied", "date_cert_granted", "date_created", "date_filed", "date_last_filing", "date_last_index", "date_modified", "date_reargued", "date_reargument_denied", "date_terminated", "docket_number", "docket_number_core", "filepath_ia", "filepath_ia_json", "filepath_local", "ia_date_first_change", "ia_needs_upload", "ia_upload_failure_count", "id", "idb_data_id", "jurisdiction_type", "jury_demand", "mdl_status", "nature_of_suit", "originating_court_information_id", "pacer_case_id", "panel_str", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "referred_to_id", "referred_to_str", "slug", "source", "view_count") VALUES (NEW."appeal_from_id", NEW."appeal_from_str", NEW."appellate_case_type_information", NEW."appellate_fee_status", NEW."assigned_to_id", NEW."assigned_to_str", NEW."blocked", NEW."case_name", NEW."case_name_full", NEW."case_name_short", NEW."cause", NEW."court_id", NEW."date_argued", NEW."date_blocked", NEW."date_cert_denied", NEW."date_cert_granted", NEW."date_created", NEW."date_filed", NEW."date_last_filing", NEW."date_last_index", NEW."date_modified", NEW."date_reargued", NEW."date_reargument_denied", NEW."date_terminated", NEW."docket_number", NEW."docket_number_core", NEW."filepath_ia", NEW."filepath_ia_json", NEW."filepath_local", NEW."ia_date_first_change", NEW."ia_needs_upload", NEW."ia_upload_failure_count", NEW."id", NEW."idb_data_id", NEW."jurisdiction_type", NEW."jury_demand", NEW."mdl_status", NEW."nature_of_suit", NEW."originating_court_information_id", NEW."pacer_case_id", NEW."panel_str", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."referred_to_id", NEW."referred_to_str", NEW."slug", NEW."source", NEW."view_count"); RETURN NULL;', hash='6e02e752adaf37d3f63141796444c9e12edcf00d', operation='UPDATE', pgid='pgtrigger_snapshot_update_1e722', table='search_docket', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='opinion',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_opinionevent" ("author_id", "author_str", "cluster_id", "date_created", "date_modified", "download_url", "extracted_by_ocr", "html", "html_anon_2020", "html_columbia", "html_lawbox", "html_with_citations", "id", "joined_by_str", "local_path", "page_count", "per_curiam", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plain_text", "sha1", "type", "xml_harvard") VALUES (NEW."author_id", NEW."author_str", NEW."cluster_id", NEW."date_created", NEW."date_modified", NEW."download_url", NEW."extracted_by_ocr", NEW."html", NEW."html_anon_2020", NEW."html_columbia", NEW."html_lawbox", NEW."html_with_citations", NEW."id", NEW."joined_by_str", NEW."local_path", NEW."page_count", NEW."per_curiam", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."plain_text", NEW."sha1", NEW."type", NEW."xml_harvard"); RETURN NULL;', hash='c65912952e99b1fa6f54facaa7d46c04ea1fabed', operation='INSERT', pgid='pgtrigger_snapshot_insert_6ae1e', table='search_opinion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='opinion',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "search_opinionevent" ("author_id", "author_str", "cluster_id", "date_created", "date_modified", "download_url", "extracted_by_ocr", "html", "html_anon_2020", "html_columbia", "html_lawbox", "html_with_citations", "id", "joined_by_str", "local_path", "page_count", "per_curiam", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plain_text", "sha1", "type", "xml_harvard") VALUES (NEW."author_id", NEW."author_str", NEW."cluster_id", NEW."date_created", NEW."date_modified", NEW."download_url", NEW."extracted_by_ocr", NEW."html", NEW."html_anon_2020", NEW."html_columbia", NEW."html_lawbox", NEW."html_with_citations", NEW."id", NEW."joined_by_str", NEW."local_path", NEW."page_count", NEW."per_curiam", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."plain_text", NEW."sha1", NEW."type", NEW."xml_harvard"); RETURN NULL;', hash='31abe6319b984ddbc8ee374a72c87b915099904c', operation='UPDATE', pgid='pgtrigger_snapshot_update_cdf06', table='search_opinion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='opinioncluster',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_opinionclusterevent" ("attorneys", "blocked", "case_name", "case_name_full", "case_name_short", "citation_count", "correction", "cross_reference", "date_blocked", "date_created", "date_filed", "date_filed_is_approximate", "date_modified", "disposition", "docket_id", "filepath_json_harvard", "headnotes", "history", "id", "judges", "nature_of_suit", "other_dates", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "posture", "precedential_status", "procedural_history", "scdb_decision_direction", "scdb_id", "scdb_votes_majority", "scdb_votes_minority", "slug", "source", "summary", "syllabus") VALUES (NEW."attorneys", NEW."blocked", NEW."case_name", NEW."case_name_full", NEW."case_name_short", NEW."citation_count", NEW."correction", NEW."cross_reference", NEW."date_blocked", NEW."date_created", NEW."date_filed", NEW."date_filed_is_approximate", NEW."date_modified", NEW."disposition", NEW."docket_id", NEW."filepath_json_harvard", NEW."headnotes", NEW."history", NEW."id", NEW."judges", NEW."nature_of_suit", NEW."other_dates", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."posture", NEW."precedential_status", NEW."procedural_history", NEW."scdb_decision_direction", NEW."scdb_id", NEW."scdb_votes_majority", NEW."scdb_votes_minority", NEW."slug", NEW."source", NEW."summary", NEW."syllabus"); RETURN NULL;', hash='2cf587c27dec64b1d23bbacd51e65724a3b5b306', operation='INSERT', pgid='pgtrigger_snapshot_insert_b55e2', table='search_opinioncluster', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='opinioncluster',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "search_opinionclusterevent" ("attorneys", "blocked", "case_name", "case_name_full", "case_name_short", "citation_count", "correction", "cross_reference", "date_blocked", "date_created", "date_filed", "date_filed_is_approximate", "date_modified", "disposition", "docket_id", "filepath_json_harvard", "headnotes", "history", "id", "judges", "nature_of_suit", "other_dates", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "posture", "precedential_status", "procedural_history", "scdb_decision_direction", "scdb_id", "scdb_votes_majority", "scdb_votes_minority", "slug", "source", "summary", "syllabus") VALUES (NEW."attorneys", NEW."blocked", NEW."case_name", NEW."case_name_full", NEW."case_name_short", NEW."citation_count", NEW."correction", NEW."cross_reference", NEW."date_blocked", NEW."date_created", NEW."date_filed", NEW."date_filed_is_approximate", NEW."date_modified", NEW."disposition", NEW."docket_id", NEW."filepath_json_harvard", NEW."headnotes", NEW."history", NEW."id", NEW."judges", NEW."nature_of_suit", NEW."other_dates", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."posture", NEW."precedential_status", NEW."procedural_history", NEW."scdb_decision_direction", NEW."scdb_id", NEW."scdb_votes_majority", NEW."scdb_votes_minority", NEW."slug", NEW."source", NEW."summary", NEW."syllabus"); RETURN NULL;', hash='aab40c6b0b890403f82c3934397e16526f1f9753', operation='UPDATE', pgid='pgtrigger_snapshot_update_f129e', table='search_opinioncluster', when='AFTER')),
        ),
        migrations.AddField(
            model_name='opinionopinionscitedevent',
            name='cited_opinion',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.opinion'),
        ),
        migrations.AddField(
            model_name='opinionopinionscitedevent',
            name='citing_opinion',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.opinion'),
        ),
        migrations.AddField(
            model_name='opinionopinionscitedevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='opinionjoinedbyevent',
            name='opinion',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.opinion'),
        ),
        migrations.AddField(
            model_name='opinionjoinedbyevent',
            name='person',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='people_db.person'),
        ),
        migrations.AddField(
            model_name='opinionjoinedbyevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='opinionevent',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The primary author of this opinion as a normalized field', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='people_db.person'),
        ),
        migrations.AddField(
            model_name='opinionevent',
            name='cluster',
            field=models.ForeignKey(db_constraint=False, help_text='The cluster that the opinion is a part of', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.opinioncluster'),
        ),
        migrations.AddField(
            model_name='opinionevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='opinionevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='search.opinion'),
        ),
        migrations.AddField(
            model_name='opinionclusterpanelevent',
            name='opinioncluster',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.opinioncluster'),
        ),
        migrations.AddField(
            model_name='opinionclusterpanelevent',
            name='person',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='people_db.person'),
        ),
        migrations.AddField(
            model_name='opinionclusterpanelevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='opinionclusternonparticipatingjudgesevent',
            name='opinioncluster',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.opinioncluster'),
        ),
        migrations.AddField(
            model_name='opinionclusternonparticipatingjudgesevent',
            name='person',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='people_db.person'),
        ),
        migrations.AddField(
            model_name='opinionclusternonparticipatingjudgesevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='opinionclusterevent',
            name='docket',
            field=models.ForeignKey(db_constraint=False, help_text='The docket that the opinion cluster is a part of', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.docket'),
        ),
        migrations.AddField(
            model_name='opinionclusterevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='opinionclusterevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='search.opinioncluster'),
        ),
        migrations.AddField(
            model_name='dockettagsevent',
            name='docket',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.docket'),
        ),
        migrations.AddField(
            model_name='dockettagsevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='dockettagsevent',
            name='tag',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.tag'),
        ),
        migrations.AddField(
            model_name='docketpanelevent',
            name='docket',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.docket'),
        ),
        migrations.AddField(
            model_name='docketpanelevent',
            name='person',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='people_db.person'),
        ),
        migrations.AddField(
            model_name='docketpanelevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='docketevent',
            name='appeal_from',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='In appellate cases, this is the lower court or administrative body where this case was originally heard. This field is frequently blank due to it not being populated historically or due to our inability to normalize the value in appeal_from_str.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.court'),
        ),
        migrations.AddField(
            model_name='docketevent',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The judge the case was assigned to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='people_db.person'),
        ),
        migrations.AddField(
            model_name='docketevent',
            name='court',
            field=models.ForeignKey(db_constraint=False, help_text='The court where the docket was filed', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.court'),
        ),
        migrations.AddField(
            model_name='docketevent',
            name='idb_data',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Data from the FJC Integrated Database associated with this case.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='recap.fjcintegrateddatabase'),
        ),
        migrations.AddField(
            model_name='docketevent',
            name='originating_court_information',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Lower court information for appellate dockets', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.originatingcourtinformation'),
        ),
        migrations.AddField(
            model_name='docketevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='docketevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='search.docket'),
        ),
        migrations.AddField(
            model_name='docketevent',
            name='referred_to',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="The judge to whom the 'assigned_to' judge is delegated.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='people_db.person'),
        ),
        migrations.AddField(
            model_name='courtevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='courtevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='search.court'),
        ),
        migrations.AddField(
            model_name='citationevent',
            name='cluster',
            field=models.ForeignKey(db_constraint=False, help_text='The cluster that the citation applies to', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.opinioncluster'),
        ),
        migrations.AddField(
            model_name='citationevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='citationevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='search.citation'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='docketpanel',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_docketpanelevent" ("docket_id", "id", "person_id", "pgh_context_id", "pgh_created_at", "pgh_label") VALUES (NEW."docket_id", NEW."id", NEW."person_id", _pgh_attach_context(), NOW(), \'snapshot\'); RETURN NULL;', hash='74d42fd24f3900652a09c52ff42225b822c3e4c4', operation='INSERT', pgid='pgtrigger_snapshot_insert_23fa7', table='search_docket_panel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='docketpanel',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "search_docketpanelevent" ("docket_id", "id", "person_id", "pgh_context_id", "pgh_created_at", "pgh_label") VALUES (NEW."docket_id", NEW."id", NEW."person_id", _pgh_attach_context(), NOW(), \'snapshot\'); RETURN NULL;', hash='cabe688dcbfa55a212287ebe5d52037924bead84', operation='UPDATE', pgid='pgtrigger_snapshot_update_e0bd2', table='search_docket_panel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='dockettags',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_dockettagsevent" ("docket_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "tag_id") VALUES (NEW."docket_id", NEW."id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."tag_id"); RETURN NULL;', hash='34cb6117e99c4cc416d306e94c46f4d38a27f14c', operation='INSERT', pgid='pgtrigger_snapshot_insert_b723b', table='search_docket_tags', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='dockettags',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "search_dockettagsevent" ("docket_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "tag_id") VALUES (NEW."docket_id", NEW."id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."tag_id"); RETURN NULL;', hash='b25d863b87575dfdfb93a36dd16afc3d3ac115e9', operation='UPDATE', pgid='pgtrigger_snapshot_update_59839', table='search_docket_tags', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='opinionclusternonparticipatingjudges',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_opinionclusternonparticipatingjudgesevent" ("id", "opinioncluster_id", "person_id", "pgh_context_id", "pgh_created_at", "pgh_label") VALUES (NEW."id", NEW."opinioncluster_id", NEW."person_id", _pgh_attach_context(), NOW(), \'snapshot\'); RETURN NULL;', hash='c98991c93dda9f29eeab5e9126470e25f4ec7ea8', operation='INSERT', pgid='pgtrigger_snapshot_insert_0000e', table='search_opinioncluster_non_participating_judges', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='opinionclusternonparticipatingjudges',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "search_opinionclusternonparticipatingjudgesevent" ("id", "opinioncluster_id", "person_id", "pgh_context_id", "pgh_created_at", "pgh_label") VALUES (NEW."id", NEW."opinioncluster_id", NEW."person_id", _pgh_attach_context(), NOW(), \'snapshot\'); RETURN NULL;', hash='22f3de5e60619ba7e4b1c57941a63fd0183abd28', operation='UPDATE', pgid='pgtrigger_snapshot_update_8f2d1', table='search_opinioncluster_non_participating_judges', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='opinionclusterpanel',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_opinionclusterpanelevent" ("id", "opinioncluster_id", "person_id", "pgh_context_id", "pgh_created_at", "pgh_label") VALUES (NEW."id", NEW."opinioncluster_id", NEW."person_id", _pgh_attach_context(), NOW(), \'snapshot\'); RETURN NULL;', hash='55685fc2e1efbfb7ba7a63a64ad0a14fcde37817', operation='INSERT', pgid='pgtrigger_snapshot_insert_3e719', table='search_opinioncluster_panel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='opinionclusterpanel',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "search_opinionclusterpanelevent" ("id", "opinioncluster_id", "person_id", "pgh_context_id", "pgh_created_at", "pgh_label") VALUES (NEW."id", NEW."opinioncluster_id", NEW."person_id", _pgh_attach_context(), NOW(), \'snapshot\'); RETURN NULL;', hash='2d92289ef7590f116a68817146315937e25b2715', operation='UPDATE', pgid='pgtrigger_snapshot_update_2a689', table='search_opinioncluster_panel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='opinionjoinedby',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_opinionjoinedbyevent" ("id", "opinion_id", "person_id", "pgh_context_id", "pgh_created_at", "pgh_label") VALUES (NEW."id", NEW."opinion_id", NEW."person_id", _pgh_attach_context(), NOW(), \'snapshot\'); RETURN NULL;', hash='ab71a7d9bdeab2baa3568b2659edb83ba5653725', operation='INSERT', pgid='pgtrigger_snapshot_insert_541c3', table='search_opinion_joined_by', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='opinionjoinedby',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "search_opinionjoinedbyevent" ("id", "opinion_id", "person_id", "pgh_context_id", "pgh_created_at", "pgh_label") VALUES (NEW."id", NEW."opinion_id", NEW."person_id", _pgh_attach_context(), NOW(), \'snapshot\'); RETURN NULL;', hash='694b606ec9b855311a850bf376434611982b334c', operation='UPDATE', pgid='pgtrigger_snapshot_update_23a70', table='search_opinion_joined_by', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='opinionopinionscited',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_opinionopinionscitedevent" ("cited_opinion_id", "citing_opinion_id", "depth", "id", "pgh_context_id", "pgh_created_at", "pgh_label") VALUES (NEW."cited_opinion_id", NEW."citing_opinion_id", NEW."depth", NEW."id", _pgh_attach_context(), NOW(), \'snapshot\'); RETURN NULL;', hash='f91e95831640ad3589cb7d1dc1cc1a2983af00d9', operation='INSERT', pgid='pgtrigger_snapshot_insert_89103', table='search_opinionscited', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='opinionopinionscited',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "search_opinionopinionscitedevent" ("cited_opinion_id", "citing_opinion_id", "depth", "id", "pgh_context_id", "pgh_created_at", "pgh_label") VALUES (NEW."cited_opinion_id", NEW."citing_opinion_id", NEW."depth", NEW."id", _pgh_attach_context(), NOW(), \'snapshot\'); RETURN NULL;', hash='a9363eda8800fd5daa11ef4119ede0e8d576fd9f', operation='UPDATE', pgid='pgtrigger_snapshot_update_6ec56', table='search_opinionscited', when='AFTER')),
        ),
    ]
