# Generated by Django 3.2.17 on 2023-02-16 07:39

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_alter_docket_sources_noop'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='docketentry',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='docketentry',
            name='snapshot_update',
        ),
        migrations.AddField(
            model_name='docketentry',
            name='time_filed',
            field=models.TimeField(blank=True, help_text='The created time of the Docket Entry according to the court timezone, null if no time data is available.', null=True),
        ),
        migrations.AddField(
            model_name='docketentryevent',
            name='time_filed',
            field=models.TimeField(blank=True, help_text='The created time of the Docket Entry according to the court timezone, null if no time data is available.', null=True),
        ),
        migrations.AlterField(
            model_name='docketentry',
            name='date_filed',
            field=models.DateField(blank=True, help_text='The created date of the Docket Entry according to the court timezone.', null=True),
        ),
        migrations.AlterField(
            model_name='docketentryevent',
            name='date_filed',
            field=models.DateField(blank=True, help_text='The created date of the Docket Entry according to the court timezone.', null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='docketentry',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_docketentryevent" ("date_created", "date_filed", "date_modified", "description", "docket_id", "entry_number", "id", "pacer_sequence_number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recap_sequence_number", "time_filed") VALUES (NEW."date_created", NEW."date_filed", NEW."date_modified", NEW."description", NEW."docket_id", NEW."entry_number", NEW."id", NEW."pacer_sequence_number", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."recap_sequence_number", NEW."time_filed"); RETURN NULL;', hash='5bdf83ede5ee24b635a78f3d61b8a9a37a09782d', operation='INSERT', pgid='pgtrigger_snapshot_insert_2de73', table='search_docketentry', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='docketentry',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "search_docketentryevent" ("date_created", "date_filed", "date_modified", "description", "docket_id", "entry_number", "id", "pacer_sequence_number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recap_sequence_number", "time_filed") VALUES (NEW."date_created", NEW."date_filed", NEW."date_modified", NEW."description", NEW."docket_id", NEW."entry_number", NEW."id", NEW."pacer_sequence_number", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."recap_sequence_number", NEW."time_filed"); RETURN NULL;', hash='d34e74de0dd87398f26bdb49ed27c7c60c2756de', operation='UPDATE', pgid='pgtrigger_snapshot_update_d8176', table='search_docketentry', when='AFTER')),
        ),
    ]
