# Generated by Django 3.2.18 on 2023-02-28 20:54
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("search", "0013_add_docket_entry_time_filed"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="docket",
            index=models.Index(
                fields=["court_id", "docket_number_core", "pacer_case_id"],
                name="district_court_docket_lookup_idx",
            ),
        ),
    ]
