# Generated by Django 3.2.18 on 2023-04-21 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_update_triggers'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpinionStub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('case_name', models.TextField(blank=True, help_text='The shortened name of the case')),
                ('case_name_full', models.TextField(blank=True, help_text='The full name of the case')),
                ('date_filed', models.DateField(blank=True, help_text='The date the case was filed', null=True)),
                ('date_decided', models.DateField(blank=True, help_text='The date the case was decided', null=True)),
                ('date_argued', models.DateField(blank=True, help_text='The date the case was argued', null=True)),
                ('date_revised', models.DateField(blank=True, help_text='The date the case was revised', null=True)),
                ('court_str', models.TextField(blank=True, help_text="Court represented as simple text. This field is used when we can't get a court from courts-db or we can't find it in the system. ")),
                ('docket_number', models.TextField(blank=True)),
                ('citations_str', models.TextField(blank=True, help_text='Raw value of citations from data')),
                ('citations', models.JSONField(blank=True, help_text='Extracted citations from data', null=True)),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.court')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
