# Generated by Django 4.2.4 on 2023-09-18 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0019_add_docket_source_noop"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courthouse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "court_seat",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the seat of the Court",
                        null=True,
                    ),
                ),
                (
                    "building_name",
                    models.CharField(
                        blank=True,
                        help_text="Ex. John Adams Courthouse",
                        max_length=255,
                        null=True,
                        verbose_name="Courthouse Name",
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Address Line 1",
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Address Line 2",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="The city/town where the court resides.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "county",
                    models.CharField(
                        blank=True,
                        help_text="The county, if any, where the court resides.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AL", "Alabama"),
                            ("AK", "Alaska"),
                            ("AS", "American Samoa"),
                            ("AZ", "Arizona"),
                            ("AR", "Arkansas"),
                            ("AA", "Armed Forces Americas"),
                            ("AE", "Armed Forces Europe"),
                            ("AP", "Armed Forces Pacific"),
                            ("CA", "California"),
                            ("CO", "Colorado"),
                            ("CT", "Connecticut"),
                            ("DE", "Delaware"),
                            ("DC", "District of Columbia"),
                            ("FM", "Federated States of Micronesia"),
                            ("FL", "Florida"),
                            ("GA", "Georgia"),
                            ("GU", "Guam"),
                            ("HI", "Hawaii"),
                            ("ID", "Idaho"),
                            ("IL", "Illinois"),
                            ("IN", "Indiana"),
                            ("IA", "Iowa"),
                            ("KS", "Kansas"),
                            ("KY", "Kentucky"),
                            ("LA", "Louisiana"),
                            ("ME", "Maine"),
                            ("MH", "Marshall Islands"),
                            ("MD", "Maryland"),
                            ("MA", "Massachusetts"),
                            ("MI", "Michigan"),
                            ("MN", "Minnesota"),
                            ("MS", "Mississippi"),
                            ("MO", "Missouri"),
                            ("MT", "Montana"),
                            ("NE", "Nebraska"),
                            ("NV", "Nevada"),
                            ("NH", "New Hampshire"),
                            ("NJ", "New Jersey"),
                            ("NM", "New Mexico"),
                            ("NY", "New York"),
                            ("NC", "North Carolina"),
                            ("ND", "North Dakota"),
                            ("MP", "Northern Mariana Islands"),
                            ("OH", "Ohio"),
                            ("OK", "Oklahoma"),
                            ("OR", "Oregon"),
                            ("PW", "Palau"),
                            ("PA", "Pennsylvania"),
                            ("PR", "Puerto Rico"),
                            ("RI", "Rhode Island"),
                            ("SC", "South Carolina"),
                            ("SD", "South Dakota"),
                            ("TN", "Tennessee"),
                            ("TX", "Texas"),
                            ("UT", "Utah"),
                            ("VT", "Vermont"),
                            ("VI", "Virgin Islands"),
                            ("VA", "Virginia"),
                            ("WA", "Washington"),
                            ("WV", "West Virginia"),
                            ("WI", "Wisconsin"),
                            ("WY", "Wyoming"),
                        ],
                        help_text="Enter the state abbreviation (e.g., CA for California)",
                        max_length=2,
                        null=True,
                        verbose_name="State",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="us",
                        max_length=2,
                        verbose_name="Two digit country code",
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="ZIP Code",
                    ),
                ),
                (
                    "court",
                    models.ForeignKey(
                        help_text="The court object associated with this Courthouse",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courts",
                        to="search.court",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Courthouses",
            },
        ),
    ]
