# Generated by Django 4.2.4 on 2023-09-30 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0021_add_pghistory_courthouse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courthouse",
            name="court",
            field=models.ForeignKey(
                help_text="The court object associated with this courthouse.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courthouses",
                to="search.court",
            ),
        ),
    ]
