# Generated by Django 5.0 on 2024-01-02 06:42

import django.db.models.functions.text
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        (
            "people_db",
            "0016_remove_abarating_update_or_delete_snapshot_update_and_more",
        ),
        (
            "recap",
            "0012_rename_fjcintegrateddatabase_district_docket_number_recap_fjcin_distric_731c7b_idx",
        ),
        ("search", "0024_add_cluster_sources_noop"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="docket",
            index=models.Index(
                django.db.models.functions.text.MD5("docket_number"),
                name="hash_docket_number_lookup_idx",
            ),
        ),
        migrations.RunSQL(
            sql="""CREATE UNIQUE INDEX CONCURRENTLY "unique_docket_per_court" ON "search_docket" ((MD5("docket_number")), "pacer_case_id", "court_id");""",
            reverse_sql='DROP INDEX "unique_docket_per_court";',
            state_operations=[
                migrations.AddConstraint(
                    model_name="docket",
                    constraint=models.UniqueConstraint(
                        django.db.models.functions.text.MD5("docket_number"),
                        models.F("pacer_case_id"),
                        models.F("court_id"),
                        name="unique_docket_per_court",
                    ),
                ),
            ],
        ),
    ]
