# Generated by Django 4.2.7 on 2023-12-07 22:34

import cl.lib.fields
from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0024_add_cluster_sources_noop"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="recapdocument",
            name="update_or_delete_snapshot_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="recapdocument",
            name="update_or_delete_snapshot_update",
        ),
        migrations.AddField(
            model_name="recapdocument",
            name="acms_document_guid",
            field=models.CharField(
                blank=True,
                help_text="The GUID of the document in ACMS.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="recapdocumentevent",
            name="acms_document_guid",
            field=models.CharField(
                blank=True,
                help_text="The GUID of the document in ACMS.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="claimhistory",
            name="pacer_case_id",
            field=models.CharField(
                blank=True,
                help_text="The case ID provided by PACER. Noted in this case on a per-document-level, since we've learned that some documents from other cases can appear in curious places.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="claimhistory",
            name="pacer_doc_id",
            field=models.CharField(
                blank=True,
                help_text="The ID of the document in PACER.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="claimhistoryevent",
            name="pacer_case_id",
            field=models.CharField(
                blank=True,
                help_text="The case ID provided by PACER. Noted in this case on a per-document-level, since we've learned that some documents from other cases can appear in curious places.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="claimhistoryevent",
            name="pacer_doc_id",
            field=models.CharField(
                blank=True,
                help_text="The ID of the document in PACER.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="docket",
            name="pacer_case_id",
            field=cl.lib.fields.CharNullField(
                blank=True,
                db_index=True,
                help_text="The case ID provided by PACER.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="docketevent",
            name="pacer_case_id",
            field=cl.lib.fields.CharNullField(
                blank=True,
                help_text="The case ID provided by PACER.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="recapdocument",
            name="pacer_doc_id",
            field=models.CharField(
                blank=True,
                help_text="The ID of the document in PACER.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="recapdocumentevent",
            name="pacer_doc_id",
            field=models.CharField(
                blank=True,
                help_text="The ID of the document in PACER.",
                max_length=64,
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="recapdocument",
            trigger=pgtrigger.compiler.Trigger(
                name="update_or_delete_snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."date_created" IS DISTINCT FROM (NEW."date_created") OR OLD."sha1" IS DISTINCT FROM (NEW."sha1") OR OLD."page_count" IS DISTINCT FROM (NEW."page_count") OR OLD."file_size" IS DISTINCT FROM (NEW."file_size") OR OLD."filepath_local" IS DISTINCT FROM (NEW."filepath_local") OR OLD."filepath_ia" IS DISTINCT FROM (NEW."filepath_ia") OR OLD."ia_upload_failure_count" IS DISTINCT FROM (NEW."ia_upload_failure_count") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."thumbnail_status" IS DISTINCT FROM (NEW."thumbnail_status") OR OLD."plain_text" IS DISTINCT FROM (NEW."plain_text") OR OLD."ocr_status" IS DISTINCT FROM (NEW."ocr_status") OR OLD."date_upload" IS DISTINCT FROM (NEW."date_upload") OR OLD."document_number" IS DISTINCT FROM (NEW."document_number") OR OLD."attachment_number" IS DISTINCT FROM (NEW."attachment_number") OR OLD."pacer_doc_id" IS DISTINCT FROM (NEW."pacer_doc_id") OR OLD."is_available" IS DISTINCT FROM (NEW."is_available") OR OLD."is_free_on_pacer" IS DISTINCT FROM (NEW."is_free_on_pacer") OR OLD."is_sealed" IS DISTINCT FROM (NEW."is_sealed") OR OLD."docket_entry_id" IS DISTINCT FROM (NEW."docket_entry_id") OR OLD."document_type" IS DISTINCT FROM (NEW."document_type") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."acms_document_guid" IS DISTINCT FROM (NEW."acms_document_guid"))',
                    func='INSERT INTO "search_recapdocumentevent" ("acms_document_guid", "attachment_number", "date_created", "date_modified", "date_upload", "description", "docket_entry_id", "document_number", "document_type", "file_size", "filepath_ia", "filepath_local", "ia_upload_failure_count", "id", "is_available", "is_free_on_pacer", "is_sealed", "ocr_status", "pacer_doc_id", "page_count", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plain_text", "sha1", "thumbnail", "thumbnail_status") VALUES (OLD."acms_document_guid", OLD."attachment_number", OLD."date_created", OLD."date_modified", OLD."date_upload", OLD."description", OLD."docket_entry_id", OLD."document_number", OLD."document_type", OLD."file_size", OLD."filepath_ia", OLD."filepath_local", OLD."ia_upload_failure_count", OLD."id", OLD."is_available", OLD."is_free_on_pacer", OLD."is_sealed", OLD."ocr_status", OLD."pacer_doc_id", OLD."page_count", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."plain_text", OLD."sha1", OLD."thumbnail", OLD."thumbnail_status"); RETURN NULL;',
                    hash="e304ad88bf00f8261bfef673a37c9f8320d0522d",
                    operation="UPDATE",
                    pgid="pgtrigger_update_or_delete_snapshot_update_8a108",
                    table="search_recapdocument",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="recapdocument",
            trigger=pgtrigger.compiler.Trigger(
                name="update_or_delete_snapshot_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "search_recapdocumentevent" ("acms_document_guid", "attachment_number", "date_created", "date_modified", "date_upload", "description", "docket_entry_id", "document_number", "document_type", "file_size", "filepath_ia", "filepath_local", "ia_upload_failure_count", "id", "is_available", "is_free_on_pacer", "is_sealed", "ocr_status", "pacer_doc_id", "page_count", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plain_text", "sha1", "thumbnail", "thumbnail_status") VALUES (OLD."acms_document_guid", OLD."attachment_number", OLD."date_created", OLD."date_modified", OLD."date_upload", OLD."description", OLD."docket_entry_id", OLD."document_number", OLD."document_type", OLD."file_size", OLD."filepath_ia", OLD."filepath_local", OLD."ia_upload_failure_count", OLD."id", OLD."is_available", OLD."is_free_on_pacer", OLD."is_sealed", OLD."ocr_status", OLD."pacer_doc_id", OLD."page_count", _pgh_attach_context(), NOW(), \'update_or_delete_snapshot\', OLD."id", OLD."plain_text", OLD."sha1", OLD."thumbnail", OLD."thumbnail_status"); RETURN NULL;',
                    hash="ac0997c8155ad58d6e51c20c5c1e60564a6d9aab",
                    operation="DELETE",
                    pgid="pgtrigger_update_or_delete_snapshot_delete_c80e6",
                    table="search_recapdocument",
                    when="AFTER",
                ),
            ),
        ),
    ]
