# Generated by Django 5.0.3 on 2024-04-09 16:00

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("search", "0026_drop_docket_unique_together_and_more"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="docketentry",
            index=models.Index(
                condition=models.Q(("entry_number", 1)),
                fields=["docket_id", "entry_number"],
                name="entry_number_idx",
            ),
        ),
    ]
