# Generated by Django 5.0.5 on 2024-04-25 18:13

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("search", "0029_search_models_acms_update"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="recapdocument",
            index=models.Index(
                condition=models.Q(("pacer_doc_id", ""), _negated=True),
                fields=["pacer_doc_id"],
                name="pacer_doc_id_idx",
            ),
        ),
    ]
