# Generated by Django 5.1.1 on 2024-09-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0034_add_harvard_pdf_to_opinioncluster"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True),
                ),
                ("get_params", models.CharField(max_length=255)),
                ("query_time_ms", models.IntegerField()),
                ("hit_cache", models.BooleanField()),
            ],
        ),
    ]
