# Generated by Django 5.0.8 on 2024-09-11 16:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0034_add_harvard_pdf_to_opinioncluster"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="opinion",
            options={"ordering": ["ordering_key"]},
        ),
    ]
