BEGIN;
--
-- Create model SearchQuery
--
CREATE TABLE "search_searchquery" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "get_params" text NOT NULL, "query_time_ms" integer NOT NULL, "hit_cache" boolean NOT NULL, "date_created" timestamp with time zone NOT NULL, "user_id" integer NULL);
ALTER TABLE "search_searchquery" ADD CONSTRAINT "search_searchquery_user_id_8918791c_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "search_searchquery_user_id_8918791c" ON "search_searchquery" ("user_id");
CREATE INDEX "search_sear_date_cr_c5fff9_idx" ON "search_searchquery" ("date_created");
COMMIT;
