# Generated by Django 5.1.1 on 2024-10-03 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0035_pghistory_v3_4_0_trigger_update"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "get_params",
                    models.TextField(
                        help_text="The GET parameters of the search query."
                    ),
                ),
                (
                    "query_time_ms",
                    models.IntegerField(
                        help_text="The milliseconds to execute the query, as returned in the ElasticSearch or Solr response."
                    ),
                ),
                (
                    "hit_cache",
                    models.BooleanField(
                        help_text="Whether the query hit the cache or not."
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Datetime when the record was created",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who performed this search query.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["date_created"],
                        name="search_sear_date_cr_c5fff9_idx",
                    )
                ],
            },
        ),
    ]
