# Generated by Django 5.1.2 on 2024-12-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0036_add_searchquery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citation",
            name="type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "A federal reporter citation (e.g. 5 F. 55)"),
                    (
                        2,
                        "A citation in a state-based reporter (e.g. Alabama Reports)",
                    ),
                    (
                        3,
                        "A citation in a regional reporter (e.g. Atlantic Reporter)",
                    ),
                    (
                        4,
                        "A citation in a specialty reporter (e.g. Lawyers' Edition)",
                    ),
                    (
                        5,
                        "A citation in an early SCOTUS reporter (e.g. 5 Black. 55)",
                    ),
                    (6, "A citation in the Lexis system (e.g. 5 LEXIS 55)"),
                    (7, "A citation in the WestLaw system (e.g. 5 WL 55)"),
                    (8, "A vendor neutral citation (e.g. 2013 FL 1)"),
                    (
                        9,
                        "A law journal citation within a scholarly or professional legal periodical (e.g. 95 Yale L.J. 5; 72 Soc.Sec.Rep.Serv. 318)",
                    ),
                ],
                help_text="The type of citation that this is.",
            ),
        ),
        migrations.AlterField(
            model_name="citationevent",
            name="type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "A federal reporter citation (e.g. 5 F. 55)"),
                    (
                        2,
                        "A citation in a state-based reporter (e.g. Alabama Reports)",
                    ),
                    (
                        3,
                        "A citation in a regional reporter (e.g. Atlantic Reporter)",
                    ),
                    (
                        4,
                        "A citation in a specialty reporter (e.g. Lawyers' Edition)",
                    ),
                    (
                        5,
                        "A citation in an early SCOTUS reporter (e.g. 5 Black. 55)",
                    ),
                    (6, "A citation in the Lexis system (e.g. 5 LEXIS 55)"),
                    (7, "A citation in the WestLaw system (e.g. 5 WL 55)"),
                    (8, "A vendor neutral citation (e.g. 2013 FL 1)"),
                    (
                        9,
                        "A law journal citation within a scholarly or professional legal periodical (e.g. 95 Yale L.J. 5; 72 Soc.Sec.Rep.Serv. 318)",
                    ),
                ],
                help_text="The type of citation that this is.",
            ),
        ),
    ]
