# Generated by Django 5.1.5 on 2025-03-25 15:35

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0038_untrack_opinions_field"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="opinion",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="opinion",
            name="delete_delete",
        ),
        migrations.AddField(
            model_name="opinion",
            name="main_version",
            field=models.ForeignKey(
                help_text="The id of another Opinion which is the updated or final version of this opinion",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versions",
                to="search.opinion",
            ),
        ),
        migrations.AddField(
            model_name="opinionevent",
            name="main_version",
            field=models.ForeignKey(
                db_constraint=False,
                help_text="The id of another Opinion which is the updated or final version of this opinion",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="search.opinion",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="opinion",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."author_id" IS DISTINCT FROM (NEW."author_id") OR OLD."author_str" IS DISTINCT FROM (NEW."author_str") OR OLD."cluster_id" IS DISTINCT FROM (NEW."cluster_id") OR OLD."download_url" IS DISTINCT FROM (NEW."download_url") OR OLD."extracted_by_ocr" IS DISTINCT FROM (NEW."extracted_by_ocr") OR OLD."html" IS DISTINCT FROM (NEW."html") OR OLD."html_anon_2020" IS DISTINCT FROM (NEW."html_anon_2020") OR OLD."html_columbia" IS DISTINCT FROM (NEW."html_columbia") OR OLD."html_lawbox" IS DISTINCT FROM (NEW."html_lawbox") OR OLD."html_with_citations" IS DISTINCT FROM (NEW."html_with_citations") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."joined_by_str" IS DISTINCT FROM (NEW."joined_by_str") OR OLD."local_path" IS DISTINCT FROM (NEW."local_path") OR OLD."main_version_id" IS DISTINCT FROM (NEW."main_version_id") OR OLD."ordering_key" IS DISTINCT FROM (NEW."ordering_key") OR OLD."page_count" IS DISTINCT FROM (NEW."page_count") OR OLD."per_curiam" IS DISTINCT FROM (NEW."per_curiam") OR OLD."plain_text" IS DISTINCT FROM (NEW."plain_text") OR OLD."sha1" IS DISTINCT FROM (NEW."sha1") OR OLD."type" IS DISTINCT FROM (NEW."type") OR OLD."xml_harvard" IS DISTINCT FROM (NEW."xml_harvard"))',
                    func='INSERT INTO "search_opinionevent" ("author_id", "author_str", "cluster_id", "date_created", "date_modified", "download_url", "extracted_by_ocr", "html", "html_anon_2020", "html_columbia", "html_lawbox", "html_with_citations", "id", "joined_by_str", "local_path", "main_version_id", "ordering_key", "page_count", "per_curiam", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plain_text", "sha1", "type", "xml_harvard") VALUES (OLD."author_id", OLD."author_str", OLD."cluster_id", OLD."date_created", OLD."date_modified", OLD."download_url", OLD."extracted_by_ocr", OLD."html", OLD."html_anon_2020", OLD."html_columbia", OLD."html_lawbox", OLD."html_with_citations", OLD."id", OLD."joined_by_str", OLD."local_path", OLD."main_version_id", OLD."ordering_key", OLD."page_count", OLD."per_curiam", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."plain_text", OLD."sha1", OLD."type", OLD."xml_harvard"); RETURN NULL;',
                    hash="d2f0c6af4988fde17f07a5216e06cb263e978fbc",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_24107",
                    table="search_opinion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="opinion",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "search_opinionevent" ("author_id", "author_str", "cluster_id", "date_created", "date_modified", "download_url", "extracted_by_ocr", "html", "html_anon_2020", "html_columbia", "html_lawbox", "html_with_citations", "id", "joined_by_str", "local_path", "main_version_id", "ordering_key", "page_count", "per_curiam", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plain_text", "sha1", "type", "xml_harvard") VALUES (OLD."author_id", OLD."author_str", OLD."cluster_id", OLD."date_created", OLD."date_modified", OLD."download_url", OLD."extracted_by_ocr", OLD."html", OLD."html_anon_2020", OLD."html_columbia", OLD."html_lawbox", OLD."html_with_citations", OLD."id", OLD."joined_by_str", OLD."local_path", OLD."main_version_id", OLD."ordering_key", OLD."page_count", OLD."per_curiam", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."plain_text", OLD."sha1", OLD."type", OLD."xml_harvard"); RETURN NULL;',
                    hash="d02e8558b3e9157ecaa523f89a8d794736b0c36c",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_613d8",
                    table="search_opinion",
                    when="AFTER",
                ),
            ),
        ),
    ]
