# Generated by Django 5.1.8 on 2025-07-17 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0040_add_opinion_main_version_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterRedirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_cluster_id', models.IntegerField()),
                ('reason', models.SmallIntegerField(choices=[(1, 'Opinion versions clusters were consolidated in a single one'), (2, 'Clusters were duplicated'), (3, 'Opinion types clusters were consolidated in a single one'), (4, 'Cluster was deleted due to sealing')], help_text='The reason why the old cluster was deleted')),
                ('cluster', models.ForeignKey(help_text='The existing cluster the deleted clusters now point to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='merged_clusters', to='search.opinioncluster')),
            ],
        ),
    ]
