# Generated by Django 5.1.8 on 2025-07-24 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0040_add_opinion_main_version_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterRedirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Datetime when the record was created.')),
                ('deleted_cluster_id', models.IntegerField(unique=True)),
                ('reason', models.SmallIntegerField(choices=[(1, 'Cluster replaced by a newer version of the same opinion'), (2, 'Cluster removed as a duplicate'), (3, 'Spread opinions were consolidated in a single cluster (e.g., a dissent opinion added to a cluster containing the majority opinion)'), (4, 'Cluster removed by court order')], help_text='The reason why the old cluster was deleted')),
                ('cluster', models.ForeignKey(help_text='The existing cluster the deleted clusters now point to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='merged_clusters', to='search.opinioncluster')),
            ],
        ),
    ]
