# Generated by Django 5.1.8 on 2025-10-15 21:15

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_db', '0020_alter_person_religion_alter_personevent_religion_and_more'),
        ('pghistory', '0006_delete_aggregateevent'),
        ('search', '0043_add_date_fields_citation_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('proceeding_date_time', models.DateTimeField(help_text='Date and time of the proceeding in local timezone')),
                ('memo', models.TextField(blank=True, help_text='Memo about the proceeding')),
                ('proceeding_room', models.TextField(blank=True, help_text='The court room of the proceeding')),
                ('event', models.TextField(blank=True, help_text='Event that occurred. E.g. "Jury Trial"')),
                ('court', models.ForeignKey(help_text='The court this proceeding takes place in', on_delete=django.db.models.deletion.RESTRICT, to='search.court')),
                ('docket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proceedings', to='search.docket')),
                ('judge', models.ForeignKey(blank=True, help_text='The judge presiding over this proceeding', null=True, on_delete=django.db.models.deletion.RESTRICT, to='people_db.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProceedingEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('proceeding_date_time', models.DateTimeField(help_text='Date and time of the proceeding in local timezone')),
                ('memo', models.TextField(blank=True, help_text='Memo about the proceeding')),
                ('proceeding_room', models.TextField(blank=True, help_text='The court room of the proceeding')),
                ('event', models.TextField(blank=True, help_text='Event that occurred. E.g. "Jury Trial"')),
                ('court', models.ForeignKey(db_constraint=False, help_text='The court this proceeding takes place in', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.court')),
                ('docket', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.docket')),
                ('judge', models.ForeignKey(blank=True, db_constraint=False, help_text='The judge presiding over this proceeding', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='people_db.person')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='search.proceeding')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='proceeding',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."court_id" IS DISTINCT FROM (NEW."court_id") OR OLD."docket_id" IS DISTINCT FROM (NEW."docket_id") OR OLD."event" IS DISTINCT FROM (NEW."event") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."judge_id" IS DISTINCT FROM (NEW."judge_id") OR OLD."memo" IS DISTINCT FROM (NEW."memo") OR OLD."proceeding_date_time" IS DISTINCT FROM (NEW."proceeding_date_time") OR OLD."proceeding_room" IS DISTINCT FROM (NEW."proceeding_room"))', func='INSERT INTO "search_proceedingevent" ("court_id", "date_created", "date_modified", "docket_id", "event", "id", "judge_id", "memo", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "proceeding_date_time", "proceeding_room") VALUES (OLD."court_id", OLD."date_created", OLD."date_modified", OLD."docket_id", OLD."event", OLD."id", OLD."judge_id", OLD."memo", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."proceeding_date_time", OLD."proceeding_room"); RETURN NULL;', hash='5dfadab82fd477cf1718a7d587cc785859265e67', operation='UPDATE', pgid='pgtrigger_update_update_8d977', table='search_proceeding', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='proceeding',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_proceedingevent" ("court_id", "date_created", "date_modified", "docket_id", "event", "id", "judge_id", "memo", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "proceeding_date_time", "proceeding_room") VALUES (OLD."court_id", OLD."date_created", OLD."date_modified", OLD."docket_id", OLD."event", OLD."id", OLD."judge_id", OLD."memo", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."proceeding_date_time", OLD."proceeding_room"); RETURN NULL;', hash='9dbf6a383f5ae2e8c040d059a6034bf006eed953', operation='DELETE', pgid='pgtrigger_delete_delete_bdbee', table='search_proceeding', when='AFTER')),
        ),
    ]
