# Generated by Django 5.1.8 on 2025-10-15 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_db', '0020_alter_person_religion_alter_personevent_religion_and_more'),
        ('search', '0043_add_date_fields_citation_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('proceeding_date_time', models.DateTimeField(help_text='Date and time of the proceeding in local timezone')),
                ('memo', models.TextField(blank=True, help_text='Memo about the proceeding')),
                ('proceeding_room', models.TextField(blank=True, help_text='The court room of the proceeding')),
                ('event', models.TextField(blank=True, help_text='Event that occurred. E.g. "Jury Trial"')),
                ('court', models.ForeignKey(help_text='The court this proceeding takes place in', on_delete=django.db.models.deletion.RESTRICT, to='search.court')),
                ('docket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proceedings', to='search.docket')),
                ('judge', models.ForeignKey(blank=True, help_text='The judge presiding over this proceeding', null=True, on_delete=django.db.models.deletion.RESTRICT, to='people_db.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
