# Generated by Django 5.1.8 on 2025-07-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0043_add_date_fields_citation_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='volume',
            field=models.TextField(help_text='The volume of the reporter'),
        ),
        migrations.AlterField(
            model_name='citationevent',
            name='volume',
            field=models.TextField(help_text='The volume of the reporter'),
        ),
    ]
