# Generated by Django 5.1.8 on 2025-11-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0046_recreate_citation_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='query_mode',
            field=models.SmallIntegerField(choices=[(1, 'Keyword'), (2, 'Semantic')], default=1, help_text='Whether the query used keyword or semantic search.'),
        ),
    ]
