# Generated by Django 5.1.8 on 2025-11-20 06:25

import cl.lib.model_helpers
import cl.lib.storage
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0006_delete_aggregateevent'),
        ('search', '0046_recreate_citation_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScotusDocketMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('capital_case', models.BooleanField(default=False, help_text='Whether this SCOTUS case is a capital case.')),
                ('discretionary_court_decision', models.DateField(blank=True, help_text="The date of the Court's discretionary decision.", null=True)),
                ('linked_with', models.CharField(blank=True, help_text='Field describing any other docket(s) this case is linked with, as shown on the SCOTUS docket.', max_length=1000)),
                ('questions_presented_url', models.CharField(blank=True, help_text="URL to the 'Questions Presented' page or document, if available.", max_length=1000)),
                ('questions_presented_file', models.FileField(blank=True, help_text="A local copy of the 'Questions Presented' document.The path is AWS S3 where the file is saved.", max_length=1000, storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.lib.model_helpers.make_pdf_path)),
                ('docket', models.OneToOneField(help_text='The docket this SCOTUS metadata applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='scotus_metadata', to='search.docket')),
            ],
            options={
                'verbose_name': 'SCOTUS Docket Metadata',
                'verbose_name_plural': 'SCOTUS Docket Metadata',
            },
        ),
        migrations.CreateModel(
            name='ScotusDocketMetadataEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('capital_case', models.BooleanField(default=False, help_text='Whether this SCOTUS case is a capital case.')),
                ('discretionary_court_decision', models.DateField(blank=True, help_text="The date of the Court's discretionary decision.", null=True)),
                ('linked_with', models.CharField(blank=True, help_text='Field describing any other docket(s) this case is linked with, as shown on the SCOTUS docket.', max_length=1000)),
                ('questions_presented_url', models.CharField(blank=True, help_text="URL to the 'Questions Presented' page or document, if available.", max_length=1000)),
                ('questions_presented_file', models.FileField(blank=True, help_text="A local copy of the 'Questions Presented' document.The path is AWS S3 where the file is saved.", max_length=1000, storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.lib.model_helpers.make_pdf_path)),
                ('docket', models.ForeignKey(db_constraint=False, help_text='The docket this SCOTUS metadata applies to.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.docket')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='search.scotusdocketmetadata')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='scotusdocketmetadata',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."capital_case" IS DISTINCT FROM (NEW."capital_case") OR OLD."discretionary_court_decision" IS DISTINCT FROM (NEW."discretionary_court_decision") OR OLD."docket_id" IS DISTINCT FROM (NEW."docket_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."linked_with" IS DISTINCT FROM (NEW."linked_with") OR OLD."questions_presented_file" IS DISTINCT FROM (NEW."questions_presented_file") OR OLD."questions_presented_url" IS DISTINCT FROM (NEW."questions_presented_url"))', func='INSERT INTO "search_scotusdocketmetadataevent" ("capital_case", "date_created", "date_modified", "discretionary_court_decision", "docket_id", "id", "linked_with", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "questions_presented_file", "questions_presented_url") VALUES (OLD."capital_case", OLD."date_created", OLD."date_modified", OLD."discretionary_court_decision", OLD."docket_id", OLD."id", OLD."linked_with", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."questions_presented_file", OLD."questions_presented_url"); RETURN NULL;', hash='6bdc225a053e2067484a05f057132657b4cb773a', operation='UPDATE', pgid='pgtrigger_update_update_f4303', table='search_scotusdocketmetadata', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='scotusdocketmetadata',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_scotusdocketmetadataevent" ("capital_case", "date_created", "date_modified", "discretionary_court_decision", "docket_id", "id", "linked_with", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "questions_presented_file", "questions_presented_url") VALUES (OLD."capital_case", OLD."date_created", OLD."date_modified", OLD."discretionary_court_decision", OLD."docket_id", OLD."id", OLD."linked_with", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."questions_presented_file", OLD."questions_presented_url"); RETURN NULL;', hash='c85ce289107f53a1a46e6b802c81ddb8cec43e94', operation='DELETE', pgid='pgtrigger_delete_delete_de8b7', table='search_scotusdocketmetadata', when='AFTER')),
        ),
    ]
