# Generated by Django 5.2.8 on 2025-11-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0047_add_query_mode_to_searchquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='opinions_cited',
            field=models.ManyToManyField(blank=True, help_text='Opinions cited by this opinion', related_name='opinions_citing', through='search.OpinionsCited', through_fields=('citing_opinion', 'cited_opinion'), to='search.opinion'),
        ),
    ]
