# Generated by Django 5.1.8 on 2025-12-02 20:07

import cl.lib.model_helpers
import cl.lib.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0047_add_query_mode_to_searchquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpinionContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('content', models.TextField(help_text='The extracted opinion content')),
                ('source', models.SmallIntegerField(choices=[(1, 'Got from juriscraper'), (2, 'Got from CAP'), (3, 'Got from 2020 Anon archive'), (4, 'Got from Columbia import'), (5, 'Got from Lawbox'), (6, 'Free opinions on RECAP'), (7, 'Got from scanning project')], help_text='Source of the opinions content')),
                ('extraction_type', models.SmallIntegerField(choices=[(0, 'Extracted by opening the document and getting the text'), (1, 'Extracted via OCR'), (2, 'Extracted via LLM. Depending on the extraction date, it may be a different LLM version')], help_text='Source of the opinions content')),
                ('is_main_version', models.BooleanField(help_text="True if this is the most up to date or official version of the Opinion's content")),
                ('sha1', models.CharField(blank=True, db_index=True, help_text='unique ID for the document, as generated via SHA1 of the binary file or text data', max_length=40)),
                ('page_count', models.IntegerField(blank=True, help_text='The number of pages in the document, if known', null=True)),
                ('download_url', models.URLField(blank=True, db_index=True, help_text='The URL where the item was originally scraped. Note that these URLs may often be dead due to the court or the bulk provider changing their website. We keep the original link here given that it often contains valuable metadata.', max_length=500, null=True)),
                ('local_path', models.FileField(blank=True, db_index=True, help_text='The location in AWS S3 where the original opinion file is stored. Note that the field name is historical, from before when we used S3. To find the location in S3, concatenate https://storage.courtlistener.com/ and the value of this field.', storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.lib.model_helpers.make_upload_path)),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.opinion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
