# Generated by Django 5.1.8 on 2025-11-23 00:36

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0048_create_scotus_docket_metadata'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='originatingcourtinformation',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='originatingcourtinformation',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='originatingcourtinformation',
            name='date_rehearing_denied',
            field=models.DateField(blank=True, help_text='The date the petition for rehearing was denied at the lower court.', null=True),
        ),
        migrations.AddField(
            model_name='originatingcourtinformationevent',
            name='date_rehearing_denied',
            field=models.DateField(blank=True, help_text='The date the petition for rehearing was denied at the lower court.', null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='originatingcourtinformation',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."assigned_to_id" IS DISTINCT FROM (NEW."assigned_to_id") OR OLD."assigned_to_str" IS DISTINCT FROM (NEW."assigned_to_str") OR OLD."court_reporter" IS DISTINCT FROM (NEW."court_reporter") OR OLD."date_disposed" IS DISTINCT FROM (NEW."date_disposed") OR OLD."date_filed" IS DISTINCT FROM (NEW."date_filed") OR OLD."date_filed_noa" IS DISTINCT FROM (NEW."date_filed_noa") OR OLD."date_judgment" IS DISTINCT FROM (NEW."date_judgment") OR OLD."date_judgment_eod" IS DISTINCT FROM (NEW."date_judgment_eod") OR OLD."date_received_coa" IS DISTINCT FROM (NEW."date_received_coa") OR OLD."date_rehearing_denied" IS DISTINCT FROM (NEW."date_rehearing_denied") OR OLD."docket_number" IS DISTINCT FROM (NEW."docket_number") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."ordering_judge_id" IS DISTINCT FROM (NEW."ordering_judge_id") OR OLD."ordering_judge_str" IS DISTINCT FROM (NEW."ordering_judge_str"))', func='INSERT INTO "search_originatingcourtinformationevent" ("assigned_to_id", "assigned_to_str", "court_reporter", "date_created", "date_disposed", "date_filed", "date_filed_noa", "date_judgment", "date_judgment_eod", "date_modified", "date_received_coa", "date_rehearing_denied", "docket_number", "id", "ordering_judge_id", "ordering_judge_str", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."assigned_to_id", OLD."assigned_to_str", OLD."court_reporter", OLD."date_created", OLD."date_disposed", OLD."date_filed", OLD."date_filed_noa", OLD."date_judgment", OLD."date_judgment_eod", OLD."date_modified", OLD."date_received_coa", OLD."date_rehearing_denied", OLD."docket_number", OLD."id", OLD."ordering_judge_id", OLD."ordering_judge_str", _pgh_attach_context(), NOW(), \'update\', OLD."id"); RETURN NULL;', hash='fc87ced23cd88de57c0b61ad46574114fb58a492', operation='UPDATE', pgid='pgtrigger_update_update_65b0a', table='search_originatingcourtinformation', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='originatingcourtinformation',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_originatingcourtinformationevent" ("assigned_to_id", "assigned_to_str", "court_reporter", "date_created", "date_disposed", "date_filed", "date_filed_noa", "date_judgment", "date_judgment_eod", "date_modified", "date_received_coa", "date_rehearing_denied", "docket_number", "id", "ordering_judge_id", "ordering_judge_str", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."assigned_to_id", OLD."assigned_to_str", OLD."court_reporter", OLD."date_created", OLD."date_disposed", OLD."date_filed", OLD."date_filed_noa", OLD."date_judgment", OLD."date_judgment_eod", OLD."date_modified", OLD."date_received_coa", OLD."date_rehearing_denied", OLD."docket_number", OLD."id", OLD."ordering_judge_id", OLD."ordering_judge_str", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='4c86669888a8ad517c1d5965b28fdb569531ea07', operation='DELETE', pgid='pgtrigger_delete_delete_ea96d', table='search_originatingcourtinformation', when='AFTER')),
        ),
    ]
