# Generated by Django 6.0.1 on 2026-01-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0049_add_fields_to_originating_court_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='opinions_cited',
            field=models.ManyToManyField(blank=True, help_text='Opinions cited by this opinion', related_name='opinions_citing', through='search.OpinionsCited', through_fields=('citing_opinion', 'cited_opinion'), to='search.opinion'),
        ),
    ]
