# Generated by Django 5.1.8 on 2026-01-09 20:23

import cl.lib.model_helpers
import cl.lib.storage
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('search', '0050_alter_opinion_opinions_cited'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('transfer_date', models.DateField(db_comment='The date this transfer occurred.', help_text='The date this transfer occurred.')),
                ('transfer_type', models.SmallIntegerField(choices=[(0, 'Appeal'), (1, 'Workload'), (2, 'Merge'), (3, 'Jurisdiction')], db_comment='The type of transfer (appeal, work sharing, etc.).', help_text='The type of transfer (appeal, work sharing, etc.).')),
                ('destination_court', models.ForeignKey(db_comment='The court the docket is being transferred to.', help_text='The court the docket is being transferred to.', on_delete=django.db.models.deletion.CASCADE, related_name='case_transfer_destination_court', to='search.court')),
                ('destination_docket', models.ForeignKey(db_comment='The case docket in the destination court.', help_text='The case docket in the destination court.', on_delete=django.db.models.deletion.CASCADE, related_name='case_transfer_destination_docket', to='search.docket')),
                ('origin_court', models.ForeignKey(db_comment='The court this transfer originates from.', help_text='The court this transfer originates from.', on_delete=django.db.models.deletion.CASCADE, related_name='case_transfer_origin_court', to='search.court')),
                ('origin_docket', models.ForeignKey(db_comment='The docket this transfer originates from.', help_text='The docket this transfer originates from.', on_delete=django.db.models.deletion.CASCADE, related_name='case_transfer_origin_docket', to='search.docket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseTransferEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('transfer_date', models.DateField(db_comment='The date this transfer occurred.', help_text='The date this transfer occurred.')),
                ('transfer_type', models.SmallIntegerField(choices=[(0, 'Appeal'), (1, 'Workload'), (2, 'Merge'), (3, 'Jurisdiction')], db_comment='The type of transfer (appeal, work sharing, etc.).', help_text='The type of transfer (appeal, work sharing, etc.).')),
                ('destination_court', models.ForeignKey(db_comment='The court the docket is being transferred to.', db_constraint=False, help_text='The court the docket is being transferred to.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.court')),
                ('destination_docket', models.ForeignKey(db_comment='The case docket in the destination court.', db_constraint=False, help_text='The case docket in the destination court.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.docket')),
                ('origin_court', models.ForeignKey(db_comment='The court this transfer originates from.', db_constraint=False, help_text='The court this transfer originates from.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.court')),
                ('origin_docket', models.ForeignKey(db_comment='The docket this transfer originates from.', db_constraint=False, help_text='The docket this transfer originates from.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.docket')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='search.casetransfer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TexasDocketEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('appellate_brief', models.BooleanField(db_comment='Whether this entry appears in the "Appellate Brief" table in TAMES.', default=False, help_text='Whether this entry appears in the "Appellate Brief" table in TAMES.')),
                ('description', models.TextField(blank=True, db_comment='For appellate brief events, a short description of the brief.', help_text='For appellate brief events, a short description of the brief.')),
                ('remarks', models.TextField(blank=True, db_comment='Field unique to the Texas Supreme Court allowing commentary and notes on the entry.', help_text='Field unique to the Texas Supreme Court allowing commentary and notes on the entry.')),
                ('disposition', models.TextField(blank=True, db_comment='Text indicating whether a motion was dismissed, denied, or granted.', help_text='Text indicating whether a motion was dismissed, denied, or granted.')),
                ('date_filed', models.DateField(blank=True, db_comment='The date that TAMES indicates this entry was filed.', help_text='The date that TAMES indicates this entry was filed.', null=True)),
                ('entry_type', models.TextField(db_comment='The type of entry from TAMES.', help_text='The type of entry from TAMES.')),
                ('sequence_number', models.CharField(db_comment='CL-generated field to keep entries in the same order they appear in TAMES. Concatenation of filing date (in ISO format) and the index in the TAMES table.', help_text='CL-generated field to keep entries in the same order they appear in TAMES. Concatenation of filing date (in ISO format) and the index in the TAMES table.', max_length=16)),
                ('docket', models.ForeignKey(db_comment='The Docket this entry is associated with.', help_text='The Docket this entry is associated with.', on_delete=django.db.models.deletion.CASCADE, to='search.docket')),
            ],
            options={
                'ordering': ['-sequence_number'],
            },
            bases=(models.Model, cl.lib.model_helpers.CSVExportMixin),
        ),
        migrations.CreateModel(
            name='TexasDocketEntryEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('appellate_brief', models.BooleanField(db_comment='Whether this entry appears in the "Appellate Brief" table in TAMES.', default=False, help_text='Whether this entry appears in the "Appellate Brief" table in TAMES.')),
                ('description', models.TextField(blank=True, db_comment='For appellate brief events, a short description of the brief.', help_text='For appellate brief events, a short description of the brief.')),
                ('remarks', models.TextField(blank=True, db_comment='Field unique to the Texas Supreme Court allowing commentary and notes on the entry.', help_text='Field unique to the Texas Supreme Court allowing commentary and notes on the entry.')),
                ('disposition', models.TextField(blank=True, db_comment='Text indicating whether a motion was dismissed, denied, or granted.', help_text='Text indicating whether a motion was dismissed, denied, or granted.')),
                ('date_filed', models.DateField(blank=True, db_comment='The date that TAMES indicates this entry was filed.', help_text='The date that TAMES indicates this entry was filed.', null=True)),
                ('entry_type', models.TextField(db_comment='The type of entry from TAMES.', help_text='The type of entry from TAMES.')),
                ('sequence_number', models.CharField(db_comment='CL-generated field to keep entries in the same order they appear in TAMES. Concatenation of filing date (in ISO format) and the index in the TAMES table.', help_text='CL-generated field to keep entries in the same order they appear in TAMES. Concatenation of filing date (in ISO format) and the index in the TAMES table.', max_length=16)),
                ('docket', models.ForeignKey(db_comment='The Docket this entry is associated with.', db_constraint=False, help_text='The Docket this entry is associated with.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.docket')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='search.texasdocketentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TexasDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('sha1', models.CharField(blank=True, help_text='The ID used for a document in RECAP', max_length=40)),
                ('page_count', models.IntegerField(blank=True, help_text='The number of pages in the document, if known', null=True)),
                ('file_size', models.IntegerField(blank=True, help_text='The size of the file in bytes, if known', null=True)),
                ('filepath_local', models.FileField(blank=True, help_text='The path is AWS S3 where the file is saved. Note that the field name is historical, from before when we used S3. To find the location in S3, concatenate https://storage.courtlistener.com/ and the value of this field.', max_length=1000, storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.lib.model_helpers.make_pdf_path)),
                ('filepath_ia', models.CharField(blank=True, help_text='The URL of the file in IA', max_length=1000)),
                ('ia_upload_failure_count', models.SmallIntegerField(blank=True, help_text='Number of times the upload to the Internet Archive failed.', null=True)),
                ('thumbnail', models.FileField(blank=True, help_text='The path to a thumbnail in S3 of the first page of the document.', null=True, storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.lib.model_helpers.make_pdf_thumb_path)),
                ('thumbnail_status', models.SmallIntegerField(choices=[(0, 'Thumbnail needed'), (1, 'Thumbnail completed successfully'), (2, 'Unable to generate thumbnail')], default=0, help_text='The status of the thumbnail generation')),
                ('plain_text', models.TextField(blank=True, help_text='Plain text of the document after extraction using pdftotext, wpd2txt, etc.')),
                ('ocr_status', models.SmallIntegerField(blank=True, choices=[(1, 'OCR Complete'), (2, 'OCR Not Necessary'), (3, 'OCR Failed'), (4, 'OCR Needed')], help_text='The status of OCR processing on this item.', null=True)),
                ('description', models.TextField(blank=True, db_comment='The description of this file in TAMES.', help_text='The description of this file in TAMES.')),
                ('media_id', models.UUIDField(db_comment='The MediaID parameter from the download URL that TAMES provided. Used to perform document merging.', help_text='The MediaID parameter from the download URL that TAMES provided. Used to perform document merging.')),
                ('media_version_id', models.UUIDField(db_comment='The MediaVersionID parameter from the download URL that TAMES provided. Used to perform document merging.', help_text='The MediaVersionID parameter from the download URL that TAMES provided. Used to perform document merging.')),
                ('document_url', models.URLField(db_comment='The download URL that TAMES provided for this document.', help_text='The download URL that TAMES provided for this document.')),
                ('docket_entry', models.ForeignKey(db_comment='The Docket this document is associated with.', help_text='The Docket this document is associated with.', on_delete=django.db.models.deletion.CASCADE, to='search.texasdocketentry')),
            ],
        ),
        migrations.CreateModel(
            name='TexasDocumentEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('sha1', models.CharField(blank=True, help_text='The ID used for a document in RECAP', max_length=40)),
                ('page_count', models.IntegerField(blank=True, help_text='The number of pages in the document, if known', null=True)),
                ('file_size', models.IntegerField(blank=True, help_text='The size of the file in bytes, if known', null=True)),
                ('filepath_local', models.FileField(blank=True, help_text='The path is AWS S3 where the file is saved. Note that the field name is historical, from before when we used S3. To find the location in S3, concatenate https://storage.courtlistener.com/ and the value of this field.', max_length=1000, storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.lib.model_helpers.make_pdf_path)),
                ('filepath_ia', models.CharField(blank=True, help_text='The URL of the file in IA', max_length=1000)),
                ('ia_upload_failure_count', models.SmallIntegerField(blank=True, help_text='Number of times the upload to the Internet Archive failed.', null=True)),
                ('thumbnail', models.FileField(blank=True, help_text='The path to a thumbnail in S3 of the first page of the document.', null=True, storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.lib.model_helpers.make_pdf_thumb_path)),
                ('thumbnail_status', models.SmallIntegerField(choices=[(0, 'Thumbnail needed'), (1, 'Thumbnail completed successfully'), (2, 'Unable to generate thumbnail')], default=0, help_text='The status of the thumbnail generation')),
                ('plain_text', models.TextField(blank=True, help_text='Plain text of the document after extraction using pdftotext, wpd2txt, etc.')),
                ('ocr_status', models.SmallIntegerField(blank=True, choices=[(1, 'OCR Complete'), (2, 'OCR Not Necessary'), (3, 'OCR Failed'), (4, 'OCR Needed')], help_text='The status of OCR processing on this item.', null=True)),
                ('description', models.TextField(blank=True, db_comment='The description of this file in TAMES.', help_text='The description of this file in TAMES.')),
                ('media_id', models.UUIDField(db_comment='The MediaID parameter from the download URL that TAMES provided. Used to perform document merging.', help_text='The MediaID parameter from the download URL that TAMES provided. Used to perform document merging.')),
                ('media_version_id', models.UUIDField(db_comment='The MediaVersionID parameter from the download URL that TAMES provided. Used to perform document merging.', help_text='The MediaVersionID parameter from the download URL that TAMES provided. Used to perform document merging.')),
                ('document_url', models.URLField(db_comment='The download URL that TAMES provided for this document.', help_text='The download URL that TAMES provided for this document.')),
                ('docket_entry', models.ForeignKey(db_comment='The Docket this document is associated with.', db_constraint=False, help_text='The Docket this document is associated with.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.texasdocketentry')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='search.texasdocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='casetransfer',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."destination_court_id" IS DISTINCT FROM (NEW."destination_court_id") OR OLD."destination_docket_id" IS DISTINCT FROM (NEW."destination_docket_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."origin_court_id" IS DISTINCT FROM (NEW."origin_court_id") OR OLD."origin_docket_id" IS DISTINCT FROM (NEW."origin_docket_id") OR OLD."transfer_date" IS DISTINCT FROM (NEW."transfer_date") OR OLD."transfer_type" IS DISTINCT FROM (NEW."transfer_type"))', func='INSERT INTO "search_casetransferevent" ("date_created", "date_modified", "destination_court_id", "destination_docket_id", "id", "origin_court_id", "origin_docket_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "transfer_date", "transfer_type") VALUES (OLD."date_created", OLD."date_modified", OLD."destination_court_id", OLD."destination_docket_id", OLD."id", OLD."origin_court_id", OLD."origin_docket_id", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."transfer_date", OLD."transfer_type"); RETURN NULL;', hash='ad9df14b2a99eab3a73da6aa98444b7fcadd1bb1', operation='UPDATE', pgid='pgtrigger_update_update_8e8e1', table='search_casetransfer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='casetransfer',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_casetransferevent" ("date_created", "date_modified", "destination_court_id", "destination_docket_id", "id", "origin_court_id", "origin_docket_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "transfer_date", "transfer_type") VALUES (OLD."date_created", OLD."date_modified", OLD."destination_court_id", OLD."destination_docket_id", OLD."id", OLD."origin_court_id", OLD."origin_docket_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."transfer_date", OLD."transfer_type"); RETURN NULL;', hash='c3bea65645b5b3b1917ac45ff2fe3bff6ef4a11a', operation='DELETE', pgid='pgtrigger_delete_delete_b8bc0', table='search_casetransfer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='texasdocketentry',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."appellate_brief" IS DISTINCT FROM (NEW."appellate_brief") OR OLD."date_filed" IS DISTINCT FROM (NEW."date_filed") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."disposition" IS DISTINCT FROM (NEW."disposition") OR OLD."docket_id" IS DISTINCT FROM (NEW."docket_id") OR OLD."entry_type" IS DISTINCT FROM (NEW."entry_type") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."remarks" IS DISTINCT FROM (NEW."remarks") OR OLD."sequence_number" IS DISTINCT FROM (NEW."sequence_number"))', func='INSERT INTO "search_texasdocketentryevent" ("appellate_brief", "date_created", "date_filed", "date_modified", "description", "disposition", "docket_id", "entry_type", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "remarks", "sequence_number") VALUES (OLD."appellate_brief", OLD."date_created", OLD."date_filed", OLD."date_modified", OLD."description", OLD."disposition", OLD."docket_id", OLD."entry_type", OLD."id", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."remarks", OLD."sequence_number"); RETURN NULL;', hash='05c2d7dec8376d83e76c4e90d6177aeb9a33eba2', operation='UPDATE', pgid='pgtrigger_update_update_8522e', table='search_texasdocketentry', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='texasdocketentry',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_texasdocketentryevent" ("appellate_brief", "date_created", "date_filed", "date_modified", "description", "disposition", "docket_id", "entry_type", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "remarks", "sequence_number") VALUES (OLD."appellate_brief", OLD."date_created", OLD."date_filed", OLD."date_modified", OLD."description", OLD."disposition", OLD."docket_id", OLD."entry_type", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."remarks", OLD."sequence_number"); RETURN NULL;', hash='4988c2fee6d0e328ecb39e61182b915ffcdfc867', operation='DELETE', pgid='pgtrigger_delete_delete_686c4', table='search_texasdocketentry', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='texasdocument',
            index=models.Index(fields=['media_id'], name='search_texa_media_i_b596e7_idx'),
        ),
        migrations.AddIndex(
            model_name='texasdocument',
            index=models.Index(fields=['filepath_local'], name='search_texa_filepat_0b592d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='texasdocument',
            unique_together={('docket_entry', 'media_id')},
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='texasdocument',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."docket_entry_id" IS DISTINCT FROM (NEW."docket_entry_id") OR OLD."document_url" IS DISTINCT FROM (NEW."document_url") OR OLD."file_size" IS DISTINCT FROM (NEW."file_size") OR OLD."filepath_ia" IS DISTINCT FROM (NEW."filepath_ia") OR OLD."filepath_local" IS DISTINCT FROM (NEW."filepath_local") OR OLD."ia_upload_failure_count" IS DISTINCT FROM (NEW."ia_upload_failure_count") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."media_id" IS DISTINCT FROM (NEW."media_id") OR OLD."media_version_id" IS DISTINCT FROM (NEW."media_version_id") OR OLD."ocr_status" IS DISTINCT FROM (NEW."ocr_status") OR OLD."page_count" IS DISTINCT FROM (NEW."page_count") OR OLD."plain_text" IS DISTINCT FROM (NEW."plain_text") OR OLD."sha1" IS DISTINCT FROM (NEW."sha1") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."thumbnail_status" IS DISTINCT FROM (NEW."thumbnail_status"))', func='INSERT INTO "search_texasdocumentevent" ("date_created", "date_modified", "description", "docket_entry_id", "document_url", "file_size", "filepath_ia", "filepath_local", "ia_upload_failure_count", "id", "media_id", "media_version_id", "ocr_status", "page_count", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plain_text", "sha1", "thumbnail", "thumbnail_status") VALUES (OLD."date_created", OLD."date_modified", OLD."description", OLD."docket_entry_id", OLD."document_url", OLD."file_size", OLD."filepath_ia", OLD."filepath_local", OLD."ia_upload_failure_count", OLD."id", OLD."media_id", OLD."media_version_id", OLD."ocr_status", OLD."page_count", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."plain_text", OLD."sha1", OLD."thumbnail", OLD."thumbnail_status"); RETURN NULL;', hash='fe2ed0cc06c8b474517ac24796a317ed7059a3ec', operation='UPDATE', pgid='pgtrigger_update_update_a0d98', table='search_texasdocument', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='texasdocument',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_texasdocumentevent" ("date_created", "date_modified", "description", "docket_entry_id", "document_url", "file_size", "filepath_ia", "filepath_local", "ia_upload_failure_count", "id", "media_id", "media_version_id", "ocr_status", "page_count", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plain_text", "sha1", "thumbnail", "thumbnail_status") VALUES (OLD."date_created", OLD."date_modified", OLD."description", OLD."docket_entry_id", OLD."document_url", OLD."file_size", OLD."filepath_ia", OLD."filepath_local", OLD."ia_upload_failure_count", OLD."id", OLD."media_id", OLD."media_version_id", OLD."ocr_status", OLD."page_count", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."plain_text", OLD."sha1", OLD."thumbnail", OLD."thumbnail_status"); RETURN NULL;', hash='2dfb6cb709f3bb5d951abe0bbd3d4029830af739', operation='DELETE', pgid='pgtrigger_delete_delete_8ef77', table='search_texasdocument', when='AFTER')),
        ),
    ]
