# Generated by Django 6.0.1 on 2026-02-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0051_texas_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casetransfer',
            name='destination_docket',
        ),
        migrations.RemoveField(
            model_name='casetransfer',
            name='origin_docket',
        ),
        migrations.RemoveField(
            model_name='casetransferevent',
            name='destination_docket',
        ),
        migrations.RemoveField(
            model_name='casetransferevent',
            name='origin_docket',
        ),
        migrations.AddField(
            model_name='casetransfer',
            name='destination_docket_id',
            field=models.TextField(db_comment='The ID of the case docket in the destination court.', default='', help_text='The ID of the case docket in the destination court.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casetransfer',
            name='origin_docket_id',
            field=models.TextField(db_comment='The ID of the docket this transfer originates from.', default='', help_text='The ID of the docket this transfer originates from.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casetransferevent',
            name='destination_docket_id',
            field=models.TextField(db_comment='The ID of the case docket in the destination court.', default='', help_text='The ID of the case docket in the destination court.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casetransferevent',
            name='origin_docket_id',
            field=models.TextField(db_comment='The ID of the docket this transfer originates from.', default='', help_text='The ID of the docket this transfer originates from.'),
            preserve_default=False,
        ),
    ]
