# Generated by Django 6.0.2 on 2026-02-17 23:32

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0052_add_scotus_docket_entry_and_scotus_documents'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='casetransfer',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='casetransfer',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='casetransfer',
            name='destination_docket_number',
            field=models.TextField(db_comment='The ID of the case docket in the destination court.', default='', help_text='The ID of the case docket in the destination court.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casetransfer',
            name='origin_docket_number',
            field=models.TextField(db_comment='The ID of the docket this transfer originates from.', default='', help_text='The ID of the docket this transfer originates from.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casetransferevent',
            name='destination_docket_number',
            field=models.TextField(db_comment='The ID of the case docket in the destination court.', default='', help_text='The ID of the case docket in the destination court.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casetransferevent',
            name='origin_docket_number',
            field=models.TextField(db_comment='The ID of the docket this transfer originates from.', default='', help_text='The ID of the docket this transfer originates from.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casetransfer',
            name='destination_docket',
            field=models.ForeignKey(blank=True, db_comment='The docket object in the destination court.', help_text='The docket object in the destination court.', on_delete=django.db.models.deletion.CASCADE, related_name='case_transfer_destination_docket', to='search.docket'),
        ),
        migrations.AlterField(
            model_name='casetransfer',
            name='origin_docket',
            field=models.ForeignKey(blank=True, db_comment='The docket object this transfer originates from.', help_text='The docket object this transfer originates from.', on_delete=django.db.models.deletion.CASCADE, related_name='case_transfer_origin_docket', to='search.docket'),
        ),
        migrations.AlterField(
            model_name='casetransferevent',
            name='destination_docket',
            field=models.ForeignKey(blank=True, db_comment='The docket object in the destination court.', db_constraint=False, help_text='The docket object in the destination court.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.docket'),
        ),
        migrations.AlterField(
            model_name='casetransferevent',
            name='origin_docket',
            field=models.ForeignKey(blank=True, db_comment='The docket object this transfer originates from.', db_constraint=False, help_text='The docket object this transfer originates from.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.docket'),
        ),
        migrations.AlterField(
            model_name='scotusdocument',
            name='url',
            field=models.URLField(db_comment='The download URL that SCOTUS provided for this document.', help_text='The download URL that SCOTUS provided for this document.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='scotusdocumentevent',
            name='url',
            field=models.URLField(db_comment='The download URL that SCOTUS provided for this document.', help_text='The download URL that SCOTUS provided for this document.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='texasdocument',
            name='url',
            field=models.URLField(db_comment='The download URL that TAMES provided for this document.', help_text='The download URL that TAMES provided for this document.', max_length=250),
        ),
        migrations.AlterField(
            model_name='texasdocumentevent',
            name='url',
            field=models.URLField(db_comment='The download URL that TAMES provided for this document.', help_text='The download URL that TAMES provided for this document.', max_length=250),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='casetransfer',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."destination_court_id" IS DISTINCT FROM (NEW."destination_court_id") OR OLD."destination_docket_id" IS DISTINCT FROM (NEW."destination_docket_id") OR OLD."destination_docket_number" IS DISTINCT FROM (NEW."destination_docket_number") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."origin_court_id" IS DISTINCT FROM (NEW."origin_court_id") OR OLD."origin_docket_id" IS DISTINCT FROM (NEW."origin_docket_id") OR OLD."origin_docket_number" IS DISTINCT FROM (NEW."origin_docket_number") OR OLD."transfer_date" IS DISTINCT FROM (NEW."transfer_date") OR OLD."transfer_type" IS DISTINCT FROM (NEW."transfer_type"))', func='INSERT INTO "search_casetransferevent" ("date_created", "date_modified", "destination_court_id", "destination_docket_id", "destination_docket_number", "id", "origin_court_id", "origin_docket_id", "origin_docket_number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "transfer_date", "transfer_type") VALUES (OLD."date_created", OLD."date_modified", OLD."destination_court_id", OLD."destination_docket_id", OLD."destination_docket_number", OLD."id", OLD."origin_court_id", OLD."origin_docket_id", OLD."origin_docket_number", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."transfer_date", OLD."transfer_type"); RETURN NULL;', hash='d24d15b86c8d481a93408ced6922dbd6858f8359', operation='UPDATE', pgid='pgtrigger_update_update_8e8e1', table='search_casetransfer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='casetransfer',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_casetransferevent" ("date_created", "date_modified", "destination_court_id", "destination_docket_id", "destination_docket_number", "id", "origin_court_id", "origin_docket_id", "origin_docket_number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "transfer_date", "transfer_type") VALUES (OLD."date_created", OLD."date_modified", OLD."destination_court_id", OLD."destination_docket_id", OLD."destination_docket_number", OLD."id", OLD."origin_court_id", OLD."origin_docket_id", OLD."origin_docket_number", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."transfer_date", OLD."transfer_type"); RETURN NULL;', hash='15faea81a7898d79313353d9b2d480de9bd0f8dc', operation='DELETE', pgid='pgtrigger_delete_delete_b8bc0', table='search_casetransfer', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='casetransfer',
            constraint=models.CheckConstraint(condition=models.Q(('origin_docket__isnull', False), ('destination_docket__isnull', False), _connector='OR'), name='docket_at_least_one_fk_set'),
        ),
    ]
