# Generated by Django 6.0.1 on 2026-02-10 17:22

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0052_add_scotus_docket_entry_and_scotus_documents"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="casetransfer",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="casetransfer",
            name="delete_delete",
        ),
        migrations.RemoveField(
            model_name="casetransfer",
            name="destination_docket",
        ),
        migrations.RemoveField(
            model_name="casetransfer",
            name="origin_docket",
        ),
        migrations.RemoveField(
            model_name="casetransferevent",
            name="destination_docket",
        ),
        migrations.RemoveField(
            model_name="casetransferevent",
            name="origin_docket",
        ),
        migrations.AddField(
            model_name="casetransfer",
            name="destination_docket_number",
            field=models.TextField(
                db_comment="The ID of the case docket in the destination court.",
                default="",
                help_text="The ID of the case docket in the destination court.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="casetransfer",
            name="origin_docket_number",
            field=models.TextField(
                db_comment="The ID of the docket this transfer originates from.",
                default="",
                help_text="The ID of the docket this transfer originates from.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="casetransferevent",
            name="destination_docket_number",
            field=models.TextField(
                db_comment="The ID of the case docket in the destination court.",
                default="",
                help_text="The ID of the case docket in the destination court.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="casetransferevent",
            name="origin_docket_number",
            field=models.TextField(
                db_comment="The ID of the docket this transfer originates from.",
                default="",
                help_text="The ID of the docket this transfer originates from.",
            ),
            preserve_default=False,
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="casetransfer",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."destination_court_id" IS DISTINCT FROM (NEW."destination_court_id") OR OLD."destination_docket_number" IS DISTINCT FROM (NEW."destination_docket_number") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."origin_court_id" IS DISTINCT FROM (NEW."origin_court_id") OR OLD."origin_docket_number" IS DISTINCT FROM (NEW."origin_docket_number") OR OLD."transfer_date" IS DISTINCT FROM (NEW."transfer_date") OR OLD."transfer_type" IS DISTINCT FROM (NEW."transfer_type"))',
                    func='INSERT INTO "search_casetransferevent" ("date_created", "date_modified", "destination_court_id", "destination_docket_number", "id", "origin_court_id", "origin_docket_number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "transfer_date", "transfer_type") VALUES (OLD."date_created", OLD."date_modified", OLD."destination_court_id", OLD."destination_docket_number", OLD."id", OLD."origin_court_id", OLD."origin_docket_number", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."transfer_date", OLD."transfer_type"); RETURN NULL;',
                    hash="80b917540054665b8a49836933ea803aad526606",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_8e8e1",
                    table="search_casetransfer",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="casetransfer",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "search_casetransferevent" ("date_created", "date_modified", "destination_court_id", "destination_docket_number", "id", "origin_court_id", "origin_docket_number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "transfer_date", "transfer_type") VALUES (OLD."date_created", OLD."date_modified", OLD."destination_court_id", OLD."destination_docket_number", OLD."id", OLD."origin_court_id", OLD."origin_docket_number", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."transfer_date", OLD."transfer_type"); RETURN NULL;',
                    hash="1ebca4ba9fa46ebba2ad0edfdedbc2710d4cb1b6",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_b8bc0",
                    table="search_casetransfer",
                    when="AFTER",
                ),
            ),
        ),
    ]
