# Generated by Django 6.0.2 on 2026-03-09 15:57

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('search', '0054_add_docket_number_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialCourtData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('docket_number', models.CharField(blank=True, db_comment='The docket number of the case with (potentially) some cleanup applied. May be blank if not available for a given state.', default='', help_text='The docket number of the case with (potentially) some cleanup applied. May be blank if not available for a given state.')),
                ('docket_number_raw', models.CharField(blank=True, db_comment='The raw docket number value as found on the source, with no cleaning or transformations applied. May be blank.', default='', help_text='The raw docket number value as found on the source, with no cleaning or transformations applied')),
                ('judge', models.TextField(blank=True, db_comment='The judge who presided over the case. May be blank if this information is not available.', help_text='The judge who presided over the case. May be blank if this information is not available.')),
                ('reporter', models.TextField(blank=True, db_comment='The court reporter listed for this case. May be blank if this information is not available.', help_text='The court reporter listed for this case. May be blank if this information is not available.')),
                ('date_filed', models.DateField(blank=True, db_comment='The date this case was originally filed. May be blank if this information is not available.', help_text='The date this case was originally filed. May be blank if this information is not available.', null=True)),
                ('court_name', models.TextField(blank=True, db_comment='The name of the court this case was filed in as it appears in the source. May be blank if this information is not available.', help_text='The name of the court this case was filed in as it appears in the source. May be blank if this information is not available.')),
                ('punishment', models.TextField(blank=True, db_comment='The punishment assigned in criminal cases if available.', help_text='The punishment assigned in criminal cases if available.')),
                ('county', models.TextField(blank=True, db_comment='The county the trial court is located in if available.', help_text='The county the trial court is located in if available.')),
                ('court', models.ForeignKey(blank=True, db_comment='A foreign key to the Court object corresponding to the court this case was heard in. May be blank if the court is not in the database or is unavailable in the source.', help_text='A foreign key to the Court object corresponding to the court this case was heard in. May be blank if the court is not in the database or is unavailable in the source.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.court')),
                ('docket', models.ForeignKey(blank=True, db_comment='The docket for the trial court case. Will be blank if the case does not exist in the database. Currently, this is always the case since we do not scrape any trial courts, so this field is just here for future-proofing.', help_text='The docket for the trial court case. Will be blank if the case does not exist in the database. Currently, this is always the case since we do not scrape any trial courts, so this field is just here for future-proofing.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.docket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrialCourtDataEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('docket_number', models.CharField(blank=True, db_comment='The docket number of the case with (potentially) some cleanup applied. May be blank if not available for a given state.', default='', help_text='The docket number of the case with (potentially) some cleanup applied. May be blank if not available for a given state.')),
                ('docket_number_raw', models.CharField(blank=True, db_comment='The raw docket number value as found on the source, with no cleaning or transformations applied. May be blank.', default='', help_text='The raw docket number value as found on the source, with no cleaning or transformations applied')),
                ('judge', models.TextField(blank=True, db_comment='The judge who presided over the case. May be blank if this information is not available.', help_text='The judge who presided over the case. May be blank if this information is not available.')),
                ('reporter', models.TextField(blank=True, db_comment='The court reporter listed for this case. May be blank if this information is not available.', help_text='The court reporter listed for this case. May be blank if this information is not available.')),
                ('date_filed', models.DateField(blank=True, db_comment='The date this case was originally filed. May be blank if this information is not available.', help_text='The date this case was originally filed. May be blank if this information is not available.', null=True)),
                ('court_name', models.TextField(blank=True, db_comment='The name of the court this case was filed in as it appears in the source. May be blank if this information is not available.', help_text='The name of the court this case was filed in as it appears in the source. May be blank if this information is not available.')),
                ('punishment', models.TextField(blank=True, db_comment='The punishment assigned in criminal cases if available.', help_text='The punishment assigned in criminal cases if available.')),
                ('county', models.TextField(blank=True, db_comment='The county the trial court is located in if available.', help_text='The county the trial court is located in if available.')),
                ('court', models.ForeignKey(blank=True, db_comment='A foreign key to the Court object corresponding to the court this case was heard in. May be blank if the court is not in the database or is unavailable in the source.', db_constraint=False, help_text='A foreign key to the Court object corresponding to the court this case was heard in. May be blank if the court is not in the database or is unavailable in the source.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.court')),
                ('docket', models.ForeignKey(blank=True, db_comment='The docket for the trial court case. Will be blank if the case does not exist in the database. Currently, this is always the case since we do not scrape any trial courts, so this field is just here for future-proofing.', db_constraint=False, help_text='The docket for the trial court case. Will be blank if the case does not exist in the database. Currently, this is always the case since we do not scrape any trial courts, so this field is just here for future-proofing.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.docket')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='search.trialcourtdata')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='trialcourtdata',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."county" IS DISTINCT FROM (NEW."county") OR OLD."court_id" IS DISTINCT FROM (NEW."court_id") OR OLD."court_name" IS DISTINCT FROM (NEW."court_name") OR OLD."date_filed" IS DISTINCT FROM (NEW."date_filed") OR OLD."docket_id" IS DISTINCT FROM (NEW."docket_id") OR OLD."docket_number" IS DISTINCT FROM (NEW."docket_number") OR OLD."docket_number_raw" IS DISTINCT FROM (NEW."docket_number_raw") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."judge" IS DISTINCT FROM (NEW."judge") OR OLD."punishment" IS DISTINCT FROM (NEW."punishment") OR OLD."reporter" IS DISTINCT FROM (NEW."reporter"))', func='INSERT INTO "search_trialcourtdataevent" ("county", "court_id", "court_name", "date_created", "date_filed", "date_modified", "docket_id", "docket_number", "docket_number_raw", "id", "judge", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "punishment", "reporter") VALUES (OLD."county", OLD."court_id", OLD."court_name", OLD."date_created", OLD."date_filed", OLD."date_modified", OLD."docket_id", OLD."docket_number", OLD."docket_number_raw", OLD."id", OLD."judge", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."punishment", OLD."reporter"); RETURN NULL;', hash='687c950cfeeda1e9e271c844f8250e2e06e0d966', operation='UPDATE', pgid='pgtrigger_update_update_64d8a', table='search_trialcourtdata', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='trialcourtdata',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_trialcourtdataevent" ("county", "court_id", "court_name", "date_created", "date_filed", "date_modified", "docket_id", "docket_number", "docket_number_raw", "id", "judge", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "punishment", "reporter") VALUES (OLD."county", OLD."court_id", OLD."court_name", OLD."date_created", OLD."date_filed", OLD."date_modified", OLD."docket_id", OLD."docket_number", OLD."docket_number_raw", OLD."id", OLD."judge", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."punishment", OLD."reporter"); RETURN NULL;', hash='6aa410158b6ec7213d84d0f56557266c35795bdc', operation='DELETE', pgid='pgtrigger_delete_delete_b8ae6', table='search_trialcourtdata', when='AFTER')),
        ),
    ]
