BEGIN;
--
-- Create model TrialCourtData
--
CREATE TABLE "search_trialcourtdata" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date_created" timestamp with time zone NOT NULL, "date_modified" timestamp with time zone NOT NULL, "docket_number" varchar NOT NULL, "docket_number_raw" varchar NOT NULL, "judge_str" text NOT NULL, "reporter" text NOT NULL, "date_filed" date NULL, "court_name" text NOT NULL, "punishment" text NOT NULL, "county" text NOT NULL, "court_id" varchar(15) NULL, "docket_id" integer NULL, "judge_id" integer NULL);
COMMENT ON COLUMN "search_trialcourtdata"."docket_number" IS 'The docket number of the case with (potentially) some cleanup applied. May be blank if not available for a given state.';
COMMENT ON COLUMN "search_trialcourtdata"."docket_number_raw" IS 'The raw docket number value as found on the source, with no cleaning or transformations applied. May be blank.';
COMMENT ON COLUMN "search_trialcourtdata"."judge_str" IS 'The name of the judge who presided over the case. May be blank if this information is not available.';
COMMENT ON COLUMN "search_trialcourtdata"."reporter" IS 'The court reporter listed for this case. May be blank if this information is not available.';
COMMENT ON COLUMN "search_trialcourtdata"."date_filed" IS 'The date this case was originally filed. May be blank if this information is not available.';
COMMENT ON COLUMN "search_trialcourtdata"."court_name" IS 'The name of the court this case was filed in as it appears in the source. May be blank if this information is not available.';
COMMENT ON COLUMN "search_trialcourtdata"."punishment" IS 'The punishment assigned in criminal cases if available.';
COMMENT ON COLUMN "search_trialcourtdata"."county" IS 'The county the trial court is located in if available.';
COMMENT ON COLUMN "search_trialcourtdata"."court_id" IS 'A foreign key to the Court object corresponding to the court this case was heard in. May be blank if the court is not in the database or is unavailable in the source.';
COMMENT ON COLUMN "search_trialcourtdata"."docket_id" IS 'The docket for the trial court case. Will be blank if the case does not exist in the database. Currently, this is always the case since we do not scrape any trial courts, so this field is just here for future-proofing.';
COMMENT ON COLUMN "search_trialcourtdata"."judge_id" IS 'The entry in people_db.Person for the judge who presided over this case if available.';
--
-- Create model TrialCourtDataEvent
--
CREATE TABLE "search_trialcourtdataevent" ("pgh_id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "pgh_created_at" timestamp with time zone NOT NULL, "pgh_label" text NOT NULL, "id" integer NOT NULL, "date_created" timestamp with time zone NOT NULL, "date_modified" timestamp with time zone NOT NULL, "docket_number" varchar NOT NULL, "docket_number_raw" varchar NOT NULL, "judge_str" text NOT NULL, "reporter" text NOT NULL, "date_filed" date NULL, "court_name" text NOT NULL, "punishment" text NOT NULL, "county" text NOT NULL, "court_id" varchar(15) NULL, "docket_id" integer NULL, "judge_id" integer NULL, "pgh_context_id" uuid NULL, "pgh_obj_id" integer NOT NULL);
COMMENT ON COLUMN "search_trialcourtdataevent"."docket_number" IS 'The docket number of the case with (potentially) some cleanup applied. May be blank if not available for a given state.';
COMMENT ON COLUMN "search_trialcourtdataevent"."docket_number_raw" IS 'The raw docket number value as found on the source, with no cleaning or transformations applied. May be blank.';
COMMENT ON COLUMN "search_trialcourtdataevent"."judge_str" IS 'The name of the judge who presided over the case. May be blank if this information is not available.';
COMMENT ON COLUMN "search_trialcourtdataevent"."reporter" IS 'The court reporter listed for this case. May be blank if this information is not available.';
COMMENT ON COLUMN "search_trialcourtdataevent"."date_filed" IS 'The date this case was originally filed. May be blank if this information is not available.';
COMMENT ON COLUMN "search_trialcourtdataevent"."court_name" IS 'The name of the court this case was filed in as it appears in the source. May be blank if this information is not available.';
COMMENT ON COLUMN "search_trialcourtdataevent"."punishment" IS 'The punishment assigned in criminal cases if available.';
COMMENT ON COLUMN "search_trialcourtdataevent"."county" IS 'The county the trial court is located in if available.';
COMMENT ON COLUMN "search_trialcourtdataevent"."court_id" IS 'A foreign key to the Court object corresponding to the court this case was heard in. May be blank if the court is not in the database or is unavailable in the source.';
COMMENT ON COLUMN "search_trialcourtdataevent"."docket_id" IS 'The docket for the trial court case. Will be blank if the case does not exist in the database. Currently, this is always the case since we do not scrape any trial courts, so this field is just here for future-proofing.';
COMMENT ON COLUMN "search_trialcourtdataevent"."judge_id" IS 'The entry in people_db.Person for the judge who presided over this case if available.';

ALTER TABLE "search_trialcourtdata" ADD CONSTRAINT "search_trialcourtdata_court_id_95930b69_fk_search_court_id" FOREIGN KEY ("court_id") REFERENCES "search_court" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "search_trialcourtdata" ADD CONSTRAINT "search_trialcourtdata_docket_id_708ffe2a_fk_search_docket_id" FOREIGN KEY ("docket_id") REFERENCES "search_docket" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "search_trialcourtdata" ADD CONSTRAINT "search_trialcourtdata_judge_id_eb283aba_fk_people_db_person_id" FOREIGN KEY ("judge_id") REFERENCES "people_db_person" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "search_trialcourtdata_date_created_d4f647d1" ON "search_trialcourtdata" ("date_created");
CREATE INDEX "search_trialcourtdata_date_modified_7964102f" ON "search_trialcourtdata" ("date_modified");
CREATE INDEX "search_trialcourtdata_court_id_95930b69" ON "search_trialcourtdata" ("court_id");
CREATE INDEX "search_trialcourtdata_court_id_95930b69_like" ON "search_trialcourtdata" ("court_id" varchar_pattern_ops);
CREATE INDEX "search_trialcourtdata_docket_id_708ffe2a" ON "search_trialcourtdata" ("docket_id");
CREATE INDEX "search_trialcourtdata_judge_id_eb283aba" ON "search_trialcourtdata" ("judge_id");

CREATE INDEX "search_trialcourtdataevent_court_id_2f9def01" ON "search_trialcourtdataevent" ("court_id");
CREATE INDEX "search_trialcourtdataevent_court_id_2f9def01_like" ON "search_trialcourtdataevent" ("court_id" varchar_pattern_ops);
CREATE INDEX "search_trialcourtdataevent_docket_id_5acb9c86" ON "search_trialcourtdataevent" ("docket_id");
CREATE INDEX "search_trialcourtdataevent_judge_id_275df537" ON "search_trialcourtdataevent" ("judge_id");
CREATE INDEX "search_trialcourtdataevent_pgh_context_id_2db0d7a9" ON "search_trialcourtdataevent" ("pgh_context_id");
CREATE INDEX "search_trialcourtdataevent_pgh_obj_id_12e81e2c" ON "search_trialcourtdataevent" ("pgh_obj_id");
COMMIT;
