# Generated by Django 6.0.2 on 2026-04-03 20:17

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0056_trialcourtdata'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='texasdocument',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='texasdocument',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='texasdocument',
            name='processing_error',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Bad URL'), (2, 'Extraction Failure'), (3, 'Sealed')], db_comment='The processing error for the document, if any.', help_text='The processing error for the document, if any.', null=True),
        ),
        migrations.AddField(
            model_name='texasdocumentevent',
            name='processing_error',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Bad URL'), (2, 'Extraction Failure'), (3, 'Sealed')], db_comment='The processing error for the document, if any.', help_text='The processing error for the document, if any.', null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='texasdocument',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."docket_entry_id" IS DISTINCT FROM (NEW."docket_entry_id") OR OLD."file_size" IS DISTINCT FROM (NEW."file_size") OR OLD."filepath_ia" IS DISTINCT FROM (NEW."filepath_ia") OR OLD."filepath_local" IS DISTINCT FROM (NEW."filepath_local") OR OLD."ia_upload_failure_count" IS DISTINCT FROM (NEW."ia_upload_failure_count") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."media_id" IS DISTINCT FROM (NEW."media_id") OR OLD."media_version_id" IS DISTINCT FROM (NEW."media_version_id") OR OLD."ocr_status" IS DISTINCT FROM (NEW."ocr_status") OR OLD."page_count" IS DISTINCT FROM (NEW."page_count") OR OLD."plain_text" IS DISTINCT FROM (NEW."plain_text") OR OLD."processing_error" IS DISTINCT FROM (NEW."processing_error") OR OLD."sha1" IS DISTINCT FROM (NEW."sha1") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."thumbnail_status" IS DISTINCT FROM (NEW."thumbnail_status") OR OLD."url" IS DISTINCT FROM (NEW."url"))', func='INSERT INTO "search_texasdocumentevent" ("date_created", "date_modified", "description", "docket_entry_id", "file_size", "filepath_ia", "filepath_local", "ia_upload_failure_count", "id", "media_id", "media_version_id", "ocr_status", "page_count", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plain_text", "processing_error", "sha1", "thumbnail", "thumbnail_status", "url") VALUES (OLD."date_created", OLD."date_modified", OLD."description", OLD."docket_entry_id", OLD."file_size", OLD."filepath_ia", OLD."filepath_local", OLD."ia_upload_failure_count", OLD."id", OLD."media_id", OLD."media_version_id", OLD."ocr_status", OLD."page_count", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."plain_text", OLD."processing_error", OLD."sha1", OLD."thumbnail", OLD."thumbnail_status", OLD."url"); RETURN NULL;', hash='8118f9846681e8ccc7f65494ea196ec18760c52b', operation='UPDATE', pgid='pgtrigger_update_update_a0d98', table='search_texasdocument', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='texasdocument',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_texasdocumentevent" ("date_created", "date_modified", "description", "docket_entry_id", "file_size", "filepath_ia", "filepath_local", "ia_upload_failure_count", "id", "media_id", "media_version_id", "ocr_status", "page_count", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plain_text", "processing_error", "sha1", "thumbnail", "thumbnail_status", "url") VALUES (OLD."date_created", OLD."date_modified", OLD."description", OLD."docket_entry_id", OLD."file_size", OLD."filepath_ia", OLD."filepath_local", OLD."ia_upload_failure_count", OLD."id", OLD."media_id", OLD."media_version_id", OLD."ocr_status", OLD."page_count", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."plain_text", OLD."processing_error", OLD."sha1", OLD."thumbnail", OLD."thumbnail_status", OLD."url"); RETURN NULL;', hash='b6ebcc26af4e965324693582d660cd3d15f93dd1', operation='DELETE', pgid='pgtrigger_delete_delete_8ef77', table='search_texasdocument', when='AFTER')),
        ),
    ]
