# Generated by Django 6.0.2 on 2026-04-02 21:00

import cl.search.cluster_sources
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0056_trialcourtdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinioncluster',
            name='source',
            field=models.CharField(blank=True, help_text='the source of the cluster, one of: C (court website), R (public.resource.org), CR (court website merged with resource.org), L (lawbox), LC (lawbox merged with court), LR (lawbox merged with resource.org), M (manual input), A (internet archive), Z (columbia archive), ZC (columbia merged with court), ZL (columbia merged with lawbox), ZLC (columbia merged with lawbox and court), U (Harvard, Library Innovation Lab Case Law Access Project), CU (court website merged with Harvard), D (direct court input), Q (2020 anonymous database), CRU (court website merged with public.resource.org and Harvard), LU (lawbox merged with Harvard), LCU (Lawbox merged with court website and Harvard), LRU (Lawbox merged with public.resource.org and with Harvard), LCRU (Lawbox merged with court website, public.resource.org and Harvard), MU (Manual input merged with Harvard), RU (public.resource.org merged with Harvard), ZU (columbia archive merged with Harvard), ZLU (columbia archive merged with Lawbox and Harvard), ZCU (columbia archive merged with court website and Harvard), ZLCU (columbia archive merged with lawbox, court website and Harvard), G (recap), S (scanning project)', max_length=10, validators=[cl.search.cluster_sources.ClusterSources.validate_source]),
        ),
        migrations.AlterField(
            model_name='opinionclusterevent',
            name='source',
            field=models.CharField(blank=True, help_text='the source of the cluster, one of: C (court website), R (public.resource.org), CR (court website merged with resource.org), L (lawbox), LC (lawbox merged with court), LR (lawbox merged with resource.org), M (manual input), A (internet archive), Z (columbia archive), ZC (columbia merged with court), ZL (columbia merged with lawbox), ZLC (columbia merged with lawbox and court), U (Harvard, Library Innovation Lab Case Law Access Project), CU (court website merged with Harvard), D (direct court input), Q (2020 anonymous database), CRU (court website merged with public.resource.org and Harvard), LU (lawbox merged with Harvard), LCU (Lawbox merged with court website and Harvard), LRU (Lawbox merged with public.resource.org and with Harvard), LCRU (Lawbox merged with court website, public.resource.org and Harvard), MU (Manual input merged with Harvard), RU (public.resource.org merged with Harvard), ZU (columbia archive merged with Harvard), ZLU (columbia archive merged with Lawbox and Harvard), ZCU (columbia archive merged with court website and Harvard), ZLCU (columbia archive merged with lawbox, court website and Harvard), G (recap), S (scanning project)', max_length=10, validators=[cl.search.cluster_sources.ClusterSources.validate_source]),
        ),
    ]
