# Generated by Django 6.0.2 on 2026-04-03 02:25

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0056_trialcourtdata'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='texasdocument',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='texasdocument',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='texasdocument',
            name='processing_state',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Downloaded'), (2, 'Bad URL'), (3, 'Summarized'), (4, 'Summary Failed'), (5, 'Sealed')], db_comment='The processing state of the document.', default=0, help_text='The processing state of the document.'),
        ),
        migrations.AddField(
            model_name='texasdocumentevent',
            name='processing_state',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Downloaded'), (2, 'Bad URL'), (3, 'Summarized'), (4, 'Summary Failed'), (5, 'Sealed')], db_comment='The processing state of the document.', default=0, help_text='The processing state of the document.'),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE search_texasdocument
                SET processing_state = CASE
                    WHEN plain_text != '' THEN 3
                    WHEN filepath_local != '' THEN 1
                    ELSE 0
                END
                WHERE filepath_local != '' OR plain_text != '';
            """,
            reverse_sql="""
                UPDATE search_texasdocument
                SET processing_state = 0;
            """,
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='texasdocument',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."docket_entry_id" IS DISTINCT FROM (NEW."docket_entry_id") OR OLD."file_size" IS DISTINCT FROM (NEW."file_size") OR OLD."filepath_ia" IS DISTINCT FROM (NEW."filepath_ia") OR OLD."filepath_local" IS DISTINCT FROM (NEW."filepath_local") OR OLD."ia_upload_failure_count" IS DISTINCT FROM (NEW."ia_upload_failure_count") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."media_id" IS DISTINCT FROM (NEW."media_id") OR OLD."media_version_id" IS DISTINCT FROM (NEW."media_version_id") OR OLD."ocr_status" IS DISTINCT FROM (NEW."ocr_status") OR OLD."page_count" IS DISTINCT FROM (NEW."page_count") OR OLD."plain_text" IS DISTINCT FROM (NEW."plain_text") OR OLD."processing_state" IS DISTINCT FROM (NEW."processing_state") OR OLD."sha1" IS DISTINCT FROM (NEW."sha1") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."thumbnail_status" IS DISTINCT FROM (NEW."thumbnail_status") OR OLD."url" IS DISTINCT FROM (NEW."url"))', func='INSERT INTO "search_texasdocumentevent" ("date_created", "date_modified", "description", "docket_entry_id", "file_size", "filepath_ia", "filepath_local", "ia_upload_failure_count", "id", "media_id", "media_version_id", "ocr_status", "page_count", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plain_text", "processing_state", "sha1", "thumbnail", "thumbnail_status", "url") VALUES (OLD."date_created", OLD."date_modified", OLD."description", OLD."docket_entry_id", OLD."file_size", OLD."filepath_ia", OLD."filepath_local", OLD."ia_upload_failure_count", OLD."id", OLD."media_id", OLD."media_version_id", OLD."ocr_status", OLD."page_count", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."plain_text", OLD."processing_state", OLD."sha1", OLD."thumbnail", OLD."thumbnail_status", OLD."url"); RETURN NULL;', hash='fe74683571ae9476828640d22ced8de707958152', operation='UPDATE', pgid='pgtrigger_update_update_a0d98', table='search_texasdocument', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='texasdocument',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_texasdocumentevent" ("date_created", "date_modified", "description", "docket_entry_id", "file_size", "filepath_ia", "filepath_local", "ia_upload_failure_count", "id", "media_id", "media_version_id", "ocr_status", "page_count", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plain_text", "processing_state", "sha1", "thumbnail", "thumbnail_status", "url") VALUES (OLD."date_created", OLD."date_modified", OLD."description", OLD."docket_entry_id", OLD."file_size", OLD."filepath_ia", OLD."filepath_local", OLD."ia_upload_failure_count", OLD."id", OLD."media_id", OLD."media_version_id", OLD."ocr_status", OLD."page_count", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."plain_text", OLD."processing_state", OLD."sha1", OLD."thumbnail", OLD."thumbnail_status", OLD."url"); RETURN NULL;', hash='01b8d4f57dc2931800ed1c9384d33e63f38dad18', operation='DELETE', pgid='pgtrigger_delete_delete_8ef77', table='search_texasdocument', when='AFTER')),
        ),
    ]
