# Generated by Django 6.0.5 on 2026-07-24 16:13

import cl.lib.model_helpers
import cl.lib.storage
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_db', '0021_partytype_pro_se'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('search', '0058_texasdocument_processing_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloridaDocketEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('date_filed', models.DateTimeField(blank=True, db_comment='The filing date indicated by Florida ACIS', help_text='The filing date indicated by Florida ACIS', null=True)),
                ('date_submitted', models.DateTimeField(blank=True, db_comment='Pulled directly from Florida results', help_text='Pulled directly from Florida results', null=True)),
                ('entry_type', models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Brief'), (2, 'Disposition'), (3, 'Event'), (4, 'Letter'), (5, 'Motion'), (6, 'Notice'), (7, 'Order'), (8, 'Petition'), (9, 'Unassigned')], db_comment='Mirror of Juriscraper `DocketEntryType` enum.', default=0, help_text='Mirror of Juriscraper `DocketEntryType` enum.')),
                ('entry_type_raw', models.TextField(blank=True, db_comment='Value of `entry_type_raw` in Juriscraper results. Pulled from Florida API with no modification.', help_text='Value of `entry_type_raw` in Juriscraper results. Pulled from Florida API with no modification.')),
                ('entry_name', models.TextField(blank=True, db_comment='Pulled directly from Florida results', help_text='Pulled directly from Florida results')),
                ('description', models.TextField(blank=True, db_comment='Pulled directly from Florida results', help_text='Pulled directly from Florida results')),
                ('status', models.TextField(blank=True, db_comment="Pulled directly from Florida's `entry_status` field", help_text="Pulled directly from Florida's `entry_status` field")),
                ('docket_entry_uuid', models.UUIDField(db_comment='Pulled directly from Florida results', help_text='Pulled directly from Florida results')),
                ('docket', models.ForeignKey(db_comment='The Docket this entry is associated with.', help_text='The Docket this entry is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='florida_docket_entries', to='search.docket')),
                ('submitted_by', models.ForeignKey(blank=True, db_comment='FK to the case party that submitted this document.', help_text='FK to the case party that submitted this document.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='people_db.party')),
            ],
            options={
                'verbose_name_plural': 'Florida Docket Entries',
                'ordering': ['-date_filed'],
            },
            bases=(models.Model, cl.lib.model_helpers.CSVExportMixin),
        ),
        migrations.CreateModel(
            name='FloridaDocketEntryEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('date_filed', models.DateTimeField(blank=True, db_comment='The filing date indicated by Florida ACIS', help_text='The filing date indicated by Florida ACIS', null=True)),
                ('date_submitted', models.DateTimeField(blank=True, db_comment='Pulled directly from Florida results', help_text='Pulled directly from Florida results', null=True)),
                ('entry_type', models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Brief'), (2, 'Disposition'), (3, 'Event'), (4, 'Letter'), (5, 'Motion'), (6, 'Notice'), (7, 'Order'), (8, 'Petition'), (9, 'Unassigned')], db_comment='Mirror of Juriscraper `DocketEntryType` enum.', default=0, help_text='Mirror of Juriscraper `DocketEntryType` enum.')),
                ('entry_type_raw', models.TextField(blank=True, db_comment='Value of `entry_type_raw` in Juriscraper results. Pulled from Florida API with no modification.', help_text='Value of `entry_type_raw` in Juriscraper results. Pulled from Florida API with no modification.')),
                ('entry_name', models.TextField(blank=True, db_comment='Pulled directly from Florida results', help_text='Pulled directly from Florida results')),
                ('description', models.TextField(blank=True, db_comment='Pulled directly from Florida results', help_text='Pulled directly from Florida results')),
                ('status', models.TextField(blank=True, db_comment="Pulled directly from Florida's `entry_status` field", help_text="Pulled directly from Florida's `entry_status` field")),
                ('docket_entry_uuid', models.UUIDField(db_comment='Pulled directly from Florida results', help_text='Pulled directly from Florida results')),
                ('docket', models.ForeignKey(db_comment='The Docket this entry is associated with.', db_constraint=False, help_text='The Docket this entry is associated with.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.docket')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='search.floridadocketentry')),
                ('submitted_by', models.ForeignKey(blank=True, db_comment='FK to the case party that submitted this document.', db_constraint=False, help_text='FK to the case party that submitted this document.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='people_db.party')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FloridaDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('sha1', models.CharField(blank=True, help_text='The ID used for a document in RECAP', max_length=40)),
                ('page_count', models.IntegerField(blank=True, help_text='The number of pages in the document, if known', null=True)),
                ('file_size', models.IntegerField(blank=True, help_text='The size of the file in bytes, if known', null=True)),
                ('filepath_local', models.FileField(blank=True, help_text='The path is AWS S3 where the file is saved. Note that the field name is historical, from before when we used S3. To find the location in S3, concatenate https://storage.courtlistener.com/ and the value of this field.', max_length=1000, storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.lib.model_helpers.make_pdf_path)),
                ('filepath_ia', models.CharField(blank=True, help_text='The URL of the file in IA', max_length=1000)),
                ('ia_upload_failure_count', models.SmallIntegerField(blank=True, help_text='Number of times the upload to the Internet Archive failed.', null=True)),
                ('thumbnail', models.FileField(blank=True, help_text='The path to a thumbnail in S3 of the first page of the document.', null=True, storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.lib.model_helpers.make_pdf_thumb_path)),
                ('thumbnail_status', models.SmallIntegerField(choices=[(0, 'Thumbnail needed'), (1, 'Thumbnail completed successfully'), (2, 'Unable to generate thumbnail')], default=0, help_text='The status of the thumbnail generation')),
                ('plain_text', models.TextField(blank=True, help_text='Plain text of the document after extraction using pdftotext, wpd2txt, etc.')),
                ('ocr_status', models.SmallIntegerField(blank=True, choices=[(1, 'OCR Complete'), (2, 'OCR Not Necessary'), (3, 'OCR Failed'), (4, 'OCR Needed')], help_text='The status of OCR processing on this item.', null=True)),
                ('content_type', models.CharField(blank=True, db_comment='The MIME type indicated by Florida ACIS', help_text='The MIME type indicated by Florida ACIS', max_length=63)),
                ('document_name', models.TextField(blank=True, db_comment='The name of the document in Florida ACIS', help_text='The name of the document in Florida ACIS')),
                ('document_type', models.TextField(blank=True, db_comment='The type of the document in Florida ACIS', help_text='The type of the document in Florida ACIS')),
                ('description', models.TextField(blank=True, db_comment='The description of the document in Florida ACIS', help_text='The description of the document in Florida ACIS')),
                ('link_uuid', models.UUIDField(db_comment='The attachment link UUID retrieved from Florida ACIS. Used to generate document download URL.', help_text='The attachment link UUID retrieved from Florida ACIS. Used to generate document download URL.')),
                ('url', models.URLField(db_comment='Download URL for attachment. Derived from uuid and link_uuid. Stored for safety.', help_text='Download URL for attachment. Derived from uuid and link_uuid. Stored for safety.', max_length=250)),
                ('processing_error', models.SmallIntegerField(blank=True, choices=[(1, 'Bad URL'), (2, 'Extraction Failure'), (3, 'Sealed')], db_comment='The processing error for the document, if any.', help_text='The processing error for the document, if any.', null=True)),
                ('docket_entry', models.ForeignKey(db_comment='The Docket entry this document is associated with.', help_text='The Docket entry this document is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='search.floridadocketentry')),
            ],
            options={
                'ordering': ['link_uuid'],
            },
        ),
        migrations.CreateModel(
            name='FloridaDocumentEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('sha1', models.CharField(blank=True, help_text='The ID used for a document in RECAP', max_length=40)),
                ('page_count', models.IntegerField(blank=True, help_text='The number of pages in the document, if known', null=True)),
                ('file_size', models.IntegerField(blank=True, help_text='The size of the file in bytes, if known', null=True)),
                ('filepath_local', models.FileField(blank=True, help_text='The path is AWS S3 where the file is saved. Note that the field name is historical, from before when we used S3. To find the location in S3, concatenate https://storage.courtlistener.com/ and the value of this field.', max_length=1000, storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.lib.model_helpers.make_pdf_path)),
                ('filepath_ia', models.CharField(blank=True, help_text='The URL of the file in IA', max_length=1000)),
                ('ia_upload_failure_count', models.SmallIntegerField(blank=True, help_text='Number of times the upload to the Internet Archive failed.', null=True)),
                ('thumbnail', models.FileField(blank=True, help_text='The path to a thumbnail in S3 of the first page of the document.', null=True, storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.lib.model_helpers.make_pdf_thumb_path)),
                ('thumbnail_status', models.SmallIntegerField(choices=[(0, 'Thumbnail needed'), (1, 'Thumbnail completed successfully'), (2, 'Unable to generate thumbnail')], default=0, help_text='The status of the thumbnail generation')),
                ('plain_text', models.TextField(blank=True, help_text='Plain text of the document after extraction using pdftotext, wpd2txt, etc.')),
                ('ocr_status', models.SmallIntegerField(blank=True, choices=[(1, 'OCR Complete'), (2, 'OCR Not Necessary'), (3, 'OCR Failed'), (4, 'OCR Needed')], help_text='The status of OCR processing on this item.', null=True)),
                ('content_type', models.CharField(blank=True, db_comment='The MIME type indicated by Florida ACIS', help_text='The MIME type indicated by Florida ACIS', max_length=63)),
                ('document_name', models.TextField(blank=True, db_comment='The name of the document in Florida ACIS', help_text='The name of the document in Florida ACIS')),
                ('document_type', models.TextField(blank=True, db_comment='The type of the document in Florida ACIS', help_text='The type of the document in Florida ACIS')),
                ('description', models.TextField(blank=True, db_comment='The description of the document in Florida ACIS', help_text='The description of the document in Florida ACIS')),
                ('link_uuid', models.UUIDField(db_comment='The attachment link UUID retrieved from Florida ACIS. Used to generate document download URL.', help_text='The attachment link UUID retrieved from Florida ACIS. Used to generate document download URL.')),
                ('url', models.URLField(db_comment='Download URL for attachment. Derived from uuid and link_uuid. Stored for safety.', help_text='Download URL for attachment. Derived from uuid and link_uuid. Stored for safety.', max_length=250)),
                ('processing_error', models.SmallIntegerField(blank=True, choices=[(1, 'Bad URL'), (2, 'Extraction Failure'), (3, 'Sealed')], db_comment='The processing error for the document, if any.', help_text='The processing error for the document, if any.', null=True)),
                ('docket_entry', models.ForeignKey(db_comment='The Docket entry this document is associated with.', db_constraint=False, help_text='The Docket entry this document is associated with.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.floridadocketentry')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='search.floridadocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='floridadocketentry',
            constraint=models.UniqueConstraint(fields=('docket_entry_uuid', 'docket'), name='unique_docket_entry_uuid_per_docket'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='floridadocketentry',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."date_filed" IS DISTINCT FROM (NEW."date_filed") OR OLD."date_submitted" IS DISTINCT FROM (NEW."date_submitted") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."docket_id" IS DISTINCT FROM (NEW."docket_id") OR OLD."docket_entry_uuid" IS DISTINCT FROM (NEW."docket_entry_uuid") OR OLD."entry_name" IS DISTINCT FROM (NEW."entry_name") OR OLD."entry_type" IS DISTINCT FROM (NEW."entry_type") OR OLD."entry_type_raw" IS DISTINCT FROM (NEW."entry_type_raw") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."submitted_by_id" IS DISTINCT FROM (NEW."submitted_by_id"))', func='INSERT INTO "search_floridadocketentryevent" ("date_created", "date_filed", "date_modified", "date_submitted", "description", "docket_entry_uuid", "docket_id", "entry_name", "entry_type", "entry_type_raw", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "submitted_by_id") VALUES (OLD."date_created", OLD."date_filed", OLD."date_modified", OLD."date_submitted", OLD."description", OLD."docket_entry_uuid", OLD."docket_id", OLD."entry_name", OLD."entry_type", OLD."entry_type_raw", OLD."id", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."status", OLD."submitted_by_id"); RETURN NULL;', hash='d799a497904d9469e457808dbc270b10e3806924', operation='UPDATE', pgid='pgtrigger_update_update_7a74a', table='search_floridadocketentry', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='floridadocketentry',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_floridadocketentryevent" ("date_created", "date_filed", "date_modified", "date_submitted", "description", "docket_entry_uuid", "docket_id", "entry_name", "entry_type", "entry_type_raw", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "submitted_by_id") VALUES (OLD."date_created", OLD."date_filed", OLD."date_modified", OLD."date_submitted", OLD."description", OLD."docket_entry_uuid", OLD."docket_id", OLD."entry_name", OLD."entry_type", OLD."entry_type_raw", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."status", OLD."submitted_by_id"); RETURN NULL;', hash='60f38c43278bb768fca9b9037b9a8b85932563a7', operation='DELETE', pgid='pgtrigger_delete_delete_b2235', table='search_floridadocketentry', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='floridadocument',
            index=models.Index(fields=['link_uuid'], name='search_flor_link_uu_c13b56_idx'),
        ),
        migrations.AddIndex(
            model_name='floridadocument',
            index=models.Index(fields=['filepath_local'], name='search_flor_filepat_68aedb_idx'),
        ),
        migrations.AddConstraint(
            model_name='floridadocument',
            constraint=models.UniqueConstraint(fields=('docket_entry', 'link_uuid'), name='unique_link_uuid_per_docket_entry'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='floridadocument',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."content_type" IS DISTINCT FROM (NEW."content_type") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."docket_entry_id" IS DISTINCT FROM (NEW."docket_entry_id") OR OLD."document_name" IS DISTINCT FROM (NEW."document_name") OR OLD."document_type" IS DISTINCT FROM (NEW."document_type") OR OLD."file_size" IS DISTINCT FROM (NEW."file_size") OR OLD."filepath_ia" IS DISTINCT FROM (NEW."filepath_ia") OR OLD."filepath_local" IS DISTINCT FROM (NEW."filepath_local") OR OLD."ia_upload_failure_count" IS DISTINCT FROM (NEW."ia_upload_failure_count") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."link_uuid" IS DISTINCT FROM (NEW."link_uuid") OR OLD."ocr_status" IS DISTINCT FROM (NEW."ocr_status") OR OLD."page_count" IS DISTINCT FROM (NEW."page_count") OR OLD."plain_text" IS DISTINCT FROM (NEW."plain_text") OR OLD."processing_error" IS DISTINCT FROM (NEW."processing_error") OR OLD."sha1" IS DISTINCT FROM (NEW."sha1") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."thumbnail_status" IS DISTINCT FROM (NEW."thumbnail_status") OR OLD."url" IS DISTINCT FROM (NEW."url"))', func='INSERT INTO "search_floridadocumentevent" ("content_type", "date_created", "date_modified", "description", "docket_entry_id", "document_name", "document_type", "file_size", "filepath_ia", "filepath_local", "ia_upload_failure_count", "id", "link_uuid", "ocr_status", "page_count", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plain_text", "processing_error", "sha1", "thumbnail", "thumbnail_status", "url") VALUES (OLD."content_type", OLD."date_created", OLD."date_modified", OLD."description", OLD."docket_entry_id", OLD."document_name", OLD."document_type", OLD."file_size", OLD."filepath_ia", OLD."filepath_local", OLD."ia_upload_failure_count", OLD."id", OLD."link_uuid", OLD."ocr_status", OLD."page_count", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."plain_text", OLD."processing_error", OLD."sha1", OLD."thumbnail", OLD."thumbnail_status", OLD."url"); RETURN NULL;', hash='95d098e9635844c47ef8297fdf0bf130ccd5aa52', operation='UPDATE', pgid='pgtrigger_update_update_58cce', table='search_floridadocument', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='floridadocument',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_floridadocumentevent" ("content_type", "date_created", "date_modified", "description", "docket_entry_id", "document_name", "document_type", "file_size", "filepath_ia", "filepath_local", "ia_upload_failure_count", "id", "link_uuid", "ocr_status", "page_count", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plain_text", "processing_error", "sha1", "thumbnail", "thumbnail_status", "url") VALUES (OLD."content_type", OLD."date_created", OLD."date_modified", OLD."description", OLD."docket_entry_id", OLD."document_name", OLD."document_type", OLD."file_size", OLD."filepath_ia", OLD."filepath_local", OLD."ia_upload_failure_count", OLD."id", OLD."link_uuid", OLD."ocr_status", OLD."page_count", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."plain_text", OLD."processing_error", OLD."sha1", OLD."thumbnail", OLD."thumbnail_status", OLD."url"); RETURN NULL;', hash='aeb23cffb5912c4e9941f12c772ba18b6434cfdd', operation='DELETE', pgid='pgtrigger_delete_delete_648db', table='search_floridadocument', when='AFTER')),
        ),
    ]
