# Generated by Django 6.0.4 on 2026-05-22 19:56

import cl.lib.model_helpers
import cl.lib.storage
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('search', '0058_texasdocument_processing_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='NYCoADocketEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('sequence_number', models.CharField(db_comment='Stable ordering key. For FILINGS-derived entries it is the ISO date plus a zero-padded index; for file-only entries it is the literal "file." prefix plus a zero-padded file index. Disjoint by prefix so the natural key (docket, sequence_number) never collides across origins.', help_text='Stable ordering key. For FILINGS-derived entries it is the ISO date plus a zero-padded index; for file-only entries it is the literal "file." prefix plus a zero-padded file index. Disjoint by prefix so the natural key (docket, sequence_number) never collides across origins.', max_length=32)),
                ('date_filed', models.DateField(blank=True, db_comment='Date the entry was received by the court.', help_text='Date the entry was received by the court.', null=True)),
                ('description', models.TextField(blank=True, db_comment="Free-text description. For FILINGS entries the FILINGS row's filing_type concatenated with party; for file-only entries the file's display name.", help_text="Free-text description. For FILINGS entries the FILINGS row's filing_type concatenated with party; for file-only entries the file's display name.")),
                ('filing_type', models.TextField(blank=True, db_comment='Court-PASS filing-type string when known (Appellant Brief, Respondent Brief, etc.). Empty for file-only entries.', help_text='Court-PASS filing-type string when known (Appellant Brief, Respondent Brief, etc.). Empty for file-only entries.')),
                ('party_side', models.TextField(blank=True, db_comment='Party-side label when known (Appellant, Respondent, Amicus Curiae, etc.). Empty for file-only entries.', help_text='Party-side label when known (Appellant, Respondent, Amicus Curiae, etc.). Empty for file-only entries.')),
                ('docket', models.ForeignKey(db_comment='The Docket this entry belongs to.', help_text='The Docket this entry belongs to.', on_delete=django.db.models.deletion.CASCADE, to='search.docket')),
            ],
            options={
                'ordering': ['-sequence_number'],
                'unique_together': {('docket', 'sequence_number')},
            },
            bases=(models.Model, cl.lib.model_helpers.CSVExportMixin),
        ),
        migrations.CreateModel(
            name='NYCoADocketEntryEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('sequence_number', models.CharField(db_comment='Stable ordering key. For FILINGS-derived entries it is the ISO date plus a zero-padded index; for file-only entries it is the literal "file." prefix plus a zero-padded file index. Disjoint by prefix so the natural key (docket, sequence_number) never collides across origins.', help_text='Stable ordering key. For FILINGS-derived entries it is the ISO date plus a zero-padded index; for file-only entries it is the literal "file." prefix plus a zero-padded file index. Disjoint by prefix so the natural key (docket, sequence_number) never collides across origins.', max_length=32)),
                ('date_filed', models.DateField(blank=True, db_comment='Date the entry was received by the court.', help_text='Date the entry was received by the court.', null=True)),
                ('description', models.TextField(blank=True, db_comment="Free-text description. For FILINGS entries the FILINGS row's filing_type concatenated with party; for file-only entries the file's display name.", help_text="Free-text description. For FILINGS entries the FILINGS row's filing_type concatenated with party; for file-only entries the file's display name.")),
                ('filing_type', models.TextField(blank=True, db_comment='Court-PASS filing-type string when known (Appellant Brief, Respondent Brief, etc.). Empty for file-only entries.', help_text='Court-PASS filing-type string when known (Appellant Brief, Respondent Brief, etc.). Empty for file-only entries.')),
                ('party_side', models.TextField(blank=True, db_comment='Party-side label when known (Appellant, Respondent, Amicus Curiae, etc.). Empty for file-only entries.', help_text='Party-side label when known (Appellant, Respondent, Amicus Curiae, etc.). Empty for file-only entries.')),
                ('docket', models.ForeignKey(db_comment='The Docket this entry belongs to.', db_constraint=False, help_text='The Docket this entry belongs to.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.docket')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='search.nycoadocketentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NYCoADocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('sha1', models.CharField(blank=True, help_text='The ID used for a document in RECAP', max_length=40)),
                ('page_count', models.IntegerField(blank=True, help_text='The number of pages in the document, if known', null=True)),
                ('file_size', models.IntegerField(blank=True, help_text='The size of the file in bytes, if known', null=True)),
                ('filepath_local', models.FileField(blank=True, help_text='The path is AWS S3 where the file is saved. Note that the field name is historical, from before when we used S3. To find the location in S3, concatenate https://storage.courtlistener.com/ and the value of this field.', max_length=1000, storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.lib.model_helpers.make_pdf_path)),
                ('filepath_ia', models.CharField(blank=True, help_text='The URL of the file in IA', max_length=1000)),
                ('ia_upload_failure_count', models.SmallIntegerField(blank=True, help_text='Number of times the upload to the Internet Archive failed.', null=True)),
                ('thumbnail', models.FileField(blank=True, help_text='The path to a thumbnail in S3 of the first page of the document.', null=True, storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.lib.model_helpers.make_pdf_thumb_path)),
                ('thumbnail_status', models.SmallIntegerField(choices=[(0, 'Thumbnail needed'), (1, 'Thumbnail completed successfully'), (2, 'Unable to generate thumbnail')], default=0, help_text='The status of the thumbnail generation')),
                ('plain_text', models.TextField(blank=True, help_text='Plain text of the document after extraction using pdftotext, wpd2txt, etc.')),
                ('ocr_status', models.SmallIntegerField(blank=True, choices=[(1, 'OCR Complete'), (2, 'OCR Not Necessary'), (3, 'OCR Failed'), (4, 'OCR Needed')], help_text='The status of OCR processing on this item.', null=True)),
                ('file_name', models.TextField(blank=True, db_comment="Raw filename from Court-PASS's gvFiles row.", help_text="Raw filename from Court-PASS's gvFiles row.")),
                ('file_index', models.IntegerField(blank=True, db_comment='0-based position in the files table on the filing-detail page.', help_text='0-based position in the files table on the filing-detail page.', null=True)),
                ('docket_entry', models.OneToOneField(db_comment='The entry this file is attached to.', help_text='The entry this file is attached to.', on_delete=django.db.models.deletion.CASCADE, to='search.nycoadocketentry')),
            ],
        ),
        migrations.CreateModel(
            name='NYCoADocumentEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('sha1', models.CharField(blank=True, help_text='The ID used for a document in RECAP', max_length=40)),
                ('page_count', models.IntegerField(blank=True, help_text='The number of pages in the document, if known', null=True)),
                ('file_size', models.IntegerField(blank=True, help_text='The size of the file in bytes, if known', null=True)),
                ('filepath_local', models.FileField(blank=True, help_text='The path is AWS S3 where the file is saved. Note that the field name is historical, from before when we used S3. To find the location in S3, concatenate https://storage.courtlistener.com/ and the value of this field.', max_length=1000, storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.lib.model_helpers.make_pdf_path)),
                ('filepath_ia', models.CharField(blank=True, help_text='The URL of the file in IA', max_length=1000)),
                ('ia_upload_failure_count', models.SmallIntegerField(blank=True, help_text='Number of times the upload to the Internet Archive failed.', null=True)),
                ('thumbnail', models.FileField(blank=True, help_text='The path to a thumbnail in S3 of the first page of the document.', null=True, storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.lib.model_helpers.make_pdf_thumb_path)),
                ('thumbnail_status', models.SmallIntegerField(choices=[(0, 'Thumbnail needed'), (1, 'Thumbnail completed successfully'), (2, 'Unable to generate thumbnail')], default=0, help_text='The status of the thumbnail generation')),
                ('plain_text', models.TextField(blank=True, help_text='Plain text of the document after extraction using pdftotext, wpd2txt, etc.')),
                ('ocr_status', models.SmallIntegerField(blank=True, choices=[(1, 'OCR Complete'), (2, 'OCR Not Necessary'), (3, 'OCR Failed'), (4, 'OCR Needed')], help_text='The status of OCR processing on this item.', null=True)),
                ('file_name', models.TextField(blank=True, db_comment="Raw filename from Court-PASS's gvFiles row.", help_text="Raw filename from Court-PASS's gvFiles row.")),
                ('file_index', models.IntegerField(blank=True, db_comment='0-based position in the files table on the filing-detail page.', help_text='0-based position in the files table on the filing-detail page.', null=True)),
                ('docket_entry', models.ForeignKey(db_comment='The entry this file is attached to.', db_constraint=False, help_text='The entry this file is attached to.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.nycoadocketentry')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='search.nycoadocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nycoadocketentry',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."date_filed" IS DISTINCT FROM (NEW."date_filed") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."docket_id" IS DISTINCT FROM (NEW."docket_id") OR OLD."filing_type" IS DISTINCT FROM (NEW."filing_type") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."party_side" IS DISTINCT FROM (NEW."party_side") OR OLD."sequence_number" IS DISTINCT FROM (NEW."sequence_number"))', func='INSERT INTO "search_nycoadocketentryevent" ("date_created", "date_filed", "date_modified", "description", "docket_id", "filing_type", "id", "party_side", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sequence_number") VALUES (OLD."date_created", OLD."date_filed", OLD."date_modified", OLD."description", OLD."docket_id", OLD."filing_type", OLD."id", OLD."party_side", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."sequence_number"); RETURN NULL;', hash='dcc05eb6aa0294a3e15d075c801c5ff303535d6b', operation='UPDATE', pgid='pgtrigger_update_update_5dd01', table='search_nycoadocketentry', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nycoadocketentry',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_nycoadocketentryevent" ("date_created", "date_filed", "date_modified", "description", "docket_id", "filing_type", "id", "party_side", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sequence_number") VALUES (OLD."date_created", OLD."date_filed", OLD."date_modified", OLD."description", OLD."docket_id", OLD."filing_type", OLD."id", OLD."party_side", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."sequence_number"); RETURN NULL;', hash='53d35ba3640fa14105fec177de522d1525fc3f8f', operation='DELETE', pgid='pgtrigger_delete_delete_12897', table='search_nycoadocketentry', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='nycoadocument',
            index=models.Index(fields=['filepath_local'], name='search_nyco_filepat_9734a0_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nycoadocument',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."docket_entry_id" IS DISTINCT FROM (NEW."docket_entry_id") OR OLD."file_index" IS DISTINCT FROM (NEW."file_index") OR OLD."file_name" IS DISTINCT FROM (NEW."file_name") OR OLD."file_size" IS DISTINCT FROM (NEW."file_size") OR OLD."filepath_ia" IS DISTINCT FROM (NEW."filepath_ia") OR OLD."filepath_local" IS DISTINCT FROM (NEW."filepath_local") OR OLD."ia_upload_failure_count" IS DISTINCT FROM (NEW."ia_upload_failure_count") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."ocr_status" IS DISTINCT FROM (NEW."ocr_status") OR OLD."page_count" IS DISTINCT FROM (NEW."page_count") OR OLD."plain_text" IS DISTINCT FROM (NEW."plain_text") OR OLD."sha1" IS DISTINCT FROM (NEW."sha1") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."thumbnail_status" IS DISTINCT FROM (NEW."thumbnail_status"))', func='INSERT INTO "search_nycoadocumentevent" ("date_created", "date_modified", "docket_entry_id", "file_index", "file_name", "file_size", "filepath_ia", "filepath_local", "ia_upload_failure_count", "id", "ocr_status", "page_count", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plain_text", "sha1", "thumbnail", "thumbnail_status") VALUES (OLD."date_created", OLD."date_modified", OLD."docket_entry_id", OLD."file_index", OLD."file_name", OLD."file_size", OLD."filepath_ia", OLD."filepath_local", OLD."ia_upload_failure_count", OLD."id", OLD."ocr_status", OLD."page_count", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."plain_text", OLD."sha1", OLD."thumbnail", OLD."thumbnail_status"); RETURN NULL;', hash='2f8d5194a6eb8fa079e879e453d80852ca40108c', operation='UPDATE', pgid='pgtrigger_update_update_8efbf', table='search_nycoadocument', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nycoadocument',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_nycoadocumentevent" ("date_created", "date_modified", "docket_entry_id", "file_index", "file_name", "file_size", "filepath_ia", "filepath_local", "ia_upload_failure_count", "id", "ocr_status", "page_count", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plain_text", "sha1", "thumbnail", "thumbnail_status") VALUES (OLD."date_created", OLD."date_modified", OLD."docket_entry_id", OLD."file_index", OLD."file_name", OLD."file_size", OLD."filepath_ia", OLD."filepath_local", OLD."ia_upload_failure_count", OLD."id", OLD."ocr_status", OLD."page_count", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."plain_text", OLD."sha1", OLD."thumbnail", OLD."thumbnail_status"); RETURN NULL;', hash='585d2c42813c48a88c7dc652994bfa9ff4d7f4e1', operation='DELETE', pgid='pgtrigger_delete_delete_d8581', table='search_nycoadocument', when='AFTER')),
        ),
    ]
