# Generated by Django 6.0.4 on 2026-05-25 16:13

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('search', '0059_update_source_field_noop'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocketIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('type', models.SmallIntegerField(choices=[(1, 'U.S. patent'), (2, 'U.S. patent application'), (3, 'U.S. published patent application'), (4, 'Foreign patent')], help_text='The type of identifier that this is.')),
                ('value', models.TextField(db_index=True, help_text="The identifier exactly as found in the source, e.g. a patent number like '7654321', 'RE38123', or 'D456789'.")),
                ('docket', models.ForeignKey(help_text='The docket in which this identifier is at issue.', on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='search.docket')),
            ],
            options={
                'unique_together': {('docket', 'type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='DocketIdentifierEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('type', models.SmallIntegerField(choices=[(1, 'U.S. patent'), (2, 'U.S. patent application'), (3, 'U.S. published patent application'), (4, 'Foreign patent')], help_text='The type of identifier that this is.')),
                ('value', models.TextField(help_text="The identifier exactly as found in the source, e.g. a patent number like '7654321', 'RE38123', or 'D456789'.")),
                ('docket', models.ForeignKey(db_constraint=False, help_text='The docket in which this identifier is at issue.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.docket')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='search.docketidentifier')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='docketidentifier',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."docket_id" IS DISTINCT FROM (NEW."docket_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."type" IS DISTINCT FROM (NEW."type") OR OLD."value" IS DISTINCT FROM (NEW."value"))', func='INSERT INTO "search_docketidentifierevent" ("date_created", "date_modified", "docket_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "type", "value") VALUES (OLD."date_created", OLD."date_modified", OLD."docket_id", OLD."id", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."type", OLD."value"); RETURN NULL;', hash='5274ba920baa6c9d9e766f1cc02c4dd33527e40e', operation='UPDATE', pgid='pgtrigger_update_update_24822', table='search_docketidentifier', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='docketidentifier',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_docketidentifierevent" ("date_created", "date_modified", "docket_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "type", "value") VALUES (OLD."date_created", OLD."date_modified", OLD."docket_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."type", OLD."value"); RETURN NULL;', hash='99bb7a9ce77cfe8a906e6382a5bcd0195abce64b', operation='DELETE', pgid='pgtrigger_delete_delete_985ab', table='search_docketidentifier', when='AFTER')),
        ),
    ]
