BEGIN;
--
-- Create model NYCoADocketIssue
--
CREATE TABLE "search_nycoadocketissue" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date_created" timestamp with time zone NOT NULL, "date_modified" timestamp with time zone NOT NULL, "category" smallint NOT NULL, "subcategory" smallint NOT NULL, "category_raw" text NOT NULL, "detail" text NOT NULL);
COMMENT ON COLUMN "search_nycoadocketissue"."category" IS 'The issue''s category.';
COMMENT ON COLUMN "search_nycoadocketissue"."subcategory" IS 'The issue''s subcategory. Unknown on the issues the Court states as a bare category.';
COMMENT ON COLUMN "search_nycoadocketissue"."category_raw" IS 'The issue exactly as Court-PASS stated it, category and subcategory together.';
COMMENT ON COLUMN "search_nycoadocketissue"."detail" IS 'The Court''s description of the issue. Blank when Court-PASS stated none. Deliberately outside the key, because the Court does assign a case two issues under one category pair, told apart only by this, and it also rewords a description it has already published, so which of the two a scrape is looking at is the merger''s call rather than the database''s.';
--
-- Create model NYCoADocketEntry
--
CREATE TABLE "search_nycoadocketentry" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date_created" timestamp with time zone NOT NULL, "date_modified" timestamp with time zone NOT NULL, "docket_entry_id" text NOT NULL, "entry_index" integer NULL, "filing_type" smallint NOT NULL, "filing_type_raw" text NOT NULL, "filing_role" smallint NOT NULL, "filing_doctype" smallint NOT NULL, "filing_type_recognized" boolean NOT NULL, "party_name" text NOT NULL, "date_filed" date NULL, "date_due" date NULL, "docket_id" integer NOT NULL, "party_id" integer NULL);
COMMENT ON COLUMN "search_nycoadocketentry"."docket_entry_id" IS 'The identifier for this entry, unique within the docket and stable across scrapes. Composed from the filing type and party for a FILINGS table row, and from the role, party, and document type for an entry reconstructed from a document.';
COMMENT ON COLUMN "search_nycoadocketentry"."entry_index" IS 'The position of this entry in the source listing. Reproduces the order Court-PASS displayed, but shifts between scrapes because new rows are inserted above existing ones, so it is not an identifier.';
COMMENT ON COLUMN "search_nycoadocketentry"."filing_type" IS 'The type of filing the FILINGS table listed. Unknown on a reconstructed filing, whose role and document type are still recorded.';
COMMENT ON COLUMN "search_nycoadocketentry"."filing_type_raw" IS 'The filing type exactly as the FILINGS table rendered it. Blank when no table row listed this filing.';
COMMENT ON COLUMN "search_nycoadocketentry"."filing_role" IS 'The role of the party that made this filing.';
COMMENT ON COLUMN "search_nycoadocketentry"."filing_doctype" IS 'The kind of document this filing consists of.';
COMMENT ON COLUMN "search_nycoadocketentry"."filing_type_recognized" IS 'Whether the filing type resolved to a known role and document type. False on an entry taken from the FILINGS table means Court-PASS used a filing type we do not recognize yet.';
COMMENT ON COLUMN "search_nycoadocketentry"."party_name" IS 'The party as the FILINGS table named it. Court-PASS only identifies a party''s attorneys elsewhere on the page, so `party` stays null for a party with no attorney of record; this preserves the name either way.';
COMMENT ON COLUMN "search_nycoadocketentry"."date_filed" IS 'The date Court-PASS recorded this filing as received. Null on entries reconstructed from a document, which carry no date.';
COMMENT ON COLUMN "search_nycoadocketentry"."date_due" IS 'The date Court-PASS recorded this filing as due.';
COMMENT ON COLUMN "search_nycoadocketentry"."docket_id" IS 'The Docket this entry is associated with.';
COMMENT ON COLUMN "search_nycoadocketentry"."party_id" IS 'FK to the case party associated with this filing. May be null if the party cannot be found.';
--
-- Create model NYCoADocketEntryEvent
--
CREATE TABLE "search_nycoadocketentryevent" ("pgh_id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "pgh_created_at" timestamp with time zone NOT NULL, "pgh_label" text NOT NULL, "id" integer NOT NULL, "date_created" timestamp with time zone NOT NULL, "date_modified" timestamp with time zone NOT NULL, "docket_entry_id" text NOT NULL, "entry_index" integer NULL, "filing_type" smallint NOT NULL, "filing_type_raw" text NOT NULL, "filing_role" smallint NOT NULL, "filing_doctype" smallint NOT NULL, "filing_type_recognized" boolean NOT NULL, "party_name" text NOT NULL, "date_filed" date NULL, "date_due" date NULL, "docket_id" integer NOT NULL, "party_id" integer NULL, "pgh_context_id" uuid NULL, "pgh_obj_id" integer NOT NULL);
COMMENT ON COLUMN "search_nycoadocketentryevent"."docket_entry_id" IS 'The identifier for this entry, unique within the docket and stable across scrapes. Composed from the filing type and party for a FILINGS table row, and from the role, party, and document type for an entry reconstructed from a document.';
COMMENT ON COLUMN "search_nycoadocketentryevent"."entry_index" IS 'The position of this entry in the source listing. Reproduces the order Court-PASS displayed, but shifts between scrapes because new rows are inserted above existing ones, so it is not an identifier.';
COMMENT ON COLUMN "search_nycoadocketentryevent"."filing_type" IS 'The type of filing the FILINGS table listed. Unknown on a reconstructed filing, whose role and document type are still recorded.';
COMMENT ON COLUMN "search_nycoadocketentryevent"."filing_type_raw" IS 'The filing type exactly as the FILINGS table rendered it. Blank when no table row listed this filing.';
COMMENT ON COLUMN "search_nycoadocketentryevent"."filing_role" IS 'The role of the party that made this filing.';
COMMENT ON COLUMN "search_nycoadocketentryevent"."filing_doctype" IS 'The kind of document this filing consists of.';
COMMENT ON COLUMN "search_nycoadocketentryevent"."filing_type_recognized" IS 'Whether the filing type resolved to a known role and document type. False on an entry taken from the FILINGS table means Court-PASS used a filing type we do not recognize yet.';
COMMENT ON COLUMN "search_nycoadocketentryevent"."party_name" IS 'The party as the FILINGS table named it. Court-PASS only identifies a party''s attorneys elsewhere on the page, so `party` stays null for a party with no attorney of record; this preserves the name either way.';
COMMENT ON COLUMN "search_nycoadocketentryevent"."date_filed" IS 'The date Court-PASS recorded this filing as received. Null on entries reconstructed from a document, which carry no date.';
COMMENT ON COLUMN "search_nycoadocketentryevent"."date_due" IS 'The date Court-PASS recorded this filing as due.';
COMMENT ON COLUMN "search_nycoadocketentryevent"."docket_id" IS 'The Docket this entry is associated with.';
COMMENT ON COLUMN "search_nycoadocketentryevent"."party_id" IS 'FK to the case party associated with this filing. May be null if the party cannot be found.';
--
-- Create model NYCoADocketMetadata
--
CREATE TABLE "search_nycoadocketmetadata" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date_created" timestamp with time zone NOT NULL, "date_modified" timestamp with time zone NOT NULL, "decision_date" date NULL, "official_citation" varchar(255) NOT NULL, "lower_court_citation" varchar(255) NOT NULL, "docket_id" integer NOT NULL UNIQUE);
COMMENT ON COLUMN "search_nycoadocketmetadata"."decision_date" IS 'The date this case was decided, if it has been decided.';
COMMENT ON COLUMN "search_nycoadocketmetadata"."official_citation" IS 'The official citation, for decided cases.';
COMMENT ON COLUMN "search_nycoadocketmetadata"."lower_court_citation" IS 'The "Reported Below" citation for the decision under review, when Court-PASS reports one.';
COMMENT ON COLUMN "search_nycoadocketmetadata"."docket_id" IS 'The Docket this NYCoA metadata applies to.';
--
-- Create model NYCoADocketIssueEvent
--
CREATE TABLE "search_nycoadocketissueevent" ("pgh_id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "pgh_created_at" timestamp with time zone NOT NULL, "pgh_label" text NOT NULL, "id" integer NOT NULL, "date_created" timestamp with time zone NOT NULL, "date_modified" timestamp with time zone NOT NULL, "category" smallint NOT NULL, "subcategory" smallint NOT NULL, "category_raw" text NOT NULL, "detail" text NOT NULL, "pgh_context_id" uuid NULL, "pgh_obj_id" integer NOT NULL, "metadata_id" integer NOT NULL);
COMMENT ON COLUMN "search_nycoadocketissueevent"."category" IS 'The issue''s category.';
COMMENT ON COLUMN "search_nycoadocketissueevent"."subcategory" IS 'The issue''s subcategory. Unknown on the issues the Court states as a bare category.';
COMMENT ON COLUMN "search_nycoadocketissueevent"."category_raw" IS 'The issue exactly as Court-PASS stated it, category and subcategory together.';
COMMENT ON COLUMN "search_nycoadocketissueevent"."detail" IS 'The Court''s description of the issue. Blank when Court-PASS stated none. Deliberately outside the key, because the Court does assign a case two issues under one category pair, told apart only by this, and it also rewords a description it has already published, so which of the two a scrape is looking at is the merger''s call rather than the database''s.';
COMMENT ON COLUMN "search_nycoadocketissueevent"."metadata_id" IS 'The NYCoA docket metadata this issue belongs to.';
--
-- Add field metadata to nycoadocketissue
--
ALTER TABLE "search_nycoadocketissue" ADD COLUMN "metadata_id" integer NOT NULL CONSTRAINT "search_nycoadocketis_metadata_id_f2dc59ff_fk_search_ny" REFERENCES "search_nycoadocketmetadata"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "search_nycoadocketis_metadata_id_f2dc59ff_fk_search_ny" IMMEDIATE;
COMMENT ON COLUMN "search_nycoadocketissue"."metadata_id" IS 'The NYCoA docket metadata this issue belongs to.';
--
-- Create model NYCoADocketMetadataEvent
--
CREATE TABLE "search_nycoadocketmetadataevent" ("pgh_id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "pgh_created_at" timestamp with time zone NOT NULL, "pgh_label" text NOT NULL, "id" integer NOT NULL, "date_created" timestamp with time zone NOT NULL, "date_modified" timestamp with time zone NOT NULL, "decision_date" date NULL, "official_citation" varchar(255) NOT NULL, "lower_court_citation" varchar(255) NOT NULL, "docket_id" integer NOT NULL, "pgh_context_id" uuid NULL, "pgh_obj_id" integer NOT NULL);
COMMENT ON COLUMN "search_nycoadocketmetadataevent"."decision_date" IS 'The date this case was decided, if it has been decided.';
COMMENT ON COLUMN "search_nycoadocketmetadataevent"."official_citation" IS 'The official citation, for decided cases.';
COMMENT ON COLUMN "search_nycoadocketmetadataevent"."lower_court_citation" IS 'The "Reported Below" citation for the decision under review, when Court-PASS reports one.';
COMMENT ON COLUMN "search_nycoadocketmetadataevent"."docket_id" IS 'The Docket this NYCoA metadata applies to.';
--
-- Create model NYCoADocument
--
CREATE TABLE "search_nycoadocument" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date_created" timestamp with time zone NOT NULL, "date_modified" timestamp with time zone NOT NULL, "sha1" varchar(40) NOT NULL, "page_count" integer NULL, "file_size" integer NULL, "filepath_local" varchar(1000) NOT NULL, "filepath_ia" varchar(1000) NOT NULL, "ia_upload_failure_count" smallint NULL, "thumbnail" varchar(100) NULL, "thumbnail_status" smallint NOT NULL, "plain_text" text NOT NULL, "ocr_status" smallint NULL, "url" varchar(250) NOT NULL, "processing_error" smallint NULL, "file_name" text NOT NULL, "content_type" varchar(255) NOT NULL, "available" boolean NOT NULL, "doc_role" text NOT NULL, "doc_party" text NOT NULL, "doc_type" text NOT NULL, "volume" integer NULL, "part" integer NULL, "docket_entry_id" integer NOT NULL);
COMMENT ON COLUMN "search_nycoadocument"."url" IS 'The endpoint the document is requested from. Court-PASS serves every document from one URL by POST, so unlike the other states this is the same value on every row and does not identify the document.';
COMMENT ON COLUMN "search_nycoadocument"."processing_error" IS 'The processing error for the document, if any.';
COMMENT ON COLUMN "search_nycoadocument"."file_name" IS 'The name of the file as Court-PASS published it. Filers are expected to follow the Court''s naming convention, which encodes the party role, party name, and document type.';
COMMENT ON COLUMN "search_nycoadocument"."content_type" IS 'The MIME type of the file. Court-PASS publishes PDFs along with playlist files for oral argument recordings.';
COMMENT ON COLUMN "search_nycoadocument"."available" IS 'Whether the file can be downloaded. False for sealed files and files the site lists but does not serve.';
COMMENT ON COLUMN "search_nycoadocument"."doc_role" IS 'The party role encoded in the file name, e.g. "appellant". Blank when the file name does not follow the naming convention.';
COMMENT ON COLUMN "search_nycoadocument"."doc_party" IS 'The party name encoded in the file name. Blank when the file name does not follow the naming convention.';
COMMENT ON COLUMN "search_nycoadocument"."doc_type" IS 'The document type encoded in the file name, e.g. "brf". Values beginning with an underscore are the court''s own output rather than a party filing. Blank when the file name does not follow the naming convention.';
COMMENT ON COLUMN "search_nycoadocument"."volume" IS 'The volume number, for a record or appendix published in several volumes.';
COMMENT ON COLUMN "search_nycoadocument"."part" IS 'The part number, for a volume that is itself split into parts.';
COMMENT ON COLUMN "search_nycoadocument"."docket_entry_id" IS 'The Docket entry this document is associated with.';
--
-- Create model NYCoADocumentEvent
--
CREATE TABLE "search_nycoadocumentevent" ("pgh_id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "pgh_created_at" timestamp with time zone NOT NULL, "pgh_label" text NOT NULL, "id" integer NOT NULL, "date_created" timestamp with time zone NOT NULL, "date_modified" timestamp with time zone NOT NULL, "sha1" varchar(40) NOT NULL, "page_count" integer NULL, "file_size" integer NULL, "filepath_local" varchar(1000) NOT NULL, "filepath_ia" varchar(1000) NOT NULL, "ia_upload_failure_count" smallint NULL, "thumbnail" varchar(100) NULL, "thumbnail_status" smallint NOT NULL, "plain_text" text NOT NULL, "ocr_status" smallint NULL, "url" varchar(250) NOT NULL, "processing_error" smallint NULL, "file_name" text NOT NULL, "content_type" varchar(255) NOT NULL, "available" boolean NOT NULL, "doc_role" text NOT NULL, "doc_party" text NOT NULL, "doc_type" text NOT NULL, "volume" integer NULL, "part" integer NULL, "docket_entry_id" integer NOT NULL, "pgh_context_id" uuid NULL, "pgh_obj_id" integer NOT NULL);
COMMENT ON COLUMN "search_nycoadocumentevent"."url" IS 'The endpoint the document is requested from. Court-PASS serves every document from one URL by POST, so unlike the other states this is the same value on every row and does not identify the document.';
COMMENT ON COLUMN "search_nycoadocumentevent"."processing_error" IS 'The processing error for the document, if any.';
COMMENT ON COLUMN "search_nycoadocumentevent"."file_name" IS 'The name of the file as Court-PASS published it. Filers are expected to follow the Court''s naming convention, which encodes the party role, party name, and document type.';
COMMENT ON COLUMN "search_nycoadocumentevent"."content_type" IS 'The MIME type of the file. Court-PASS publishes PDFs along with playlist files for oral argument recordings.';
COMMENT ON COLUMN "search_nycoadocumentevent"."available" IS 'Whether the file can be downloaded. False for sealed files and files the site lists but does not serve.';
COMMENT ON COLUMN "search_nycoadocumentevent"."doc_role" IS 'The party role encoded in the file name, e.g. "appellant". Blank when the file name does not follow the naming convention.';
COMMENT ON COLUMN "search_nycoadocumentevent"."doc_party" IS 'The party name encoded in the file name. Blank when the file name does not follow the naming convention.';
COMMENT ON COLUMN "search_nycoadocumentevent"."doc_type" IS 'The document type encoded in the file name, e.g. "brf". Values beginning with an underscore are the court''s own output rather than a party filing. Blank when the file name does not follow the naming convention.';
COMMENT ON COLUMN "search_nycoadocumentevent"."volume" IS 'The volume number, for a record or appendix published in several volumes.';
COMMENT ON COLUMN "search_nycoadocumentevent"."part" IS 'The part number, for a volume that is itself split into parts.';
COMMENT ON COLUMN "search_nycoadocumentevent"."docket_entry_id" IS 'The Docket entry this document is associated with.';
--
-- Create index nycoa_entry_docket_order_idx on field(s) docket, date_filed, entry_index of model nycoadocketentry
--
CREATE INDEX "nycoa_entry_docket_order_idx" ON "search_nycoadocketentry" ("docket_id", "date_filed", "entry_index");
--
-- Create constraint unique_nycoa_entry_id_per_docket on model nycoadocketentry
--
ALTER TABLE "search_nycoadocketentry" ADD CONSTRAINT "unique_nycoa_entry_id_per_docket" UNIQUE ("docket_id", "docket_entry_id");
--
-- Create index nycoa_issue_category_idx on field(s) metadata, category, subcategory of model nycoadocketissue
--
CREATE INDEX "nycoa_issue_category_idx" ON "search_nycoadocketissue" ("metadata_id", "category", "subcategory");
--
-- Create index search_nyco_filepat_9734a0_idx on field(s) filepath_local of model nycoadocument
--
CREATE INDEX "search_nyco_filepat_9734a0_idx" ON "search_nycoadocument" ("filepath_local");
--
-- Create constraint unique_nycoa_file_name_per_docket_entry on model nycoadocument
--
ALTER TABLE "search_nycoadocument" ADD CONSTRAINT "unique_nycoa_file_name_per_docket_entry" UNIQUE ("docket_entry_id", "file_name");
CREATE INDEX "search_nycoadocketissue_date_created_77c58167" ON "search_nycoadocketissue" ("date_created");
CREATE INDEX "search_nycoadocketissue_date_modified_7fc19e9f" ON "search_nycoadocketissue" ("date_modified");
ALTER TABLE "search_nycoadocketentry" ADD CONSTRAINT "search_nycoadocketentry_docket_id_791230fc_fk_search_docket_id" FOREIGN KEY ("docket_id") REFERENCES "search_docket" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "search_nycoadocketentry" ADD CONSTRAINT "search_nycoadocketentry_party_id_752424ab_fk_people_db_party_id" FOREIGN KEY ("party_id") REFERENCES "people_db_party" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "search_nycoadocketentry_date_created_34399128" ON "search_nycoadocketentry" ("date_created");
CREATE INDEX "search_nycoadocketentry_date_modified_ade544eb" ON "search_nycoadocketentry" ("date_modified");
CREATE INDEX "search_nycoadocketentry_docket_id_791230fc" ON "search_nycoadocketentry" ("docket_id");
CREATE INDEX "search_nycoadocketentry_party_id_752424ab" ON "search_nycoadocketentry" ("party_id");
CREATE INDEX "search_nycoadocketentryevent_docket_id_7c8747ae" ON "search_nycoadocketentryevent" ("docket_id");
CREATE INDEX "search_nycoadocketentryevent_party_id_308a3053" ON "search_nycoadocketentryevent" ("party_id");
CREATE INDEX "search_nycoadocketentryevent_pgh_context_id_e5490265" ON "search_nycoadocketentryevent" ("pgh_context_id");
CREATE INDEX "search_nycoadocketentryevent_pgh_obj_id_09f6c0f4" ON "search_nycoadocketentryevent" ("pgh_obj_id");
ALTER TABLE "search_nycoadocketmetadata" ADD CONSTRAINT "search_nycoadocketme_docket_id_1b0da300_fk_search_do" FOREIGN KEY ("docket_id") REFERENCES "search_docket" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "search_nycoadocketmetadata_date_created_60250ddd" ON "search_nycoadocketmetadata" ("date_created");
CREATE INDEX "search_nycoadocketmetadata_date_modified_a53a5608" ON "search_nycoadocketmetadata" ("date_modified");
CREATE INDEX "search_nycoadocketissueevent_pgh_context_id_d54dff0e" ON "search_nycoadocketissueevent" ("pgh_context_id");
CREATE INDEX "search_nycoadocketissueevent_pgh_obj_id_5623e332" ON "search_nycoadocketissueevent" ("pgh_obj_id");
CREATE INDEX "search_nycoadocketissueevent_metadata_id_302925c2" ON "search_nycoadocketissueevent" ("metadata_id");
CREATE INDEX "search_nycoadocketissue_metadata_id_f2dc59ff" ON "search_nycoadocketissue" ("metadata_id");
CREATE INDEX "search_nycoadocketmetadataevent_docket_id_f3b3baae" ON "search_nycoadocketmetadataevent" ("docket_id");
CREATE INDEX "search_nycoadocketmetadataevent_pgh_context_id_547e5d8d" ON "search_nycoadocketmetadataevent" ("pgh_context_id");
CREATE INDEX "search_nycoadocketmetadataevent_pgh_obj_id_c3c1dbe4" ON "search_nycoadocketmetadataevent" ("pgh_obj_id");
ALTER TABLE "search_nycoadocument" ADD CONSTRAINT "search_nycoadocument_docket_entry_id_99e20288_fk_search_ny" FOREIGN KEY ("docket_entry_id") REFERENCES "search_nycoadocketentry" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "search_nycoadocument_date_created_304b40c2" ON "search_nycoadocument" ("date_created");
CREATE INDEX "search_nycoadocument_date_modified_ef70b44c" ON "search_nycoadocument" ("date_modified");
CREATE INDEX "search_nycoadocument_docket_entry_id_99e20288" ON "search_nycoadocument" ("docket_entry_id");
CREATE INDEX "search_nycoadocumentevent_docket_entry_id_6052bea4" ON "search_nycoadocumentevent" ("docket_entry_id");
CREATE INDEX "search_nycoadocumentevent_pgh_context_id_f496cd82" ON "search_nycoadocumentevent" ("pgh_context_id");
CREATE INDEX "search_nycoadocumentevent_pgh_obj_id_b0f2ed59" ON "search_nycoadocumentevent" ("pgh_obj_id");
COMMIT;
