BEGIN;
--
-- Create model DocketIdentifier
--
CREATE TABLE "search_docketidentifier" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date_created" timestamp with time zone NOT NULL, "date_modified" timestamp with time zone NOT NULL, "type" smallint NOT NULL, "value" text NOT NULL, "docket_id" integer NOT NULL);
ALTER TABLE "search_docketidentifier" ADD CONSTRAINT "search_docketidentifier_docket_id_type_value_1a7d522b_uniq" UNIQUE ("docket_id", "type", "value");
ALTER TABLE "search_docketidentifier" ADD CONSTRAINT "search_docketidentifier_docket_id_d5d4092b_fk_search_docket_id" FOREIGN KEY ("docket_id") REFERENCES "search_docket" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "search_docketidentifier_date_created_62090ebb" ON "search_docketidentifier" ("date_created");
CREATE INDEX "search_docketidentifier_date_modified_5bbe0d05" ON "search_docketidentifier" ("date_modified");
CREATE INDEX "search_docketidentifier_value_ddaa5ef6" ON "search_docketidentifier" ("value");
CREATE INDEX "search_docketidentifier_value_ddaa5ef6_like" ON "search_docketidentifier" ("value" text_pattern_ops);
CREATE INDEX "search_docketidentifier_docket_id_d5d4092b" ON "search_docketidentifier" ("docket_id");
COMMIT;
