# Generated by Django 6.0.5 on 2026-07-23 19:03

import cl.lib.model_helpers
import cl.lib.storage
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('search', '0059_florida_docket_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='NYCoADocketEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('page', models.IntegerField(choices=[(1, 'Documents page'), (2, 'Filings page')], db_comment='The Court-PASS page this entry was scraped from. Entries are numbered independently per page, so two entries from different pages can share a ``sequence_number``; ``page`` is therefore part of the natural key.', help_text='The Court-PASS page this entry was scraped from. Entries are numbered independently per page, so this is part of the natural key.')),
                ('filing_type', models.TextField(blank=True, db_comment='The filing type from the Court-PASS FILINGS table (e.g. "Appellant Brief"). Blank for entries that only carry a document.', help_text='The filing type from the Court-PASS FILINGS table (e.g. "Appellant Brief"). Blank for entries that only carry a document.')),
                ('party', models.TextField(blank=True, db_comment='The party associated with the filing, if any.', help_text='The party associated with the filing, if any.')),
                ('date_received', models.DateField(blank=True, db_comment='The date Court-PASS recorded the filing as received.', help_text='The date Court-PASS recorded the filing as received.', null=True)),
                ('sequence_number', models.CharField(db_comment="CL-generated field to keep entries in a stable order. Concatenation of a filing date (in ISO format) and the entry's per-page index, mirroring the convention used for Texas dockets.", help_text="CL-generated field to keep entries in a stable order. Concatenation of a filing date (in ISO format) and the entry's per-page index, mirroring the convention used for Texas dockets.", max_length=16)),
                ('docket', models.ForeignKey(db_comment='The Docket this entry is associated with.', help_text='The Docket this entry is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='nycoa_docket_entries', to='search.docket')),
            ],
            options={
                'verbose_name_plural': 'NYCoA Docket Entries',
                'ordering': ['page', 'sequence_number'],
                'unique_together': {('docket', 'page', 'sequence_number')},
            },
            bases=(models.Model, cl.lib.model_helpers.CSVExportMixin),
        ),
        migrations.CreateModel(
            name='NYCoADocketEntryEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('page', models.IntegerField(choices=[(1, 'Documents page'), (2, 'Filings page')], db_comment='The Court-PASS page this entry was scraped from. Entries are numbered independently per page, so two entries from different pages can share a ``sequence_number``; ``page`` is therefore part of the natural key.', help_text='The Court-PASS page this entry was scraped from. Entries are numbered independently per page, so this is part of the natural key.')),
                ('filing_type', models.TextField(blank=True, db_comment='The filing type from the Court-PASS FILINGS table (e.g. "Appellant Brief"). Blank for entries that only carry a document.', help_text='The filing type from the Court-PASS FILINGS table (e.g. "Appellant Brief"). Blank for entries that only carry a document.')),
                ('party', models.TextField(blank=True, db_comment='The party associated with the filing, if any.', help_text='The party associated with the filing, if any.')),
                ('date_received', models.DateField(blank=True, db_comment='The date Court-PASS recorded the filing as received.', help_text='The date Court-PASS recorded the filing as received.', null=True)),
                ('sequence_number', models.CharField(db_comment="CL-generated field to keep entries in a stable order. Concatenation of a filing date (in ISO format) and the entry's per-page index, mirroring the convention used for Texas dockets.", help_text="CL-generated field to keep entries in a stable order. Concatenation of a filing date (in ISO format) and the entry's per-page index, mirroring the convention used for Texas dockets.", max_length=16)),
                ('docket', models.ForeignKey(db_comment='The Docket this entry is associated with.', db_constraint=False, help_text='The Docket this entry is associated with.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.docket')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='search.nycoadocketentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NYCoADocketMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('issue', models.TextField(blank=True, help_text='The issue categories the Court of Appeals associated with this case.')),
                ('summary', models.TextField(blank=True, help_text='The detailed issue descriptions for this case.')),
                ('decision_date', models.DateField(blank=True, help_text='The date this case was decided, if it has been decided.', null=True)),
                ('opinion_by', models.TextField(blank=True, help_text='The author of the opinion, for decided cases.', null=True)),
                ('official_citation', models.CharField(blank=True, help_text='The official citation, for decided cases.', max_length=255, null=True)),
                ('docket', models.OneToOneField(help_text='The docket this NYCoA metadata applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='nycoa_metadata', to='search.docket')),
            ],
            options={
                'verbose_name': 'NYCoA Docket Metadata',
                'verbose_name_plural': 'NYCoA Docket Metadata',
            },
        ),
        migrations.CreateModel(
            name='NYCoADocketMetadataEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('issue', models.TextField(blank=True, help_text='The issue categories the Court of Appeals associated with this case.')),
                ('summary', models.TextField(blank=True, help_text='The detailed issue descriptions for this case.')),
                ('decision_date', models.DateField(blank=True, help_text='The date this case was decided, if it has been decided.', null=True)),
                ('opinion_by', models.TextField(blank=True, help_text='The author of the opinion, for decided cases.', null=True)),
                ('official_citation', models.CharField(blank=True, help_text='The official citation, for decided cases.', max_length=255, null=True)),
                ('docket', models.ForeignKey(db_constraint=False, help_text='The docket this NYCoA metadata applies to.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.docket')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='search.nycoadocketmetadata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NYCoADocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('sha1', models.CharField(blank=True, help_text='The ID used for a document in RECAP', max_length=40)),
                ('page_count', models.IntegerField(blank=True, help_text='The number of pages in the document, if known', null=True)),
                ('file_size', models.IntegerField(blank=True, help_text='The size of the file in bytes, if known', null=True)),
                ('filepath_local', models.FileField(blank=True, help_text='The path is AWS S3 where the file is saved. Note that the field name is historical, from before when we used S3. To find the location in S3, concatenate https://storage.courtlistener.com/ and the value of this field.', max_length=1000, storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.lib.model_helpers.make_pdf_path)),
                ('filepath_ia', models.CharField(blank=True, help_text='The URL of the file in IA', max_length=1000)),
                ('ia_upload_failure_count', models.SmallIntegerField(blank=True, help_text='Number of times the upload to the Internet Archive failed.', null=True)),
                ('thumbnail', models.FileField(blank=True, help_text='The path to a thumbnail in S3 of the first page of the document.', null=True, storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.lib.model_helpers.make_pdf_thumb_path)),
                ('thumbnail_status', models.SmallIntegerField(choices=[(0, 'Thumbnail needed'), (1, 'Thumbnail completed successfully'), (2, 'Unable to generate thumbnail')], default=0, help_text='The status of the thumbnail generation')),
                ('plain_text', models.TextField(blank=True, help_text='Plain text of the document after extraction using pdftotext, wpd2txt, etc.')),
                ('ocr_status', models.SmallIntegerField(blank=True, choices=[(1, 'OCR Complete'), (2, 'OCR Not Necessary'), (3, 'OCR Failed'), (4, 'OCR Needed')], help_text='The status of OCR processing on this item.', null=True)),
                ('file_name', models.TextField(blank=True, db_comment='The filename as shown on the Court-PASS filing-detail page.', help_text='The filename as shown on the Court-PASS filing-detail page.')),
                ('document_number', models.IntegerField(db_comment='The 1-based document number for the file, numbered from the bottom of the Court-PASS files table up.', help_text='The 1-based document number for the file, numbered from the bottom of the Court-PASS files table up.')),
                ('available', models.BooleanField(db_comment='Whether the file is available (False for sealed or not-available files).', default=True, help_text='Whether the file is available (False for sealed or not-available files).')),
                ('docket_entry', models.ForeignKey(db_comment='The docket entry this document is associated with.', help_text='The docket entry this document is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='search.nycoadocketentry')),
            ],
        ),
        migrations.CreateModel(
            name='NYCoADocumentEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('sha1', models.CharField(blank=True, help_text='The ID used for a document in RECAP', max_length=40)),
                ('page_count', models.IntegerField(blank=True, help_text='The number of pages in the document, if known', null=True)),
                ('file_size', models.IntegerField(blank=True, help_text='The size of the file in bytes, if known', null=True)),
                ('filepath_local', models.FileField(blank=True, help_text='The path is AWS S3 where the file is saved. Note that the field name is historical, from before when we used S3. To find the location in S3, concatenate https://storage.courtlistener.com/ and the value of this field.', max_length=1000, storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.lib.model_helpers.make_pdf_path)),
                ('filepath_ia', models.CharField(blank=True, help_text='The URL of the file in IA', max_length=1000)),
                ('ia_upload_failure_count', models.SmallIntegerField(blank=True, help_text='Number of times the upload to the Internet Archive failed.', null=True)),
                ('thumbnail', models.FileField(blank=True, help_text='The path to a thumbnail in S3 of the first page of the document.', null=True, storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.lib.model_helpers.make_pdf_thumb_path)),
                ('thumbnail_status', models.SmallIntegerField(choices=[(0, 'Thumbnail needed'), (1, 'Thumbnail completed successfully'), (2, 'Unable to generate thumbnail')], default=0, help_text='The status of the thumbnail generation')),
                ('plain_text', models.TextField(blank=True, help_text='Plain text of the document after extraction using pdftotext, wpd2txt, etc.')),
                ('ocr_status', models.SmallIntegerField(blank=True, choices=[(1, 'OCR Complete'), (2, 'OCR Not Necessary'), (3, 'OCR Failed'), (4, 'OCR Needed')], help_text='The status of OCR processing on this item.', null=True)),
                ('file_name', models.TextField(blank=True, db_comment='The filename as shown on the Court-PASS filing-detail page.', help_text='The filename as shown on the Court-PASS filing-detail page.')),
                ('document_number', models.IntegerField(db_comment='The 1-based document number for the file, numbered from the bottom of the Court-PASS files table up.', help_text='The 1-based document number for the file, numbered from the bottom of the Court-PASS files table up.')),
                ('available', models.BooleanField(db_comment='Whether the file is available (False for sealed or not-available files).', default=True, help_text='Whether the file is available (False for sealed or not-available files).')),
                ('docket_entry', models.ForeignKey(db_comment='The docket entry this document is associated with.', db_constraint=False, help_text='The docket entry this document is associated with.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='search.nycoadocketentry')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='search.nycoadocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nycoadocketentry',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."date_received" IS DISTINCT FROM (NEW."date_received") OR OLD."docket_id" IS DISTINCT FROM (NEW."docket_id") OR OLD."filing_type" IS DISTINCT FROM (NEW."filing_type") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."page" IS DISTINCT FROM (NEW."page") OR OLD."party" IS DISTINCT FROM (NEW."party") OR OLD."sequence_number" IS DISTINCT FROM (NEW."sequence_number"))', func='INSERT INTO "search_nycoadocketentryevent" ("date_created", "date_modified", "date_received", "docket_id", "filing_type", "id", "page", "party", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sequence_number") VALUES (OLD."date_created", OLD."date_modified", OLD."date_received", OLD."docket_id", OLD."filing_type", OLD."id", OLD."page", OLD."party", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."sequence_number"); RETURN NULL;', hash='5f1cec3c56f3be43e149adf1377be5edfac91789', operation='UPDATE', pgid='pgtrigger_update_update_5dd01', table='search_nycoadocketentry', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nycoadocketentry',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_nycoadocketentryevent" ("date_created", "date_modified", "date_received", "docket_id", "filing_type", "id", "page", "party", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sequence_number") VALUES (OLD."date_created", OLD."date_modified", OLD."date_received", OLD."docket_id", OLD."filing_type", OLD."id", OLD."page", OLD."party", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."sequence_number"); RETURN NULL;', hash='2a37b05d36a10a2146c6117a584edfe6ed9eafe4', operation='DELETE', pgid='pgtrigger_delete_delete_12897', table='search_nycoadocketentry', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nycoadocketmetadata',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."decision_date" IS DISTINCT FROM (NEW."decision_date") OR OLD."docket_id" IS DISTINCT FROM (NEW."docket_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."issue" IS DISTINCT FROM (NEW."issue") OR OLD."official_citation" IS DISTINCT FROM (NEW."official_citation") OR OLD."opinion_by" IS DISTINCT FROM (NEW."opinion_by") OR OLD."summary" IS DISTINCT FROM (NEW."summary"))', func='INSERT INTO "search_nycoadocketmetadataevent" ("date_created", "date_modified", "decision_date", "docket_id", "id", "issue", "official_citation", "opinion_by", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "summary") VALUES (OLD."date_created", OLD."date_modified", OLD."decision_date", OLD."docket_id", OLD."id", OLD."issue", OLD."official_citation", OLD."opinion_by", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."summary"); RETURN NULL;', hash='81664149656e68295ee02c943bb0ea32e91737d4', operation='UPDATE', pgid='pgtrigger_update_update_583e1', table='search_nycoadocketmetadata', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nycoadocketmetadata',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_nycoadocketmetadataevent" ("date_created", "date_modified", "decision_date", "docket_id", "id", "issue", "official_citation", "opinion_by", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "summary") VALUES (OLD."date_created", OLD."date_modified", OLD."decision_date", OLD."docket_id", OLD."id", OLD."issue", OLD."official_citation", OLD."opinion_by", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."summary"); RETURN NULL;', hash='438d64ef18c700703b0cbd5e7679ea5ee9306952', operation='DELETE', pgid='pgtrigger_delete_delete_e885e', table='search_nycoadocketmetadata', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='nycoadocument',
            index=models.Index(fields=['filepath_local'], name='search_nyco_filepat_9734a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nycoadocument',
            unique_together={('docket_entry', 'document_number')},
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nycoadocument',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."available" IS DISTINCT FROM (NEW."available") OR OLD."docket_entry_id" IS DISTINCT FROM (NEW."docket_entry_id") OR OLD."document_number" IS DISTINCT FROM (NEW."document_number") OR OLD."file_name" IS DISTINCT FROM (NEW."file_name") OR OLD."file_size" IS DISTINCT FROM (NEW."file_size") OR OLD."filepath_ia" IS DISTINCT FROM (NEW."filepath_ia") OR OLD."filepath_local" IS DISTINCT FROM (NEW."filepath_local") OR OLD."ia_upload_failure_count" IS DISTINCT FROM (NEW."ia_upload_failure_count") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."ocr_status" IS DISTINCT FROM (NEW."ocr_status") OR OLD."page_count" IS DISTINCT FROM (NEW."page_count") OR OLD."plain_text" IS DISTINCT FROM (NEW."plain_text") OR OLD."sha1" IS DISTINCT FROM (NEW."sha1") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."thumbnail_status" IS DISTINCT FROM (NEW."thumbnail_status"))', func='INSERT INTO "search_nycoadocumentevent" ("available", "date_created", "date_modified", "docket_entry_id", "document_number", "file_name", "file_size", "filepath_ia", "filepath_local", "ia_upload_failure_count", "id", "ocr_status", "page_count", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plain_text", "sha1", "thumbnail", "thumbnail_status") VALUES (OLD."available", OLD."date_created", OLD."date_modified", OLD."docket_entry_id", OLD."document_number", OLD."file_name", OLD."file_size", OLD."filepath_ia", OLD."filepath_local", OLD."ia_upload_failure_count", OLD."id", OLD."ocr_status", OLD."page_count", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."plain_text", OLD."sha1", OLD."thumbnail", OLD."thumbnail_status"); RETURN NULL;', hash='3eaf795e6176f2d7cc04f358e682b120c32161ef', operation='UPDATE', pgid='pgtrigger_update_update_8efbf', table='search_nycoadocument', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nycoadocument',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_nycoadocumentevent" ("available", "date_created", "date_modified", "docket_entry_id", "document_number", "file_name", "file_size", "filepath_ia", "filepath_local", "ia_upload_failure_count", "id", "ocr_status", "page_count", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plain_text", "sha1", "thumbnail", "thumbnail_status") VALUES (OLD."available", OLD."date_created", OLD."date_modified", OLD."docket_entry_id", OLD."document_number", OLD."file_name", OLD."file_size", OLD."filepath_ia", OLD."filepath_local", OLD."ia_upload_failure_count", OLD."id", OLD."ocr_status", OLD."page_count", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."plain_text", OLD."sha1", OLD."thumbnail", OLD."thumbnail_status"); RETURN NULL;', hash='9b537158a1c823343d6f19f918834ea0ebe2ac6e', operation='DELETE', pgid='pgtrigger_delete_delete_d8581', table='search_nycoadocument', when='AFTER')),
        ),
    ]
