# Generated by Django 6.0.7 on 2026-09-04 17:27

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0061_florida_document_content_type_length'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='nycoadocument',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='nycoadocument',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='nycoadocument',
            name='sha256',
            field=models.CharField(blank=True, db_comment='Hex digest of the file.', help_text='Hex digest of the file.', max_length=64),
        ),
        migrations.AddField(
            model_name='nycoadocumentevent',
            name='sha256',
            field=models.CharField(blank=True, db_comment='Hex digest of the file.', help_text='Hex digest of the file.', max_length=64),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nycoadocument',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."available" IS DISTINCT FROM (NEW."available") OR OLD."content_type" IS DISTINCT FROM (NEW."content_type") OR OLD."doc_party" IS DISTINCT FROM (NEW."doc_party") OR OLD."doc_role" IS DISTINCT FROM (NEW."doc_role") OR OLD."doc_type" IS DISTINCT FROM (NEW."doc_type") OR OLD."docket_entry_id" IS DISTINCT FROM (NEW."docket_entry_id") OR OLD."file_name" IS DISTINCT FROM (NEW."file_name") OR OLD."file_size" IS DISTINCT FROM (NEW."file_size") OR OLD."filepath_ia" IS DISTINCT FROM (NEW."filepath_ia") OR OLD."filepath_local" IS DISTINCT FROM (NEW."filepath_local") OR OLD."ia_upload_failure_count" IS DISTINCT FROM (NEW."ia_upload_failure_count") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."ocr_status" IS DISTINCT FROM (NEW."ocr_status") OR OLD."page_count" IS DISTINCT FROM (NEW."page_count") OR OLD."part" IS DISTINCT FROM (NEW."part") OR OLD."plain_text" IS DISTINCT FROM (NEW."plain_text") OR OLD."processing_error" IS DISTINCT FROM (NEW."processing_error") OR OLD."sha1" IS DISTINCT FROM (NEW."sha1") OR OLD."sha256" IS DISTINCT FROM (NEW."sha256") OR OLD."thumbnail" IS DISTINCT FROM (NEW."thumbnail") OR OLD."thumbnail_status" IS DISTINCT FROM (NEW."thumbnail_status") OR OLD."volume" IS DISTINCT FROM (NEW."volume"))', func='INSERT INTO "search_nycoadocumentevent" ("available", "content_type", "date_created", "date_modified", "doc_party", "doc_role", "doc_type", "docket_entry_id", "file_name", "file_size", "filepath_ia", "filepath_local", "ia_upload_failure_count", "id", "ocr_status", "page_count", "part", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plain_text", "processing_error", "sha1", "sha256", "thumbnail", "thumbnail_status", "volume") VALUES (OLD."available", OLD."content_type", OLD."date_created", OLD."date_modified", OLD."doc_party", OLD."doc_role", OLD."doc_type", OLD."docket_entry_id", OLD."file_name", OLD."file_size", OLD."filepath_ia", OLD."filepath_local", OLD."ia_upload_failure_count", OLD."id", OLD."ocr_status", OLD."page_count", OLD."part", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."plain_text", OLD."processing_error", OLD."sha1", OLD."sha256", OLD."thumbnail", OLD."thumbnail_status", OLD."volume"); RETURN NULL;', hash='2bb18ea26e9aa5e30687be403da80bb495b91047', operation='UPDATE', pgid='pgtrigger_update_update_8efbf', table='search_nycoadocument', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nycoadocument',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "search_nycoadocumentevent" ("available", "content_type", "date_created", "date_modified", "doc_party", "doc_role", "doc_type", "docket_entry_id", "file_name", "file_size", "filepath_ia", "filepath_local", "ia_upload_failure_count", "id", "ocr_status", "page_count", "part", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plain_text", "processing_error", "sha1", "sha256", "thumbnail", "thumbnail_status", "volume") VALUES (OLD."available", OLD."content_type", OLD."date_created", OLD."date_modified", OLD."doc_party", OLD."doc_role", OLD."doc_type", OLD."docket_entry_id", OLD."file_name", OLD."file_size", OLD."filepath_ia", OLD."filepath_local", OLD."ia_upload_failure_count", OLD."id", OLD."ocr_status", OLD."page_count", OLD."part", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."plain_text", OLD."processing_error", OLD."sha1", OLD."sha256", OLD."thumbnail", OLD."thumbnail_status", OLD."volume"); RETURN NULL;', hash='387d96e2c4c767c40c0310cc23417cb93f3be419', operation='DELETE', pgid='pgtrigger_delete_delete_d8581', table='search_nycoadocument', when='AFTER')),
        ),
    ]
