# Generated by Django 6.0.8 on 2026-10-02 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0063_nycoa_document_drop_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scotusdocketentry',
            name='docket',
            field=models.ForeignKey(db_comment='The Docket this entry is associated with.', help_text='The Docket this entry is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='scotus_docket_entries', to='search.docket'),
        ),
        migrations.AlterField(
            model_name='scotusdocument',
            name='docket_entry',
            field=models.ForeignKey(db_comment='The Docket this document is associated with.', help_text='The Docket this document is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='scotus_documents', to='search.scotusdocketentry'),
        ),
    ]
