# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-20 03:57


import django.db.models.deletion
from django.db import migrations, models

import cl.lib.model_helpers
import cl.lib.storage


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0084_add_claims_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankruptcyinformation',
            options={'verbose_name_plural': 'Bankruptcy Information'},
        ),
        migrations.AlterModelOptions(
            name='claimhistory',
            options={'verbose_name_plural': 'Claim History Entries'},
        ),
        migrations.AlterField(
            model_name='bankruptcyinformation',
            name='docket',
            field=models.OneToOneField(help_text='The docket that the bankruptcy info is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='bankruptcy_information', to='search.Docket'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_number',
            field=models.CharField(blank=True, db_index=True, help_text='The number of the claim.', max_length=10),
        ),
        migrations.AlterField(
            model_name='claimhistory',
            name='thumbnail',
            field=models.FileField(blank=True, help_text='A thumbnail of the first page of the document', null=True, storage=cl.lib.storage.IncrementingFileSystemStorage(), upload_to=cl.lib.model_helpers.make_pdf_thumb_path),
        ),
        migrations.AlterField(
            model_name='recapdocument',
            name='thumbnail',
            field=models.FileField(blank=True, help_text='A thumbnail of the first page of the document', null=True, storage=cl.lib.storage.IncrementingFileSystemStorage(), upload_to=cl.lib.model_helpers.make_pdf_thumb_path),
        ),
    ]
