# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-28 00:04


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0085_add_index_to_claim_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimhistory',
            name='claim',
            field=models.ForeignKey(help_text=b'The claim that the history row is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='claim_history_entries', to='search.Claim'),
        ),
    ]
