# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-28 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0086_claims_related_name"),
    ]

    operations = [
        migrations.RunSQL(
            """UPDATE "search_opinion" SET "html" = '' WHERE "html" IS NULL;""",
            reverse_sql="""UPDATE "search_opinion" SET "html" = NULL WHERE "html" = '';"""
        ),
        migrations.RunSQL(
            """UPDATE "search_opinion" SET "html_columbia" = '' WHERE "html_columbia" IS NULL;""",
            reverse_sql="""UPDATE "search_opinion" SET "html_columbia" = NULL WHERE "html_columbia" = '';"""
        ),
        migrations.RunSQL(
            """UPDATE "search_opinion" SET "html_lawbox" = '' WHERE "html_lawbox" IS NULL;""",
            reverse_sql="""UPDATE "search_opinion" SET "html_lawbox" = NULL WHERE "html_lawbox" = '';"""
        ),
    ]
