# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-27 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0087_set_values_to_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='joined_by_str',
            field=models.TextField(blank=True, help_text=b'Other judges that joined the primary author in this opinion str'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='xml_harvard',
            field=models.TextField(blank=True, help_text=b'XML of Harvard CaseLaw Access Project opinion'),
        ),
        migrations.AddField(
            model_name='opinioncluster',
            name='correction',
            field=models.TextField(blank=True, help_text=b"Publisher's correction to the case text. Example: Replace last paragraph on page 476 with this text: blah blah blah. This is basically an unstructured text that can be used to manually correct case content according to publisher's instructions. No footnotes is expected within it."),
        ),
        migrations.AddField(
            model_name='opinioncluster',
            name='cross_reference',
            field=models.TextField(blank=True, help_text=b'Cross-reference citation (often to a past or future similar case). It does NOT identify this case.'),
        ),
        migrations.AddField(
            model_name='opinioncluster',
            name='disposition',
            field=models.TextField(blank=True, help_text=b'Description of the procedural outcome of the case, e.g. Reversed, dismissed etc. Generally a short paragraph that appears just after the summary or synopsis'),
        ),
        migrations.AddField(
            model_name='opinioncluster',
            name='filepath_json_harvard',
            field=models.FileField(blank=True, help_text=b'Path to local storage of JSON collected from Harvard Case Law project containing available metadata, opinion and opinion cluster.', max_length=1000, upload_to=b''),
        ),
        migrations.AddField(
            model_name='opinioncluster',
            name='headnotes',
            field=models.TextField(blank=True, help_text=b'Headnotes are summary descriptions of the legal issues discussed by the court in the particular case. They appear at the beginning of each case just after the summary and disposition. They are short paragraphs with a heading in bold face type. From Wikipedia - A headnote is a brief summary of a particular point of law that is added to the text of a courtdecision to aid readers in locating discussion of a legalissue in an opinion. As the term implies, headnotes appearat the beginning of the published opinion. Frequently, headnotes are value-added components appended to decisions by the publisher who compiles the decisions of a court for resale. As handed down by the court, a decision or written opinion does not contain headnotes. These are added later by an editor not connected to the court, but who instead works for a legal publishing house.'),
        ),
        migrations.AddField(
            model_name='opinioncluster',
            name='history',
            field=models.TextField(blank=True, help_text=b'History of the case (similar to the summary, but focused on past events related to this case). Appears at the beginning of the case just after the title of the case and court information'),
        ),
        migrations.AddField(
            model_name='opinioncluster',
            name='other_dates',
            field=models.TextField(blank=True, help_text=b'Other date(s) as specified in the text (case header). This may include follow-up dates.'),
        ),
        migrations.AddField(
            model_name='opinioncluster',
            name='summary',
            field=models.TextField(blank=True, help_text=b'A summary of what happened in the case. Appears at the beginning of the case just after the title of the case and court information.'),
        ),
        migrations.AlterField(
            model_name='claimhistory',
            name='claim',
            field=models.ForeignKey(help_text=b'The claim that the history row is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='claim_history_entries', to='search.Claim'),
        ),
        migrations.AlterField(
            model_name='docket',
            name='source',
            field=models.SmallIntegerField(choices=[(0, b'Default'), (1, b'RECAP'), (2, b'Scraper'), (3, b'RECAP and Scraper'), (4, b'Columbia'), (6, b'Columbia and Scraper'), (5, b'Columbia and RECAP'), (7, b'Columbia, RECAP, and Scraper'), (8, b'Integrated Database'), (9, b'RECAP and IDB'), (10, b'Scraper and IDB'), (11, b'RECAP, Scraper, and IDB'), (12, b'Columbia and IDB'), (13, b'Columbia, RECAP, and IDB'), (14, b'Columbia, Scraper, and IDB'), (15, b'Columbia, RECAP, Scraper, and IDB'), (16, b'Harvard'), (17, b'Scraper and Harvard')], help_text=b'contains the source of the Docket.'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='html',
            field=models.TextField(blank=True, default='', help_text=b'HTML of the document, if available in the original'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opinion',
            name='html_columbia',
            field=models.TextField(blank=True, default='', help_text=b'HTML of Columbia archive'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opinion',
            name='html_lawbox',
            field=models.TextField(blank=True, default='', help_text=b'HTML of Lawbox documents'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opinion',
            name='type',
            field=models.CharField(choices=[(b'010combined', b'Combined Opinion'), (b'015unamimous', b'Unanimous Opinion'), (b'020lead', b'Lead Opinion'), (b'025plurality', b'Plurality Opinion'), (b'030concurrence', b'Concurrence Opinion'), (b'035concurrenceinpart', b'In Part Opinion'), (b'040dissent', b'Dissent'), (b'050addendum', b'Addendum'), (b'060remittitur', b'Remittitur'), (b'070rehearing', b'Rehearing'), (b'080onthemerits', b'On the Merits'), (b'090onmotiontostrike', b'On Motion to Strike Cost Bill')], max_length=20),
        ),
        migrations.AlterField(
            model_name='opinioncluster',
            name='source',
            field=models.CharField(blank=True, choices=[(b'C', b'court website'), (b'R', b'public.resource.org'), (b'CR', b'court website merged with resource.org'), (b'L', b'lawbox'), (b'LC', b'lawbox merged with court'), (b'LR', b'lawbox merged with resource.org'), (b'LCR', b'lawbox merged with court and resource.org'), (b'M', b'manual input'), (b'A', b'internet archive'), (b'H', b'brad heath archive'), (b'Z', b'columbia archive'), (b'ZC', b'columbia merged with court'), (b'ZLC', b'columbia merged with lawbox and court'), (b'ZLR', b'columbia merged with lawbox and resource.org'), (b'ZLCR', b'columbia merged with lawbox, court, and resource.org'), (b'ZR', b'columbia merged with resource.org'), (b'ZCR', b'columbia merged with court and resource.org'), (b'ZL', b'columbia merged with lawbox'), (b'U', b'Harvard, Library Innovation Lab Case Law Access Project'), (b'CU', b'court website merged with Harvard')], help_text=b'the source of the cluster, one of: C (court website), R (public.resource.org), CR (court website merged with resource.org), L (lawbox), LC (lawbox merged with court), LR (lawbox merged with resource.org), LCR (lawbox merged with court and resource.org), M (manual input), A (internet archive), H (brad heath archive), Z (columbia archive), ZC (columbia merged with court), ZLC (columbia merged with lawbox and court), ZLR (columbia merged with lawbox and resource.org), ZLCR (columbia merged with lawbox, court, and resource.org), ZR (columbia merged with resource.org), ZCR (columbia merged with court and resource.org), ZL (columbia merged with lawbox), U (Harvard, Library Innovation Lab Case Law Access Project), CU (court website merged with Harvard)', max_length=10),
        ),
    ]
