# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-28 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0088_add_harvard_opinions"),
    ]

    operations = [
        migrations.AddField(
            model_name="opinionscited",
            name="depth",
            field=models.IntegerField(
                db_index=True,
                default=1,
                help_text=b"The number of times the cited opinion was cited in the citing opinion",
            ),
        ),
    ]
