# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-13 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0090_update_opinion_sha1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinioncluster',
            name='federal_cite_one',
        ),
        migrations.RemoveField(
            model_name='opinioncluster',
            name='federal_cite_three',
        ),
        migrations.RemoveField(
            model_name='opinioncluster',
            name='federal_cite_two',
        ),
        migrations.RemoveField(
            model_name='opinioncluster',
            name='lexis_cite',
        ),
        migrations.RemoveField(
            model_name='opinioncluster',
            name='neutral_cite',
        ),
        migrations.RemoveField(
            model_name='opinioncluster',
            name='scotus_early_cite',
        ),
        migrations.RemoveField(
            model_name='opinioncluster',
            name='specialty_cite_one',
        ),
        migrations.RemoveField(
            model_name='opinioncluster',
            name='state_cite_one',
        ),
        migrations.RemoveField(
            model_name='opinioncluster',
            name='state_cite_regional',
        ),
        migrations.RemoveField(
            model_name='opinioncluster',
            name='state_cite_three',
        ),
        migrations.RemoveField(
            model_name='opinioncluster',
            name='state_cite_two',
        ),
        migrations.RemoveField(
            model_name='opinioncluster',
            name='westlaw_cite',
        ),
    ]
