# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-14 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0090_update_opinion_sha1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinioncluster',
            name='filepath_json_harvard',
            field=models.FileField(blank=True, db_index=True, help_text=b'Path to local storage of JSON collected from Harvard Case Law project containing available metadata, opinion and opinion cluster.', max_length=1000, upload_to=b''),
        ),
    ]
