# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-23 23:19


from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("search", "0092_remove_deprecated_fields"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""ALTER TABLE "search_opinionscited" ADD COLUMN "depth" integer;""",
            reverse_sql="""ALTER TABLE "search_opinionscited" DROP COLUMN "depth";""",
        ),
        migrations.RunSQL(
            sql="""UPDATE "search_opinionscited" set "depth" = 1;""",
            reverse_sql="""UPDATE "search_opinionscited" set "depth" = NULL;"""
        ),
        migrations.RunSQL(
            sql="""ALTER TABLE "search_opinionscited" ALTER COLUMN "depth" SET NOT NULL;""",
            reverse_sql="""ALTER TABLE "search_opinionscited" ALTER COLUMN "depth" DROP NOT NULL;""",
        ),
        migrations.RunSQL(
            sql="""
            CREATE INDEX CONCURRENTLY "search_opinionscited_depth_46bacaef" ON "search_opinionscited" ("depth");
            """,
            reverse_sql="""
            DROP INDEX "search_opinionscited_depth_46bacaef";
            """,
            state_operations=[
                migrations.AddField(
                    model_name="opinionscited",
                    name="depth",
                    field=models.IntegerField(
                        db_index=True,
                        default=1,
                        help_text="The number of times the cited opinion was cited in the citing opinion",
                    ),
                ),
            ],
        ),
    ]
