# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-26 06:39


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0093_add_citation_depth'),
        ('search', '0093_convert_docket_no_into_text'),
    ]

    operations = [
    ]
