# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-23 15:03


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0095_noop_update_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='date_last_pacer_contact',
            field=models.DateTimeField(blank=True, help_text='The last time the PACER website for the court was successfully contacted', null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='pacer_rss_entry_types',
            field=models.TextField(blank=True, help_text="The types of entries provided by the court's RSS feed."),
        ),
        migrations.AlterField(
            model_name='docket',
            name='date_last_filing',
            field=models.DateField(blank=True, help_text="The date the case was last updated in the docket, as shown in PACER's Docket History report or iquery page.", null=True),
        ),
        migrations.AlterField(
            model_name='opinioncluster',
            name='source',
            field=models.CharField(blank=True, choices=[('C', 'court website'), ('R', 'public.resource.org'), ('CR', 'court website merged with resource.org'), ('L', 'lawbox'), ('LC', 'lawbox merged with court'), ('LR', 'lawbox merged with resource.org'), ('LCR', 'lawbox merged with court and resource.org'), ('M', 'manual input'), ('A', 'internet archive'), ('H', 'brad heath archive'), ('Z', 'columbia archive'), ('ZC', 'columbia merged with court'), ('ZLC', 'columbia merged with lawbox and court'), ('ZLR', 'columbia merged with lawbox and resource.org'), ('ZLCR', 'columbia merged with lawbox, court, and resource.org'), ('ZR', 'columbia merged with resource.org'), ('ZCR', 'columbia merged with court and resource.org'), ('ZL', 'columbia merged with lawbox'), ('U', 'Harvard, Library Innovation Lab Case Law Access Project'), ('CU', 'court website merged with Harvard'), ('D', 'direct court input')], help_text='the source of the cluster, one of: C (court website), R (public.resource.org), CR (court website merged with resource.org), L (lawbox), LC (lawbox merged with court), LR (lawbox merged with resource.org), LCR (lawbox merged with court and resource.org), M (manual input), A (internet archive), H (brad heath archive), Z (columbia archive), ZC (columbia merged with court), ZLC (columbia merged with lawbox and court), ZLR (columbia merged with lawbox and resource.org), ZLCR (columbia merged with lawbox, court, and resource.org), ZR (columbia merged with resource.org), ZCR (columbia merged with court and resource.org), ZL (columbia merged with lawbox), U (Harvard, Library Innovation Lab Case Law Access Project), CU (court website merged with Harvard), D (direct court input)', max_length=10),
        ),
        migrations.AlterField(
            model_name='docket',
            name='source',
            field=models.SmallIntegerField(
                choices=[(0, 'Default'), (1, 'RECAP'), (2, 'Scraper'),
                         (3, 'RECAP and Scraper'), (4, 'Columbia'),
                         (6, 'Columbia and Scraper'),
                         (5, 'Columbia and RECAP'),
                         (7, 'Columbia, RECAP, and Scraper'),
                         (8, 'Integrated Database'), (9, 'RECAP and IDB'),
                         (10, 'Scraper and IDB'),
                         (11, 'RECAP, Scraper, and IDB'),
                         (12, 'Columbia and IDB'),
                         (13, 'Columbia, RECAP, and IDB'),
                         (14, 'Columbia, Scraper, and IDB'),
                         (15, 'Columbia, RECAP, Scraper, and IDB'),
                         (16, 'Harvard'), (17, 'Scraper and Harvard'),
                         (32, 'Direct court input')],
                help_text='contains the source of the Docket.'),
        ),
    ]
