# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-23 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0097_auto_20201118_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankruptcyinformation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.'),
        ),
        migrations.AlterField(
            model_name='bankruptcyinformation',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown'),
        ),
        migrations.AlterField(
            model_name='claimhistory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.'),
        ),
        migrations.AlterField(
            model_name='claimhistory',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown'),
        ),
        migrations.AlterField(
            model_name='docket',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.'),
        ),
        migrations.AlterField(
            model_name='docketentry',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.'),
        ),
        migrations.AlterField(
            model_name='docketentry',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.'),
        ),
        migrations.AlterField(
            model_name='opinioncluster',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.'),
        ),
        migrations.AlterField(
            model_name='originatingcourtinformation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.'),
        ),
        migrations.AlterField(
            model_name='originatingcourtinformation',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown'),
        ),
        migrations.AlterField(
            model_name='recapdocument',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.'),
        ),
        migrations.AlterField(
            model_name='recapdocument',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.'),
        ),
    ]
