# Generated by Django 3.1.7 on 2021-04-17 00:02

from django.db import migrations, models

import cl.lib.model_helpers
import cl.lib.storage


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0098_abstract_datetime_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='filepath_local',
            field=models.FileField(blank=True, help_text="Path to RECAP's Docket XML page as provided by the original RECAP architecture. These fields are for backup purposes only. Note that the field name is historical, from before when we used S3. To find the location in S3, concatenate https://storage.courtlistener.com/ and the value of this field.", max_length=1000, storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.lib.model_helpers.make_recap_path),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='local_path',
            field=models.FileField(blank=True, db_index=True, help_text='The location in AWS S3 where the original opinion file is stored. Note that the field name is historical, from before when we used S3. To find the location in S3, concatenate https://storage.courtlistener.com/ and the value of this field.', storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.lib.model_helpers.make_upload_path),
        ),
        migrations.AlterField(
            model_name='recapdocument',
            name='filepath_local',
            field=models.FileField(blank=True, db_index=True,
                                   help_text='The path is AWS S3 where the file is saved. Note that the field name is historical, from before when we used S3. To find the location in S3, concatenate https://storage.courtlistener.com/ and the value of this field.',
                                   max_length=1000,
                                   storage=cl.lib.storage.IncrementingAWSMediaStorage(),
                                   upload_to=cl.lib.model_helpers.make_pdf_path),
        ),
        migrations.AlterField(
            model_name='recapdocument',
            name='thumbnail',
            field=models.FileField(blank=True,
                                   help_text='The path to a thumbnail in S3 of the first page of the document.',
                                   null=True,
                                   storage=cl.lib.storage.IncrementingAWSMediaStorage(),
                                   upload_to=cl.lib.model_helpers.make_pdf_thumb_path),
        ),
        migrations.AlterField(
            model_name='claimhistory',
            name='thumbnail',
            field=models.FileField(blank=True,
                                   help_text='The path to a thumbnail in S3 of the first page of the document.',
                                   null=True,
                                   storage=cl.lib.storage.IncrementingAWSMediaStorage(),
                                   upload_to=cl.lib.model_helpers.make_pdf_thumb_path),
        ),
    ]
