# Generated by Django 3.1.7 on 2021-04-27 21:47
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('search', '0099_switch_to_s3_noop'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='docket',
            index=models.Index(fields=['court_id', 'id'], name='search_dock_court_i_a043ae_idx'),
        ),
    ]
