# Generated by Django 3.1.7 on 2021-05-28 19:34

import django.db.models.deletion
import localflavor.us.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABARating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('year_rated', models.PositiveSmallIntegerField(help_text='The year of the rating.', null=True)),
                ('rating', models.CharField(choices=[('ewq', 'Exceptionally Well Qualified'), ('wq', 'Well Qualified'), ('q', 'Qualified'), ('nq', 'Not Qualified'), ('nqa', 'Not Qualified By Reason of Age')], help_text='The rating given to the person.', max_length=5)),
            ],
            options={
                'verbose_name': 'American Bar Association Rating',
                'verbose_name_plural': 'American Bar Association Ratings',
            },
        ),
        migrations.CreateModel(
            name='Attorney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('name', models.TextField(db_index=True, help_text='The name of the attorney.')),
                ('contact_raw', models.TextField(help_text='The raw contents of the contact field')),
                ('phone', models.CharField(blank=True, help_text='The phone number of the attorney.', max_length=20)),
                ('fax', models.CharField(blank=True, help_text='The fax number of the attorney.', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='The email address of the attorney.', max_length=254)),
            ],
            options={
                'permissions': (('has_recap_api_access', 'Can work with RECAP API'),),
            },
        ),
        migrations.CreateModel(
            name='AttorneyOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('lookup_key', models.TextField(db_index=True, help_text='A trimmed version of the address for duplicate matching.', unique=True)),
                ('name', models.TextField(db_index=True, help_text='The name of the organization.')),
                ('address1', models.TextField(db_index=True, help_text='The normalized address1 of the organization')),
                ('address2', models.TextField(db_index=True, help_text='The normalized address2 of the organization')),
                ('city', models.TextField(db_index=True, help_text='The normalized city of the organization')),
                ('state', localflavor.us.models.USPostalCodeField(db_index=True, help_text='The two-letter USPS postal abbreviation for the organization', max_length=2)),
                ('zip_code', localflavor.us.models.USZipCodeField(db_index=True, help_text='The zip code for the organization, XXXXX or XXXXX-XXXX work.', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AttorneyOrganizationAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CriminalComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text="The name of the criminal complaint, for example, '8:1326 Reentry of Deported Alien'")),
                ('disposition', models.TextField(blank=True, help_text='The disposition of the criminal complaint.')),
            ],
        ),
        migrations.CreateModel(
            name='CriminalCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text="The name of the count, such as '21:952 and 960 - Importation of Marijuana(1)'.")),
                ('disposition', models.TextField(blank=True, help_text="The disposition of the count, such as 'Custody of BOP for 60 months, followed by 4 years supervised release. No fine. $100 penalty assessment.")),
                ('status', models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Terminated')], help_text='Whether the count is pending or terminated.')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('degree_level', models.CharField(blank=True, choices=[('ba', "Bachelor's (e.g. B.A.)"), ('ma', "Master's (e.g. M.A.)"), ('jd', 'Juris Doctor (J.D.)'), ('llm', 'Master of Laws (LL.M)'), ('llb', 'Bachelor of Laws (e.g. LL.B)'), ('jsd', 'Doctor of Law (J.S.D)'), ('phd', 'Doctor of Philosophy (PhD)'), ('aa', 'Associate (e.g. A.A.)'), ('md', 'Medical Degree (M.D.)'), ('mba', 'Master of Business Administration (M.B.A.)'), ('cfa', 'Accounting Certification (C.P.A., C.M.A., C.F.A.)'), ('cert', 'Certificate')], help_text='Normalized degree level, e.g. BA, JD.', max_length=4)),
                ('degree_detail', models.CharField(blank=True, help_text='Detailed degree description, e.g. including major.', max_length=100)),
                ('degree_year', models.PositiveSmallIntegerField(blank=True, help_text='The year the degree was awarded.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('name', models.TextField(db_index=True, help_text='The name of the party.')),
                ('extra_info', models.TextField(db_index=True, help_text='Prior to March, 2018, this field briefly held additional info from PACER about particular parties. That was a modelling mistake and the information has been moved to the PartyType.extra_info field instead. This field will be removed in October, 2020.')),
            ],
            options={
                'verbose_name_plural': 'Parties',
                'permissions': (('has_recap_api_access', 'Can work with RECAP API'),),
            },
        ),
        migrations.CreateModel(
            name='PartyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='The name of the type (Defendant, Plaintiff, etc.)', max_length=100)),
                ('date_terminated', models.DateField(blank=True, help_text='The date that the party was terminated from the case, if applicable.', null=True)),
                ('extra_info', models.TextField(blank=True, db_index=True, help_text='Additional info from PACER')),
                ('highest_offense_level_opening', models.TextField(blank=True, help_text='In a criminal case, the highest offense level at the opening of the case.')),
                ('highest_offense_level_terminated', models.TextField(blank=True, help_text='In a criminal case, the highest offense level at the end of the case.')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('date_completed', models.DateTimeField(blank=True, help_text='Whenever an editor last decided that a profile was complete in some sense.', null=True)),
                ('fjc_id', models.IntegerField(blank=True, db_index=True, help_text='The ID of a judge as assigned by the Federal Judicial Center.', null=True, unique=True)),
                ('cl_id', models.CharField(db_index=True, help_text='A unique identifier for judge, also indicating source of data.', max_length=30, unique=True)),
                ('slug', models.SlugField(help_text='A generated path for this item as used in CourtListener URLs', max_length=158)),
                ('name_first', models.CharField(help_text='The first name of this person.', max_length=50)),
                ('name_middle', models.CharField(blank=True, help_text='The middle name or names of this person', max_length=50)),
                ('name_last', models.CharField(db_index=True, help_text='The last name of this person', max_length=50)),
                ('name_suffix', models.CharField(blank=True, choices=[('jr', 'Jr.'), ('sr', 'Sr.'), ('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV')], help_text="Any suffixes that this person's name may have", max_length=5)),
                ('date_dob', models.DateField(blank=True, help_text='The date of birth for the person', null=True)),
                ('date_granularity_dob', models.CharField(blank=True, choices=[('%Y', 'Year'), ('%Y-%m', 'Month'), ('%Y-%m-%d', 'Day')], max_length=15)),
                ('date_dod', models.DateField(blank=True, help_text='The date of death for the person', null=True)),
                ('date_granularity_dod', models.CharField(blank=True, choices=[('%Y', 'Year'), ('%Y-%m', 'Month'), ('%Y-%m-%d', 'Day')], max_length=15)),
                ('dob_city', models.CharField(blank=True, help_text='The city where the person was born.', max_length=50)),
                ('dob_state', localflavor.us.models.USStateField(blank=True, help_text='The state where the person was born.', max_length=2)),
                ('dob_country', models.CharField(blank=True, default='United States', help_text='The country where the person was born.', max_length=50)),
                ('dod_city', models.CharField(blank=True, help_text='The city where the person died.', max_length=50)),
                ('dod_state', localflavor.us.models.USStateField(blank=True, help_text='The state where the person died.', max_length=2)),
                ('dod_country', models.CharField(blank=True, default='United States', help_text='The country where the person died.', max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], help_text="The person's gender", max_length=2)),
                ('religion', models.CharField(blank=True, help_text='The religion of a person', max_length=30)),
                ('ftm_total_received', models.FloatField(blank=True, db_index=True, help_text='The amount of money received by this person and logged by Follow the Money.', null=True)),
                ('ftm_eid', models.CharField(blank=True, help_text='The ID of a judge as assigned by the Follow the Money database.', max_length=30, null=True)),
                ('has_photo', models.BooleanField(default=False, help_text='Whether there is a photo corresponding to this person in the judge pics project.')),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='PoliticalAffiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('political_party', models.CharField(choices=[('d', 'Democratic'), ('r', 'Republican'), ('i', 'Independent'), ('g', 'Green'), ('l', 'Libertarian'), ('f', 'Federalist'), ('w', 'Whig'), ('j', 'Jeffersonian Republican'), ('u', 'National Union')], help_text='The political party the person is affiliated with.', max_length=5)),
                ('source', models.CharField(blank=True, choices=[('b', 'Ballot'), ('a', 'Appointer'), ('o', 'Other')], help_text='The source of the political affiliation -- where it is documented that this affiliation exists.', max_length=5)),
                ('date_start', models.DateField(blank=True, help_text='The date the political affiliation was first documented', null=True)),
                ('date_granularity_start', models.CharField(blank=True, choices=[('%Y', 'Year'), ('%Y-%m', 'Month'), ('%Y-%m-%d', 'Day')], max_length=15)),
                ('date_end', models.DateField(blank=True, help_text='The date the affiliation ended.', null=True)),
                ('date_granularity_end', models.CharField(blank=True, choices=[('%Y', 'Year'), ('%Y-%m', 'Month'), ('%Y-%m-%d', 'Day')], max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('position_type', models.CharField(blank=True, choices=[('Judge', (('act-jud', 'Acting Judge'), ('act-pres-jud', 'Acting Presiding Judge'), ('ass-jud', 'Associate Judge'), ('ass-c-jud', 'Associate Chief Judge'), ('ass-pres-jud', 'Associate Presiding Judge'), ('jud', 'Judge'), ('jus', 'Justice'), ('c-jud', 'Chief Judge'), ('c-jus', 'Chief Justice'), ('c-spec-m', 'Chief Special Master'), ('pres-jud', 'Presiding Judge'), ('pres-jus', 'Presiding Justice'), ('com', 'Commissioner'), ('com-dep', 'Deputy Commissioner'), ('jud-pt', 'Judge Pro Tem'), ('jus-pt', 'Justice Pro Tem'), ('ref-jud-tr', 'Judge Trial Referee'), ('ref-off', 'Official Referee'), ('ref-state-trial', 'State Trial Referee'), ('ret-act-jus', 'Active Retired Justice'), ('ret-ass-jud', 'Retired Associate Judge'), ('ret-c-jud', 'Retired Chief Judge'), ('ret-jus', 'Retired Justice'), ('ret-senior-jud', 'Senior Judge'), ('mag', 'Magistrate'), ('c-mag', 'Chief Magistrate'), ('pres-mag', 'Presiding Magistrate'), ('mag-pt', 'Magistrate Pro Tem'), ('mag-rc', 'Magistrate (Recalled)'), ('mag-part-time', 'Magistrate (Part-Time)'), ('spec-chair', 'Special Chairman'), ('spec-jud', 'Special Judge'), ('spec-m', 'Special Master'), ('spec-scjcbc', 'Special Superior Court Judge for Complex Business Cases'), ('chair', 'Chairman'), ('chan', 'Chancellor'), ('presi-jud', 'President'), ('res-jud', 'Reserve Judge'), ('trial-jud', 'Trial Judge'), ('vice-chan', 'Vice Chancellor'), ('vice-cj', 'Vice Chief Judge'))), ('Attorney General', (('att-gen', 'Attorney General'), ('att-gen-ass', 'Assistant Attorney General'), ('att-gen-ass-spec', 'Special Assistant Attorney General'), ('sen-counsel', 'Senior Counsel'), ('dep-sol-gen', 'Deputy Solicitor General'))), ('Appointing Authority', (('pres', 'President of the United States'), ('gov', 'Governor'))), ('Clerkships', (('clerk', 'Clerk'), ('clerk-chief-dep', 'Chief Deputy Clerk'), ('staff-atty', 'Staff Attorney'))), ('prof', 'Professor'), ('prac', 'Practitioner'), ('pros', 'Prosecutor'), ('pub-def', 'Public Defender'), ('legis', 'Legislator')], help_text='If this is a judicial position, this indicates the role the person had. This field may be blank if job_title is complete instead.', max_length=20, null=True)),
                ('job_title', models.CharField(blank=True, help_text="If title isn't in position_type, a free-text position may be entered here.", max_length=100)),
                ('sector', models.SmallIntegerField(blank=True, choices=[(1, 'Private sector'), (2, 'Public sector')], default=None, help_text='Whether the job was private or public sector.', null=True)),
                ('organization_name', models.CharField(blank=True, help_text='If the organization where this position was held is not a school or court, this is the place it was held.', max_length=120, null=True)),
                ('location_city', models.CharField(blank=True, help_text='If not a court or school, the city where person worked.', max_length=50)),
                ('location_state', localflavor.us.models.USStateField(blank=True, help_text='If not a court or school, the state where person worked.', max_length=2)),
                ('date_nominated', models.DateField(blank=True, db_index=True, help_text='The date recorded in the Senate Executive Journal when a federal judge was nominated for their position or the date a state judge nominated by the legislature. When a nomination is by primary election, this is the date of the election. When a nomination is from a merit commission, this is the date the nomination was announced.', null=True)),
                ('date_elected', models.DateField(blank=True, db_index=True, help_text='Judges are elected in most states. This is the date of theirfirst election. This field will be null if the judge was initially selected by nomination.', null=True)),
                ('date_recess_appointment', models.DateField(blank=True, db_index=True, help_text='If a judge was appointed while congress was in recess, this is the date of that appointment.', null=True)),
                ('date_referred_to_judicial_committee', models.DateField(blank=True, db_index=True, help_text='Federal judges are usually referred to the Judicial Committee before being nominated. This is the date of that referral.', null=True)),
                ('date_judicial_committee_action', models.DateField(blank=True, db_index=True, help_text='The date that the Judicial Committee took action on the referral.', null=True)),
                ('judicial_committee_action', models.CharField(blank=True, choices=[('no_rep', 'Not Reported'), ('rep_w_rec', 'Reported with Recommendation'), ('rep_wo_rec', 'Reported without Recommendation'), ('rec_postpone', 'Recommendation Postponed'), ('rec_bad', 'Recommended Unfavorably')], help_text='The action that the judicial committee took in response to a nomination', max_length=20)),
                ('date_hearing', models.DateField(blank=True, db_index=True, help_text='After being nominated, a judge is usually subject to a hearing. This is the date of that hearing.', null=True)),
                ('date_confirmation', models.DateField(blank=True, db_index=True, help_text='After the hearing the senate will vote on judges. This is the date of that vote.', null=True)),
                ('date_start', models.DateField(blank=True, db_index=True, help_text='The date the position starts active duty.', null=True)),
                ('date_granularity_start', models.CharField(blank=True, choices=[('%Y', 'Year'), ('%Y-%m', 'Month'), ('%Y-%m-%d', 'Day')], max_length=15)),
                ('date_termination', models.DateField(blank=True, db_index=True, help_text='The last date of their employment. The compliment to date_start', null=True)),
                ('termination_reason', models.CharField(blank=True, choices=[('ded', 'Death'), ('retire_vol', 'Voluntary Retirement'), ('retire_mand', 'Mandatory Retirement'), ('resign', 'Resigned'), ('other_pos', 'Appointed to Other Judgeship'), ('lost', 'Lost Election'), ('abolished', 'Court Abolished'), ('bad_judge', 'Impeached and Convicted'), ('recess_not_confirmed', 'Recess Appointment Not Confirmed'), ('termed_out', 'Term Limit Reached')], help_text='The reason for a termination', max_length=25)),
                ('date_granularity_termination', models.CharField(blank=True, choices=[('%Y', 'Year'), ('%Y-%m', 'Month'), ('%Y-%m-%d', 'Day')], max_length=15)),
                ('date_retirement', models.DateField(blank=True, db_index=True, help_text='The date when they become a senior judge by going into active retirement', null=True)),
                ('nomination_process', models.CharField(blank=True, choices=[('fed_senate', 'U.S. Senate'), ('state_senate', 'State Senate'), ('election', 'Primary Election'), ('merit_comm', 'Merit Commission')], help_text='The process by which a person was nominated into this position.', max_length=20)),
                ('vote_type', models.CharField(blank=True, choices=[('s', 'Senate'), ('p', 'Partisan Election'), ('np', 'Non-Partisan Election')], help_text='The type of vote that resulted in this position.', max_length=2)),
                ('voice_vote', models.BooleanField(blank=True, help_text='Whether the Senate voted by voice vote for this position.', null=True)),
                ('votes_yes', models.PositiveIntegerField(blank=True, help_text='If votes are an integer, this is the number of votes in favor of a position.', null=True)),
                ('votes_no', models.PositiveIntegerField(blank=True, help_text='If votes are an integer, this is the number of votes opposed to a position.', null=True)),
                ('votes_yes_percent', models.FloatField(blank=True, help_text='If votes are a percentage, this is the percentage of votes in favor of a position.', null=True)),
                ('votes_no_percent', models.FloatField(blank=True, help_text='If votes are a percentage, this is the percentage of votes opposed to a position.', null=True)),
                ('how_selected', models.CharField(blank=True, choices=[('Election', (('e_part', 'Partisan Election'), ('e_non_part', 'Non-Partisan Election'))), ('Appointment', (('a_pres', 'Appointment (President)'), ('a_gov', 'Appointment (Governor)'), ('a_legis', 'Appointment (Legislature)'), ('a_judge', 'Appointment (Judge)')))], help_text='The method that was used for selecting this judge for this position (generally an election or appointment).', max_length=20)),
                ('has_inferred_values', models.BooleanField(default=False, help_text='Some or all of the values for this position were inferred from a data source instead of manually added. See sources field for more details.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(choices=[('w', 'White'), ('b', 'Black or African American'), ('i', 'American Indian or Alaska Native'), ('a', 'Asian'), ('p', 'Native Hawaiian or Other Pacific Islander'), ('h', 'Hispanic/Latino')], max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetentionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('retention_type', models.CharField(choices=[('reapp_gov', 'Governor Reappointment'), ('reapp_leg', 'Legislative Reappointment'), ('elec_p', 'Partisan Election'), ('elec_n', 'Nonpartisan Election'), ('elec_u', 'Uncontested Election')], help_text='The method through which this position was retained.', max_length=10)),
                ('date_retention', models.DateField(db_index=True, help_text='The date of retention')),
                ('votes_yes', models.PositiveIntegerField(blank=True, help_text='If votes are an integer, this is the number of votes in favor of a position.', null=True)),
                ('votes_no', models.PositiveIntegerField(blank=True, help_text='If votes are an integer, this is the number of votes opposed to a position.', null=True)),
                ('votes_yes_percent', models.FloatField(blank=True, help_text='If votes are a percentage, this is the percentage of votes in favor of a position.', null=True)),
                ('votes_no_percent', models.FloatField(blank=True, help_text='If votes are a percentage, this is the percentage of votes opposed to a position.', null=True)),
                ('unopposed', models.BooleanField(blank=True, help_text='Whether the position was unopposed at the time of retention.', null=True)),
                ('won', models.BooleanField(blank=True, help_text='Whether the retention event was won.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('url', models.URLField(blank=True, help_text='The URL where this data was gathered.', max_length=2000)),
                ('date_accessed', models.DateField(blank=True, help_text='The date the data was gathered.', null=True)),
                ('notes', models.TextField(blank=True, help_text="Any additional notes about the data's provenance, in Markdown format.")),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='people_db.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('name', models.CharField(db_index=True, help_text='The name of the school or alias', max_length=120)),
                ('ein', models.IntegerField(blank=True, db_index=True, help_text='The EIN assigned by the IRS', null=True)),
                ('is_alias_of', models.ForeignKey(blank=True, help_text='Any alternate names that a school may have', null=True, on_delete=django.db.models.deletion.CASCADE, to='people_db.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.SmallIntegerField(choices=[(1, 'Attorney to be noticed'), (2, 'Lead attorney'), (3, 'Attorney in sealed group'), (4, 'Pro hac vice'), (5, 'Self-terminated'), (6, 'Terminated'), (7, 'Suspended'), (8, 'Inactive'), (9, 'Disbarred'), (10, 'Unknown')], db_index=True, help_text="The name of the attorney's role. Used primarily in district court cases.", null=True)),
                ('role_raw', models.TextField(blank=True, help_text='The raw value of the role, as a string. Items prior to 2018-06-06 may not have this value.')),
                ('date_action', models.DateField(help_text='The date the attorney was disbarred, suspended, terminated...', null=True)),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='people_db.attorney')),
            ],
        ),
    ]
