# Generated by Django 3.1.14 on 2022-02-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_db', '0005_auto_20210922_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='religion',
            field=models.CharField(blank=True, choices=[('ca', 'Catholic'), ('pr', 'Protestant'), ('je', 'Jewish'), ('mu', 'Muslim'), ('at', 'Atheist'), ('ag', 'Agnostic'), ('mo', 'Mormon'), ('bu', 'Buddhist'), ('hi', 'Hindu')], help_text='The religion of a person', max_length=30),
        ),
    ]
