# Generated by Django 3.2.12 on 2022-04-05 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_add_parenthetical_groups'),
        ('people_db', '0008_auto_20220309_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.ForeignKey(help_text='The school where this education was completed', on_delete=django.db.models.deletion.RESTRICT, related_name='educations', to='people_db.school'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_alias_of',
            field=models.ForeignKey(blank=True, help_text='Any nicknames or other aliases that a person has. For example, William Jefferson Clinton has an alias to Bill', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliases', to='people_db.person'),
        ),
        migrations.AlterField(
            model_name='position',
            name='appointer',
            field=models.ForeignKey(blank=True, help_text='If this is an appointed position, the person-position responsible for the appointment. This field references other positions instead of referencing people because that allows you to know the position a person held when an appointment was made.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='appointed_positions', to='people_db.position'),
        ),
        migrations.AlterField(
            model_name='position',
            name='court',
            field=models.ForeignKey(blank=True, help_text='If this was a judicial position, this is the jurisdiction where it was held.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='court_positions', to='search.court'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_type',
            field=models.CharField(blank=True, choices=[('Judge', (('jud', 'Judge'), ('jus', 'Justice'), ('ad-law-jud', 'Administrative Law Judge'), ('act-jud', 'Acting Judge'), ('act-jus', 'Acting Justice'), ('act-pres-jud', 'Acting Presiding Judge'), ('ass-jud', 'Associate Judge'), ('ass-jus', 'Associate Justice'), ('ass-c-jud', 'Associate Chief Judge'), ('ass-pres-jud', 'Associate Presiding Judge'), ('asst-pres-jud', 'Assistant Presiding Judge'), ('c-jud', 'Chief Judge'), ('c-jus', 'Chief Justice'), ('c-spec-m', 'Chief Special Master'), ('pres-jud', 'Presiding Judge'), ('pres-jus', 'Presiding Justice'), ('sup-jud', 'Supervising Judge'), ('ad-pres-jus', 'Administrative Presiding Justice'), ('com', 'Commissioner'), ('com-dep', 'Deputy Commissioner'), ('jud-pt', 'Judge Pro Tem'), ('jus-pt', 'Justice Pro Tem'), ('ref-jud-tr', 'Judge Trial Referee'), ('ref-off', 'Official Referee'), ('ref-state-trial', 'State Trial Referee'), ('ret-act-jus', 'Active Retired Justice'), ('ret-ass-jud', 'Retired Associate Judge'), ('ret-c-jud', 'Retired Chief Judge'), ('ret-jus', 'Retired Justice'), ('ret-senior-jud', 'Senior Judge'), ('mag', 'Magistrate'), ('c-mag', 'Chief Magistrate'), ('pres-mag', 'Presiding Magistrate'), ('mag-pt', 'Magistrate Pro Tem'), ('mag-rc', 'Magistrate (Recalled)'), ('mag-part-time', 'Magistrate (Part-Time)'), ('spec-chair', 'Special Chairman'), ('spec-jud', 'Special Judge'), ('spec-m', 'Special Master'), ('spec-scjcbc', 'Special Superior Court Judge for Complex Business Cases'), ('chair', 'Chairman'), ('chan', 'Chancellor'), ('presi-jud', 'President'), ('res-jud', 'Reserve Judge'), ('trial-jud', 'Trial Judge'), ('vice-chan', 'Vice Chancellor'), ('vice-cj', 'Vice Chief Judge'))), ('Attorney General', (('att-gen', 'Attorney General'), ('att-gen-ass', 'Assistant Attorney General'), ('att-gen-ass-spec', 'Special Assistant Attorney General'), ('sen-counsel', 'Senior Counsel'), ('dep-sol-gen', 'Deputy Solicitor General'))), ('Appointing Authority', (('pres', 'President of the United States'), ('gov', 'Governor'))), ('Clerkships', (('clerk', 'Clerk'), ('clerk-chief-dep', 'Chief Deputy Clerk'), ('staff-atty', 'Staff Attorney'))), ('prof', 'Professor'), ('prac', 'Practitioner'), ('pros', 'Prosecutor'), ('pub-def', 'Public Defender'), ('legis', 'Legislator')], help_text='If this is a judicial position, this indicates the role the person had. This field may be blank if job_title is complete instead.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='predecessor',
            field=models.ForeignKey(blank=True, help_text='The person that previously held this position', null=True, on_delete=django.db.models.deletion.RESTRICT, to='people_db.person'),
        ),
        migrations.AlterField(
            model_name='position',
            name='school',
            field=models.ForeignKey(blank=True, help_text='If this was an academic job, this is the school where the person worked.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='people_db.school'),
        ),
        migrations.AlterField(
            model_name='position',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='If this is a clerkship, the supervising judge.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='supervised_positions', to='people_db.person'),
        ),
        migrations.AlterField(
            model_name='school',
            name='is_alias_of',
            field=models.ForeignKey(blank=True, help_text='Any alternate names that a school may have', null=True, on_delete=django.db.models.deletion.SET_NULL, to='people_db.school'),
        ),
    ]
