# Generated by Django 3.2.12 on 2022-04-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_db', '0009_fix_on_delete_add_acting_justice_noop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalaffiliation',
            name='political_party',
            field=models.CharField(choices=[('d', 'Democratic'), ('r', 'Republican'), ('i', 'Independent'), ('g', 'Green'), ('l', 'Libertarian'), ('f', 'Federalist'), ('w', 'Whig'), ('j', 'Jeffersonian Republican'), ('u', 'National Union'), ('z', 'Reform Party')], help_text='The political party the person is affiliated with.', max_length=5),
        ),
    ]
