# Generated by Django 3.2.13 on 2022-05-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people_db', '0012_add_position_types_noop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='cl_id',
        ),
    ]
