# Generated by Django 5.1.8 on 2025-10-16 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_db', '0020_alter_person_religion_alter_personevent_religion_and_more'),
        ('search', '0044_add_statedocumet_model_and_state_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('agent_name', models.CharField(blank=True, help_text='Name of the agent.', max_length=100)),
                ('authorization_date', models.DateTimeField(blank=True, help_text='Date the agent was authorized.', null=True)),
                ('revocation_date', models.DateTimeField(blank=True, help_text='Date the authorization was revoked.', null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorized_agents', to='people_db.person')),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_agents', to='people_db.attorney')),
                ('docket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_agents', to='search.docket')),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorized_agents', to='people_db.party')),
            ],
            options={
                'unique_together': {('docket', 'attorney', 'agent_name')},
            },
        ),
    ]
