# Generated by Django 6.0.5 on 2026-07-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_db', '0020_alter_person_religion_alter_personevent_religion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='pro_se_flag',
            field=models.BooleanField(default=False, help_text='Whether the party is representing themselves (pro se).'),
        ),
    ]
