# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-19 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_db', '0039_add_role_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partytype',
            name='name',
            field=models.CharField(db_index=True, help_text=b'The name of the type (Defendant, Plaintiff, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='politicalaffiliation',
            name='political_party',
            field=models.CharField(choices=[(b'd', b'Democratic'), (b'r', b'Republican'), (b'i', b'Independent'), (b'g', b'Green'), (b'l', b'Libertarian'), (b'f', b'Federalist'), (b'w', b'Whig'), (b'j', b'Jeffersonian Republican'), (b'u', b'National Union')], help_text=b'The political party the person is affiliated with.', max_length=5),
        ),
    ]
