# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-19 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people_db', '0040_auto_20190719_1539'),
        ('people_db', '0040_update_field_descriptions'),
    ]

    operations = [
    ]
