# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-25 00:02


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_db', '0041_merge_20190819_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='extra_info',
            field=models.TextField(db_index=True, help_text=b'Prior to March, 2018, this field briefly held additional info from PACER about particular parties. That was a modelling mistake and the information has been moved to the PartyType.extra_info field instead. This field will eventually be removed.'),
        ),
    ]
