BEGIN;
--
-- Alter field date_granularity_start on position
--
--The following two lines don't accomplish anything but are auto-generated by Django's migration system.
--ALTER TABLE "people_db_position" ALTER COLUMN "date_granularity_start" SET DEFAULT '';
--ALTER TABLE "people_db_position" ALTER COLUMN "date_granularity_start" DROP DEFAULT;
COMMIT;
