# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-24 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people_db', '0046_abstract_datetime_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdisclosure',
            name='person',
        ),
        migrations.DeleteModel(
            name='FinancialDisclosure',
        ),
    ]
