# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-25 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disclosures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='date',
            new_name='date_raw',
        ),
        migrations.RenameField(
            model_name='noninvestmentincome',
            old_name='date',
            new_name='date_raw',
        ),
        migrations.RenameField(
            model_name='reimbursement',
            old_name='dates',
            new_name='date_raw',
        ),
        migrations.RenameField(
            model_name='spouseincome',
            old_name='date',
            new_name='date_raw',
        ),
        migrations.AlterField(
            model_name='agreement',
            name='redacted',
            field=models.BooleanField(default=False, help_text='Does the agreement row contain redaction(s)?'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='redacted',
            field=models.BooleanField(default=False, help_text='Does the debt row contain redaction(s)?'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='value_code',
            field=models.CharField(blank=True, choices=[('J', '1 - 15,000'), ('K', '15,001 - 50,000'), ('L', '50,001 - 100,000'), ('M', '100,001 - 250,000'), ('N', '250,001 - 500,000'), ('O', '500,001 - 1,000,000'), ('P1', '1,000,001 - 5,000,000'), ('P2', '5,000,001 - 25,000,000'), ('P3', '25,000,001 - 50,000,000'), ('P4', '50,000,001 - '), ('-1', 'Failed Extraction')], help_text='Form code for the value of the judicial debt.', max_length=5),
        ),
        migrations.AlterField(
            model_name='financialdisclosure',
            name='is_amended',
            field=models.NullBooleanField(default=False, help_text='Is disclosure amended?'),
        ),
        migrations.AlterField(
            model_name='financialdisclosure',
            name='report_type',
            field=models.SmallIntegerField(choices=[(-1, 'Unknown Report'), (0, 'Nomination Report'), (1, 'Initial Report'), (2, 'Annual Report'), (3, 'Final Report')], default=-1, help_text='Financial Disclosure report type'),
        ),
        migrations.AlterField(
            model_name='financialdisclosure',
            name='sha1',
            field=models.CharField(blank=True, db_index=True, help_text='SHA1 hash of the generated PDF', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='value_code',
            field=models.CharField(blank=True, choices=[('J', '1 - 15,000'), ('K', '15,001 - 50,000'), ('L', '50,001 - 100,000'), ('M', '100,001 - 250,000'), ('N', '250,001 - 500,000'), ('O', '500,001 - 1,000,000'), ('P1', '1,000,001 - 5,000,000'), ('P2', '5,000,001 - 25,000,000'), ('P3', '25,000,001 - 50,000,000'), ('P4', '50,000,001 - '), ('-1', 'Failed Extraction')], help_text='Value of the judicial gift, (ex. A)', max_length=5),
        ),
        migrations.AlterField(
            model_name='investment',
            name='gross_value_code',
            field=models.CharField(blank=True, choices=[('J', '1 - 15,000'), ('K', '15,001 - 50,000'), ('L', '50,001 - 100,000'), ('M', '100,001 - 250,000'), ('N', '250,001 - 500,000'), ('O', '500,001 - 1,000,000'), ('P1', '1,000,001 - 5,000,000'), ('P2', '5,000,001 - 25,000,000'), ('P3', '25,000,001 - 50,000,000'), ('P4', '50,000,001 - '), ('-1', 'Failed Extraction')], help_text='Investment total value code at end of reporting period as code (ex. J (1-15,000)).', max_length=5),
        ),
        migrations.AlterField(
            model_name='investment',
            name='gross_value_method',
            field=models.CharField(blank=True, choices=[('Q', 'Appraisal'), ('R', 'Cost (Real Estate Only)'), ('S', 'Assessment'), ('T', 'Cash Market'), ('U', 'Book Value'), ('V', 'Other'), ('-1', 'Failed Extraction')], help_text='Investment valuation method code (ex. Q = Appraisal)', max_length=5),
        ),
        migrations.AlterField(
            model_name='investment',
            name='income_during_reporting_period_code',
            field=models.CharField(blank=True, choices=[('A', '1 - 1,000'), ('B', '1,001 - 2,500'), ('C', '2,501 - 5,000'), ('D', '5,001 - 15,000'), ('E', '15,001 - 50,000'), ('F', '50,001 - 100,000'), ('G', '100,001 - 1,000,000'), ('H1', '1,000,001 - 5,000,000'), ('H2', '5,000,001 +'), ('-1', 'Failed Extraction')], help_text='Increase in investment value - as a form code', max_length=5),
        ),
        migrations.AlterField(
            model_name='investment',
            name='redacted',
            field=models.BooleanField(default=False, help_text='Does the investment row contains redaction(s)?'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='transaction_gain_code',
            field=models.CharField(blank=True, choices=[('A', '1 - 1,000'), ('B', '1,001 - 2,500'), ('C', '2,501 - 5,000'), ('D', '5,001 - 15,000'), ('E', '15,001 - 50,000'), ('F', '50,001 - 100,000'), ('G', '100,001 - 1,000,000'), ('H1', '1,000,001 - 5,000,000'), ('H2', '5,000,001 +'), ('-1', 'Failed Extraction')], help_text='Gain from investment transaction if any (ex. A (1-1000)).', max_length=5),
        ),
        migrations.AlterField(
            model_name='investment',
            name='transaction_value_code',
            field=models.CharField(blank=True, choices=[('J', '1 - 15,000'), ('K', '15,001 - 50,000'), ('L', '50,001 - 100,000'), ('M', '100,001 - 250,000'), ('N', '250,001 - 500,000'), ('O', '500,001 - 1,000,000'), ('P1', '1,000,001 - 5,000,000'), ('P2', '5,000,001 - 25,000,000'), ('P3', '25,000,001 - 50,000,000'), ('P4', '50,000,001 - '), ('-1', 'Failed Extraction')], help_text='Transaction value amount, as form code (ex. J (1-15,000)).', max_length=5),
        ),
        migrations.AlterField(
            model_name='noninvestmentincome',
            name='income_amount',
            field=models.TextField(blank=True, help_text="Amount earned by judge, often a number, but sometimes with explanatory text (e.g. 'Income at firm: $xyz')."),
        ),
        migrations.AlterField(
            model_name='noninvestmentincome',
            name='redacted',
            field=models.BooleanField(default=False, help_text='Does the non-investment income row contain redaction(s)?'),
        ),
        migrations.AlterField(
            model_name='position',
            name='financial_disclosure',
            field=models.ForeignKey(help_text='The financial disclosure associated with this financial position.', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='disclosures.FinancialDisclosure'),
        ),
        migrations.AlterField(
            model_name='position',
            name='redacted',
            field=models.BooleanField(default=False, help_text='Does the position row contain redaction(s)?'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='redacted',
            field=models.BooleanField(default=False, help_text='Does the reimbursement contain redaction(s)?'),
        ),
        migrations.AlterField(
            model_name='spouseincome',
            name='redacted',
            field=models.TextField(default=False, help_text='Does the spousal-income row contain redaction(s)?'),
        ),
    ]
