# Generated by Django 3.2.18 on 2023-03-16 02:45

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disclosures', '0002_add_event_tables_and_triggers'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='agreement',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='agreement',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='debt',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='debt',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='financialdisclosure',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='financialdisclosure',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='gift',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='gift',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='investment',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='investment',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='noninvestmentincome',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='noninvestmentincome',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='position',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='position',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='reimbursement',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='reimbursement',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='spouseincome',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='spouseincome',
            name='snapshot_update',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='agreement',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "disclosures_agreementevent" ("date_created", "date_modified", "date_raw", "financial_disclosure_id", "id", "parties_and_terms", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "redacted") VALUES (NEW."date_created", NEW."date_modified", NEW."date_raw", NEW."financial_disclosure_id", NEW."id", NEW."parties_and_terms", _pgh_attach_context(), NOW(), \'custom_snapshot\', NEW."id", NEW."redacted"); RETURN NULL;', hash='5a56075dfa625b635cf1505cf84f296aac00f975', operation='INSERT', pgid='pgtrigger_custom_snapshot_insert_060c9', table='disclosures_agreement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='agreement',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "disclosures_agreementevent" ("date_created", "date_modified", "date_raw", "financial_disclosure_id", "id", "parties_and_terms", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "redacted") VALUES (OLD."date_created", OLD."date_modified", OLD."date_raw", OLD."financial_disclosure_id", OLD."id", OLD."parties_and_terms", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."id", OLD."redacted"); RETURN NULL;', hash='e555ba91dbb5564616a341f7e72e25a862527c3a', operation='UPDATE', pgid='pgtrigger_custom_snapshot_update_02c65', table='disclosures_agreement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='debt',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "disclosures_debtevent" ("creditor_name", "date_created", "date_modified", "description", "financial_disclosure_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "redacted", "value_code") VALUES (NEW."creditor_name", NEW."date_created", NEW."date_modified", NEW."description", NEW."financial_disclosure_id", NEW."id", _pgh_attach_context(), NOW(), \'custom_snapshot\', NEW."id", NEW."redacted", NEW."value_code"); RETURN NULL;', hash='50ba25bba13d9876582a93009d7a175d32e96c8d', operation='INSERT', pgid='pgtrigger_custom_snapshot_insert_a3213', table='disclosures_debt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='debt',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "disclosures_debtevent" ("creditor_name", "date_created", "date_modified", "description", "financial_disclosure_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "redacted", "value_code") VALUES (OLD."creditor_name", OLD."date_created", OLD."date_modified", OLD."description", OLD."financial_disclosure_id", OLD."id", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."id", OLD."redacted", OLD."value_code"); RETURN NULL;', hash='f6a4e4405feb43218cb2decfe6554aec653b6152', operation='UPDATE', pgid='pgtrigger_custom_snapshot_update_3bd4e', table='disclosures_debt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='financialdisclosure',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "disclosures_financialdisclosureevent" ("addendum_content_raw", "addendum_redacted", "date_created", "date_modified", "download_filepath", "filepath", "has_been_extracted", "id", "is_amended", "page_count", "person_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "report_type", "sha1", "thumbnail", "thumbnail_status", "year") VALUES (NEW."addendum_content_raw", NEW."addendum_redacted", NEW."date_created", NEW."date_modified", NEW."download_filepath", NEW."filepath", NEW."has_been_extracted", NEW."id", NEW."is_amended", NEW."page_count", NEW."person_id", _pgh_attach_context(), NOW(), \'custom_snapshot\', NEW."id", NEW."report_type", NEW."sha1", NEW."thumbnail", NEW."thumbnail_status", NEW."year"); RETURN NULL;', hash='afde16c3f6debcf10296d9c820b9b63b6c0cc64c', operation='INSERT', pgid='pgtrigger_custom_snapshot_insert_c180d', table='disclosures_financialdisclosure', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='financialdisclosure',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "disclosures_financialdisclosureevent" ("addendum_content_raw", "addendum_redacted", "date_created", "date_modified", "download_filepath", "filepath", "has_been_extracted", "id", "is_amended", "page_count", "person_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "report_type", "sha1", "thumbnail", "thumbnail_status", "year") VALUES (OLD."addendum_content_raw", OLD."addendum_redacted", OLD."date_created", OLD."date_modified", OLD."download_filepath", OLD."filepath", OLD."has_been_extracted", OLD."id", OLD."is_amended", OLD."page_count", OLD."person_id", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."id", OLD."report_type", OLD."sha1", OLD."thumbnail", OLD."thumbnail_status", OLD."year"); RETURN NULL;', hash='b1ba35407a8f5e96c7124e06625755d19b1c3ef7', operation='UPDATE', pgid='pgtrigger_custom_snapshot_update_d66d5', table='disclosures_financialdisclosure', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gift',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "disclosures_giftevent" ("date_created", "date_modified", "description", "financial_disclosure_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "redacted", "source", "value") VALUES (NEW."date_created", NEW."date_modified", NEW."description", NEW."financial_disclosure_id", NEW."id", _pgh_attach_context(), NOW(), \'custom_snapshot\', NEW."id", NEW."redacted", NEW."source", NEW."value"); RETURN NULL;', hash='74897c41d509d4dd727dee4b1171dea5e5463839', operation='INSERT', pgid='pgtrigger_custom_snapshot_insert_7be22', table='disclosures_gift', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gift',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "disclosures_giftevent" ("date_created", "date_modified", "description", "financial_disclosure_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "redacted", "source", "value") VALUES (OLD."date_created", OLD."date_modified", OLD."description", OLD."financial_disclosure_id", OLD."id", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."id", OLD."redacted", OLD."source", OLD."value"); RETURN NULL;', hash='f017aeea4e1ee8d02eaf46115d4697a02a95c62a', operation='UPDATE', pgid='pgtrigger_custom_snapshot_update_a8157', table='disclosures_gift', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='investment',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "disclosures_investmentevent" ("date_created", "date_modified", "description", "financial_disclosure_id", "gross_value_code", "gross_value_method", "has_inferred_values", "id", "income_during_reporting_period_code", "income_during_reporting_period_type", "page_number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "redacted", "transaction_date", "transaction_date_raw", "transaction_during_reporting_period", "transaction_gain_code", "transaction_partner", "transaction_value_code") VALUES (NEW."date_created", NEW."date_modified", NEW."description", NEW."financial_disclosure_id", NEW."gross_value_code", NEW."gross_value_method", NEW."has_inferred_values", NEW."id", NEW."income_during_reporting_period_code", NEW."income_during_reporting_period_type", NEW."page_number", _pgh_attach_context(), NOW(), \'custom_snapshot\', NEW."id", NEW."redacted", NEW."transaction_date", NEW."transaction_date_raw", NEW."transaction_during_reporting_period", NEW."transaction_gain_code", NEW."transaction_partner", NEW."transaction_value_code"); RETURN NULL;', hash='8e5f8db7fc234680557bf9fe6a17a56b2ae2bd22', operation='INSERT', pgid='pgtrigger_custom_snapshot_insert_0a550', table='disclosures_investment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='investment',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "disclosures_investmentevent" ("date_created", "date_modified", "description", "financial_disclosure_id", "gross_value_code", "gross_value_method", "has_inferred_values", "id", "income_during_reporting_period_code", "income_during_reporting_period_type", "page_number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "redacted", "transaction_date", "transaction_date_raw", "transaction_during_reporting_period", "transaction_gain_code", "transaction_partner", "transaction_value_code") VALUES (OLD."date_created", OLD."date_modified", OLD."description", OLD."financial_disclosure_id", OLD."gross_value_code", OLD."gross_value_method", OLD."has_inferred_values", OLD."id", OLD."income_during_reporting_period_code", OLD."income_during_reporting_period_type", OLD."page_number", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."id", OLD."redacted", OLD."transaction_date", OLD."transaction_date_raw", OLD."transaction_during_reporting_period", OLD."transaction_gain_code", OLD."transaction_partner", OLD."transaction_value_code"); RETURN NULL;', hash='099292bc3958706d7bf0b19dfc76a831e31005c8', operation='UPDATE', pgid='pgtrigger_custom_snapshot_update_440ee', table='disclosures_investment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='noninvestmentincome',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "disclosures_noninvestmentincomeevent" ("date_created", "date_modified", "date_raw", "financial_disclosure_id", "id", "income_amount", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "redacted", "source_type") VALUES (NEW."date_created", NEW."date_modified", NEW."date_raw", NEW."financial_disclosure_id", NEW."id", NEW."income_amount", _pgh_attach_context(), NOW(), \'custom_snapshot\', NEW."id", NEW."redacted", NEW."source_type"); RETURN NULL;', hash='5652c43b0f4326cc8eeaaecc0ba9c7f4475fc23f', operation='INSERT', pgid='pgtrigger_custom_snapshot_insert_1b22e', table='disclosures_noninvestmentincome', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='noninvestmentincome',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "disclosures_noninvestmentincomeevent" ("date_created", "date_modified", "date_raw", "financial_disclosure_id", "id", "income_amount", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "redacted", "source_type") VALUES (OLD."date_created", OLD."date_modified", OLD."date_raw", OLD."financial_disclosure_id", OLD."id", OLD."income_amount", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."id", OLD."redacted", OLD."source_type"); RETURN NULL;', hash='12efe25e6d0a0d6281f71402b9b555aaed80d010', operation='UPDATE', pgid='pgtrigger_custom_snapshot_update_4adf3', table='disclosures_noninvestmentincome', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='position',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "disclosures_positionevent" ("date_created", "date_modified", "financial_disclosure_id", "id", "organization_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "position", "redacted") VALUES (NEW."date_created", NEW."date_modified", NEW."financial_disclosure_id", NEW."id", NEW."organization_name", _pgh_attach_context(), NOW(), \'custom_snapshot\', NEW."id", NEW."position", NEW."redacted"); RETURN NULL;', hash='5b3891591301d5379823fd701bab97256b037a1d', operation='INSERT', pgid='pgtrigger_custom_snapshot_insert_9ebfd', table='disclosures_position', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='position',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "disclosures_positionevent" ("date_created", "date_modified", "financial_disclosure_id", "id", "organization_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "position", "redacted") VALUES (OLD."date_created", OLD."date_modified", OLD."financial_disclosure_id", OLD."id", OLD."organization_name", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."id", OLD."position", OLD."redacted"); RETURN NULL;', hash='ef7e5702222b17b1826f252778014a1307e3e0fd', operation='UPDATE', pgid='pgtrigger_custom_snapshot_update_908be', table='disclosures_position', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reimbursement',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "disclosures_reimbursementevent" ("date_created", "date_modified", "date_raw", "financial_disclosure_id", "id", "items_paid_or_provided", "location", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "purpose", "redacted", "source") VALUES (NEW."date_created", NEW."date_modified", NEW."date_raw", NEW."financial_disclosure_id", NEW."id", NEW."items_paid_or_provided", NEW."location", _pgh_attach_context(), NOW(), \'custom_snapshot\', NEW."id", NEW."purpose", NEW."redacted", NEW."source"); RETURN NULL;', hash='3fbd7e2f16f7123f4a3fed1d52ec9beb59a49445', operation='INSERT', pgid='pgtrigger_custom_snapshot_insert_40cd8', table='disclosures_reimbursement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reimbursement',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "disclosures_reimbursementevent" ("date_created", "date_modified", "date_raw", "financial_disclosure_id", "id", "items_paid_or_provided", "location", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "purpose", "redacted", "source") VALUES (OLD."date_created", OLD."date_modified", OLD."date_raw", OLD."financial_disclosure_id", OLD."id", OLD."items_paid_or_provided", OLD."location", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."id", OLD."purpose", OLD."redacted", OLD."source"); RETURN NULL;', hash='bb7f98ee839fe9ec3c4f198b6ef0954e262aded1', operation='UPDATE', pgid='pgtrigger_custom_snapshot_update_fa704', table='disclosures_reimbursement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='spouseincome',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "disclosures_spouseincomeevent" ("date_created", "date_modified", "date_raw", "financial_disclosure_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "redacted", "source_type") VALUES (NEW."date_created", NEW."date_modified", NEW."date_raw", NEW."financial_disclosure_id", NEW."id", _pgh_attach_context(), NOW(), \'custom_snapshot\', NEW."id", NEW."redacted", NEW."source_type"); RETURN NULL;', hash='8f53becb619a5e28ff44938ef5af871d5f861de5', operation='INSERT', pgid='pgtrigger_custom_snapshot_insert_01662', table='disclosures_spouseincome', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='spouseincome',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "disclosures_spouseincomeevent" ("date_created", "date_modified", "date_raw", "financial_disclosure_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "redacted", "source_type") VALUES (OLD."date_created", OLD."date_modified", OLD."date_raw", OLD."financial_disclosure_id", OLD."id", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."id", OLD."redacted", OLD."source_type"); RETURN NULL;', hash='8824cee8d1676381ff1bd348f578b57bfde27050', operation='UPDATE', pgid='pgtrigger_custom_snapshot_update_049d4', table='disclosures_spouseincome', when='AFTER')),
        ),
    ]
