# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-29 22:08
from __future__ import unicode_literals

import cl.lib.model_helpers
import cl.lib.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disclosures', '0003_auto_20201228_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdisclosure',
            name='thumbnail',
            field=models.FileField(blank=True, help_text='A thumbnail of the first page of the disclosure form.', null=True, storage=cl.lib.storage.AWSMediaStorage(), upload_to=cl.lib.model_helpers.make_financial_disclosure_thumbnail_path),
        ),
    ]
