# Generated by Django 3.1.7 on 2021-03-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disclosures', '0004_alter_gross_value_method_noop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spouseincome',
            name='redacted',
            field=models.BooleanField(default=False, help_text='Does the spousal-income row contain redaction(s)?'),
        ),
    ]
