fd_pairs = (
    ('D(\.|:|(istrict))?,? (court )?(of )?Colu(m|(in))bia', 'dcd'),
    ('M(\.|(iddle))? ?D(\.|:|(istrict)),? ?(of )?Alabama', 'almd'),
    ('N(\.|(orthern))? ?D(\.|:|(istrict)),? ?(of )?Alabama', 'alnd'),
    ('S(\.|(outhern))? ?D(\.|:|(istrict)),? ?(of )?Alabama', 'alsd'),
    ('Alaska', 'akd'),
    ('D(\.|:|(istrict))? ?(of )?Arizona', 'azd'),
    ('E(\.|(astern))? ?D(\.|:|(istrict)),? ?(of )?Arkansas', 'ared'),
    ('W(\.|(estern))? ?D(\.|:|(istrict)),? ?(of )?Arkansas', 'arwd'),
    ('C(\.|(entral))? ?D(\.|:|(istrict)),? ?(of )?Cal(ifornia)?', 'cacd'),
    ('N(\.|(orthern))? ?D(\.|:|(istrict)),? ?(of )?Cal(ifornia)?', 'cand'),
    ('S(\.|(outhern))? ?D(\.|:|(istrict)),? ?(of )?Cal(ifornia)?', 'casd'),
    # No longer exists. Existed 1866-07-27 to 1886-08-05
    ('D(\.|:|(istrict))? ?(of )?California', 'californiad'), # Must go last for Cal.
    ('D(\.|:|(istrict))? ?(of )?Colo(rado)?', 'cod'),
    ('D(\.|:|(istrict))? ?(of )?Conn', 'ctd'),
    ('D(\.|:|(istrict))? ?(of )?Delaware', 'ded'),
    ('M(\.|(iddle))? ?D(\.|:|(istrict)),? ?(of )?Fl(orid)?a', 'flmd'),
    ('N(\.|(orthern))? ?D(\.|:|(istrict)),? ?(of )?Fl(orid)?a', 'flnd'),
    ('S(\.|(outhern))? ?D(\.|:|(istrict)),? ?(of )?Fl(orid)?a', 'flsd'),
    ('M(\.|(iddle))? ?D(\.|:|(istrict)),? ?(of )?G(a|(eorgia))', 'gamd'),
    ('N(\.|(orthern))? ?D(\.|:|(istrict)),? ?(of )?G(a|(eorgia))', 'gand'),
    ('S(\.|(outhern))? ?D(\.|:|(istrict)),? ?(of )?G(a|(eorgia))', 'gasd'),
    ('Hawai', 'hid'),
    ('D(\.|:|(istrict))? ?(of )?Idaho', 'idd'),
    ('C(\.|(entral))? ?D(\.|:|(istrict))?,? ?(of )?Ill(inois)?', 'ilcd'),
    ('N(\.|(orthern))? ?D(\.|:|(istrict))?,? ?(of )?Ill(inois)?', 'ilnd'),
    ('S(\.|(outhern))? ?D(\.|:|(istrict)),? ?(of )?Illinois', 'ilsd'),
    # Abolished. 1905-03-03 to 1978-10-02
    ('E(\.|(astern))? ?D(\.|:|(istrict)),? ?(of )?Illinois', 'illinoised'),
    # Abolished. 1819-03-03 to 1855-02-13
    ('D(\.|:|(istrict))? ?(of )?Illinois', 'illinoisd'), # Must go last
    ('N(\.|(orthern))? ?D(\.|:|(istrict))?,? ?(of )?Indiana', 'innd'),
    ('S(\.|(outhern))? ?D(\.|:|(istrict))?,? ?(of )?Indiana', 'insd'),
    # Abolished. 1817-03-03 to 1928-04-21
    ('D(\.|:|(istrict))? ?(of )?Indiana', 'indianad'), # Must go last
    ('N(\.|(orthern))? ?D(\.|:|(istrict)),? ?(of )?Iowa', 'iand'),
    ('S(\.|(outhern))? ?D(\.|:|(istrict))?,? ?(of )?Iowa', 'iasd'),
    ('Kansas', 'ksd'),
    ('E(\.|(astern))? ?D(\.|:|(istrict)),? ?(of )?Kentucky', 'kyed'),
    ('W(\.|(estern))? ?D(\.|:|(istrict)),? ?(of )?Kentucky', 'kywd'),
    ('E(\.|(astern))? ?D(\.|:|(istrict)),? ?(of )?Louisiana', 'laed'),
    ('Eastern District, Louisiana', 'laed'),
    ('M(\.|(iddle))? ?D(\.|:|(istrict)),? ?(of )?Louisiana', 'lamd'),
    ('W(\.|(estern))? ?D(\.|:|(istrict)),? ?(of )?Louisiana', 'lawd'),
    ('D(\.|:|(istrict))? ?(of )?Maine', 'med'),
    ('D(\.|(istrict))? ?(of )?Maryland', 'mdd'),
        (', Maryland', 'mdd'),
        ('Maryland Admiralty', 'mdd'),
    ('D?\.? ?(of )?Mass(achusetts)?', 'mad'),
    ('E(\.|(astern))? ?D(\.|:|(istrict))?,? ?(of )?Michigan', 'mied'),
    ('W(\.|(estern))? ?D(\.|:|(istrict))?,? ?(of )?Michigan', 'miwd'),
    ('D(\.|:|(istrict))? ?(of )?Minnesota', 'mnd'),
    ('N(\.|(orthern))? ?D(\.|:|(istrict)),? ?(of )?Mississippi', 'msnd'),
    ('S(\.|(outhern))? ?D(\.|:|(istrict)),? ?(of )?Mississippi', 'mssd'),
    ('C(\.|(entral))? ?D(\.|:|(istrict)),? ?(of )?Missouri', 'mocd'),
    ('E(\.|(astern))? ?D(\.|(istrict))?,? ?(of )?(the )?Missouri', 'moed'),
    ('W(\.|(estern))? ?D(\.|:|(istrict)),? ?(of )?Missouri', 'mowd'),
        ('Missouri, W\.D', 'mowd'),
    ('D(\.|:|(istrict))? ?(of )?Montana', 'mtd'),
    ('D(\.|(istrict))? ?(of )?Nebraska', 'ned'),
    ('D(\.|:|(istrict))? ?(of )?Nevada', 'nvd'),
    ('D(\.|:|(istrict))? ?(of )?New Hampshire', 'nhd'),
    ('New Jersey', 'njd'),
    ('D(\.|:|(istrict))? ?(of )?New Mexico', 'nmd'),
    ('E(\.|(astern))? ?D(\.|(istrict)),? ?(of )?N(\.|(ew)) ?Y(ork)?', 'nyed'),
    ('N(\.|(orthern))? ?D(\.|:|(istrict))?,? ?(of )?N(\.|(ew)) ?Y(ork)?', 'nynd'),
    ('S(\.|(outhern))? ?D(\.|:|(istrict))?,? ?(of )?N(\.|(ew)) ?Y(ork)?', 'nysd'),
    ('W(\.|(estern))? ?D(\.|:|(istrict))?,? ?(of )?N(\.|(ew)) ?Y(ork)?', 'nywd'),
    ('E(\.|(astern))? ?D(\.|:|(istrict)),? ?(of )?North Carolina', 'nced'),
    ('M(\.|(iddle))? ?D(\.|:|(istrict)),? ?(of )?North Carolina', 'ncmd'),
    ('Greensboro Division', 'ncmd'),
    ('W(\.|(estern))? ?D(\.|:|(istrict)),? ?(of )?North Carolina', 'ncwd'),
    ('North Dakota', 'ndd'),
    ('N(\.|(orthern))? ?D(\.|:|(istrict)),? ?(of )?Ohio', 'ohnd'),
    ('S(\.|(outhern))? ?D(\.|:|(istrict)),? ?(of )?Ohio', 'ohsd'),
    # Abolished. 1803-02-19 to 1855-02-10
    ('D(\.|:|(istrict))? ?(of )?Ohio', 'ohiod'), # Must be the last court!
    ('E(\.|(astern))? ?D(\.|:|(istrict)),? ?(of )?Oklahoma', 'oked'),
    ('N(\.|(orthern))? ?D(\.|:|(istrict)),? ?(of )?Oklahoma', 'oknd'),
    ('W(\.|(estern))? ?D(\.|:|(istrict)),? ?(of )?Oklahoma', 'okwd'),
    ('D(\.|:|(istrict))? ?(of )?Oregon', 'ord'),
    ('E(\.|(astern))? ?D(\.|:|(istrict)),? ?(of )?P(a|(ennsylvania))', 'paed'),
    ('M(\.|(iddle))? ?D(\.|(ist\.))?,? ?(of )?P(a|(ennsylvania))', 'pamd'),
    ('W(\.|(estern))? ?D(\.|:|(istrict)),? ?(of )?P(a|(ennsylvania))', 'pawd'),
    # Abolished. 1789-09-24 to 1818-04-20
    ('D(\.|:|(istrict))? ?(of )?P(a|(ennsylvania))', 'pennsylvaniad'), # Must go last
    ('Rhode Island', 'rid'),
    # Abolished. 1823-02-21 to 1965-10-07
    ('E(\.|(astern))? ?D(\.|:|(istrict)),? ?(of )?South Carolina', 'southcarolinaed'),
    # Abolished. 1823-02-21 to 1965-10-07
    ('W(\.|(estern))? ?D(\.|:|(istrict)),? ?(of )?South Carolina', 'southcarolinawd'),
    ('D(\.|:|(istrict))? ?(of )?South Carolina', 'scd'), # Must go last!
    ('South Dakota', 'sdd'),
    ('E(\.|(astern))? ?D(\.|:|(istrict)),? ?(of )?Tennessee', 'tned'),
    ('M(\.|(iddle))? ?D(\.|(istrict))?,? ?(of )?Tennessee', 'tnmd'),
    ('W(\.|(estern))? ?D(\.|:|(istrict)),? ?(of )?Tennessee', 'tnwd'),
    # Abolished. 1797-01-31 to 1839-06-18
    ('D(\.|(istrict))? ?(of )?Tennessee', 'tennessed'), # Must be the last court!
    ('E(\.|(astern))? ?D(\.|:|(istrict)),? ?(of )?Texas', 'txed'),
    ('N(\.|(orthern))? ?D(\.|:|(istrict)),? ?(of )?Texas', 'txnd'),
    ('S(\.|(outhern))? ?D(\.|(istrict)),? ?(of )?Texas', 'txsd'),
    ('W(\.|(estern))? ?D(\.|:|(istrict))?,? ?(of )?Texas', 'txwd'),
        ('Midland/Odessa', 'txwd'),
    ('Utah', 'utd'),
    ('Vermont', 'vtd'),
    ('E(\.|(astern))? ?D(\.|:|(istrict))?,? ?(of )?Virginia', 'vaed'),
    ('W(\.|(estern))? ?D(\.|:|(istrict)),? ?(of )?Virginia', 'vawd'),
        ('Abingdon', 'vawd'),
        ('Big Stone Gap', 'vawd'),
    ('E(\.|(astern))? ?D(\.|:|(istrict)),? ?(of )?Wash(ington)?', 'waed'),
    ('W(\.|(estern))? ?D(\.|:|(istrict)),? ?(of )?Wash(ington)?', 'wawd'),
    ('N(\.|(orthern))? ?D(\.|:|(istrict)),? ?(of )?W(\.|(est)) V(a|(irginia))', 'wvnd'),
    ('S(\.|(outhern))? ?D(\.|:|(istrict)),? ?(of )?W(\.|(est)) V(a|(irginia))', 'wvsd'),
    ('West Virginia, at Charleston', 'wvsd'),
    ('E(\.|(astern))? ?D(\.|:|(istrict)),? ?(of )?Wisconsin', 'wied'),
        ('D\. Wisconsin, E\. D', 'wied'),
    ('W(\.|(estern))? ?D(\.|:|(istrict)),? ?(of )?Wisconsin', 'wiwd'),
    ('Wyoming', 'wyd'),
    # Abolished. 1937-07-26 to 1982-03-31
    ('Canal Zone', 'canalzoned'),
    ('Guam', 'gud'),
    ('Northern Mariana', 'nmid'),
    ('Puerto Rico', 'prd'),
    ('Virgin Islands', 'vid'),
)
