# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-25 17:42
from __future__ import unicode_literals

import cl.lib.models
import cl.lib.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSONFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text=b'The time when this item was created')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text=b'The last moment when the item was modified.')),
                ('filepath', models.FileField(help_text=b'The path of the original json file.', max_length=150, storage=cl.lib.storage.UUIDFileSystemStorage(), upload_to=cl.lib.models.make_json_data_path)),
                ('upload_type', models.SmallIntegerField(choices=[(1, b'HTML Docket'), (2, b'HTML attachment page'), (3, b'PDF')], help_text=b'The type of object that is uploaded')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
