# Generated by Django 5.1.2 on 2024-11-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapers", "0003_delete_errorlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="MVLatestOpinion",
            fields=[
                (
                    "court_id",
                    models.TextField(primary_key=True, serialize=False),
                ),
                ("latest_creation_date", models.DateTimeField()),
                ("time_since", models.TextField()),
                ("view_last_updated", models.DateTimeField()),
            ],
            options={
                "db_table": "scrapers_mv_latest_opinion",
                "managed": False,
            },
        ),
        migrations.RunSQL("""
        CREATE MATERIALIZED VIEW IF NOT EXISTS
            scrapers_mv_latest_opinion
        AS
        (
        SELECT
            court_id,
            max(so.date_created) as latest_creation_date,
            DATE_TRUNC('minutes', (now() - max(so.date_created)))::text as time_since,
            now() as view_last_updated
        FROM
            (
                SELECT id, court_id
                FROM search_docket
                WHERE court_id IN (
                    SELECT id
                    FROM search_court
                    /*
                        Only check courts with scrapers in use
                    */
                    WHERE
                        has_opinion_scraper
                        AND in_use
                )
            ) sd
        INNER JOIN
            (SELECT id, docket_id FROM search_opinioncluster) soc ON soc.docket_id = sd.id
        INNER JOIN
            search_opinion so ON so.cluster_id = soc.id
        GROUP BY
            sd.court_id
        HAVING
            /*
                Only return results for courts with no updates in a week
            */
            now() - max(so.date_created) > interval '7 days'
        ORDER BY
            2 DESC
        )
        """)
    ]
