# Generated by Django 6.0.2 on 2026-04-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0005_alter_mvlatestopinion_options_noop'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('scraper', models.IntegerField(choices=[(1, 'TAMES CaseMail')], help_text='The scraper/site the account is for.')),
                ('email', models.EmailField(help_text='The email address for the account.', max_length=254)),
                ('user_name', models.CharField(help_text='The username of the account.', max_length=30)),
                ('first_subscription', models.DateField(help_text='The date of the first subscription.')),
                ('last_subscription', models.DateField(help_text='The date of the last subscription.')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scraper', 'user_name'), name='unique_scraper_user_name')],
            },
        ),
    ]
