# Generated by Django 6.0.5 on 2026-08-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0007_optimize_mv_latest_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacerfreedocumentlog',
            name='parsed_document_count',
            field=models.PositiveIntegerField(blank=True, help_text='The number of rows we parsed out of the Written Opinions report for this scrape. Lower than the reported count means the parser silently dropped rows. Null means unknown (the scrape failed or predates this field).', null=True),
        ),
        migrations.AddField(
            model_name='pacerfreedocumentlog',
            name='reported_document_count',
            field=models.PositiveIntegerField(blank=True, help_text="The number of opinions PACER's Written Opinions report said it had for this scrape ('Total number of opinions reported', summed over every page queried). Null means unknown (the scrape failed or predates this field).", null=True),
        ),
        migrations.AddField(
            model_name='pacerfreedocumentlog',
            name='saved_document_count',
            field=models.PositiveIntegerField(blank=True, help_text='The number of parsed rows we saved for ingestion from this scrape. Lower than the parsed count means rows were skipped as unusable, e.g. missing a docket number. Null means unknown (the scrape failed or predates this field).', null=True),
        ),
    ]
