# Generated by Django 6.0.2 on 2026-07-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrapers", "0007_optimize_mv_latest_opinion"),
    ]

    operations = [
        migrations.AddField(
            model_name="pacerfreedocumentrow",
            name="download_attempts",
            field=models.PositiveIntegerField(
                default=0,
                help_text="How many runs have ended with a terminal "
                "download failure for this row after exhausting in-task "
                "retries.",
            ),
        ),
        migrations.AddField(
            model_name="pacerfreedocumentrow",
            name="last_attempt",
            field=models.DateTimeField(
                blank=True,
                help_text="When this row's PDF download last failed "
                "terminally.",
                null=True,
            ),
        ),
    ]
