# Generated by Django 3.1.7 on 2021-11-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recap', '0003_auto_20210908_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailprocessingqueue',
            name='destination_emails',
            field=models.JSONField(default=list, help_text='The emails that received the notification.'),
        ),
    ]
