BEGIN;
--
-- Alter field court on emailprocessingqueue
--
--
-- Alter field uploader on emailprocessingqueue
--
--
-- Alter field circuit on fjcintegrateddatabase
--
--
-- Alter field district on fjcintegrateddatabase
--
--
-- Alter field court on pacerfetchqueue
--
--
-- Alter field docket on pacerfetchqueue
--
--
-- Alter field recap_document on pacerfetchqueue
--
--
-- Alter field user on pacerfetchqueue
--
--
-- Alter field court on processingqueue
--
--
-- Alter field docket on processingqueue
--
--
-- Alter field docket_entry on processingqueue
--
--
-- Alter field recap_document on processingqueue
--
--
-- Alter field uploader on processingqueue
--
COMMIT;
