# Generated by Django 4.2.4 on 2023-10-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "recap",
            "0012_rename_fjcintegrateddatabase_district_docket_number_recap_fjcin_distric_731c7b_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="processingqueue",
            name="acms_document_guid",
            field=models.CharField(
                blank=True,
                help_text="The GUID of the document in ACMS.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="pacerhtmlfiles",
            name="upload_type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "HTML Docket"),
                    (2, "HTML attachment page"),
                    (3, "PDF"),
                    (4, "Docket history report"),
                    (5, "Appellate HTML docket"),
                    (6, "Appellate HTML attachment page"),
                    (7, "Internet Archive XML docket"),
                    (8, "Case report (iquery.pl) page"),
                    (9, "Claims register page"),
                    (10, "Zip archive of RECAP Documents"),
                    (11, "Email in the SES storage format"),
                    (12, "Case query page"),
                    (13, "Appellate Case query page"),
                    (14, "Case query result page"),
                    (15, "Appellate Case query result page"),
                    (16, "ACMS docket JSON object"),
                ],
                help_text="The type of object that is uploaded",
            ),
        ),
        migrations.AlterField(
            model_name="processingqueue",
            name="pacer_case_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The case ID provided by PACER.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="processingqueue",
            name="pacer_doc_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The ID of the document in PACER.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="processingqueue",
            name="upload_type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "HTML Docket"),
                    (2, "HTML attachment page"),
                    (3, "PDF"),
                    (4, "Docket history report"),
                    (5, "Appellate HTML docket"),
                    (6, "Appellate HTML attachment page"),
                    (7, "Internet Archive XML docket"),
                    (8, "Case report (iquery.pl) page"),
                    (9, "Claims register page"),
                    (10, "Zip archive of RECAP Documents"),
                    (11, "Email in the SES storage format"),
                    (12, "Case query page"),
                    (13, "Appellate Case query page"),
                    (14, "Case query result page"),
                    (15, "Appellate Case query result page"),
                    (16, "ACMS docket JSON object"),
                ],
                help_text="The type of object that is uploaded",
            ),
        ),
        migrations.AddIndex(
            model_name="processingqueue",
            index=models.Index(
                fields=["acms_document_guid"],
                name="recap_proce_acms_do_2e7cae_idx",
            ),
        ),
    ]
