# Generated by Django 4.2.7 on 2023-11-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "recap",
            "0012_rename_fjcintegrateddatabase_district_docket_number_recap_fjcin_distric_731c7b_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="processingqueue",
            name="document_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The docket entry number for the document.",
                max_length=32,
            ),
            preserve_default=False,
        ),
    ]
