# Generated by Django 6.0.2 on 2026-03-27 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('recap', '0015_alter_pacerhtmlfiles_upload_type_noop'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailprocessingqueue',
            name='object_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='emailprocessingqueue',
            name='related_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='emailprocessingqueue',
            name='source',
            field=models.SmallIntegerField(choices=[(1, 'PACER email notification.'), (2, 'SCOTUS email notification.'), (3, 'State email notification.')], default=1, help_text='The source of this email notification.'),
        ),
    ]
