# Generated by Django 6.0.2 on 2026-03-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recap', '0015_alter_pacerhtmlfiles_upload_type_noop'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailprocessingqueue',
            name='source',
            field=models.SmallIntegerField(choices=[(1, 'PACER email notification.'), (2, 'SCOTUS email notification.'), (3, 'State email notification.')], default=1, help_text='The source of this email notification.'),
        ),
    ]
