# Generated by Django 6.0.2 on 2026-02-20 17:35

import cl.lib.storage
import cl.recap.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recap', '0015_alter_pacerhtmlfiles_upload_type_noop'),
        ('search', '0053_tx_scotus_url_length_and_case_transfer_docket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailprocessingqueue',
            name='source',
            field=models.SmallIntegerField(choices=[(1, 'PACER email notification.'), (2, 'SCOTUS email notification.'), (3, 'State email notification.')], db_comment='The source of this email notification.', default=1, help_text='The source of this email notification.'),
        ),
        migrations.AlterField(
            model_name='emailprocessingqueue',
            name='court',
            field=models.ForeignKey(db_comment='The court where the upload was from.', help_text='The court where the upload was from.', on_delete=django.db.models.deletion.RESTRICT, related_name='recap_email_processing_queue', to='search.court'),
        ),
        migrations.AlterField(
            model_name='emailprocessingqueue',
            name='destination_emails',
            field=models.JSONField(db_comment='The emails that received the notification.', default=list, help_text='The emails that received the notification.'),
        ),
        migrations.AlterField(
            model_name='emailprocessingqueue',
            name='filepath',
            field=models.FileField(db_comment='The S3 filepath to the email and receipt stored as JSON text.', help_text='The S3 filepath to the email and receipt stored as JSON text.', max_length=300, null=True, storage=cl.lib.storage.IncrementingAWSMediaStorage(), upload_to=cl.recap.models.make_recap_email_processing_queue_aws_path),
        ),
        migrations.AlterField(
            model_name='emailprocessingqueue',
            name='message_id',
            field=models.TextField(db_comment='The S3 message identifier, used to pull the file in the processing tasks.', default=None, help_text='The S3 message identifier, used to pull the file in the processing tasks.'),
        ),
        migrations.AlterField(
            model_name='emailprocessingqueue',
            name='recap_documents',
            field=models.ManyToManyField(related_name='recap_email_processing_queue', to='search.recapdocument'),
        ),
        migrations.AlterField(
            model_name='emailprocessingqueue',
            name='status_message',
            field=models.TextField(blank=True, db_comment='Any errors that occurred while processing an item.', help_text='Any errors that occurred while processing an item.'),
        ),
        migrations.AlterField(
            model_name='emailprocessingqueue',
            name='uploader',
            field=models.ForeignKey(db_comment='The user that sent in the email for processing.', help_text='The user that sent in the email for processing.', on_delete=django.db.models.deletion.RESTRICT, related_name='recap_email_processing_queue', to=settings.AUTH_USER_MODEL),
        ),
    ]
