# Generated by Django 5.1.8 on 2026-01-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recap', '0015_alter_pacerhtmlfiles_upload_type_noop'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailprocessingqueue',
            name='source',
            field=models.SmallIntegerField(choices=[(1, 'PACER email notification.'), (2, 'SCOTUS email notification.')], default=1, help_text='The source from this email notification'),
        ),
    ]
