# Generated by Django 6.0.4 on 2026-06-24 21:29

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('recap', '0016_add_source_object_ids_to_epq'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='pacerhtmlfiles',
            index=models.Index(
                fields=['content_type', 'object_id'],
                name='recap_pacerhtmlfiles_ct_obj_idx',
            ),
        ),
    ]
