# Generated by Django 6.0.5 on 2026-07-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recap', '0017_pacerhtmlfiles_recap_pacerhtmlfiles_ct_obj_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingqueue',
            name='source',
            field=models.SmallIntegerField(choices=[(1, 'Extension or API upload'), (2, 'recap.email'), (3, 'Subdocket replication'), (4, 'Unknown')], default=4, help_text='The source that created this ProcessingQueue instance.'),
        ),
    ]
