# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recap', '0024_idb_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fjcintegrateddatabase',
            name='nature_of_suit',
            field=models.IntegerField(blank=True, choices=[(110, b'110 Insurance'), (120, b'120 Marine contract actions'), (130, b'130 Miller act'), (140, b'140 Negotiable instruments'), (150, b'150 Overpayments & enforcement of judgments'), (151, b'151 Overpayments under the medicare act'), (152, b'152 Recovery of defaulted student loans'), (153, b'153 Recovery of overpayments of vet benefits'), (160, b"160 Stockholder's suits"), (190, b'190 Other contract actions'), (195, b'195 Contract product liability'), (196, b'196 Contract franchise'), (210, b'210 Land condemnation'), (220, b'220 Foreclosure'), (230, b'230 Rent, lease, ejectment'), (240, b'240 Torts to land'), (245, b'245 Tort product liability'), (290, b'290 Other real property actions'), (310, b'310 Airplane personal injury'), (315, b'315 Airplane product liability'), (320, b'320 Assault, libel, and slander'), (330, b"330 Federal employers' liability"), (340, b'340 Marine personal injury'), (345, b'345 Marine - Product liability'), (350, b'350 Motor vehicle personal injury'), (355, b'355 Motor vehicle product liability'), (360, b'360 Other personal liability'), (362, b'362 Medical malpractice'), (365, b'365 Personal injury - Product liability'), (367, b'367 Health care / pharm'), (368, b'368 Asbestos personal injury - Prod. Liab.'), (370, b'370 Other fraud'), (371, b'371 Truth in lending'), (375, b'375 False Claims Act'), (380, b'380 Other personal property damage'), (385, b'385 Property damage - Product liability'), (400, b'400 State re-appointment'), (410, b'410 Antitrust'), (422, b'422 Bankruptcy appeals rule 28 USC 158'), (423, b'423 Bankruptcy withdrawal 28 USC 157'), (430, b'430 Banks and banking'), (440, b'440 Civil rights other'), (441, b'441 Civil rights voting'), (442, b'442 Civil rights jobs'), (443, b'443 Civil rights accomodations'), (444, b'444 Civil rights welfare'), (445, b'445 Civil rights ADA employment'), (446, b'446 Civil rights ADA other'), (448, b'448 Education'), (450, b'450 Interstate commerce'), (460, b'460 Deportation'), (462, b'462 Naturalization, petition for hearing of denial'), (463, b'463 Habeas corpus - alien detainee'), (465, b'465 Other immigration actions'), (470, b'470 Civil (RICO)'), (480, b'480 Consumer credit'), (490, b'490 Cable/Satellite TV'), (510, b'510 Prisoner petitions - vacate sentence'), (530, b'530 Prisoner petitions - habeas corpus'), (535, b'535 Habeas corpus: Death penalty'), (540, b'540 Prisoner petitions - mandamus and other'), (550, b'550 Prisoner - civil rights'), (555, b'555 Prisoner - prison condition'), (560, b'560 Civil detainee'), (610, b'610 Agricultural acts'), (620, b'620 Food and drug acts'), (625, b'625 Drug related seizure of property'), (630, b'630 Liquor laws'), (640, b'640 Railroad and trucks'), (650, b'650 Airline regulations'), (660, b'660 Occupational safety/health'), (690, b'690 Other forfeiture and penalty suits'), (710, b'710 Fair Labor Standards Act'), (720, b'720 Labor/Management Relations Act'), (730, b'730 Labor/Management report & disclosure'), (740, b'740 Railway Labor Act'), (751, b'751 Family and Medical Leave Act'), (790, b'790 Other labor litigation'), (791, b'791 Employee Retirement Income Security Act'), (810, b'810 Selective service'), (820, b'820 Copyright'), (830, b'830 Patent'), (840, b'840 Trademark'), (850, b'850 Securities, Commodities, Exchange'), (860, b'860 Social security'), (861, b'861 HIA (1395 FF) / Medicare'), (862, b'862 Black lung'), (863, b'863 D.I.W.C. / D.I.W.W.'), (864, b'864 S.S.I.D.'), (865, b'865 R.S.I.'), (870, b'870 Tax suits'), (871, b'871 IRS 3rd party suits 26 USC 7609'), (875, b'875 Customer challenge 12 USC 3410'), (890, b'890 Other statutory actions'), (891, b'891 Agricultural acts'), (892, b'892 Economic Stabilization Act'), (893, b'893 Environmental matters'), (894, b'894 Energy Allocation Act'), (895, b'895 Freedom of Information Act of 1974'), (896, b'896 Arbitration'), (899, b'899 Administrative procedure act / review or appeal of agency decision'), (900, b'900 Appeal of fee - equal access to justice'), (910, b'910 Domestic relations'), (920, b'920 Insanity'), (930, b'930 Probate'), (940, b'940 Substitute trustee'), (950, b'950 Constitutionality of state statutes'), (990, b'990 Other'), (992, b'992 Local jurisdictional appeal'), (999, b'999 Miscellaneous')], help_text=b'A three digit statistical code representing the nature of suit of the action filed.', null=True),
        ),
        migrations.AlterField(
            model_name='fjcintegrateddatabase',
            name='office',
            field=models.CharField(blank=True, help_text=b'The code that designates the office within the district where the case is filed. Must conform with format established in Volume XI, Guide to Judiciary Policies and Procedures, Appendix A. See: https://free.law/idb-facts/', max_length=3),
        ),
        migrations.AlterField(
            model_name='fjcintegrateddatabase',
            name='origin',
            field=models.SmallIntegerField(blank=True, choices=[(1, b'Original Proceeding'), (2, b'Removed  (began in the state court, removed to the district court)'), (3, b'Remanded for further action (removal from court of appeals)'), (4, b'Reinstated/reopened (previously opened and closed, reopened for additional action)'), (5, b'Transferred from another district(pursuant to 28 USC 1404)'), (6, b'Multi district litigation (cases transferred to this district by an order entered by Judicial Panel on Multi District Litigation pursuant to 28 USC 1407)'), (7, b"Appeal to a district judge of a magistrate judge's decision"), (8, b'Second reopen'), (9, b'Third reopen'), (10, b'Fourth reopen'), (11, b'Fifth reopen'), (12, b'Sixth reopen'), (13, b'Multi district litigation originating in the district (valid beginning July 1, 2016)')], help_text=b'A single digit code describing the manner in which the case was filed in the district.', null=True),
        ),
        migrations.AlterField(
            model_name='fjcintegrateddatabase',
            name='transfer_docket_number',
            field=models.TextField(blank=True, help_text=b'The docket number of the case in the losing district'),
        ),
    ]
