# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-20 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recap', '0025_update_field_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacerhtmlfiles',
            name='upload_type',
            field=models.SmallIntegerField(choices=[(1, b'HTML Docket'), (2, b'HTML attachment page'), (3, b'PDF'), (4, b'Docket history report'), (5, b'Appellate HTML docket'), (6, b'Appellate HTML attachment page'), (7, b'Internet Archive XML docket'), (8, b'Case report (iquery.pl) page'), (9, b'Claims register page')], help_text=b'The type of object that is uploaded'),
        ),
        migrations.AlterField(
            model_name='processingqueue',
            name='upload_type',
            field=models.SmallIntegerField(choices=[(1, b'HTML Docket'), (2, b'HTML attachment page'), (3, b'PDF'), (4, b'Docket history report'), (5, b'Appellate HTML docket'), (6, b'Appellate HTML attachment page'), (7, b'Internet Archive XML docket'), (8, b'Case report (iquery.pl) page'), (9, b'Claims register page')], help_text=b'The type of object that is uploaded'),
        ),
    ]
