# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-05 22:54


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recap', '0028_add_zip_filetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacerfetchqueue',
            name='request_type',
            field=models.SmallIntegerField(choices=[(1, 'HTML Docket'), (2, 'PDF'), (3, 'Attachment Page')], help_text='The type of object that is requested'),
        ),
        migrations.AlterField(
            model_name='pacerfetchqueue',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Awaiting processing in queue.'), (2, 'Item processed successfully.'), (3, 'Item encountered an error while processing.'), (4, 'Item is currently being processed.'), (5, 'Item failed processing, but will be retried.'), (6, 'Item failed validity tests.'), (7, 'There was insufficient metadata to complete the task.')], db_index=True, default=1, help_text='The current status of this request. Possible values are: (1): Awaiting processing in queue., (2): Item processed successfully., (3): Item encountered an error while processing., (4): Item is currently being processed., (5): Item failed processing, but will be retried., (6): Item failed validity tests., (7): There was insufficient metadata to complete the task.'),
        ),
        migrations.AlterField(
            model_name='processingqueue',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Awaiting processing in queue.'), (2, 'Item processed successfully.'), (3, 'Item encountered an error while processing.'), (4, 'Item is currently being processed.'), (5, 'Item failed processing, but will be retried.'), (6, 'Item failed validity tests.'), (7, 'There was insufficient metadata to complete the task.')], db_index=True, default=1, help_text='The current status of this upload. Possible values are: (1): Awaiting processing in queue., (2): Item processed successfully., (3): Item encountered an error while processing., (4): Item is currently being processed., (5): Item failed processing, but will be retried., (6): Item failed validity tests., (7): There was insufficient metadata to complete the task.'),
        ),
    ]
