# Generated by Django 3.1.7 on 2021-05-25 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('event_type', models.IntegerField(choices=[(1, 'RECAP Email received'), (2, 'Alert triggered')], help_text='The event type that triggers the webhook.')),
                ('url', models.URLField(help_text='The URL that receives a POST request from the webhook.', max_length=2000)),
                ('enabled', models.BooleanField(default=False, help_text='An on/off switch for the webhook.')),
                ('webhook_version', models.IntegerField(default=1, help_text='The specific version of the webhook provisioned.')),
                ('failure_count', models.IntegerField(default=0, help_text='The number of failures (400+ status) responses the webhook has received.')),
                ('user', models.ForeignKey(help_text='The user that has provisioned the webhook.', on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('status_code', models.IntegerField(help_text='The HTTP status code received when the webhook event was created.')),
                ('content', models.JSONField(help_text='The content of the outgoing body in the POST request.')),
                ('response', models.TextField(help_text='The response received from the POST request.')),
                ('webhook', models.ForeignKey(help_text='The Webhook this event is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='api.webhook')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
