# Generated by Django 3.2.13 on 2022-07-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tweak_status_code_noop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Docket Alert'), (2, 'Search Alert'), (3, 'Recap Fetch')], help_text='The event type that triggers the webhook.'),
        ),
    ]
