# Generated by Django 3.2.16 on 2022-11-14 19:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_webhook_event_types_noop'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='debug',
            field=models.BooleanField(default=False, help_text='Enabled if this is a test event for debugging purposes.'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='error_message',
            field=models.TextField(blank=True, help_text='The error raised by a failed POST request.'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='event_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique event identifier'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='event_status',
            field=models.SmallIntegerField(choices=[(0, 'Delivery in progress'), (1, 'Enqueued for retry'), (2, 'Delivered successfully'), (3, 'Failed')], default=0, help_text='The webhook event status.'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='next_retry_date',
            field=models.DateTimeField(blank=True, help_text='The scheduled datetime to retry the webhook event.', null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='retry_counter',
            field=models.SmallIntegerField(default=0, help_text='The retry counter for the exponential backoff event.'),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='content',
            field=models.JSONField(blank=True, help_text='The content of the outgoing body in the POST request.', null=True),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='response',
            field=models.TextField(blank=True, help_text='The response received from the POST request.'),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='status_code',
            field=models.SmallIntegerField(blank=True, choices=[(100, 'Continue'), (101, 'Switching Protocols'), (102, 'Processing'), (103, 'Early Hints'), (200, 'Ok'), (201, 'Created'), (202, 'Accepted'), (203, 'Non Authoritative Information'), (204, 'No Content'), (205, 'Reset Content'), (206, 'Partial Content'), (207, 'Multi Status'), (208, 'Already Reported'), (226, 'Im Used'), (300, 'Multiple Choices'), (301, 'Moved Permanently'), (302, 'Found'), (303, 'See Other'), (304, 'Not Modified'), (305, 'Use Proxy'), (307, 'Temporary Redirect'), (308, 'Permanent Redirect'), (400, 'Bad Request'), (401, 'Unauthorized'), (402, 'Payment Required'), (403, 'Forbidden'), (404, 'Not Found'), (405, 'Method Not Allowed'), (406, 'Not Acceptable'), (407, 'Proxy Authentication Required'), (408, 'Request Timeout'), (409, 'Conflict'), (410, 'Gone'), (411, 'Length Required'), (412, 'Precondition Failed'), (413, 'Request Entity Too Large'), (414, 'Request Uri Too Long'), (415, 'Unsupported Media Type'), (416, 'Requested Range Not Satisfiable'), (417, 'Expectation Failed'), (418, 'Im A Teapot'), (421, 'Misdirected Request'), (422, 'Unprocessable Entity'), (423, 'Locked'), (424, 'Failed Dependency'), (425, 'Too Early'), (426, 'Upgrade Required'), (428, 'Precondition Required'), (429, 'Too Many Requests'), (431, 'Request Header Fields Too Large'), (451, 'Unavailable For Legal Reasons'), (500, 'Internal Server Error'), (501, 'Not Implemented'), (502, 'Bad Gateway'), (503, 'Service Unavailable'), (504, 'Gateway Timeout'), (505, 'Http Version Not Supported'), (506, 'Variant Also Negotiates'), (507, 'Insufficient Storage'), (508, 'Loop Detected'), (510, 'Not Extended'), (511, 'Network Authentication Required')], help_text='The HTTP status code received from the POST request.', null=True),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['next_retry_date', 'event_status'], name='api_webhook_next_re_3e78b7_idx'),
        ),
    ]
