# Generated by Django 3.2.16 on 2022-11-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_webhooks_retries'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='debug',
            field=models.BooleanField(default=False, help_text='Enabled if this is a test event for debugging purposes.'),
        ),
    ]
