# Generated by Django 3.2.16 on 2022-11-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_webhooks_retries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookevent',
            name='event_status',
            field=models.SmallIntegerField(choices=[(0, 'Delivery in progress'), (1, 'Enqueued for retry'), (2, 'Delivered successfully'), (3, 'Failed'), (4, 'Endpoint disabled')], default=0, help_text='The webhook event status.'),
        ),
    ]
