# Generated by Django 3.2.16 on 2022-12-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_webhook_url_noop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Docket Alert'), (2, 'Search Alert'), (3, 'Recap Fetch'), (4, 'Old Docket Alerts Report')], help_text='The event type that triggers the webhook.'),
        ),
    ]
