# Generated by Django 3.2.16 on 2023-01-26 00:06

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_webhook_event_type_noop'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='webhook',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "api_webhookevent" ("date_created", "date_modified", "enabled", "event_type", "failure_count", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "url", "user_id", "version") VALUES (NEW."date_created", NEW."date_modified", NEW."enabled", NEW."event_type", NEW."failure_count", NEW."id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."url", NEW."user_id", NEW."version"); RETURN NULL;', hash='a2420e8215cc7e2ed382545cb396ce141e00c1db', operation='INSERT', pgid='pgtrigger_snapshot_insert_81718', table='api_webhook', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='webhook',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "api_webhookevent" ("date_created", "date_modified", "enabled", "event_type", "failure_count", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "url", "user_id", "version") VALUES (NEW."date_created", NEW."date_modified", NEW."enabled", NEW."event_type", NEW."failure_count", NEW."id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."url", NEW."user_id", NEW."version"); RETURN NULL;', hash='7e7e23e049b7f1a61d745a0efd9175d140a5f6cc', operation='UPDATE', pgid='pgtrigger_snapshot_update_980eb', table='api_webhook', when='AFTER')),
        ),
    ]
