# Generated by Django 3.2.18 on 2023-03-16 02:45

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_event_tables_and_triggers'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='webhook',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='webhook',
            name='snapshot_update',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='webhook',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "api_webhookhistoryevent" ("date_created", "date_modified", "enabled", "event_type", "failure_count", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "url", "user_id", "version") VALUES (NEW."date_created", NEW."date_modified", NEW."enabled", NEW."event_type", NEW."failure_count", NEW."id", _pgh_attach_context(), NOW(), \'custom_snapshot\', NEW."id", NEW."url", NEW."user_id", NEW."version"); RETURN NULL;', hash='d1c8c10c49ada99369ce8d2cca614bc0feab6426', operation='INSERT', pgid='pgtrigger_custom_snapshot_insert_c3f55', table='api_webhook', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='webhook',
            trigger=pgtrigger.compiler.Trigger(name='custom_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "api_webhookhistoryevent" ("date_created", "date_modified", "enabled", "event_type", "failure_count", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "url", "user_id", "version") VALUES (OLD."date_created", OLD."date_modified", OLD."enabled", OLD."event_type", OLD."failure_count", OLD."id", _pgh_attach_context(), NOW(), \'custom_snapshot\', OLD."id", OLD."url", OLD."user_id", OLD."version"); RETURN NULL;', hash='6704a4d306024ba09a94c9168faeb046e5bbf0e7', operation='UPDATE', pgid='pgtrigger_custom_snapshot_update_fcc01', table='api_webhook', when='AFTER')),
        ),
    ]
