# Generated by Django 5.0.1 on 2024-02-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "api",
            "0010_remove_webhook_update_or_delete_snapshot_update_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="event_type",
            field=models.IntegerField(
                choices=[
                    (1, "Docket Alert"),
                    (2, "Search Alert"),
                    (3, "Recap Fetch"),
                    (4, "Old Docket Alerts Report"),
                    (5, "Opinion Create"),
                    (6, "Opinion Update"),
                    (7, "Opinion Delete"),
                    (8, "Opinion Cluster Create"),
                    (9, "Opinion Cluster Update"),
                    (10, "Opinion Cluster Delete"),
                ],
                help_text="The event type that triggers the webhook.",
            ),
        ),
        migrations.AlterField(
            model_name="webhookhistoryevent",
            name="event_type",
            field=models.IntegerField(
                choices=[
                    (1, "Docket Alert"),
                    (2, "Search Alert"),
                    (3, "Recap Fetch"),
                    (4, "Old Docket Alerts Report"),
                    (5, "Opinion Create"),
                    (6, "Opinion Update"),
                    (7, "Opinion Delete"),
                    (8, "Opinion Cluster Create"),
                    (9, "Opinion Cluster Update"),
                    (10, "Opinion Cluster Delete"),
                ],
                help_text="The event type that triggers the webhook.",
            ),
        ),
    ]
