# Generated by Django 5.1.2 on 2024-11-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_webhookevent_status_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="version",
            field=models.IntegerField(
                choices=[(1, "v1"), (2, "v2")],
                default=1,
                help_text="The specific version of the webhook provisioned.",
            ),
        ),
        migrations.AlterField(
            model_name="webhookhistoryevent",
            name="version",
            field=models.IntegerField(
                choices=[(1, "v1"), (2, "v2")],
                default=1,
                help_text="The specific version of the webhook provisioned.",
            ),
        ),
    ]
