# Generated by Django 5.1.8 on 2025-10-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_webhook_version_choices_noop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Docket Alert'), (2, 'Search Alert'), (3, 'Recap Fetch'), (4, 'Old Docket Alerts Report'), (5, 'Pray And Pay Alert')], help_text='The event type that triggers the webhook.'),
        ),
        migrations.AlterField(
            model_name='webhookhistoryevent',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Docket Alert'), (2, 'Search Alert'), (3, 'Recap Fetch'), (4, 'Old Docket Alerts Report'), (5, 'Pray And Pay Alert')], help_text='The event type that triggers the webhook.'),
        ),
    ]
