# Generated by Django 6.0.1 on 2026-01-25 23:53

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_webhook_event_type_and_more_noop'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIThrottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('throttle_type', models.SmallIntegerField(choices=[(1, 'API'), (2, 'Citation Lookup')], help_text='The type of throttle being overridden.')),
                ('blocked', models.BooleanField(default=False, help_text='If True, the user is blocked from making requests. Takes precedence over rate.')),
                ('rate', models.CharField(blank=True, help_text="The rate limit (e.g., '100/hour', '1000/day'). Required if not blocked.", max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about why this override exists.')),
                ('user', models.ForeignKey(help_text='The user whose throttle rate is being overridden.', on_delete=django.db.models.deletion.CASCADE, related_name='api_throttles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='APIThrottleEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('throttle_type', models.SmallIntegerField(choices=[(1, 'API'), (2, 'Citation Lookup')], help_text='The type of throttle being overridden.')),
                ('blocked', models.BooleanField(default=False, help_text='If True, the user is blocked from making requests. Takes precedence over rate.')),
                ('rate', models.CharField(blank=True, help_text="The rate limit (e.g., '100/hour', '1000/day'). Required if not blocked.", max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about why this override exists.')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='api.apithrottle')),
                ('user', models.ForeignKey(db_constraint=False, help_text='The user whose throttle rate is being overridden.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='apithrottle',
            constraint=models.UniqueConstraint(fields=('user', 'throttle_type'), name='unique_user_throttle_type'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='apithrottle',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."blocked" IS DISTINCT FROM (NEW."blocked") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."rate" IS DISTINCT FROM (NEW."rate") OR OLD."throttle_type" IS DISTINCT FROM (NEW."throttle_type") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))', func='INSERT INTO "api_apithrottleevent" ("blocked", "date_created", "date_modified", "id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rate", "throttle_type", "user_id") VALUES (OLD."blocked", OLD."date_created", OLD."date_modified", OLD."id", OLD."notes", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."rate", OLD."throttle_type", OLD."user_id"); RETURN NULL;', hash='8a0f036551a9013aa3ade6d4499a90ac6d613a26', operation='UPDATE', pgid='pgtrigger_update_update_9846f', table='api_apithrottle', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='apithrottle',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "api_apithrottleevent" ("blocked", "date_created", "date_modified", "id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rate", "throttle_type", "user_id") VALUES (OLD."blocked", OLD."date_created", OLD."date_modified", OLD."id", OLD."notes", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."rate", OLD."throttle_type", OLD."user_id"); RETURN NULL;', hash='627483e5ba91e09f56fedf4e632536619fa422dc', operation='DELETE', pgid='pgtrigger_delete_delete_3cec8', table='api_apithrottle', when='AFTER')),
        ),
    ]
