BEGIN;
--
-- Create model APIThrottleRate
--
CREATE TABLE "api_apithrottlerate" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date_created" timestamp with time zone NOT NULL, "date_modified" timestamp with time zone NOT NULL, "rate" varchar(20) NOT NULL, "throttle_id" integer NOT NULL);
--
-- Create model APIThrottleRateEvent
--
CREATE TABLE "api_apithrottlerateevent" ("pgh_id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "pgh_created_at" timestamp with time zone NOT NULL, "pgh_label" text NOT NULL, "id" integer NOT NULL, "date_created" timestamp with time zone NOT NULL, "date_modified" timestamp with time zone NOT NULL, "rate" varchar(20) NOT NULL, "pgh_context_id" uuid NULL, "pgh_obj_id" integer NOT NULL, "throttle_id" integer NOT NULL);
--
-- Create constraint unique_throttle_rate on model apithrottlerate
--
ALTER TABLE "api_apithrottlerate" ADD CONSTRAINT "unique_throttle_rate" UNIQUE ("throttle_id", "rate");

ALTER TABLE "api_apithrottlerate" ADD CONSTRAINT "api_apithrottlerate_throttle_id_3db4d0cb_fk_api_apithrottle_id" FOREIGN KEY ("throttle_id") REFERENCES "api_apithrottle" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "api_apithrottlerate_date_created_b57f169c" ON "api_apithrottlerate" ("date_created");
CREATE INDEX "api_apithrottlerate_date_modified_f7b7f099" ON "api_apithrottlerate" ("date_modified");
CREATE INDEX "api_apithrottlerate_throttle_id_3db4d0cb" ON "api_apithrottlerate" ("throttle_id");
CREATE INDEX "api_apithrottlerateevent_pgh_context_id_4f4a3631" ON "api_apithrottlerateevent" ("pgh_context_id");
CREATE INDEX "api_apithrottlerateevent_pgh_obj_id_eb3d1096" ON "api_apithrottlerateevent" ("pgh_obj_id");
CREATE INDEX "api_apithrottlerateevent_throttle_id_a8315549" ON "api_apithrottlerateevent" ("throttle_id");
COMMIT;
