# Generated by Django 6.0.2 on 2026-04-21 12:24

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_api_throttle'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIThrottleRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('rate', models.CharField(help_text="The rate limit (e.g., '5/min', '50/hour', '125/day').", max_length=20)),
                ('throttle', models.ForeignKey(help_text='The parent throttle configuration.', on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='api.apithrottle')),
            ],
        ),
        migrations.CreateModel(
            name='APIThrottleRateEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('rate', models.CharField(help_text="The rate limit (e.g., '5/min', '50/hour', '125/day').", max_length=20)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='api.apithrottlerate')),
                ('throttle', models.ForeignKey(db_constraint=False, help_text='The parent throttle configuration.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='api.apithrottle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='apithrottlerate',
            constraint=models.UniqueConstraint(fields=('throttle', 'rate'), name='unique_throttle_rate'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='apithrottlerate',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."rate" IS DISTINCT FROM (NEW."rate") OR OLD."throttle_id" IS DISTINCT FROM (NEW."throttle_id"))', func='INSERT INTO "api_apithrottlerateevent" ("date_created", "date_modified", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rate", "throttle_id") VALUES (OLD."date_created", OLD."date_modified", OLD."id", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."rate", OLD."throttle_id"); RETURN NULL;', hash='2cbd1c41258bbc18e378da5dc7a932dfc5253b9e', operation='UPDATE', pgid='pgtrigger_update_update_a8eba', table='api_apithrottlerate', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='apithrottlerate',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "api_apithrottlerateevent" ("date_created", "date_modified", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rate", "throttle_id") VALUES (OLD."date_created", OLD."date_modified", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."rate", OLD."throttle_id"); RETURN NULL;', hash='9c4829e0b4cd1c1665f1da10aa0079fed116afd2', operation='DELETE', pgid='pgtrigger_delete_delete_04746', table='api_apithrottlerate', when='AFTER')),
        ),
    ]
