# Generated by Django 6.0.2 on 2026-04-21 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_api_throttle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='apithrottle',
            name='unique_user_throttle_type',
        ),
        migrations.AddConstraint(
            model_name='apithrottle',
            constraint=models.UniqueConstraint(fields=('user', 'throttle_type', 'rate'), name='unique_user_throttle_type_rate'),
        ),
    ]
