# Generated by Django 6.0.2 on 2026-04-26 20:57

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_relax_apithrottle_unique_constraint'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='apithrottle',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='apithrottle',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='apithrottle',
            name='source',
            field=models.SmallIntegerField(choices=[(1, 'Manual'), (2, 'Membership')], default=1, help_text="Where this throttle came from. MANUAL rows are admin overrides and are never touched by Neon webhooks. MEMBERSHIP rows are written by Neon membership-lifecycle handlers and are wiped/replaced when the user's level changes."),
        ),
        migrations.AddField(
            model_name='apithrottleevent',
            name='source',
            field=models.SmallIntegerField(choices=[(1, 'Manual'), (2, 'Membership')], default=1, help_text="Where this throttle came from. MANUAL rows are admin overrides and are never touched by Neon webhooks. MEMBERSHIP rows are written by Neon membership-lifecycle handlers and are wiped/replaced when the user's level changes."),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='apithrottle',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."blocked" IS DISTINCT FROM (NEW."blocked") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."rate" IS DISTINCT FROM (NEW."rate") OR OLD."source" IS DISTINCT FROM (NEW."source") OR OLD."throttle_type" IS DISTINCT FROM (NEW."throttle_type") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))', func='INSERT INTO "api_apithrottleevent" ("blocked", "date_created", "date_modified", "id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rate", "source", "throttle_type", "user_id") VALUES (OLD."blocked", OLD."date_created", OLD."date_modified", OLD."id", OLD."notes", _pgh_attach_context(), NOW(), \'update\', OLD."id", OLD."rate", OLD."source", OLD."throttle_type", OLD."user_id"); RETURN NULL;', hash='372578744181a6dd05ec5cb0b72d7fcb4f5ccfdc', operation='UPDATE', pgid='pgtrigger_update_update_9846f', table='api_apithrottle', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='apithrottle',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "api_apithrottleevent" ("blocked", "date_created", "date_modified", "id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rate", "source", "throttle_type", "user_id") VALUES (OLD."blocked", OLD."date_created", OLD."date_modified", OLD."id", OLD."notes", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."rate", OLD."source", OLD."throttle_type", OLD."user_id"); RETURN NULL;', hash='38a96d07cd9cc6a6db3082b74501024efe22a500', operation='DELETE', pgid='pgtrigger_delete_delete_3cec8', table='api_apithrottle', when='AFTER')),
        ),
    ]
