# Generated by Django 6.0.4 on 2026-06-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_apithrottle_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apithrottle',
            name='throttle_type',
            field=models.SmallIntegerField(choices=[(1, 'API'), (2, 'Citation Lookup'), (3, 'Alerts')], help_text='The type of throttle being overridden.'),
        ),
        migrations.AlterField(
            model_name='apithrottleevent',
            name='throttle_type',
            field=models.SmallIntegerField(choices=[(1, 'API'), (2, 'Citation Lookup'), (3, 'Alerts')], help_text='The type of throttle being overridden.'),
        ),
    ]
