# Generated by Django 5.1.8 on 2025-10-17 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_line1", models.CharField(max_length=255)),
                ("address_line2", models.CharField(max_length=255, null=True)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("zip_code", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Court",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("court_name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Opinion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(null=True, upload_to="opinions/pdf/%Y/%m/"),
                ),
                (
                    "pdf_uri",
                    models.URLField(
                        help_text="External PDF URL if hosted elsewhere",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "docx_file",
                    models.FileField(null=True, upload_to="opinions/docx/%Y/%m/"),
                ),
                (
                    "docx_uri",
                    models.URLField(
                        help_text="External DOCX URL if hosted elsewhere",
                        max_length=500,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaseSummary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appellate_court_case_number",
                    models.CharField(
                        help_text="Described as Court of Appeal Case in the Case Summary section.",
                        max_length=7,
                        unique=True,
                    ),
                ),
                ("division", models.IntegerField()),
                ("case_caption", models.CharField(max_length=500)),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("CR", "Criminal"),
                            ("CV", "Civil"),
                            ("JV", "Juvenile"),
                            ("PR", "Probate"),
                        ],
                        max_length=2,
                    ),
                ),
                ("filing_date", models.DateField(null=True)),
                ("completion_date", models.DateField(null=True)),
                ("oral_argument_date_time", models.DateTimeField(null=True)),
                (
                    "appellate_court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases",
                        to="state_appellate.court",
                    ),
                ),
                (
                    "court_of_appeal_opinion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="state_appellate.opinion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=255, null=True)),
                (
                    "address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_set",
                        to="state_appellate.address",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Attorney",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="as_attorney",
                        to="state_appellate.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("party_type", models.CharField(max_length=20)),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="as_party",
                        to="state_appellate.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartyAttorney",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_date", models.DateField(null=True)),
                (
                    "associated_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="state_appellate.casesummary",
                    ),
                ),
                (
                    "attorney",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="state_appellate.attorney",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="state_appellate.party",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("middle_name", models.CharField(max_length=255, null=True)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_set",
                        to="state_appellate.address",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="party",
            name="person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="as_party",
                to="state_appellate.person",
            ),
        ),
        migrations.AddField(
            model_name="attorney",
            name="contact_person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attorney_contact_for",
                to="state_appellate.person",
            ),
        ),
        migrations.AddField(
            model_name="attorney",
            name="person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="as_attorney",
                to="state_appellate.person",
            ),
        ),
        migrations.CreateModel(
            name="TrialCourt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("county", models.CharField(max_length=255)),
                ("case_number", models.CharField(max_length=100)),
                ("judgement_date", models.DateField()),
                (
                    "judge",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="state_appellate.person",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="casesummary",
            name="trial_court_case",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="state_appellate.trialcourt",
            ),
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_action_was_filed", models.DateField()),
                ("description", models.TextField(null=True)),
                ("notes", models.TextField(null=True)),
                (
                    "associated_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="state_appellate.casesummary",
                    ),
                ),
            ],
            options={
                "ordering": ["associated_case", "date_action_was_filed"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("associated_case", "date_action_was_filed"),
                        name="unique_action_per_case_per_date",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="party",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("organization__isnull", True), ("person__isnull", False)),
                    models.Q(("organization__isnull", False), ("person__isnull", True)),
                    _connector="OR",
                ),
                name="party_is_person_or_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="attorney",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("organization__isnull", True), ("person__isnull", False)),
                    models.Q(("organization__isnull", False), ("person__isnull", True)),
                    _connector="OR",
                ),
                name="attorney_is_person_or_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="trialcourt",
            constraint=models.UniqueConstraint(
                fields=("name", "case_number"), name="unique_trial_court_case"
            ),
        ),
    ]
