---

# Possible upgrade is to slim this down to one task that accepts a variable
# from the include statement, so that the include statement says what variable
# it wants, and this processes the request and spits it back.

- name: copy get_vars.sh to target host
  copy:
    src: get_vars.sh
    dest: /tmp/get_vars.sh
    mode: 0744

- name: register INSTALL_ROOT from /etc/courtlistener
  shell: /tmp/get_vars.sh INSTALL_ROOT
  register: INSTALL_ROOT
  changed_when: False
  tags: setup, testing, dependencies

- name: register CL_SOLR_XMX from /etc/courtlistener
  shell:  /tmp/get_vars.sh CL_SOLR_XMX
  register: CL_SOLR_XMX
  changed_when: False
  tags: setup, testing, dependencies

- name: register VIRTUALENV_ROOT from /etc/courtlistener
  shell: /tmp/get_vars.sh VIRTUALENV_ROOT
  register: VIRTUALENV_ROOT
  changed_when: False
  tags: setup, testing, dependencies

- name: check if celery exists (or this is a dev machine)
  stat: path=/etc/init.d/celeryd
  register: celeryd_status
