from django.db.models import Q

from cl.people_db.models import Person


def get_scotus_judges(d):
    """Get the panel of scotus judges at a given date."""
    return Person.objects.filter(  # Find all the judges...
        Q(positions__court_id="scotus"),  # In SCOTUS...
        Q(positions__date_start__lt=d),  # Started as of the date...
        Q(positions__date_retirement__gt=d)
        | Q(positions__date_retirement=None),  # Haven't retired yet...
        Q(positions__date_termination__gt=d)
        | Q(positions__date_termination=None),  # Nor been terminated...
        Q(date_dod__gt=d) | Q(date_dod=None),  # And are still alive.
    ).distinct()
