# Generated by Django 5.1.8 on 2025-12-11 23:49

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('config_name', models.CharField(help_text="Unique identifier for this configuration (e.g., 'gemini2-5-high-temp'). It will be slugified if it is not in this format.", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description about when/why to use this specific config')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google Gemini')], default='openai', help_text='The LLM provider to use', max_length=20)),
                ('model_name', models.CharField(help_text="The specific model ID expected by the API (e.g., 'gpt-4o', 'claude-3-opus')", max_length=255)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text="JSON dictionary for specific model settings like {'temperature': 0.5, 'max_tokens': 1000}")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LLMPromptSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('prompt_set_name', models.CharField(db_index=True, help_text="Identifier for the task, must be lowercase and use underscores (e.g., 'ocr-scan-p3d'). This name must be repeated across versions to use the latest active one.", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this version of the prompt set attempts to achieve')),
                ('version', models.PositiveIntegerField(default=1, help_text='Incremental version number for this specific task name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates if this is the currently active version for the task')),
                ('notes', models.TextField(blank=True, help_text="Internal comments, known limitations, or reasons for changes (e.g., 'v1 failed on handwritten text; v2 adds examples to fix this')")),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('prompt_name', models.CharField(help_text="Unique identifier name for prompt (e.g. 'ocr-p3d-sys-v1'). It will be slugified if it is not in this format.", max_length=255, unique=True)),
                ('role', models.SmallIntegerField(choices=[(1, 'System'), (2, 'User')], default=2, help_text='The identifier used by the LLM API to distinguish the type of message (e.g., system instructions vs. user input)')),
                ('text', models.TextField(help_text='The actual text of the prompt used')),
                ('position', models.PositiveSmallIntegerField(help_text='The sequence order for this prompt within a prompt set (e.g., 1 for System, 2 for User, etc)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LLMRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('output', models.TextField(blank=True, help_text='The raw text response returned by the LLM, useful for debugging parsing errors')),
                ('success', models.BooleanField(default=True, help_text='True if the output was successfully obtained')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('llm_config', models.ForeignKey(help_text='The configuration (provider/model/params) used for this run', on_delete=django.db.models.deletion.CASCADE, to='ai.llmconfig')),
                ('prompt_set', models.ForeignKey(help_text='The specific version of prompts used', on_delete=django.db.models.deletion.CASCADE, to='ai.llmpromptset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='llmpromptset',
            name='prompts',
            field=models.ManyToManyField(help_text='The collection of individual prompts that make up this instruction set', to='ai.prompt'),
        ),
        migrations.AlterUniqueTogether(
            name='llmpromptset',
            unique_together={('prompt_set_name', 'version')},
        ),
    ]
