# Generated by Django 5.0.6 on 2024-06-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio", "0008_audiotranscriptionmetadata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="stt_status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Speech to Text Needed"),
                    (1, "Speech to Text Complete"),
                    (2, "Speech to Text Failed"),
                    (3, "Transcription does not match audio"),
                    (4, "File size is bigger than 25 MB"),
                    (5, "File does not exist"),
                ],
                default=0,
                help_text="The status of the Speech to Text for this item?",
                verbose_name="Speech to text status",
            ),
        ),
        migrations.AlterField(
            model_name="audioevent",
            name="stt_status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Speech to Text Needed"),
                    (1, "Speech to Text Complete"),
                    (2, "Speech to Text Failed"),
                    (3, "Transcription does not match audio"),
                    (4, "File size is bigger than 25 MB"),
                    (5, "File does not exist"),
                ],
                default=0,
                help_text="The status of the Speech to Text for this item?",
                verbose_name="Speech to text status",
            ),
        ),
    ]
