# Generated by Django 3.1.7 on 2021-04-07 00:24

from django.db import migrations, models

import cl.lib.model_helpers
import cl.lib.storage


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0009_abstract_datetime_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='local_path_mp3',
            field=models.FileField(blank=True, db_index=True, help_text='The location, relative to MEDIA_ROOT, on the CourtListener server, where encoded file is stored', storage=cl.lib.storage.AWSMediaStorage(), upload_to=cl.lib.model_helpers.make_upload_path),
        ),
        migrations.AlterField(
            model_name='audio',
            name='local_path_original_file',
            field=models.FileField(db_index=True, help_text='The location, relative to MEDIA_ROOT, on the CourtListener server, where the original file is stored', storage=cl.lib.storage.AWSMediaStorage(), upload_to=cl.lib.model_helpers.make_upload_path),
        ),
    ]
