# Generated by Django 6.0.2 on 2026-04-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0011_alter_audio_source_alter_audioevent_source_noop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='source',
            field=models.CharField(blank=True, choices=[('C', 'court website'), ('H', 'brad heath archive')], help_text='the source of the audio file, one of: C (court website), H (brad heath archive)', max_length=10),
        ),
        migrations.AlterField(
            model_name='audioevent',
            name='source',
            field=models.CharField(blank=True, choices=[('C', 'court website'), ('H', 'brad heath archive')], help_text='the source of the audio file, one of: C (court website), H (brad heath archive)', max_length=10),
        ),
    ]
